### ISSUE TITLE
Recursion RestXQ: deploying web app fails 

### ISSUE THREAD

**Issue by peterstadler** [eXist-db/exist#1010]
I just upgraded my eXist instance via git and did a `build.sh rebuild`.
All went fine, but now I’m having problems installing my [web app](https://github.com/Edirom/WeGA-WebApp/releases/download/v2.0.0/WeGA-WebApp-2.0.0.xar). The deployment process simply hangs, whether I upload via browser or try via autodeploy.
I updated from commit 72b4bc7d3112593df2d508ca563ad23a31189c3e (February 1st) and I can confirm that going back to this commit indeed fixes the issue for me.

My system:
OS X 10.11.4
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
eXist develop branch at 5d6fc97102e27f5404f22ddf3e90e41b4310ae02

@wolfgangmm confirmed on [exist-open](http://exist.2174344.n4.nabble.com/Problem-deploying-web-app-tp4670225p4670226.html):

> I can see an endless loop in the thread dump (the first lines are repeated over and over again):

```
at org.exist.extensions.exquery.restxq.impl.ExistXqueryRegistry.findServices(ExistXqueryRegistry.java:239)
at org.exist.extensions.exquery.restxq.impl.ExistXqueryRegistry.reexamineModulesWithResolvedDependencies(ExistXqueryRegistry.java:320)
at org.exist.extensions.exquery.restxq.impl.ExistXqueryRegistry.findServices(ExistXqueryRegistry.java:239)
at org.exist.extensions.exquery.restxq.impl.ExistXqueryRegistry.reexamineModulesWithResolvedDependencies(ExistXqueryRegistry.java:320)
at org.exist.extensions.exquery.restxq.impl.ExistXqueryRegistry.findServices(ExistXqueryRegistry.java:239)
at org.exist.extensions.exquery.restxq.impl.RestXqTrigger.after(RestXqTrigger.java:113)
at org.exist.extensions.exquery.restxq.impl.RestXqTrigger.afterCreateDocument(RestXqTrigger.java:51)
at org.exist.collections.triggers.DocumentTriggers.afterCreateDocument(DocumentTriggers.java:236)
at org.exist.collections.Collection.addBinaryResource(Collection.java:1955)
at org.exist.collections.Collection.addBinaryResource(Collection.java:1865)
at org.exist.collections.Collection.addBinaryResource(Collection.java:1858)
at org.exist.repo.Deployment.storeFiles(Deployment.java:771)
```

> Workaround: comment out the restxq trigger in EXIST_HOME/collection.xconf.init and /db/system/config/db/collection.xconf. As far as I can see your app is not using it.

**Comment by dizzzz** [comment]
@adamretter  please could you have a look?

**Comment by adamretter** [comment]
@dizzzz Yes, but I won't have time to look into this for at least a week. Feel free to keep reminding me though ;-)

**Comment by adamretter** [comment]
@peterstadler Sorry this one slipped through the cracks. Does it still happen with eXist-db 5.0.0?

**Comment by peterstadler** [comment]
just tried with the provided Docker images existdb/existdb:4.7.1 and existdb/existdb:5.1.0 and both let me install properly. So I assume the issue got fixed in the meantime – many thanks!

**Comment by peterstadler** [comment]
sorry @adamretter, I managed to fool myself …
Because of this bug I added a pre-install hook to my app which removes `/db/system/config/db/collection.xconf` and forgot about it. So, in January I tested _with_ this pre-install hook. Now I tested without and I'm yet again unable to install the app (tested on current FusionDB and eXist5).

This looks related to #3448 and might be a duplicate.
