### ISSUE TITLE
importing xquery modules fails in latest develop code

### ISSUE THREAD

**Issue by rvdb** [eXist-db/exist#1031]
In eXist-develop (tested with rev. 18a7151, on Windows 7 pro 64 bit, with oracle-jdk-1.8.0_92), when an XQuery file stored in the file system imports a XQuery module, an error is thrown. 

For example, this query (hello.xq):

    xquery version "3.0";
    import module namespace echo="echo" at "echo.xq";

    <p>{echo:hello('world')}</p>

...which imports following module (echo.xq):

    xquery version "3.0";
    module namespace echo="echo";

    declare function echo:hello($string) {
      string-join(('hello', $string), ' ')
    };

When these queries are stored in the file system at `${exist.home}/webapp/helloworld`, and called via [http://localhost:8080/exist/helloworld/hello.xq](http://localhost:8080/exist/helloworld/hello.xq), following error is thrown:

> java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///F:/devtools/eXist/eXist-git/webapp/helloworld/echo.xq
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source) ~[?:1.8.0_92]
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:1.8.0_92]
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:1.8.0_92]
	at sun.nio.fs.WindowsPath.parse(Unknown Source) ~[?:1.8.0_92]
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source) ~[?:1.8.0_92]
       ....

(full error log message in attachment [import_error_log.txt](https://github.com/eXist-db/exist/files/289996/import_error_log.txt))

This error occurs even if no function from the imported module is called, so it seems that either module syntax parsing, or resolution of the file system path is at stake.

However, when the same XQuery files are stored in the database at `/db/apps/helloworld`, and called via [http://localhost:8080/exist/apps/helloworld/hello.xq](http://localhost:8080/exist/apps/helloworld/hello.xq), the expected result `<p>hello world</p>` is returned without errors.

Another reason why I suspect this is a bug, is that the file system variant of this query runs fine on earlier eXist versions, including eXist-RC1.

Attached is a file [helloworld.tar.gz](https://github.com/eXist-db/exist/files/290002/helloworld.tar.gz), containing a folder with both xquery files and a controller, illustrating the issue. Just store it in the file system at `${exist.home}/webapp`, and in the database at `/db/apps/` and see the difference.

**Comment by dizzzz** [comment]
it might have a relation with https://github.com/eXist-db/exist/pull/938 or https://github.com/eXist-db/exist/pull/914
