### ISSUE TITLE
Invalid usage of check-and-set pattern

### ISSUE THREAD

**Issue by alebastrov** [eXist-db/exist#1042]
There are classes with such checking

```
...
private ContextUpdateListener updateListener = null;
...
public void registerUpdateListener( UpdateListener listener )
    {
        if( updateListener == null ) {
updateListener = new ContextUpdateListener();
...
}
```

This checking SHOULD be performed only on volatile references, so I suggest to change the declaration to

```
private volatile ContextUpdateListener updateListener = null;
```

This also happen with other implementation of UpdateListener interface, for instance
in BindingExpression, XQueryContext

I found this through investigation such problem

```
2016-06-09 09:27:24,755 [http-nio-8080-exec-9] ERROR (DBDAO.java [queryCollection]:518) - Failed to query: doc('app.xml')/configuration/configitem[@name='cache.xsl.enable'] on collection: /db/LiveContent/config/ 

org.xmldb.api.base.XMLDBException: 0 listener not found: 770387096
    at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:459)
    at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:157)
    at com.sdl.cd.livecontent.repository.DBDAO.queryCollection(DBDAO.java:515)
```

**Comment by duncdrum** [comment]
this is a very old issue, if it persists with more recent versions of exist-db please open a new issue, providing more details about exist, os, java etc versions.
