### ISSUE TITLE
NPE while multithreading access

### ISSUE THREAD

**Issue by alebastrov** [eXist-db/exist#1046]
ExistDB 2.2
~~~
2016-06-14 09:47:23,752 [http-bio-8080-exec-111] ERROR (ConfigurationDaoImpl.java [getItem]:112) - XPathException: exerr:ERROR Failed to query: doc('app.xml')/configuration/configitem[@name='pub.session.timeout'] on collection: /db/LiveContent/config/ 
org.exist.xquery.XPathException: exerr:ERROR Failed to query: doc('app.xml')/configuration/configitem[@name='pub.session.timeout'] on collection: /db/LiveContent/config/
	at com.sdl.cd.livecontent.repository.DBDAO.queryCollection(DBDAO.java:498)
	at com.sdl.cd.livecontent.repository.impl.ConfigurationDaoImpl.getItem(ConfigurationDaoImpl.java:101)
	at com.sdl.cd.livecontent.controllers.BaseController.setSessionTimeout(BaseController.java:143)
	at com.sdl.cd.livecontent.controllers.BaseController.enrichSession(BaseController.java:103)
	at com.sdl.cd.livecontent.controllers.BaseController.prepareSessionContext(BaseController.java:216)
	at com.sdl.cd.livecontent.controllers.UploadController.uploadResource(UploadController.java:97)
	at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:869)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.sdl.cd.livecontent.filter.ApiFilter.doFilter(ApiFilter.java:44)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
	at com.sdl.cd.livecontent.filter.ApiFilter.doFilter(ApiFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.sdl.cd.livecontent.sso.LCFilter.doFilter(LCFilter.java:148)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.cxf.fediz.example.FederationFilter.doFilter(FederationFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.cxf.fediz.tomcat.FederationAuthenticator.invoke(FederationAuthenticator.java:156)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.xmldb.api.base.XMLDBException
	at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:459)
	at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:157)
	at com.sdl.cd.livecontent.repository.DBDAO.queryCollection(DBDAO.java:494)
	... 58 more
Caused by: java.lang.NullPointerException
	at org.exist.xquery.Predicate.selectByNodeSet(Predicate.java:451)
	at org.exist.xquery.Predicate.evalPredicate(Predicate.java:326)
	at org.exist.xquery.LocationStep.processPredicate(LocationStep.java:251)
	at org.exist.xquery.LocationStep.applyPredicate(LocationStep.java:238)
	at org.exist.xquery.LocationStep.eval(LocationStep.java:462)
	at org.exist.xquery.pragmas.Optimize.eval(Optimize.java:172)
	at org.exist.xquery.ExtensionExpression.eval(ExtensionExpression.java:70)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.XQuery.execute(XQuery.java:297)
	at org.exist.xquery.XQuery.execute(XQuery.java:217)
	at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:452)
	... 60 more
~~~

**Comment by adamretter** [comment]
Seems to be an issue with the caching of results from evaluation of Predicate expressions, https://github.com/eXist-db/exist/blob/eXist-2.2/src/org/exist/xquery/Predicate.java#L451

@wolfgangmm Could this be a `reset` issue?

**Comment by alebastrov** [comment]
If it is so, then 
~~~
private CachedResult cached = null;
~~~
should be 
~~~
private volatile CachedResult cached = null;
~~~

**Comment by alebastrov** [comment]
I had to look at this error again and found out that LocationStep has insufficient sync
Common usage of sync by context there 
~~~
synchronized (context) {
     final StructuralIndex index = context.getBroker().getStructuralIndex();
     currentSet = index.findElementsByTagName(ElementValue.ELEMENT, docs, test.getName(), null, this);
     currentDocs = docs;
     registerUpdateListener(context);
}
~~~
Bu sometimes it is working outside the sync block like below
~~~
final StructuralIndex index = context.getBroker().getStructuralIndex();
if (!contextSet.getProcessInReverseOrder()) {
    return index.findDescendantsByTagName(ElementValue.ATTRIBUTE, test.getName(), axis, docs, contextSet, contextId, this);
}
~~~
It seems to me they should be fixed in order to use the same way of storing links to currentSet, currentDocs, and index usage.
Moreover, UpdateListener there should be volatile reference (of course if it can be used in multithreading environment) and it resets references to currenDoc, currentSet without any sync by context. I think it also should be enveloped into sync like below
~~~
public void documentUpdated(DocumentImpl document, int event) {
					synchronized (context) {
						cached = null;
						if (document == null || event == UpdateListener.ADD
									|| event == UpdateListener.REMOVE) {
							// clear all
							currentDocs = null;
							currentSet = null;
						} else {
							if (currentDocs != null
										&& currentDocs
												   .contains(document.getDocId())) {
								currentDocs = null;
								currentSet = null;
							}
						}
					}
				}
~~~

**Comment by shabanovd** [comment]
I think better to `synchronized (LocationStep.this)` all access to `cached`, `currentDocs` & `currentSet`.

**Comment by alebastrov** [comment]
I would recommend to rewrite registerUpdateListener via atomic reference like below
~~~
protected AtomicReference<UpdateListener> listener = new AtomicReference<>();
UpdateListener locListener = new UpdateListener() {...}
if (listener.compareAndSet(null, locListener)) {
    this.context.registerUpdateListener(locListener);
}
~~~

**Comment by shabanovd** [comment]
I'm not sure how it help with `cached` set to `null` while different thread reading it

**Comment by alebastrov** [comment]
As far as I see "cached" is not used in exist-db2.2

**Comment by alebastrov** [comment]
It may help with
~~~
2016-08-17 20:08:21,430 [http-nio-8080-exec-8] ERROR (DBDAO.java [queryCollection]:549) - Failed to xQuery: doc('/db/LiveContent/publications/description/Ins20_3043_OM-v1.xml')/pub on collection: /db/LiveContent/publications/description/ 
org.xmldb.api.base.XMLDBException: 327475913 listener not found: 1953710622
	at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:459)
	at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:157)
	at com.sdl.cd.livecontent.repository.DBDAO.queryCollection(DBDAO.java:546)
	at com.sdl.cd.livecontent.repository.impl.PublicationDaoImpl.checkPublication(PublicationDaoImpl.java:788)
	at com.sdl.cd.livecontent.repository.impl.CachedPublicationDao.checkPublication(CachedPublicationDao.java:337)
	at com.sdl.cd.livecontent.controllers.PubLangController.setConfig(PubLangController.java:79)
	at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at com.sdl.cd.livecontent.filter.ApiFilter.doFilter(ApiFilter.java:45)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:720)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
	at com.sdl.cd.livecontent.filter.ApiFilter.doFilter(ApiFilter.java:80)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at com.sdl.cd.livecontent.sso.LCFilter.doFilter(LCFilter.java:148)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.cxf.fediz.example.FederationFilter.doFilter(FederationFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.cxf.fediz.tomcat.FederationAuthenticator.invoke(FederationAuthenticator.java:144)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: 327475913 listener not found: 1953710622
	at org.exist.storage.NotificationService.unsubscribe(NotificationService.java:66)
	at org.exist.xquery.XQueryContext.clearUpdateListeners(XQueryContext.java:3454)
	at org.exist.xquery.XQueryContext.reset(XQueryContext.java:1443)
	at org.exist.xquery.XQueryContext.reset(XQueryContext.java:1367)
	at org.exist.xquery.XQuery.execute(XQuery.java:312)
	at org.exist.xquery.XQuery.execute(XQuery.java:217)
	at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:452)
	... 59 more
Caused by: java.lang.RuntimeException: 327475913 listener not found: 1953710622
	at org.exist.storage.NotificationService.unsubscribe(NotificationService.java:66)
	at org.exist.xquery.XQueryContext.clearUpdateListeners(XQueryContext.java:3454)
	at org.exist.xquery.XQueryContext.reset(XQueryContext.java:1443)
	at org.exist.xquery.XQueryContext.reset(XQueryContext.java:1367)
	at org.exist.xquery.XQuery.execute(XQuery.java:312)
	at org.exist.xquery.XQuery.execute(XQuery.java:217)
	at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:452)
	at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:157)
	at com.sdl.cd.livecontent.repository.DBDAO.queryCollection(DBDAO.java:546)
	at com.sdl.cd.livecontent.repository.impl.PublicationDaoImpl.checkPublication(PublicationDaoImpl.java:788)
	at com.sdl.cd.livecontent.repository.impl.CachedPublicationDao.checkPublication(CachedPublicationDao.java:337)
	at com.sdl.cd.livecontent.controllers.PubLangController.setConfig(PubLangController.java:79)
	at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at com.sdl.cd.livecontent.filter.ApiFilter.doFilter(ApiFilter.java:45)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:720)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
	at com.sdl.cd.livecontent.filter.ApiFilter.doFilter(ApiFilter.java:80)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at com.sdl.cd.livecontent.sso.LCFilter.doFilter(LCFilter.java:148)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.cxf.fediz.example.FederationFilter.doFilter(FederationFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.cxf.fediz.tomcat.FederationAuthenticator.invoke(FederationAuthenticator.java:144)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
~~~

**Comment by alebastrov** [comment]
As far as I can see there is no any changes with methods like 
~~~
protected void registerUpdateListener()
~~~
All of them do not support multithreading.

We've changed all that places as shown below
~~~
private final AtomicReference<UpdateListener> listener = new AtomicReference<>();
...
protected void registerUpdateListener(final XQueryContext context) {
        UpdateListener locListener = new UpdateListener() {
            public void documentUpdated(DocumentImpl document, int event) {
                cached = null;
                if (document == null || event == UpdateListener.ADD || event == UpdateListener.REMOVE) {
                    // clear all
                    synchronized (context) {
                        currentDocs = null;
                        currentSet = null;
                    }
                } else {
                    synchronized (context) {
                        if (currentDocs != null && currentDocs.contains(document.getDocId())) {
                            currentDocs = null;
                            currentSet = null;
                        }
                    }
                }
            }

            public void nodeMoved(NodeId oldNodeId, StoredNode newNode) {
            }

            public void unsubscribe() {
                LocationStep.this.listener.set(null);
            }

            public void debug() {
                LOG.debug("UpdateListener: Line: "
                                  + LocationStep.this.toString() + "; id: "
                                  + LocationStep.this.getExpressionId());
            }
        };
        if (listener.compareAndSet(null, locListener)) {
            this.context.registerUpdateListener(locListener);
        }
    }
~~~

**Comment by alebastrov** [comment]
It should be done before 3.2 is released
