### ISSUE TITLE
errors with 'illegal file'

### ISSUE THREAD

**Issue by pherk** [eXist-db/exist#1060]
dear ExistDB gurus,
FYI
a lock file from libreoffice was accidentally included in a package
loading the package via dashboard->package manager succeeded without error
but the collection browser gives an error while navigating to the subdir with the lock file

the lock file holds just one line without eol:
,peter,T440,01.07.2016 18:37,file:///home/peter/.config/libreoffice/4;

exist.log:
```
javax.servlet.ServletException: An error occurred while processing request to /exist/apps/dashboard/plugins/browsing/contents/: exerr:ERROR Resource or collection 'xmldb:/db/apps/nabudocs/scripts/xmldb:.~lock.NeuhalfenJanSebastian1115.htm#' does not exist. [at line 75, column 30, source: /db/apps/dashboard/plugins/browsing/service.xql]
In function:
        service:resource-xml(xs:string, xs:string?, xs:boolean, xs:string) [67:17:/db/apps/dashboard/plugins/browsing/service.xql]
        service:resources(xs:string) [46:43:/db/apps/dashboard/plugins/browsing/service.xql]
        restxq:call-with-args(function, function*) [88:17:/db/apps/dashboard/modules/restxq.xql](function, element%28%29, map) [83:68:/db/apps/dashboard/modules/restxq.xql]
        restxq:function-by-annotation(function+, map, function) [83:9:/db/apps/dashboard/modules/restxq.xql]
        restxq:process(xs:string?, function+) [49:9:/db/apps/dashboard/modules/restxq.xql]
        at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:381) ~[exist-optional.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[servlet-api-3.0.jar:?]
```
I tried to repair the package before I saw the file and got a NullPointerException (not reproduced)

regards 
Peter

**Comment by pherk** [comment]
after deleting the package and reloading via package manager (without the lock file)
many exceptions in the terminal, the exist.log does not show new errors
java.lang.NullPointerException
	at org.exist.repo.Deployment.storeFiles(Deployment.java:771)
	at org.exist.repo.Deployment.scanDirectory(Deployment.java:693)
	at org.exist.repo.Deployment.lambda$scanDirectory$4(Deployment.java:698)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.exist.repo.Deployment.scanDirectory(Deployment.java:698)
	at org.exist.repo.Deployment.deploy(Deployment.java:410)
	at org.exist.repo.Deployment.installAndDeploy(Deployment.java:271)
	at org.exist.repo.Deployment.installAndDeploy(Deployment.java:158)
	at org.exist.xquery.modules.expathrepo.Deploy.installAndDeployFromDb(Deploy.java:213)
	at org.exist.xquery.modules.expathrepo.Deploy.eval(Deploy.java:169)

browsing to to subdir gives the old error as if the lock file is still present

Peter

**Comment by dizzzz** [comment]
sorry for not responding earlier. what version of eXist-db?
You are not mentioning the webDAV interface... I had a similar issue using this interface, kinda gave up to find a good solution in the code (that is what I think I remember).  Can you 'escape' the hash character?

**Comment by pherk** [comment]
existdb 3.0RC2 develop-9558475
I don't use webDAV. The file was loaded via Package Manager.
I have no problem with the error (just removed the extra file). 
I only reported it because it took some time to find the cause of package failure and the error has led to an inconsistent state of the database. The database had to be killed and setup afresh. 

Peter

**Comment by joewiz** [comment]
Any chance you could upload a sample package and set of steps for reproducing the NPE? 

It sounds like the lock file, `xmldb:/db/apps/nabudocs/scripts/xmldb:.~lock.NeuhalfenJanSebastian1115.htm#`, was invalid XML and/or contained invalid characters in the filename, and the repo installation routine choked on this. Still, there shouldn't be an NPE, so steps to reproduce could help. Please also include eXist version number.

**Comment by KitWallace** [comment]
an additional problem is that not only will such a file will not be backed up, but neither wil its containing directory.

The problem seems to lie with the terminal #  -  such files won't load through the java client because it throws an unknown suffix.  Neither can it be created via Oxygen or eXide because the terminal # is removed ,  but the issue remains with webdav and the package loader it appears.  Easy enough to recreate the issue by creating such a file on the client side of webdav and then attempting to backup the directory (from the java client)  - which fails when encountering the bad file and subsequent files are lost.  Fortunately, a full backup is more robust and  seems only to loose the containing directory.

**Comment by line-o** [comment]
A lot has been done to better support resources with special characters. I assume this issue has been resolved. Needs to be retested.

- create a package with a file with the name`.~lock.testfile.htm#`
- install that package into exist
- list the collection contents in eXide
- list the collection contents in xst
- list the collection contents with xmld:get-child-resources

**Comment by duncdrum** [comment]
Retested against current develop (`existdb/existdb:pr6662` Docker image).

**Repro package:** minimal EXPath library (`barebones@0.1.0`) that includes a LibreOffice-style lock file named `.~lock.testfile.htm#` at the package root. (see below rename `.zip` -> `.xar` )

**Steps**
1. Install via  xst or dashboard — succeeds (`installed barebones@0.1.0`).
2. `xmldb:get-child-resources("/db/apps/barebones")` — returns `expath-pkg.xml`, `xmldb:.~lock.testfile.htm#`, `repo.xml` (name is mangled / `#` treated as URI fragment).
3. `xst list /db/apps/barebones` — fails with:
   `Invalid URI: xmldb URI scheme has no instance name: xmldb:.~lock.testfile.htm`
4. `util:binary-doc-available("/db/apps/barebones/.~lock.testfile.htm#")` — `true` (resource is stored).
5.  exide shows 0 contents under `db/apps/barebones` 

**Verdict:** still broken. Package install succeeds, but collection listing / URI resolution chokes on the trailing `#` in the resource name — same class of failure as in the original report.

[barebones-0.1.0.zip](https://github.com/user-attachments/files/32055623/barebones-0.1.0.zip)

**Comment by joewiz** [comment]
[This response was prompted by Joe, drafted by Claude Code, and reviewed by Joe.]

Thanks for the retest, @duncdrum — that's a clean reproduction, and it lands exactly on an open design decision rather than on a separate defect. I traced it on current `develop`.

## Why the name comes back mangled

The tell is the shape of what `xmldb:get-child-resources` returns: `xmldb:.~lock.testfile.htm#`, with the scheme glued onto the name and the path gone. That is what you get when a `#` reaches `java.net.URI` as a fragment delimiter.

The path is `XmldbURI.create(name)` → `xmldbUriFor(name, escape = true)` → `AnyURIValue.escape` → `FunEscapeURI.escape(s, false)`, whose keep-set is:

```
-_.!~*'()%;/?:@&=+$,#[]
```

`#` is kept literal. That is correct for `iri-to-uri` applied to a whole URI — `#` is a delimiter there and must survive. It is wrong when the string being encoded is a resource *name*, where `#` is just a character someone typed. So `new URI(".~lock.testfile.htm#")` parses the `#` as the start of a fragment, the name is truncated, and everything downstream that round-trips through `XmldbURI` breaks. `util:binary-doc-available` returns `true` because the bytes really are stored; it is the key that is wrong, not the storage.

Worth noting `%` sits in that same keep-set, which is the `a%20b` silent-corruption case already on the table in #6463.

## This is decision 2 of #6463

The divergence is not hypothetical, and it is not confined to the deployer: **REST and WebDAV already store `#` as `%23` today.** So right now the XQuery/Java surfaces and the HTTP surfaces disagree about the stored identity of the same filename. That is precisely the class of problem #6463 exists to settle, and this issue is a nine-year-old instance of it that a maintainer has now reproduced on current code.

There is a working prototype. On the resource-naming prototype branch, the codec is aligned to RFC 3986 pchar, and the tests already pin this exact case — `a#b.xml` → `a%23b.xml` — with `#` carried as a row in the cross-surface conformance corpus, asserting that all surfaces converge on one stored key.

## One surface the prototype does not yet cover

The prototype wires `xmldb:store` / `xmldb:create-collection`, `doc()` / `collection()` / `doc-available()`, and XML-RPC reads. It does **not** touch the EXPath package installer, which is the surface a `.xar` goes through:

```java
// Deployment.java
final XmldbURI name = XmldbURI.create(FileUtils.fileName(file));
```

That is the raw filesystem name handed straight to `XmldbURI.create`, with no name-level encoding boundary. So even with decision 2 landed as currently prototyped, installing your `barebones` package would still store a literal `#`. Adding the installer to the wired surfaces is a small change, but it needs the codec decision made first — otherwise it just moves the divergence.

## What I think this issue is now worth

Two things, beyond "still broken":

1. **It is evidence for the decision.** #6463 has been waiting on a maintainer call on the canonical stored form. This is a concrete, reproduced, user-visible failure that the decision resolves — package installs succeeding while the collection then lists as empty, with no error anywhere.

2. **The consequences are worse than the title suggests.** @KitWallace noted in 2020 that a resource with such a name is not merely skipped by backup — its *containing collection* is lost too. That makes this a data-loss path, not only a display bug.

So rather than patching the installer in isolation — which would make packages install correctly while leaving the codec divergence in place, which is how this keeps coming back — I'd like to use this as the argument for settling #6463 and landing the codec across every write boundary, installer included. @line-o @duncdrum, is there anything still blocking that decision that we could usefully break down?
