### ISSUE TITLE
ExistDB allows to save document with empty name

### ISSUE THREAD

**Issue by alebastrov** [eXist-db/exist#1092]
It will lead to different issues with collection

**Comment by dizzzz** [comment]
Sorry this report makes yet no sense to me.

Please provide details how you created such a document, what is for you an "empty name", it will lead... But does it?

We appreciate feedback from you but please write a report in a way we can reproduce and understand.

With the current description I don't think anyone will spend time in it.

Help us to help you :)

**Comment by dizzzz** [comment]
Save = store document in database?

**Comment by alebastrov** [comment]
Yes, it is.
empty document name means 
~~~
collection.createResource("", "XMLResource");
~~~

**Comment by alebastrov** [comment]
To check what happens just call BACKUP and then RESTORE db with that document.
~~~
java.lang.NullPointerException

        at org.exist.backup.Backup.backup(Backup.java:335)

        at org.exist.backup.Backup.backup(Backup.java:424)

        at org.exist.backup.Backup.backup(Backup.java:424)

        at org.exist.backup.Backup.backup(Backup.java:424)

        at org.exist.backup.Backup.backup(Backup.java:424)

        at org.exist.backup.Backup.backup(Backup.java:424)

        at org.exist.backup.Backup.backup(Backup.java:236)

        at org.exist.backup.Backup.backup(Backup.java:216)

        at org.exist.backup.Main.process(Main.java:275)

        at org.exist.backup.Main.main(Main.java:488)
~~~
