### ISSUE TITLE
eXide does not work (expathrepo issue)

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#1152]
In current develop (clean clone) I can't open eXide; full logfile is attached, the core of the exception is below; it is a deployment issue.

other apps *can* be installed from the public-repo; the special part is (probably) that user eXide is created during startup/initialization...

To reproduce
- clean repo ( `git clean -fdx` `git reset --hard` etc, warning bla bla)
- rebuild existdb `./build.sh rebuild`
- start existdb `bin/startup.sh`
- check `webapp/WEB-INF/logs/expath-repo.log`

```
2016-10-20 21:56:51,472 [main] INFO  (Deployment.java [installAndDeploy]:270) - Deploying package http://exist-db.org/apps/eXide 
2016-10-20 21:56:51,522 [main] WARN  (AutoDeploymentTrigger.java [execute]:74) - Exception during deployment of app eXide-2.2.0.xar: Failed to create user: eXide 
org.expath.pkg.repo.PackageException: Failed to create user: eXide
	at org.exist.repo.Deployment.checkUserSettings(Deployment.java:620) ~[exist.jar:?]
	at org.exist.repo.Deployment.deploy(Deployment.java:405) ~[exist.jar:?]
	at org.exist.repo.Deployment.installAndDeploy(Deployment.java:271) ~[exist.jar:?]
	at org.exist.repo.AutoDeploymentTrigger.execute(AutoDeploymentTrigger.java:72) [exist.jar:?]
	at org.exist.storage.StartupTriggersManager.startPreMultiUserSystem(StartupTriggersManager.java:58) [exist.jar:?]
	at org.exist.storage.BrokerPoolServicesManager.startPreMultiUserSystemServices(BrokerPoolServicesManager.java:190) [exist.jar:?]
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:631) [exist.jar:?]
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:415) [exist.jar:?]
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:181) [exist.jar:?]
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:110) [exist.jar:?]
	at org.exist.jetty.JettyStart.run(JettyStart.java:164) [exist-optional.jar:?]
	at org.exist.jetty.JettyStart.main(JettyStart.java:78) [exist-optional.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.exist.start.Main.invokeMain(Main.java:140) [start.jar:?]
	at org.exist.start.Main.run(Main.java:453) [start.jar:?]
	at org.exist.start.Main.main(Main.java:64) [start.jar:?]
Caused by: org.exist.config.ConfigurationException: org.exist.EXistException: Database instance 'exist' is not available
	at org.exist.config.ConfigurationImpl.save(ConfigurationImpl.java:429) ~[exist.jar:?]
	at org.exist.security.internal.SecurityManagerImpl.save(SecurityManagerImpl.java:650) ~[exist.jar:?]
	at org.exist.security.internal.SecurityManagerImpl.addGroup(SecurityManagerImpl.java:595) ~[exist.jar:?]
	at org.exist.repo.Deployment.checkUserSettings(Deployment.java:608) ~[exist.jar:?]
	... 18 more
Caused by: java.io.IOException: org.exist.EXistException: Database instance 'exist' is not available
	at org.exist.config.Configurator.save(Configurator.java:1231) ~[exist.jar:?]
	at org.exist.config.ConfigurationImpl.save(ConfigurationImpl.java:424) ~[exist.jar:?]
	at org.exist.security.internal.SecurityManagerImpl.save(SecurityManagerImpl.java:650) ~[exist.jar:?]
	at org.exist.security.internal.SecurityManagerImpl.addGroup(SecurityManagerImpl.java:595) ~[exist.jar:?]
	at org.exist.repo.Deployment.checkUserSettings(Deployment.java:608) ~[exist.jar:?]
	... 18 more
Caused by: org.exist.EXistException: Database instance 'exist' is not available
	at org.exist.storage.BrokerPools.getInstance(BrokerPools.java:260) ~[exist.jar:?]
	at org.exist.storage.BrokerPools.getInstance(BrokerPools.java:239) ~[exist.jar:?]
	at org.exist.config.Configurator.save(Configurator.java:1228) ~[exist.jar:?]
	at org.exist.config.ConfigurationImpl.save(ConfigurationImpl.java:424) ~[exist.jar:?]
	at org.exist.security.internal.SecurityManagerImpl.save(SecurityManagerImpl.java:650) ~[exist.jar:?]
	at org.exist.security.internal.SecurityManagerImpl.addGroup(SecurityManagerImpl.java:595) ~[exist.jar:?]
	at org.exist.repo.Deployment.checkUserSettings(Deployment.java:608) ~[exist.jar:?]
	... 18 more
```

[expath-repo.log.txt](https://github.com/eXist-db/exist/files/542771/expath-repo.log.txt)

**Comment by dizzzz** [comment]
The issue is first visible in eba32dabc13b1bcd44f5dd2841e264ffe746b441 ,  #1082 ; @adamretter that is your brokerfix PR....

**Comment by joewiz** [comment]
I can reproduce the problem on macOS Sierra (10.12) with Java JDK 1.8.0_112-b16. 

(Also, double-clicking on start.jar fails, but starting with bin/startup.sh works. The java process starts but no eXist splash screen. You too, Dannes? If so, I'll open an issue.)

**Comment by adamretter** [comment]
@dizzzz @joewiz I am working on a fix...

**Comment by joewiz** [comment]
@adamretter Great, thank you!

**Comment by dizzzz** [comment]
workaround: install eXide manually

**Comment by adamretter** [comment]
@dizzzz @joewiz Just sent the PR

**Comment by dizzzz** [comment]
i'll test the commit tonight ; I did not realize the fix was not that complex....

**Comment by joewiz** [comment]
I can confirm after testing the PR after it was merged into develop that the problems I was experiencing - with eXide installation and start.jar startup - are fixed. Thanks @adamretter and @dizzzz!
