### ISSUE TITLE
HTTP Unauthorized

### ISSUE THREAD

**Issue by zacheryt757** [eXist-db/exist#1218]
Running into issues after drive space filled up and the export directory that was filled with .log and .zip files were deleted to re-gain space on drive. When attempting to open Collection Browser getting `Sorry an Error occurred. 2017-01-10 11:39:55,397 [eXistThread-2677] ERROR (StandardFilter.java [process]:68) - process
java.lang.NullPointerException. When attempting to open Java Admin Client and logging in this error message is displayed: XmlRpcException: Failed to invoke method getSubCollectionPermissions. `

When attempting to run `bin/client.sh -i -c /db`
This is what is outputted to screen. Any help would be greatly appreciated and this is probably not the best place to put this type of issue.

```
Connection to database failed; message: HTTP server returned unexpected status: Unauthorized
org.xmldb.api.base.XMLDBException: HTTP server returned unexpected status: Unauthorized
        at org.exist.xmldb.RemoteCollection.instance(RemoteCollection.java:98)
        at org.exist.xmldb.RemoteCollection.instance(RemoteCollection.java:80)
        at org.exist.xmldb.DatabaseImpl.readCollection(DatabaseImpl.java:279)
        at org.exist.xmldb.DatabaseImpl.getRemoteCollection(DatabaseImpl.java:241)
        at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:164)
        at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:153)
        at org.xmldb.api.DatabaseManager.getCollection(Unknown Source)
        at org.exist.client.InteractiveClient.connect(InteractiveClient.java:327)
        at org.exist.client.InteractiveClient.connectToDatabase(InteractiveClient.java:2335)
        at org.exist.client.InteractiveClient.run(InteractiveClient.java:2423)
        at org.exist.client.InteractiveClient.main(InteractiveClient.java:289)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.exist.start.Main.invokeMain(Main.java:126)
        at org.exist.start.Main.run(Main.java:448)
        at org.exist.start.Main.main(Main.java:50)
Caused by: org.apache.xmlrpc.client.XmlRpcHttpTransportException: HTTP server returned unexpected status: Unauthorized
        at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.getInputStream(XmlRpcSunHttpTransport.java:94)
        at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:152)
        at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
        at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
        at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
        at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
        at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:158)
        at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:147)
        at org.exist.xmldb.RemoteCollection.instance(RemoteCollection.java:89)
        ... 17 more
[B@2446409dorg.apache.xmlrpc.client.XmlRpcHttpTransportException: HTTP server returned unexpected status: Unauthorized
        at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.getInputStream(XmlRpcSunHttpTransport.java:94)
        at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:152)
        at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
        at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
        at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
        at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
        at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:158)
        at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:147)
        at org.exist.xmldb.RemoteCollection.instance(RemoteCollection.java:89)
        at org.exist.xmldb.RemoteCollection.instance(RemoteCollection.java:80)
        at org.exist.xmldb.DatabaseImpl.readCollection(DatabaseImpl.java:279)
        at org.exist.xmldb.DatabaseImpl.getRemoteCollection(DatabaseImpl.java:241)
        at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:164)
        at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:153)
        at org.xmldb.api.DatabaseManager.getCollection(Unknown Source)
        at org.exist.client.InteractiveClient.connect(InteractiveClient.java:327)
        at org.exist.client.InteractiveClient.connectToDatabase(InteractiveClient.java:2335)
        at org.exist.client.InteractiveClient.run(InteractiveClient.java:2423)
        at org.exist.client.InteractiveClient.main(InteractiveClient.java:289)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.exist.start.Main.invokeMain(Main.java:126)
        at org.exist.start.Main.run(Main.java:448)
        at org.exist.start.Main.main(Main.java:50)
Caused by: org.apache.xmlrpc.client.XmlRpcHttpTransportException: HTTP server returned unexpected status: Unauthorized
        at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.getInputStream(XmlRpcSunHttpTransport.java:94)
        at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:152)
        at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
        at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
        at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
        at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
        at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:158)
        at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:147)
        at org.exist.xmldb.RemoteCollection.instance(RemoteCollection.java:89)
        at org.exist.xmldb.RemoteCollection.instance(RemoteCollection.java:80)
        at org.exist.xmldb.DatabaseImpl.readCollection(DatabaseImpl.java:279)
        at org.exist.xmldb.DatabaseImpl.getRemoteCollection(DatabaseImpl.java:241)
        at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:164)
        at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:153)
        at org.xmldb.api.DatabaseManager.getCollection(Unknown Source)
        at org.exist.client.InteractiveClient.connect(InteractiveClient.java:327)
        at org.exist.client.InteractiveClient.connectToDatabase(InteractiveClient.java:2335)
        at org.exist.client.InteractiveClient.run(InteractiveClient.java:2423)
        at org.exist.client.InteractiveClient.main(InteractiveClient.java:289)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.exist.start.Main.invokeMain(Main.java:126)
        at org.exist.start.Main.run(Main.java:448)
        at org.exist.start.Main.main(Main.java:50)
```

**Comment by adamretter** [comment]
Can you provide the stack trace for the NullPointerException from your exist.log file please?

**Comment by zacheryt757** [comment]
2017-01-10 16:33:05,866 [eXistThread-29] ERROR (StandardFilter.java [process]:68) - process
java.lang.NullPointerException
        at org.exist.webdav.ExistCollection.initMetadata(ExistCollection.java:120)
        at org.exist.webdav.MiltonResource.authenticate(MiltonResource.java:340)
        at com.bradmcevoy.http.http11.auth.BasicAuthHandler.authenticate(BasicAuthHandler.java:52)
        at com.bradmcevoy.http.AuthenticationService.authenticate(AuthenticationService.java:152)
        at com.bradmcevoy.http.HandlerHelper.checkAuthentication(HandlerHelper.java:83)
        at com.bradmcevoy.http.HandlerHelper.checkAuthorisation(HandlerHelper.java:95)
        at com.bradmcevoy.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:117)
        at com.bradmcevoy.http.webdav.PropFindHandler.processResource(PropFindHandler.java:103)
        at com.bradmcevoy.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:91)
        at com.bradmcevoy.http.webdav.PropFindHandler.process(PropFindHandler.java:97)
        at com.bradmcevoy.http.StandardFilter.process(StandardFilter.java:52)
        at com.bradmcevoy.http.FilterChain.process(FilterChain.java:40)
        at com.bradmcevoy.http.HttpManager.process(HttpManager.java:228)
        at com.bradmcevoy.http.MiltonServlet.service(MiltonServlet.java:195)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:457)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:229)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:103)
        at org.exist.http.urlrewrite.Forward.doRewrite(Forward.java:50)
        at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:221)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:457)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:368)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:488)
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:943)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1004)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:861)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:745)

**Comment by dizzzz** [comment]
Did you actually run out of diskspace? That can be fatal.... in 3.0 we have a protection mechanism built in,,,

**Comment by zacheryt757** [comment]
Yes it was completely out of disk space. Then i removed all the .log and .zip files in the export directory.

**Comment by zacheryt757** [comment]
In the log files it appears as though its still peforming tasks, its just the dashboard collection browser thats not working.

**Comment by dizzzz** [comment]
Aha. Ok then the database might be damaged, the exist.log should show. You could try to do an recovery export.....

**Comment by zacheryt757** [comment]
2017-01-10 17:00:29,204 [eXistThread-30] INFO  (HttpManager.java [process]:213) - PROPFIND :: http://myserver.com:8080/exist/webdav/db/apps/library/products/wbe/Media/mp/ - http://myserver.com:8080/exist/webdav/db/apps/library/products/wbe/Media/mp/
2017-01-10 17:00:29,204 [eXistThread-30] INFO  (MiltonResource.java [authorise]:350) - PROPFIND /db/apps/library/products/wbe/Media/mp (write=false)
2017-01-10 17:00:29,205 [eXistThread-30] INFO  (MiltonResource.java [authorise]:350) - PROPFIND /db/apps/library/products/wbe/Media/mp (write=false)
2017-01-10 17:00:29,230 [eXistThread-31] INFO  (HttpManager.java [process]:213) - PROPFIND :: http://myserver.com:8080/exist/webdav/db/apps/library/products/wbe/Media/ - http://myserver.com:8080/exist/webdav/db/apps/library/products/wbe/Media/
2017-01-10 17:00:29,230 [eXistThread-31] INFO  (MiltonResource.java [authorise]:350) - PROPFIND /db/apps/library/products/wbe/Media (write=false)
2017-01-10 17:00:29,231 [eXistThread-31] INFO  (MiltonResource.java [authorise]:350) - PROPFIND /db/apps/library/products/wbe/Media (write=false)
2017-01-10 17:00:29,256 [eXistThread-41] INFO  (HttpManager.java [process]:213) - PROPFIND :: http://myserver.com:8080/exist/webdav/db/apps/library/products/wbe/ - http://myserver.com:8080/exist/webdav/db/apps/library/products/wbe/
2017-01-10 17:00:29,256 [eXistThread-41] INFO  (MiltonResource.java [authorise]:350) - PROPFIND /db/apps/library/products/wbe (write=false)
2017-01-10 17:00:29,257 [eXistThread-41] INFO  (MiltonResource.java [authorise]:350) - PROPFIND /db/apps/library/products/wbe (write=false)
2017-01-10 17:00:29,283 [eXistThread-31] INFO  (HttpManager.java [process]:213) - PROPFIND :: http://myserver.com:8080/exist/webdav/db/apps/library/products/wbe/Media/mp/final/ - http://myserver.com:8080/exist/webdav/db/apps/library/products/wbe/Media/mp/final/
2017-01-10 17:00:29,284 [eXistThread-31] INFO  (MiltonResource.java [authorise]:350) - PROPFIND /db/apps/library/products/wbe/Media/mp/final (write=false)
2017-01-10 17:00:29,285 [eXistThread-31] INFO  (MiltonResource.java [authorise]:350) - PROPFIND /db/apps/library/products/wbe/Media/mp/final (write=false)
2017-01-10 17:00:29,696 [eXistThread-30] INFO  (HttpManager.java [process]:213) - PROPFIND :: http://myserver.com:8080/exist/webdav/db/apps/library/products/wbe/Media/vd/ - http://myserver.com:8080/exist/webdav/db/apps/library/products/wbe/Media/vd/
2017-01-10 17:00:29,697 [eXistThread-30] INFO  (MiltonResource.java [authorise]:350) - PROPFIND /db/apps/library/products/wbe/Media/vd (write=false)
2017-01-10 17:00:29,698 [eXistThread-30] INFO  (MiltonResource.java [authorise]:350) - PROPFIND /db/apps/library/products/wbe/Media/vd (write=false)
2017-01-10 17:00:29,724 [eXistThread-31] INFO  (HttpManager.java [process]:213) - PROPFIND :: http://myserver.com:8080/exist/webdav/db/apps/library/products/wbe/Media/vd/draft/ - http://myserver.com:8080/exist/webdav/db/apps/library/products/wbe/Media/vd/draft/
2017-01-10 17:00:29,724 [eXistThread-31] INFO  (MiltonResource.java [authorise]:350) - PROPFIND /db/apps/library/products/wbe/Media/vd/draft (write=false)
2017-01-10 17:00:29,725 [eXistThread-31] INFO  (MiltonResource.java [authorise]:350) - PROPFIND /db/apps/library/products/wbe/Media/vd/draft (write=false)
2017-01-10 17:00:29,775 [eXistThread-29] INFO  (HttpManager.java [process]:213) - PROPFIND :: http://myserver.com:8080/exist/webdav/db/apps/library/products/wbe/Media/vd/final/ - http://myserver.com:8080/exist/webdav/db/apps/library/products/wbe/Media/vd/final/
2017-01-10 17:00:29,776 [eXistThread-29] INFO  (MiltonResource.java [authorise]:350) - PROPFIND /db/apps/library/products/wbe/Media/vd/final (write=false)
2017-01-10 17:00:29,777 [eXistThread-29] INFO  (MiltonResource.java [authorise]:350) - PROPFIND /db/apps/library/products/wbe/Media/vd/final (write=false)
2017-01-10 17:00:30,624 [eXistThread-41] INFO  (HttpManager.java [process]:213) - PROPFIND :: http://myserver.com:8080/exist/webdav/db/apps/library/products/wbe/Media/mp/draft/ - http://myserver.com:8080/exist/webdav/db/apps/library/products/wbe/Media/mp/draft/
2017-01-10 17:00:30,625 [eXistThread-41] INFO  (MiltonResource.java [authorise]:350) - PROPFIND /db/apps/library/products/wbe/Media/mp/draft (write=false)
2017-01-10 17:00:30,626 [eXistThread-41] INFO  (MiltonResource.java [authorise]:350) - PROPFIND /db/apps/library/products/wbe/Media/mp/draft (write=false)

**Comment by zacheryt757** [comment]
(NativeBroker.java [removeXMLResource]:2641) - Removing document 213900.xml (27453) ...
2017-01-10 17:04:28,713 [eXistThread-31] DEBUG (RpcConnection.java [parse]:2264) - parsing /db/apps/library/products/wbe/Articles/wb03/final/213900.xml took 29ms.
2017-01-10 17:04:28,763 [eXistThread-41] INFO  (RpcConnection.java [doQuery]:335) - query took 0ms.
2017-01-10 17:04:28,763 [eXistThread-41] DEBUG (RpcConnection.java [queryP]:2854) - found 0
2017-01-10 17:04:28,813 [eXistThread-31] INFO  (NativeBroker.java [removeXMLResource]:2641) - Removing document 213900.xml (82711) ...
2017-01-10 17:04:28,821 [eXistThread-31] ERROR (Sender.java [createMessageFromExistMessageItem]:394) - No payload for replication
2017-01-10 17:04:28,826 [eXistThread-31] INFO  (RpcConnection.java [doQuery]:335) - query took 13ms.
2017-01-10 17:04:28,827 [eXistThread-31] DEBUG (RpcConnection.java [queryP]:2854) - found 0
2017-01-10 17:04:28,935 [eXistThread-30] INFO  (NativeBroker.java [sync]:3588) - Memory: 222,208K total; 7,456,768K max; 109,288K free
2017-01-10 17:04:28,935 [eXistThread-30] INFO  (BTree.java [printStatistics]:2549) - dom.dbx INDEX Buffers occupation : 100% (96 out of 96) Cache efficiency : 99%
2017-01-10 17:04:28,935 [eXistThread-30] INFO  (DOMFile.java [printStatistics]:1360) - dom.dbx DATA Buffers occupation : 99% (253 out of 256) Cache efficiency : 100%
2017-01-10 17:04:28,935 [eXistThread-30] INFO  (BTree.java [printStatistics]:2549) - collections.dbx INDEX Buffers occupation : 100% (96 out of 96) Cache efficiency : 100%
2017-01-10 17:04:28,935 [eXistThread-30] INFO  (BFile.java [printStatistics]:436) - collections.dbx DATA Buffers occupation : 81% (743 out of 921) Cache efficiency : 98%
2017-01-10 17:04:28,936 [eXistThread-30] INFO  (BTree.java [printStatistics]:2549) - values.dbx INDEX Buffers occupation : 0% (0 out of 64) Cache efficiency : N/A
2017-01-10 17:04:28,936 [eXistThread-30] INFO  (BFile.java [printStatistics]:436) - values.dbx DATA Buffers occupation : 0% (0 out of 64) Cache efficiency : N/A

**Comment by zacheryt757** [comment]
Sorry I am very green when it comes to administration of eXist. First time working with this product.

**Comment by dizzzz** [comment]
I think your database corrupted. you can run http://exist-db.org/exist/apps/doc/backup.xml#consistency-check to check and export your data...

**Comment by duncdrum** [comment]
@zacheryt757 it looks like you managed to save your db, if there is still an issue please open a new ticket. thx.
