### ISSUE TITLE
Inspecting KWIC module reports StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#1220]
Using a build of the current develop branch the following query:

```xquery
inspect:inspect-module-uri(xs:anyURI('http://exist-db.org/xquery/kwic'))
```

... returns the following error:

> 2017-01-11 13:26:54,013 [qtp1824570614-22] ERROR (XQueryServlet.java [process]:534) - String index out of range: -1 
> java.lang.StringIndexOutOfBoundsException: String index out of range: -1
> 	at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:237) ~[?:1.8.0_112]
> 	at java.lang.StringBuilder.charAt(StringBuilder.java:76) ~[?:1.8.0_112]
> 	at org.exist.xquery.xqdoc.parser.XQDocParser.contents(XQDocParser.java:148) ~[exist.jar:?]
> 	at org.exist.xquery.xqdoc.parser.XQDocParser.taggedContents(XQDocParser.java:107) ~[exist.jar:?]
> 	at org.exist.xquery.xqdoc.parser.XQDocParser.xqdocComment(XQDocParser.java:61) ~[exist.jar:?]
> 	at org.exist.xquery.xqdoc.XQDocHelper.parseComment(XQDocHelper.java:51) ~[exist.jar:?]
> 	at org.exist.xquery.xqdoc.XQDocHelper.parse(XQDocHelper.java:40) ~[exist.jar:?]
> 	at org.exist.xquery.functions.inspect.InspectModule.eval(InspectModule.java:71) ~[exist.jar:?]
> ...

No other modules return this problem. Only kwic has this problem, as confirmed by the following broader query:

```xquery
xquery version "3.1";

for $uri in (util:registered-modules(), util:mapped-modules())
return
    try 
        { 
            let $try := inspect:inspect-module-uri(xs:anyURI($uri)) 
            return (: we're only interested in the problems :) ()
        } 
    catch * 
        { 
            concat(
                'problem inspecting ', $uri, ': ', $err:code, ": ", 
                $err:description, ' (', $err:module, ' ', $err:line-number, ':', $err:column-number, ')'
            )
        }
```

**Comment by joewiz** [comment]
I discovered this when trying to use eXide's autocomplete feature with recent and current build of eXist. Using eXide (specifically, the current develop branch), I get an error when typing `con` and hitting control-space, instead of the expected suggestions like `concat`. 

This problem does not affect my build of the eXist develop branch rev. f111e4d from May (20160504123919). Using that build with eXide (again, using the current develop branch), the autocomplete appears as expected:

> <img width="361" alt="screen shot 2017-01-11 at 1 40 43 pm" src="https://cloud.githubusercontent.com/assets/59118/21861621/a0fda8d6-d803-11e6-86a4-67be4af068a7.png">

**Comment by dizzzz** [comment]
'''
org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:195)
	at org.exist.xmldb.LocalXPathQueryService.lambda$execute$1(LocalXPathQueryService.java:159)
	at org.exist.xmldb.function.LocalXmldbFunction.apply(LocalXmldbFunction.java:46)
	at org.exist.xmldb.AbstractLocal.withDb(AbstractLocal.java:195)
	at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:158)
	at org.exist.client.QueryDialog$QueryThread.run(QueryDialog.java:573)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:237)
	at java.lang.StringBuilder.charAt(StringBuilder.java:76)
	at org.exist.xquery.xqdoc.parser.XQDocParser.contents(XQDocParser.java:148)
	at org.exist.xquery.xqdoc.parser.XQDocParser.taggedContents(XQDocParser.java:107)
	at org.exist.xquery.xqdoc.parser.XQDocParser.xqdocComment(XQDocParser.java:61)
	at org.exist.xquery.xqdoc.XQDocHelper.parseComment(XQDocHelper.java:51)
	at org.exist.xquery.xqdoc.XQDocHelper.parse(XQDocHelper.java:40)
	at org.exist.xquery.functions.inspect.InspectModule.eval(InspectModule.java:71)
	at org.exist.xquery.BasicFunction.eval(BasicFunction.java:73)
	at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:41)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:276)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.XQuery.execute(XQuery.java:253)
	at org.exist.xquery.XQuery.execute(XQuery.java:185)
	at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:192)
	... 5 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:237)
	at java.lang.StringBuilder.charAt(StringBuilder.java:76)
	at org.exist.xquery.xqdoc.parser.XQDocParser.contents(XQDocParser.java:148)
	at org.exist.xquery.xqdoc.parser.XQDocParser.taggedContents(XQDocParser.java:107)
	at org.exist.xquery.xqdoc.parser.XQDocParser.xqdocComment(XQDocParser.java:61)
	at org.exist.xquery.xqdoc.XQDocHelper.parseComment(XQDocHelper.java:51)
	at org.exist.xquery.xqdoc.XQDocHelper.parse(XQDocHelper.java:40)
	at org.exist.xquery.functions.inspect.InspectModule.eval(InspectModule.java:71)
	at org.exist.xquery.BasicFunction.eval(BasicFunction.java:73)
	at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:41)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:276)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.XQuery.execute(XQuery.java:253)
	at org.exist.xquery.XQuery.execute(XQuery.java:185)
	at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:192)
	at org.exist.xmldb.LocalXPathQueryService.lambda$execute$1(LocalXPathQueryService.java:159)
	at org.exist.xmldb.function.LocalXmldbFunction.apply(LocalXmldbFunction.java:46)
	at org.exist.xmldb.AbstractLocal.withDb(AbstractLocal.java:195)
	at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:158)
	at org.exist.client.QueryDialog$QueryThread.run(QueryDialog.java:573)
'''

**Comment by joewiz** [comment]
Ah, sorry, should I have posted the full stack trace?

**Comment by dizzzz** [comment]
hmmmmm not sure yet :-)

**Comment by joewiz** [comment]
Thanks in advance for looking into this. It is preventing me from moving to current develop - since I rely on eXide's autocomplete (using current develop of eXide).

**Comment by dizzzz** [comment]
I filed a PR. it is maybe not completely clean, at least a check is added to prevent the exception
