### ISSUE TITLE
kwic returns null pointer exception

### ISSUE THREAD

**Issue by orazionelson** [eXist-db/exist#1234]
Hi all,
I'm using exist-db 2.2 stable.

I've a db with this structure:

archive
----folder1
--------document.1.1.xml
--------document.1.2.xml
--------document.1.3.xml
----folder2
--------document.2.1.xml
--------document.2.2.xml
--------document.2.3.xml

etc...

Each document has a structure like this:

`<?xml version="1.0" encoding="ISO-8859-1"?><?xml-stylesheet type="text/xsl" href="../my.xslt"?>
<EDITIO>
    <INFOED>
     .......
    </INFOED>
    <TENOR>
        <TESTO>
In eundem modum pro civibus Urbevetanis, et sub eadem forma civibus Perusinis, ultra festum Omnium Sanctorum in anno minime valiture.Regni nostri anno primo.XIII octobris.
       </TESTO>
    </TENOR>
    <NOTE/>
</EDITIO>`

I set up a full-text index with Lucene in collection.xconf 
`        <lucene>
            <analyzer class="org.apache.lucene.analysis.standard.StandardAnalyzer">
                <param name="stopwords" type="org.apache.lucene.analysis.util.CharArraySet"/>
            </analyzer>
            <text qname="INFOED"/>
            <text qname="TENOR"/>
            <text qname="INFOCUR"/>
        </lucene>`

A simple query works well:
`for $hit at $p in collection("/db/archive/folder1")/EDITIO//TENOR[ft:query(., 'Universis')]
     return
        $hit`

If I try to use KWIC:
1) Import the namespace 
`import module namespace kwic="http://exist-db.org/xquery/kwic";`
2) call in the function
`...
     return
         kwic:summarize($hit, <config width="40" table="yes"/>)`

I get an error:
`HTTP ERROR 500

Problem accessing /exist/apps/archive/searchres.html. Reason:

    An unknown error occurred: null
Caused by:

javax.servlet.ServletException: An unknown error occurred: null
	at org.exist.http.servlets.EXistServlet.doPost(EXistServlet.java:473)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:457)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:229)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:103)
	at org.exist.http.urlrewrite.Forward.doRewrite(Forward.java:50)
	at org.exist.http.urlrewrite.XQueryURLRewrite.doRewrite(XQueryURLRewrite.java:567)
	at org.exist.http.urlrewrite.XQueryURLRewrite.applyViews(XQueryURLRewrite.java:416)
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:362)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1448)
	at de.betterform.agent.web.filter.XFormsFilter.doFilter(XFormsFilter.java:164)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:368)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:488)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:932)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:994)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:640)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
Caused by:

java.lang.NullPointerException
Powered by Jetty://`

Why? :(

**Comment by joewiz** [comment]
Could you please check exist.log (in `$EXIST_HOME/webapp/WEB-INF/logs`) to see if it has any more detailed information about this error?

**Comment by orazionelson** [comment]
hi @joewiz, 
 when I load the page with the error, in the exist.log file the only line added is:
`2017-01-20 22:49:48,266 [eXistThread-1263] ERROR (EXistServlet.java [doPost]:472) - java.lang.NullPointerException `

Looking at monitoring and profiling tool it seems tha my collection is not indexed at all
![monitoring and profiling for exist](https://cloud.githubusercontent.com/assets/113308/22167168/f106b292-df64-11e6-9b4f-2a20b8e7e1d5.png)

**Comment by adamretter** [comment]
@orazionelson Can you tell us if you get the same error on the latest nightly build?

**Comment by orazionelson** [comment]
thanks to all, I solved,
I was wrong a path in my application
shame on me :)

**Comment by joewiz** [comment]
Good to hear, but I don't think you should ever get a null pointer exception. If you can reproduce this result with the current develop branch or latest nightly and are so inclined, please post an issue.

**Comment by dizzzz** [comment]
Alfredo,

Like Joe said, NullPointerExceptions should never happen. 

You enclosed the stacktrace as printed in the webbrowser, but this does not help too much; please could you check exist.log and check what the 2nd part of the stacktrace is about?

regards

Dannes

**Comment by orazionelson** [comment]
Hi all,
@dizzzz the only line in the exist.log that I can relate with the error is:
2017-01-20 22:49:48,266 [eXistThread-1263] ERROR (EXistServlet.java [doPost]:472) - java.lang.NullPointerException

I don't know why. :o 

I can't install a nightly build and replicate the error, but it depends by a bad value passed to **kwic:summarize** function. 
The results passed to the function came from a non-indexed collection in db root:
**/db/archive**
I moved archive/ in the data directory of myapp/
**/db/apps/myapp/data/archive/**
- then I relaunched the indexing
- then I edited the data root of myapp

and almos everything works
Thanks,
A.
