### ISSUE TITLE
The system.properties file causes errors when running from source

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#1278]
When you run eXist-db from a source code build (command line or IntelliJ), the file `$EXIST_HOME/src/org/exist/system.properties` file is not correctly populated and added to the classpath.

The `system.properties` file contains:
```
vendor=eXist-db Project
vendor-url=http://exist-db.org
product-name=eXist
product-version=@version@
product-semver=@semver@
product-build=@build@
git-commit=@git.commit@
```

Unfortunately this means that features with dependencies on these properties break.
For example you cannot install packages from the Dashboard's PackageManager, instead you get errors in `exist.log`:

```
2017-02-23 15:32:47,344 [qtp651992021-119] ERROR (Deploy.java [installAndDeploy]:194) - Invalid SemVer pattern '@semver@': first part is not a number 
org.expath.pkg.repo.PackageException: Invalid SemVer pattern '@semver@': first part is not a number
	at org.expath.pkg.repo.deps.Semver.parseError(Semver.java:214) ~[pkg-java-fork.jar:?]
	at org.expath.pkg.repo.deps.Semver.parse(Semver.java:183) ~[pkg-java-fork.jar:?]
	at org.expath.pkg.repo.deps.Semver.<init>(Semver.java:37) ~[pkg-java-fork.jar:?]
	at org.expath.pkg.repo.deps.DepSemverMinMax.isCompatible(DepSemverMinMax.java:33) ~[pkg-java-fork.jar:?]
	at org.exist.repo.Deployment.checkProcessorVersion(Deployment.java:291) ~[eXist-db/:?]
	at org.exist.repo.Deployment.installAndDeploy(Deployment.java:217) ~[eXist-db/:?]
	at org.exist.repo.Deployment.installAndDeploy(Deployment.java:163) ~[eXist-db/:?]
	at org.exist.xquery.modules.expathrepo.Deploy.installAndDeploy(Deploy.java:188) [eXist-db/:?]
	at org.exist.xquery.modules.expathrepo.Deploy.eval(Deploy.java:163) [eXist-db/:?]
	at org.exist.xquery.BasicFunction.eval(BasicFunction.java:73) [eXist-db/:?]
	at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:41) [eXist-db/:?]
```

A better solution is required...

**Comment by adamretter** [comment]
This is fixed by the Mavenized build of eXist-db.
