### ISSUE TITLE
Unable to inject fields into builder class for plugin type class ...appender.ConsoleAppender, element Console.

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#1314]
### What is the problem
Log4j2 related stacktrace during eXist-db startup, in windows7

### What did you expect
no stacktrace during startup

### Describe how to reproduce or add a test
`bin\startup.bat`
`tools\yajsw\bin\runConsole.bat`

### Context information
- eXist-db version :  eXist-db 3.0 /  2fc3306  
- Java version : (Java8u121)
- Operating system : (Windows 7)
- 64 bit

on macOS the start was 'clean' when the log4j2 update was pulled in!

```
WARNING|wrapper|eXist-db|17-03-03 10:48:20|YAJSW: yajsw-stable-12.08
WARNING|wrapper|eXist-db|17-03-03 10:48:20|OS   : Windows 7/6.1/x86
WARNING|wrapper|eXist-db|17-03-03 10:48:20|JVM  : Oracle Corporation/1.8.0_121/C:\Program Files (x86)\Java\jre1.8.0_121/32
system.env 75
INFO|wrapper|eXist-db|17-03-03 10:48:42|started process with pid 10056
INFO|10056/0|eXist-db|17-03-03 10:48:42|[INFO] StandardFileSystemManager - Using "C:\Users\XXXXXXX\AppData\Local\Temp\vfs_cache" as temporary files s
tore.
INFO|10056/0|eXist-db|17-03-03 10:48:43|2017-03-03 10:48:43,377 main ERROR Unable to inject fields into builder class for plugin type class org.apache
.logging.log4j.core.appender.ConsoleAppender, element Console. java.nio.charset.UnsupportedCharsetException: sun.stdout.encoding
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at java.nio.charset.Charset.forName(Charset.java:531)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.util.PropertiesUtil.getCharsetProperty(PropertiesUtil.java:146)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.util.PropertiesUtil.getCharsetProperty(PropertiesUtil.java:134)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.appender.ConsoleAppender$Target.getCharset(ConsoleAppender.java:85)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.appender.ConsoleAppender$Target$1.getDefaultCharset(ConsoleAppender.j
ava:71)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.appender.ConsoleAppender$Builder.build(ConsoleAppender.java:218)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.appender.ConsoleAppender$Builder.build(ConsoleAppender.java:185)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration
.java:952)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguratio
n.java:892)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguratio
n.java:884)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:5
08)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:23
2)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:244)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:152)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:551)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.exist.jetty.JettyStart.<clinit>(JettyStart.java:74)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45
)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at java.lang.Class.newInstance(Class.java:442)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.exist.yajsw.Main.start(Main.java:40)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.exist.yajsw.Main.main(Main.java:65)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at java.lang.reflect.Method.invoke(Method.java:498)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
INFO|10056/0|eXist-db|17-03-03 10:48:43|
INFO|10056/0|eXist-db|17-03-03 10:48:43|2017-03-03 10:48:43,380 main ERROR Unable to invoke factory method in class class org.apache.logging.log4j.cor
e.appender.ConsoleAppender for element Console. java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appen
der.ConsoleAppender
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.jav
a:224)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:130)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration
.java:952)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguratio
n.java:892)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguratio
n.java:884)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:5
08)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:23
2)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:244)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:152)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:551)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.exist.jetty.JettyStart.<clinit>(JettyStart.java:74)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45
)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at java.lang.Class.newInstance(Class.java:442)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.exist.yajsw.Main.start(Main.java:40)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.exist.yajsw.Main.main(Main.java:65)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at java.lang.reflect.Method.invoke(Method.java:498)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
INFO|10056/0|eXist-db|17-03-03 10:48:43|        at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
INFO|10056/0|eXist-db|17-03-03 10:48:43|
INFO|10056/0|eXist-db|17-03-03 10:48:43|2017-03-03 10:48:43,422 main ERROR Null object returned for Console in Appenders.
INFO|10056/0|eXist-db|17-03-03 10:48:43|2017-03-03 10:48:43,433 main ERROR Unable to locate appender "STDOUT" for logger config "org.exist.jetty.Jetty
Start"
INFO|10056/0|eXist-db|17-03-03 10:48:43|2017-03-03 10:48:43,433 main ERROR Unable to locate appender "STDOUT" for logger config "org.exist.jetty.Stand
aloneServer"
INFO|10056/0|eXist-db|17-03-03 10:48:44|Mar 03, 2017 10:48:44 AM org.expath.pkg.repo.tools.Logger info
```

--> it looks like a 32bit JRE is used?

```
java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) Client VM (build 25.121-b13, mixed mode, sharing)

echo %JAVA_HOME%
C:\XXXXXX\Program Files\Java\jdk1.8.0_121
```

**Comment by dizzzz** [comment]
It seems to be only an issue in windows....

**Comment by joewiz** [comment]
Crazy! Things can go wrong in the strangest problem. Reminds me of that annoying problem with the rolling logger in the wrapper that was ultimately due to a problem in lib c.

**Comment by TheNilesh** [comment]
Issue with 2.8.7 build

**Comment by adamretter** [comment]
@TheNilesh eXist 3.0.0 ships with log4j 2.7.

The latest log4j is 2.8.1. We ship with 2.8.1 in eXist-3.1.0. Could you upgrade to 3.1.0 and see if you have the same problem?

**Comment by dizzzz** [comment]
@TheNilesh sorry no idea what you mean with the oneliner? what is "2.8.7" ? What issue do you see? how to repeat? do you have logs?

**Comment by agwidarsito** [comment]
I had same problem: make sure you launch the bat file from a CMD that is launched as administrator :)

**Comment by dizzzz** [comment]
@agwidarsito  you are referring to an old and closed issue. please can you describe what you mean in more details? Your oneliner without context is not really understandable (for me).
