### ISSUE TITLE
Failed to execute eXist Ant store task <xdb:store>

### ISSUE THREAD

**Issue by dovikos** [eXist-db/exist#1380]
### What is the problem
Executing Ant store task `<xdb:store>` fails.

### What did you expect
I expect the task to execute without error and to store some documents.

### Describe how to reproduce or add a test
- Prepare an Ant task in a `build.xml` file, similar to this:

```xml
<target name="ImportData" description="Create a new collection and import data into it">
	<echo>Importing data to new collection</echo>
	<xdb:store uri="${BaseUri}/${to-collection}" user="${Username}" password="${Password}" 
initdb="true" createcollection="true">
		<fileset dir="${from-directory}" includes="*.xml"/>
	</xdb:store>
</target>
```
In the same file, configure the variables `${BaseUri}`, `${Username}` and `${Password}`.

- Create a "sample" directory containing one or more XML documents.

- Start eXist-db.

- In a prompt opened on the directory storing the build.xml, execute the command:
`ant -Dfrom-directory=sample -Dto-collection=myCollection ImportData`
- The task fails. Here is the stacktrace:

<pre>ImportData:
     [echo] Importing data to new collection
[xdb:store] Database driver registered.
[xdb:store] Found 0 directories and 1 files.
[xdb:store] Storing dummy_test.xml ...

BUILD FAILED
C:\[path to Ant task]\build.xml:109: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/[path to my eXist home]/conf.xml
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at org.exist.util.ConfigurationHelper.getExistHome(ConfigurationHelper.java:97)
        at org.exist.util.ConfigurationHelper.getExistHome(ConfigurationHelper.java:32)
        at org.exist.util.ConfigurationHelper.lookup(ConfigurationHelper.java:139)
        at org.exist.util.ConfigurationHelper.lookup(ConfigurationHelper.java:116)
        at org.exist.util.MimeTable.load(MimeTable.java:212)
        at org.exist.util.MimeTable.<init>(MimeTable.java:113)
        at org.exist.util.MimeTable.getInstance(MimeTable.java:81)
        at org.exist.ant.XMLDBStoreTask.getMimeTable(XMLDBStoreTask.java:391)
        at org.exist.ant.XMLDBStoreTask.execute(XMLDBStoreTask.java:280)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:857)
        at org.apache.tools.ant.Main.startAnt(Main.java:236)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)

Total time: 1 second
</pre>

### Context information
- eXist-db version + Git Revision hash: eXist-db 3.1 /  [`c679cd8`](https://github.com/eXist-db/exist/commit/c679cd8a1fb991a2c9f10b8196d30cd9cf864792) 
- Java version: Java8u121
- Operating system: Windows 7
- 64 bit
- No custom changes

**Comment by joewiz** [comment]
Please attach a complete build.xml file that exhibits the problem.

**Comment by joewiz** [comment]
Also, can you confirm that you followed the documentation at http://exist-db.org/exist/apps/doc/ant-tasks.xml?

**Comment by dovikos** [comment]
Hi @joewiz. Yes I followed this documentation.
But looking at this again, I found the the line that make the task failed.

Here is the complete `build.xml` file: the last `<pathelement>` inside `<path>` tag is causing the error. Removing it succeeds the task... ✔

```xml
<project xmlns:xdb="http://exist-db.org/ant" name="eXistExample-1" basedir="." default="ImportData">

    <property name="BaseUri" value="xmldb:exist://localhost:8080/exist/xmlrpc/db/"/>
    <property name="Username" value="admin"/>
    <property name="Password" value="admin"/>

    <property environment="Env"/>
    <fail unless="Env.EXIST_HOME">Environment variable EXIST_HOME not set</fail>

    <path id="classpath.core">
        <fileset dir="${Env.EXIST_HOME}/lib/core">
            <include name="*.jar"/>
        </fileset>
        <pathelement path="${Env.EXIST_HOME}/exist.jar"/>
        <pathelement path="${Env.EXIST_HOME}/exist-optional.jar"/>
        <pathelement path="${Env.EXIST_HOME}"/>
    </path>
    
    <typedef resource="org/exist/ant/antlib.xml" uri="http://exist-db.org/ant">
        <classpath refid="classpath.core"/>
    </typedef>

  <!-- ================================================================== -->
  <!-- Import new collection -->
  <!-- -->
    <target name="ImportData" description="Create a new collection and import data into it">
        <echo>Importing data to new collection</echo>
		<xdb:store uri="${BaseUri}/${to-collection}" user="${Username}" password="${Password}" initdb="true" createcollection="true">
			<fileset dir="${from-directory}" includes="*.xml"/>
		</xdb:store>
    </target>
  <!-- -->

</project>
```

Thanks for support
Dovikos
