### ISSUE TITLE
NPE in Security Manager

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#1384]
### What is the problem
During restore of a `3.0RC` generated backup into `3.2.0-SNAPSHOT` there is a NPE, see below; as a result eXide has not been stored correctly, the administration in `WEB-INF\data\expathrepo\.expath-pkg` is incorrect. 

```
2017-03-27 09:10:39,774 [pool-3-thread-1] INFO  (Configurator.java [save]:1280) - Storing configuration /db/system/security/exist/accounts/admin.xml 
2017-03-27 09:10:39,785 [pool-3-thread-1] INFO  (NativeBroker.java [removeXMLResource]:2707) - Removing document admin.xml (3) ... 
2017-03-27 09:10:39,915 [pool-3-thread-1] INFO  (NativeBroker.java [removeXMLResource]:2707) - Removing document config.xml (2) ... 
2017-03-27 09:10:39,932 [pool-3-thread-1] INFO  (NativeBroker.java [removeXMLResource]:2707) - Removing document admin.xml (3) ... 
2017-03-27 09:10:39,944 [pool-3-thread-1] INFO  (NativeBroker.java [removeXMLResource]:2707) - Removing document guest.xml (4) ... 
2017-03-27 09:10:39,957 [pool-3-thread-1] INFO  (NativeBroker.java [removeXMLResource]:2707) - Removing document monex.xml (743) ... 
2017-03-27 09:10:39,967 [pool-3-thread-1] INFO  (NativeBroker.java [removeXMLResource]:2707) - Removing document eXide.xml (541) ... 
2017-03-27 09:10:39,984 [pool-3-thread-1] ERROR (DocumentTriggers.java [afterCreateDocument]:238) - null 
java.lang.NullPointerException: null
	at org.exist.security.internal.SecurityManagerImpl.lambda$processPramatter$12(SecurityManagerImpl.java:902) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.security.internal.SecurityManagerImpl$PrincipalDbById.modify(SecurityManagerImpl.java:1008) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.security.internal.SecurityManagerImpl.processPramatter(SecurityManagerImpl.java:901) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.config.ConfigurationDocumentTrigger.afterCreateDocument(ConfigurationDocumentTrigger.java:148) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.collections.triggers.DocumentTriggers.afterCreateDocument(DocumentTriggers.java:236) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.collections.MutableCollection.storeXMLInternal(MutableCollection.java:1259) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.collections.MutableCollection.store(MutableCollection.java:1120) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.xmldb.LocalCollection.lambda$storeXMLResource$13(LocalCollection.java:583) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.xmldb.function.LocalXmldbCollectionFunction.apply(LocalXmldbCollectionFunction.java:48) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.xmldb.LocalCollection.lambda$null$22(LocalCollection.java:729) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.xmldb.function.LocalXmldbCollectionFunction.apply(LocalXmldbCollectionFunction.java:48) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.xmldb.AbstractLocal.lambda$with$6(AbstractLocal.java:172) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.xmldb.AbstractLocal.lambda$null$4(AbstractLocal.java:118) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.xmldb.function.LocalXmldbFunction.apply(LocalXmldbFunction.java:46) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.xmldb.AbstractLocal.withDb(AbstractLocal.java:195) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.xmldb.AbstractLocal.lambda$modify$5(AbstractLocal.java:118) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.xmldb.LocalCollection.lambda$modify$23(LocalCollection.java:727) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.xmldb.LocalCollection.storeXMLResource(LocalCollection.java:552) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.xmldb.LocalCollection.storeResource(LocalCollection.java:502) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.backup.restore.RestoreHandler.restoreResourceEntry(RestoreHandler.java:392) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:122) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.exist.backup.restore.RestoreHandler.restoreSubCollectionEntry(RestoreHandler.java:255) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:128) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.exist.backup.restore.RestoreHandler.restoreSubCollectionEntry(RestoreHandler.java:255) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:128) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.exist.backup.restore.RestoreHandler.restoreSubCollectionEntry(RestoreHandler.java:255) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:128) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
	at org.exist.backup.Restore.restore(Restore.java:87) ~[exist.jar:3.2.0-SNAPSHOT]
	at org.exist.client.ClientFrame.lambda$doRestore$17(ClientFrame.java:1143) ~[exist.jar:3.2.0-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2017-03-27 09:10:40,008 [pool-3-thread-1] INFO  (NativeBroker.java [removeXMLResource]:2707) - Removing document eXide.xml (540) ... 
2017-03-27 09:10:40,011 [pool-3-thread-1] ERROR (SecurityManagerImpl.java [processPramatter]:930) - Group 'eXide' pressent at 'exist' realm, but get event that new one created. 
2017-03-27 09:10:40,034 [pool-3-thread-1] INFO  (NativeBroker.java [removeXMLResource]:2707) - Removing document monex.xml (742) ... 
2017-03-27 09:10:40,036 [pool-3-thread-1] ERROR (SecurityManagerImpl.java [processPramatter]:930) - Group 'monex' pressent at 'exist' realm, but get event that new one created. 
2017-03-27 09:10:40,051 [pool-3-thread-1] INFO  (NativeBroker.java [removeXMLResource]:2707) - Removing document collection.xconf (1) ... 
2017-03-27 09:10:40,085 [pool-3-thread-1] WARN  (TransactionManager.java [close]:186) - Transaction was not committed or aborted, auto aborting! 
```

### What did you expect

The restore of a backup must be without any exceptions. I can provide the file upon request, offline.

### Describe how to reproduce or add a test

Restore a backup containing an older version of the eXide application.

### Context information
Please always add the following information
- eXist-db 3.2.0-SNAPSHOT (2017-03-17)
- Java version (Java8u121)
- Operating system (Windows 7)
- 64 bit
- Any custom changes in e.g. conf.xml : None

**Comment by duncdrum** [comment]
@dizzzz can you try this again with 4.2.1. I think this could be fixed now.

**Comment by adamretter** [comment]
@dizzzz I think this is very likely solved in 5.0.0-RC1. Note sure about 4.2.1...

**Comment by adamretter** [comment]
@dizzzz Were you able to test this on 4.3.0 and 5.0.0-RC1?

**Comment by dizzzz** [comment]
I'll do so

**Comment by adamretter** [comment]
@dizzzz any update please?

**Comment by dizzzz** [comment]
Afaik no issue
