### ISSUE TITLE
Long time locking for threads in NativeStructuralIndexWorker

### ISSUE THREAD

**Issue by alebastrov** [eXist-db/exist#1400]
As you can see in threaddump below we have 1 thread which aquired READ lock and processing (NativeStructuralIndexWorker.findDescendantsByTagName) and the similar thread which wants to acquire READ lock, but no success, and 2 threads which are waiting to acquire WRITE lock (NativeStructuralIndexWorker.getQNamesForDoc)

It looks very strange because lock is ReentrantReadWriteLock which allows to read in parallel
~~~
"[Resolving refs early] 'publish_performance_o08-bg'" #533 prio=5 os_prio=0 tid=0x000000003ccf5000 nid=0x3094 in Object.wait() [0x000000005d3bd000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.exist.storage.lock.ReentrantReadWriteLock.acquire(ReentrantReadWriteLock.java:147)
	- locked <0x0000000096659840> (a org.exist.storage.lock.ReentrantReadWriteLock)
	at org.exist.storage.structural.NativeStructuralIndexWorker.findDescendantsByTagName(NativeStructuralIndexWorker.java:140)
	at org.exist.xquery.LocationStep.getAttributes(LocationStep.java:647)
	at org.exist.xquery.LocationStep.eval(LocationStep.java:435)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.GeneralComparison.quickNodeSetCompare(GeneralComparison.java:683)
	at org.exist.xquery.GeneralComparison.eval(GeneralComparison.java:464)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
	at org.exist.xquery.OpAnd.eval(OpAnd.java:69)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
	at org.exist.xquery.Predicate.selectByNodeSet(Predicate.java:446)
	at org.exist.xquery.Predicate.evalPredicate(Predicate.java:326)
	at org.exist.xquery.LocationStep.processPredicate(LocationStep.java:252)
	at org.exist.xquery.LocationStep.applyPredicate(LocationStep.java:239)
	at org.exist.xquery.LocationStep.eval(LocationStep.java:463)
	at org.exist.xquery.pragmas.Optimize.eval(Optimize.java:172)
	at org.exist.xquery.ExtensionExpression.eval(ExtensionExpression.java:70)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
	at org.exist.xquery.DynamicCardinalityCheck.eval(DynamicCardinalityCheck.java:74)
	at org.exist.xquery.functions.fn.FunData.eval(FunData.java:81)
	at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:56)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.XQuery.execute(XQuery.java:297)
	at org.exist.xquery.XQuery.execute(XQuery.java:217)
	at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:452)
	at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:157)
	at com.sdl.cd.livecontent.repository.DBDAO.queryCollection(DBDAO.java:572)
	at com.sdl.cd.livecontent.repository.ContentDao.queryCollection(ContentDao.java:383)
	at com.sdl.cd.livecontent.repository.ContentDao.getHrefForKeydef(ContentDao.java:1716)
	at com.sdl.cd.livecontent.services.publishing.graph.impl.ConrefAndConkeyrefGraphBuilderImpl.getGraphFileNameFromKeydef(ConrefAndConkeyrefGraphBuilderImpl.java:73)
	at com.sdl.cd.livecontent.services.publishing.graph.impl.ConrefAndConkeyrefGraphBuilderImpl.getGraphFileNameFromKeydef(ConrefAndConkeyrefGraphBuilderImpl.java:21)
	at com.sdl.cd.livecontent.repository.ContentDao.setFileNameViaReferenceType(ContentDao.java:896)
	at com.sdl.cd.livecontent.repository.ContentDao$3.apply(ContentDao.java:845)
	at com.sdl.cd.livecontent.repository.ContentDao$3.apply(ContentDao.java:824)
	at com.sdl.cd.livecontent.util.walker.ResourceSetWalker$2.apply(ResourceSetWalker.java:47)
	at com.sdl.cd.livecontent.util.walker.ResourceSetWalker$2.apply(ResourceSetWalker.java:44)
	at com.sdl.cd.livecontent.util.walker.ResourceSetWalker.forEach(ResourceSetWalker.java:92)
	at com.sdl.cd.livecontent.util.walker.ResourceSetWalker.forEachResource(ResourceSetWalker.java:44)
	at com.sdl.cd.livecontent.repository.ContentDao.getDocumentNameForFoundDocumentsByXpath(ContentDao.java:1167)
	at com.sdl.cd.livecontent.repository.ContentDao.addReferencesForConkeyref(ContentDao.java:1148)
	at com.sdl.cd.livecontent.services.content.impl.GraphServiceImpl.getDocumentIdsForContentReferences(GraphServiceImpl.java:695)
	at com.sdl.cd.livecontent.services.content.impl.GraphServiceImpl.processReferences(GraphServiceImpl.java:676)
	at com.sdl.cd.livecontent.services.resolve_refs_earlier.impl.ResolveRefsEarlyService.resolveReferences(ResolveRefsEarlyService.java:805)
	at com.sdl.cd.livecontent.services.resolve_refs_earlier.impl.ResolveRefsEarlyService.resolveRefsEarly(ResolveRefsEarlyService.java:781)
	at com.sdl.cd.livecontent.services.resolve_refs_earlier.impl.ResolveRefsEarlyService.resolveRefsEarly(ResolveRefsEarlyService.java:82)
	at com.sdl.cd.livecontent.controllers.PublishingController$4.produce(PublishingController.java:133)
	at com.sdl.cd.livecontent.stream.impl.LongTimeResponseServiceImpl.performProcess(LongTimeResponseServiceImpl.java:75)
	at com.sdl.cd.livecontent.stream.impl.LongTimeResponseServiceImpl.lambda$prepareAndStartProcess$31(LongTimeResponseServiceImpl.java:65)
	at com.sdl.cd.livecontent.stream.impl.LongTimeResponseServiceImpl$$Lambda$21/162200793.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x00000000efd72e10> (a java.util.concurrent.ThreadPoolExecutor$Worker) 
	
	"[Resolving refs early] 'publish_performance_o07-ba'" #526 prio=5 os_prio=0 tid=0x000000003ccf2000 nid=0x2f94 runnable [0x000000005bd1d000]
   java.lang.Thread.State: RUNNABLE
	at org.exist.storage.cache.BTreeCache.add(BTreeCache.java:42)
	at org.exist.storage.cache.BTreeCache.add(BTreeCache.java:38)
	at org.exist.storage.btree.BTree.getBTreeNode(BTree.java:465)
	at org.exist.storage.btree.BTree.access$0(BTree.java:456)
	at org.exist.storage.btree.BTree$BTreeNode.getChildNode(BTree.java:1364)
	at org.exist.storage.btree.BTree$BTreeNode.query(BTree.java:1761)
	at org.exist.storage.btree.BTree$BTreeNode.query(BTree.java:1761)
	at org.exist.storage.btree.BTree$BTreeNode.access$12(BTree.java:1736)
	at org.exist.storage.btree.BTree.query(BTree.java:381)
	at org.exist.storage.structural.NativeStructuralIndexWorker.findDescendantsByTagName(NativeStructuralIndexWorker.java:155)
	at org.exist.xquery.LocationStep.getAttributes(LocationStep.java:647)
	at org.exist.xquery.LocationStep.eval(LocationStep.java:435)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.GeneralComparison.quickNodeSetCompare(GeneralComparison.java:683)
	at org.exist.xquery.GeneralComparison.eval(GeneralComparison.java:464)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
	at org.exist.xquery.OpAnd.eval(OpAnd.java:69)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
	at org.exist.xquery.Predicate.selectByNodeSet(Predicate.java:446)
	at org.exist.xquery.Predicate.evalPredicate(Predicate.java:326)
	at org.exist.xquery.LocationStep.processPredicate(LocationStep.java:252)
	at org.exist.xquery.LocationStep.applyPredicate(LocationStep.java:239)
	at org.exist.xquery.LocationStep.eval(LocationStep.java:463)
	at org.exist.xquery.pragmas.Optimize.eval(Optimize.java:172)
	at org.exist.xquery.ExtensionExpression.eval(ExtensionExpression.java:70)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
	at org.exist.xquery.DynamicCardinalityCheck.eval(DynamicCardinalityCheck.java:74)
	at org.exist.xquery.functions.fn.FunData.eval(FunData.java:81)
	at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:56)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.XQuery.execute(XQuery.java:297)
	at org.exist.xquery.XQuery.execute(XQuery.java:217)
	at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:452)
	at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:157)
	at com.sdl.cd.livecontent.repository.DBDAO.queryCollection(DBDAO.java:572)
	at com.sdl.cd.livecontent.repository.ContentDao.queryCollection(ContentDao.java:383)
	at com.sdl.cd.livecontent.repository.ContentDao.getHrefForKeydef(ContentDao.java:1716)
	at com.sdl.cd.livecontent.services.publishing.graph.impl.ConrefAndConkeyrefGraphBuilderImpl.getGraphFileNameFromKeydef(ConrefAndConkeyrefGraphBuilderImpl.java:73)
	at com.sdl.cd.livecontent.services.publishing.graph.impl.ConrefAndConkeyrefGraphBuilderImpl.getGraphFileNameFromKeydef(ConrefAndConkeyrefGraphBuilderImpl.java:21)
	at com.sdl.cd.livecontent.repository.ContentDao.setFileNameViaReferenceType(ContentDao.java:896)
	at com.sdl.cd.livecontent.repository.ContentDao$3.apply(ContentDao.java:845)
	at com.sdl.cd.livecontent.repository.ContentDao$3.apply(ContentDao.java:824)
	at com.sdl.cd.livecontent.util.walker.ResourceSetWalker$2.apply(ResourceSetWalker.java:47)
	at com.sdl.cd.livecontent.util.walker.ResourceSetWalker$2.apply(ResourceSetWalker.java:44)
	at com.sdl.cd.livecontent.util.walker.ResourceSetWalker.forEach(ResourceSetWalker.java:92)
	at com.sdl.cd.livecontent.util.walker.ResourceSetWalker.forEachResource(ResourceSetWalker.java:44)
	at com.sdl.cd.livecontent.repository.ContentDao.getDocumentNameForFoundDocumentsByXpath(ContentDao.java:1167)
	at com.sdl.cd.livecontent.repository.ContentDao.addReferencesForConkeyref(ContentDao.java:1148)
	at com.sdl.cd.livecontent.services.content.impl.GraphServiceImpl.getDocumentIdsForContentReferences(GraphServiceImpl.java:695)
	at com.sdl.cd.livecontent.services.content.impl.GraphServiceImpl.processReferences(GraphServiceImpl.java:676)
	at com.sdl.cd.livecontent.services.resolve_refs_earlier.impl.ResolveRefsEarlyService.resolveReferences(ResolveRefsEarlyService.java:805)
	at com.sdl.cd.livecontent.services.resolve_refs_earlier.impl.ResolveRefsEarlyService.resolveRefsEarly(ResolveRefsEarlyService.java:781)
	at com.sdl.cd.livecontent.services.resolve_refs_earlier.impl.ResolveRefsEarlyService.resolveRefsEarly(ResolveRefsEarlyService.java:82)
	at com.sdl.cd.livecontent.controllers.PublishingController$4.produce(PublishingController.java:133)
	at com.sdl.cd.livecontent.stream.impl.LongTimeResponseServiceImpl.performProcess(LongTimeResponseServiceImpl.java:75)
	at com.sdl.cd.livecontent.stream.impl.LongTimeResponseServiceImpl.lambda$prepareAndStartProcess$31(LongTimeResponseServiceImpl.java:65)
	at com.sdl.cd.livecontent.stream.impl.LongTimeResponseServiceImpl$$Lambda$21/162200793.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x00000000ef99e600> (a java.util.concurrent.ThreadPoolExecutor$Worker) 
	
	"[Resolving refs early] 'publish_performance_o06-af'" #524 prio=5 os_prio=0 tid=0x000000003ccf1000 nid=0x2a7c in Object.wait() [0x000000003fb6d000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.exist.storage.lock.ReentrantReadWriteLock.acquire(ReentrantReadWriteLock.java:147)
	- locked <0x0000000096659840> (a org.exist.storage.lock.ReentrantReadWriteLock)
	at org.exist.storage.structural.NativeStructuralIndexWorker.getQNamesForDoc(NativeStructuralIndexWorker.java:494)
	at org.exist.storage.structural.NativeStructuralIndexWorker.scanByType(NativeStructuralIndexWorker.java:222)
	at org.exist.dom.VirtualNodeSet.getNodesFromIndex(VirtualNodeSet.java:457)
	at org.exist.dom.VirtualNodeSet.realize(VirtualNodeSet.java:585)
	at org.exist.dom.VirtualNodeSet.unorderedIterator(VirtualNodeSet.java:878)
	at org.exist.xquery.value.AbstractSequence.setSelfAsContext(AbstractSequence.java:249)
	at org.exist.xquery.OpAnd.eval(OpAnd.java:67)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
	at org.exist.xquery.Predicate.selectByNodeSet(Predicate.java:446)
	at org.exist.xquery.Predicate.evalPredicate(Predicate.java:326)
	at org.exist.xquery.LocationStep.processPredicate(LocationStep.java:252)
	at org.exist.xquery.LocationStep.applyPredicate(LocationStep.java:239)
	at org.exist.xquery.LocationStep.eval(LocationStep.java:463)
	at org.exist.xquery.pragmas.Optimize.eval(Optimize.java:172)
	at org.exist.xquery.ExtensionExpression.eval(ExtensionExpression.java:70)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
	at org.exist.xquery.DynamicCardinalityCheck.eval(DynamicCardinalityCheck.java:74)
	at org.exist.xquery.functions.fn.FunData.eval(FunData.java:81)
	at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:56)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.XQuery.execute(XQuery.java:297)
	at org.exist.xquery.XQuery.execute(XQuery.java:217)
	at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:452)
	at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:157)
	at com.sdl.cd.livecontent.repository.DBDAO.queryCollection(DBDAO.java:572)
	at com.sdl.cd.livecontent.repository.ContentDao.queryCollection(ContentDao.java:383)
	at com.sdl.cd.livecontent.repository.ContentDao.getHrefForKeydef(ContentDao.java:1716)
	at com.sdl.cd.livecontent.services.publishing.graph.impl.ConrefAndConkeyrefGraphBuilderImpl.getGraphFileNameFromKeydef(ConrefAndConkeyrefGraphBuilderImpl.java:73)
	at com.sdl.cd.livecontent.services.publishing.graph.impl.ConrefAndConkeyrefGraphBuilderImpl.getGraphFileNameFromKeydef(ConrefAndConkeyrefGraphBuilderImpl.java:21)
	at com.sdl.cd.livecontent.repository.ContentDao.setFileNameViaReferenceType(ContentDao.java:896)
	at com.sdl.cd.livecontent.repository.ContentDao$3.apply(ContentDao.java:845)
	at com.sdl.cd.livecontent.repository.ContentDao$3.apply(ContentDao.java:824)
	at com.sdl.cd.livecontent.util.walker.ResourceSetWalker$2.apply(ResourceSetWalker.java:47)
	at com.sdl.cd.livecontent.util.walker.ResourceSetWalker$2.apply(ResourceSetWalker.java:44)
	at com.sdl.cd.livecontent.util.walker.ResourceSetWalker.forEach(ResourceSetWalker.java:92)
	at com.sdl.cd.livecontent.util.walker.ResourceSetWalker.forEachResource(ResourceSetWalker.java:44)
	at com.sdl.cd.livecontent.repository.ContentDao.getDocumentNameForFoundDocumentsByXpath(ContentDao.java:1167)
	at com.sdl.cd.livecontent.repository.ContentDao.addReferencesForConkeyref(ContentDao.java:1148)
	at com.sdl.cd.livecontent.services.content.impl.GraphServiceImpl.getDocumentIdsForContentReferences(GraphServiceImpl.java:695)
	at com.sdl.cd.livecontent.services.content.impl.GraphServiceImpl.processReferences(GraphServiceImpl.java:676)
	at com.sdl.cd.livecontent.services.resolve_refs_earlier.impl.ResolveRefsEarlyService.resolveReferences(ResolveRefsEarlyService.java:805)
	at com.sdl.cd.livecontent.services.resolve_refs_earlier.impl.ResolveRefsEarlyService.resolveRefsEarly(ResolveRefsEarlyService.java:781)
	at com.sdl.cd.livecontent.services.resolve_refs_earlier.impl.ResolveRefsEarlyService.resolveRefsEarly(ResolveRefsEarlyService.java:82)
	at com.sdl.cd.livecontent.controllers.PublishingController$4.produce(PublishingController.java:133)
	at com.sdl.cd.livecontent.stream.impl.LongTimeResponseServiceImpl.performProcess(LongTimeResponseServiceImpl.java:75)
	at com.sdl.cd.livecontent.stream.impl.LongTimeResponseServiceImpl.lambda$prepareAndStartProcess$31(LongTimeResponseServiceImpl.java:65)
	at com.sdl.cd.livecontent.stream.impl.LongTimeResponseServiceImpl$$Lambda$21/162200793.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x00000000ef99f200> (a java.util.concurrent.ThreadPoolExecutor$Worker) 
	
	"[Resolving refs early] 'publish_performance_o05-ab'" #522 prio=5 os_prio=0 tid=0x0000000046088800 nid=0xf24 in Object.wait() [0x000000005d5ed000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.exist.storage.lock.ReentrantReadWriteLock.acquire(ReentrantReadWriteLock.java:147)
	- locked <0x0000000096659840> (a org.exist.storage.lock.ReentrantReadWriteLock)
	at org.exist.storage.structural.NativeStructuralIndexWorker.getQNamesForDoc(NativeStructuralIndexWorker.java:494)
	at org.exist.storage.structural.NativeStructuralIndexWorker.scanByType(NativeStructuralIndexWorker.java:222)
	at org.exist.dom.VirtualNodeSet.getNodesFromIndex(VirtualNodeSet.java:457)
	at org.exist.dom.VirtualNodeSet.realize(VirtualNodeSet.java:585)
	at org.exist.dom.VirtualNodeSet.unorderedIterator(VirtualNodeSet.java:878)
	at org.exist.xquery.value.AbstractSequence.setSelfAsContext(AbstractSequence.java:249)
	at org.exist.xquery.OpAnd.eval(OpAnd.java:67)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
	at org.exist.xquery.Predicate.selectByNodeSet(Predicate.java:446)
	at org.exist.xquery.Predicate.evalPredicate(Predicate.java:326)
	at org.exist.xquery.LocationStep.processPredicate(LocationStep.java:252)
	at org.exist.xquery.LocationStep.applyPredicate(LocationStep.java:239)
	at org.exist.xquery.LocationStep.eval(LocationStep.java:463)
	at org.exist.xquery.pragmas.Optimize.eval(Optimize.java:172)
	at org.exist.xquery.ExtensionExpression.eval(ExtensionExpression.java:70)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
	at org.exist.xquery.DynamicCardinalityCheck.eval(DynamicCardinalityCheck.java:74)
	at org.exist.xquery.functions.fn.FunData.eval(FunData.java:81)
	at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:56)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.XQuery.execute(XQuery.java:297)
	at org.exist.xquery.XQuery.execute(XQuery.java:217)
	at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:452)
	at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:157)
	at com.sdl.cd.livecontent.repository.DBDAO.queryCollection(DBDAO.java:572)
	at com.sdl.cd.livecontent.repository.ContentDao.queryCollection(ContentDao.java:383)
	at com.sdl.cd.livecontent.repository.ContentDao.getHrefForKeydef(ContentDao.java:1716)
	at com.sdl.cd.livecontent.services.publishing.graph.impl.ConrefAndConkeyrefGraphBuilderImpl.getGraphFileNameFromKeydef(ConrefAndConkeyrefGraphBuilderImpl.java:73)
	at com.sdl.cd.livecontent.services.publishing.graph.impl.ConrefAndConkeyrefGraphBuilderImpl.getGraphFileNameFromKeydef(ConrefAndConkeyrefGraphBuilderImpl.java:21)
	at com.sdl.cd.livecontent.repository.ContentDao.setFileNameViaReferenceType(ContentDao.java:896)
	at com.sdl.cd.livecontent.repository.ContentDao$3.apply(ContentDao.java:845)
	at com.sdl.cd.livecontent.repository.ContentDao$3.apply(ContentDao.java:824)
	at com.sdl.cd.livecontent.util.walker.ResourceSetWalker$2.apply(ResourceSetWalker.java:47)
	at com.sdl.cd.livecontent.util.walker.ResourceSetWalker$2.apply(ResourceSetWalker.java:44)
	at com.sdl.cd.livecontent.util.walker.ResourceSetWalker.forEach(ResourceSetWalker.java:92)
	at com.sdl.cd.livecontent.util.walker.ResourceSetWalker.forEachResource(ResourceSetWalker.java:44)
	at com.sdl.cd.livecontent.repository.ContentDao.getDocumentNameForFoundDocumentsByXpath(ContentDao.java:1167)
	at com.sdl.cd.livecontent.repository.ContentDao.addReferencesForConkeyref(ContentDao.java:1148)
	at com.sdl.cd.livecontent.services.content.impl.GraphServiceImpl.getDocumentIdsForContentReferences(GraphServiceImpl.java:695)
	at com.sdl.cd.livecontent.services.content.impl.GraphServiceImpl.processReferences(GraphServiceImpl.java:676)
	at com.sdl.cd.livecontent.services.resolve_refs_earlier.impl.ResolveRefsEarlyService.resolveReferences(ResolveRefsEarlyService.java:805)
	at com.sdl.cd.livecontent.services.resolve_refs_earlier.impl.ResolveRefsEarlyService.resolveRefsEarly(ResolveRefsEarlyService.java:781)
	at com.sdl.cd.livecontent.services.resolve_refs_earlier.impl.ResolveRefsEarlyService.resolveRefsEarly(ResolveRefsEarlyService.java:82)
	at com.sdl.cd.livecontent.controllers.PublishingController$4.produce(PublishingController.java:133)
	at com.sdl.cd.livecontent.stream.impl.LongTimeResponseServiceImpl.performProcess(LongTimeResponseServiceImpl.java:75)
	at com.sdl.cd.livecontent.stream.impl.LongTimeResponseServiceImpl.lambda$prepareAndStartProcess$31(LongTimeResponseServiceImpl.java:65)
	at com.sdl.cd.livecontent.stream.impl.LongTimeResponseServiceImpl$$Lambda$21/162200793.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x00000000ef7f9528> (a java.util.concurrent.ThreadPoolExecutor$Worker) 
~~~
### What is the problem
slow down for a long time (about 1-2 minutes)

### What did you expect
all threads work without locking

### Describe how to reproduce or add a test
this is multithreading problem, cannot be reproduced by some test

### Context information
Please always add the following information
- eXist-db version 2.2
- java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode) 
- Operating system Windows 10
- 64 bit
- No custom changes in conf.xml

**Comment by dizzzz** [comment]
I think it does not make sense to report issues on exist 2.2 (release end 2014) ; there will be no maintenance done anymore.

**Comment by shabanovd** [comment]
NativeStructuralIndex have single thread processing lock. That's why you see that issue. Try to avoid structure index full scans.

**Comment by alebastrov** [comment]
Here is the test. You can see there are 2 threads and both are trying to acquire READ lock, test waits forever
~~~
package org.exist.storage.lock;

import org.exist.util.LockException;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.runners.MockitoJUnitRunner;

import java.util.concurrent.CountDownLatch;

import static org.junit.Assert.assertEquals;

@RunWith(MockitoJUnitRunner.class)
public class ReentrantReadWriteLockTest {
    private Object syncObject = new Object();
    private ReentrantReadWriteLock lock = new ReentrantReadWriteLock(syncObject);

    @Test
    public void test2readers() throws LockException, InterruptedException {
        final CountDownLatch cdl_start =new CountDownLatch(2);
        final CountDownLatch cdl_finish =new CountDownLatch(2);
        Thread t1 = new Thread(() -> {
            
                try {
                    lock.acquire(Lock.READ_LOCK);
                    cdl_start.countDown();
                    cdl_start.await();
                    lock.release(Lock.READ_LOCK);
                    cdl_finish.countDown();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            
        });
        Thread t2 = new Thread(() -> {
                try {
                    lock.acquire(Lock.READ_LOCK);
                    cdl_start.countDown();
                    cdl_start.await();
                    lock.release(Lock.READ_LOCK);
                    cdl_finish.countDown();
                } catch (Exception e) {
                    e.printStackTrace();
                }
        });
        t1.start();
        t2.start();
        cdl_finish.await();
        assertEquals(0, cdl_start.getCount());
    }
}
~~~

**Comment by alebastrov** [comment]
And if you change your realization of this class to java.util.concurrent.locks.ReentrantReadWriteLock it passes

**Comment by alebastrov** [comment]
Why I write this as issue is that fact you're using this class in 3.x branch

**Comment by alebastrov** [comment]
And how can I "avoid structure index full scans"?

**Comment by adamretter** [comment]
@alebastrov I have a branch of eXist where I am switching us away from eXist custom locks and on to standard Java locks, so far I have switched the Collection locks and the Collection Cache, I hope to get to the other locks very soon. You can see the progress here -
 https://github.com/adamretter/exist/tree/cache-improvements

**Comment by adamretter** [comment]
@alebastrov eXist's `org.exist.storage.lock.ReentrantReadWriteLock` is single-reader/single-writer so what your test shows is expected.

Thanks for your test, I have incorporated and expanded upon it here: https://github.com/adamretter/exist/commit/71243052fb55549d58c7e5006add02e37bf2fc3b
You can see that it does pass in my branch where we have switched to standard Java locks.

**Comment by duncdrum** [comment]
@adamretter this is still not part of 5.0 ?

**Comment by adamretter** [comment]
@duncdrum No. It cannot be easily fixed. All of eXist-db's BTrees in their current design require exclusive locking. This is unlikely to be changed.
