### ISSUE TITLE
Newlines in string literals result in wrong error location reported

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#1405]
### What is the problem

In eXide, Atom, and oXygen (with eXist configured as the XQuery validation engine), eXist reports the wrong location of errors, and my tests below show that the offset of the error is related to the number of newlines in string literals constructed in variables in the query.

### What did you expect

The location of errors should be correct, regardless of the presence of newlines in string literals present in the query.

### Describe how to reproduce or add a test

In the following query, eXist reports the correct location of the error—on line 7 column 9:

```xquery
xquery version "3.1";

let $foo := "bar"
return
    element x {
        attribute y { "1" }
        element z { "2" }
    }
```

> Cannot compile xquery: exerr:ERROR org.exist.xquery.XPathException: err:XPST0003 unexpected token: element [at line 7, column 9]

Indeed line 7 column 9 is exactly the location of the first letter, `e`, of `element z`.

**However,** if we add any newlines to the string literal `$foo`, the error location **remains** `line 7 column 9`, **even though** the location of the error has actually moved down by one line to `line 8`. Adding additional new lines worsens the problem, because now the reported location is that many lines off:

```xquery
xquery version "3.1";

let $foo := "bar
baz
qux
quud
quuz"
return
    element x {
        attribute y { "1" }
        element z { "2" }
    }
```

Here, instead of `line 11 column 9` the location persists at `line 7 column 9`. Line 7 contains only the word `quuz`, and certainly contains nothing matching the error which says the error is caused by an `unexpected token: element` on line 7!

Is there a reason that eXist would strip or ignore newlines in string literals when it evaluates queries?

### Context information

- eXist-db version: 3.1.1
- Java version: 1.8.0_121-b13
- Operating system: macOS 10.12.4
- 32 or 64 bit: 64 bit
- Any custom changes in e.g. conf.xml: none

**Comment by joewiz** [comment]
The corresponding error in exist.log to the last sample query (with `quuz`) is as follows:

```text
2017-04-13 17:48:23,357 [qtp418235219-2006] ERROR (XQueryServlet.java [process]:534) - Cannot compile xquery: exerr:ERROR org.exist.xquery.XPathException: err:XPST0003 unexpected token: element [at line 7, column 9]
 
org.exist.EXistException: Cannot compile xquery: exerr:ERROR org.exist.xquery.XPathException: err:XPST0003 unexpected token: element [at line 7, column 9]

	at org.exist.http.servlets.XQueryServlet.process(XQueryServlet.java:428) [exist-optional.jar:3.1.1]
	at org.exist.http.servlets.XQueryServlet.doPost(XQueryServlet.java:191) [exist-optional.jar:3.1.1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [servlet-api-3.1.jar:3.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [servlet-api-3.1.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566) [jetty-security-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:159) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.exist.http.urlrewrite.Forward.doRewrite(Forward.java:50) [exist-optional.jar:3.1.1]
	at org.exist.http.urlrewrite.XQueryURLRewrite.doRewrite(XQueryURLRewrite.java:545) [exist-optional.jar:3.1.1]
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:349) [exist-optional.jar:3.1.1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [servlet-api-3.1.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
	at de.betterform.agent.web.filter.XFormsFilter.doFilter(XFormsFilter.java:171) [betterform-exist-5.1-SNAPSHOT-20160615.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524) [jetty-security-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:396) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.Server.handle(Server.java:524) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.9.v20160517.jar:9.3.9.v20160517]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: org.exist.xquery.StaticXQueryException: exerr:ERROR org.exist.xquery.XPathException: err:XPST0003 unexpected token: element [at line 7, column 9]

	at org.exist.xquery.XQuery.compile(XQuery.java:115) ~[exist.jar:3.1.1]
	at org.exist.xquery.XQuery.compile(XQuery.java:79) ~[exist.jar:3.1.1]
	at org.exist.xquery.XQuery.compile(XQuery.java:71) ~[exist.jar:3.1.1]
	at org.exist.http.servlets.XQueryServlet.process(XQueryServlet.java:425) ~[exist-optional.jar:3.1.1]
	... 48 more
```

XQuery.java:115 can be found at https://github.com/eXist-db/exist/blob/develop/src/org/exist/xquery/XQuery.java#L115.

**Comment by shabanovd** [comment]
That is ANTLR's bug:
```
line 7:9: unexpected token: element
	at org.exist.xquery.parser.XQueryParser.castExpr(XQueryParser.java:6565)
	at org.exist.xquery.parser.XQueryParser.castableExpr(XQueryParser.java:6392)
	at org.exist.xquery.parser.XQueryParser.treatExpr(XQueryParser.java:6300)
	at org.exist.xquery.parser.XQueryParser.instanceofExpr(XQueryParser.java:6209)
	at org.exist.xquery.parser.XQueryParser.intersectExceptExpr(XQueryParser.java:7589)
	at org.exist.xquery.parser.XQueryParser.unionExpr(XQueryParser.java:6849)
	at org.exist.xquery.parser.XQueryParser.multiplicativeExpr(XQueryParser.java:6784)
	at org.exist.xquery.parser.XQueryParser.additiveExpr(XQueryParser.java:6735)
	at org.exist.xquery.parser.XQueryParser.rangeExpr(XQueryParser.java:6656)
	at org.exist.xquery.parser.XQueryParser.stringConcatExpr(XQueryParser.java:6612)
```

**Comment by wolfgangmm** [comment]
Thanks @joewiz for this helpful analysis. I stumbled across the issue at times, but never got to track it down to newlines in string literals. It's actually quite easy to fix in the XQuery lexer. I'll send a PR shortly.

**Comment by joewiz** [comment]
That's great to hear! I only happened to notice the correlation between newlines in string literals and the reported location of errors yesterday when I was working with a variation of https://gist.github.com/joewiz/138d06bf97cbe1e7b52f — and I introduced an error and was trying to track it down. I noticed the reported location staying constant, even as I trimmed away entries from the string — until finally the error location was right when I trimmed the string down to a single line.

**Comment by joewiz** [comment]
Thanks so much, @wolfgangmm! (And for your hints @shabanovd & review @dizzzz!)

**Comment by joewiz** [comment]
I tested this in the latest nightly and can confirm that the fix works perfectly! Thanks again!
