### ISSUE TITLE
Search threw an exception

### ISSUE THREAD

**Issue by alebastrov** [eXist-db/exist#1424]
Exist version 2.2
probably linked to https://sourceforge.net/p/exist/mailman/message/24190180/
~~~
2017-04-13 12:10:19,340 [http-nio-443-exec-6] ERROR (XQueryServlet.java [process]:631) - String index out of range: -21 
java.lang.StringIndexOutOfBoundsException: String index out of range: -21
	at java.lang.String.substring(Unknown Source)
	at org.exist.indexing.lucene.LuceneMatchListener.characters(LuceneMatchListener.java:153)
	at org.exist.storage.serializers.NativeSerializer.serializeToReceiver(NativeSerializer.java:234)
	at org.exist.storage.serializers.NativeSerializer.serializeToReceiver(NativeSerializer.java:205)
	at org.exist.storage.serializers.NativeSerializer.serializeToReceiver(NativeSerializer.java:205)
	at org.exist.storage.serializers.NativeSerializer.serializeToReceiver(NativeSerializer.java:205)
	at org.exist.storage.serializers.NativeSerializer.serializeToReceiver(NativeSerializer.java:80)
	at org.exist.storage.serializers.Serializer.serializeToReceiver(Serializer.java:1070)
	at org.exist.storage.serializers.Serializer.toSAX(Serializer.java:878)
	at org.exist.dom.NodeProxy.toSAX(NodeProxy.java:791)
	at org.exist.xquery.functions.util.Expand.eval(Expand.java:111)
	at org.exist.xquery.BasicFunction.eval(BasicFunction.java:70)
	at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:56)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:142)
	at org.exist.xquery.BindingExpression.eval(BindingExpression.java:166)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
	at org.exist.xquery.EnclosedExpr.eval(EnclosedExpr.java:80)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
	at org.exist.xquery.ElementConstructor.eval(ElementConstructor.java:311)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:102)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:65)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:189)
	at org.exist.xquery.BindingExpression.eval(BindingExpression.java:166)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
	at org.exist.xquery.EnclosedExpr.eval(EnclosedExpr.java:80)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
	at org.exist.xquery.ElementConstructor.eval(ElementConstructor.java:311)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:65)
	at org.exist.xquery.ForExpr.eval(ForExpr.java:307)
	at org.exist.xquery.BindingExpression.eval(BindingExpression.java:166)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
	at org.exist.xquery.EnclosedExpr.eval(EnclosedExpr.java:80)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
	at org.exist.xquery.ElementConstructor.eval(ElementConstructor.java:311)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:65)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:189)
	at org.exist.xquery.BindingExpression.eval(BindingExpression.java:166)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:102)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:65)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:189)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:187)
~~~

**Comment by alebastrov** [comment]
I found the reason see line 264 and later:

~~~
NodeId nodeId = offsets.ids[idx];
                                    Offset offset = nodesWithMatch.get(nodeId);
                                    if (offset != null)
                                        if (lastIdx == idx)
                                            offset.setEndOffset(offsetAttr.endOffset() - offsets.offsets[idx]);
                                        else
                                            offset.add(offsetAttr.startOffset() - offsets.offsets[idx],
                                            offsetAttr.endOffset() - offsets.offsets[idx]);
                                    else
                                        nodesWithMatch.put(nodeId, new Offset(offsetAttr.startOffset() - offsets.offsets[idx],
                                        offsetAttr.endOffset() - offsets.offsets[idx]));
lastIdx = idx;
~~~

I propose fix
~~~
 NodeId nodeId = offsets.ids[idx];
                                    Offset offset = nodesWithMatch.get(nodeId);
                                    if (offset != null)
                                        if (lastIdx == idx){
                                            //offset.setEndOffset(offsetAttr.endOffset() - offsets.offsets[idx]);
                                            if ((offsetAttribute.endOffset() - offsetInside) > offset.getLast().startOffset) {
                                                     offset.setEndOffset(offsetAttribute.endOffset() - offsetInside);
                                            }
                                            else {
                                                     LOG.debug("Skipping offset set to "+(offsetAttribute.endOffset() - offsetInside)+" cause it's less than start offset "+offset.getLast().startOffset+" in text ["+textToSearch+"]");
                                            }
                                        }
                                        else
                                            offset.add(offsetAttr.startOffset() - offsets.offsets[idx],
                                            offsetAttr.endOffset() - offsets.offsets[idx]);
                                    else
                                        nodesWithMatch.put(nodeId, new Offset(offsetAttr.startOffset() - offsets.offsets[idx],
                                        offsetAttr.endOffset() - offsets.offsets[idx]));
lastIdx = idx;
~~~

**Comment by alebastrov** [comment]
FYI: text which cased an error
~~~
Integrating the Experience Manager Web site extension with your Web site If your Web site is dynamic in nature and uses MVC principles to assemble Web content on the fly, the standard installation instructions for the Experience Manager Web site extension may be insufficient to make Experience Manager publishing work. If so, create a custom integration. When to build a custom integration for the Experience Manager Web site extension Build a custom integration if your Web site does not serve content directly from disk. Basic Experience Manager Web site extension The following diagram shows how an out-of-the-box Experience Manager Web site extension works. Customized Experience Manager Web site extension For dynamic or MVC-based Web sites, you need to customize the default Experience Web site extension setup.
Claims you can override in your custom Claim Processor To make your custom Claim Processor handle session-specific content, you can override the Claims listed here to change the behavior of the Preview Claim Processor.
Claims produced by the Page content filter and binary content filter The following Claims are produced by the Page content filter and binary content filter, and can be used by your custom filter. Examples of Experience Manager integration with Web site setups A number of common Web site implementation scenarios, and how to integrate the Experience Manager Web site Extension with them. SDL Web-v6-en-US Integrating the Experience Manager Web site extension with your Web site Integrating the Experience Manager Web site extension with your Web site Integrating the Experience Manager Web site extension with your Web site If your Web site is dynamic in nature and uses MVC principles to assemble Web content on the fly, the standard installation instructions for the Experience Manager Web site extension may be insufficient to make Experience Manager publishing work. If so, create a custom integration.
~~~
Search phrase is 'Web site'

**Comment by alebastrov** [comment]
The reason is that offset.setEndOffset function looks for LAST element and set Offset to it, but it might be not first inclusion, so the next match will probably have index more that expected
For instance first match is 35-45 and second match 67-77, after setting ofset the structure will be
35-45 and second match will be 67-45. This will cause an issue

**Comment by adamretter** [comment]
@alebastrov The stack trace that you posted shows that the error is in `LuceneMatchListener.characters(LuceneMatchListener.java:153)`.

However the fix you have proposed is in LuceneMatchListener#scanMatches`. I don't think the two things are related. Can you explain why you think they are?

**Comment by alebastrov** [comment]
The whole for loop is 
~~~
for(int i = 0; i < terms.length; ++i) {
                    stream.restoreState((State)arrayList.get(i));
                    OffsetAttribute offsetAttribute = stream.getAttribute(OffsetAttribute.class);
                    int index = offsets.getIndex(offsetAttribute.startOffset());
                    NodeId nodeId = offsets.ids[index];
                    LuceneMatchListener.Offset offset = this.nodesWithMatch.get(nodeId);
                    final int offsetInside = offsets.offsets[index];
                    if(offset != null) {
                        if(lastIdx == index) {
                            if ((offsetAttribute.endOffset() - offsetInside) > offset.getLast().startOffset) {
                                offset.setEndOffset(offsetAttribute.endOffset() - offsetInside);
                            }
                            else {
                                LOG.debug("Skipping offset set to "+(offsetAttribute.endOffset() - offsetInside)+" cause it's less than start offset "+offset.getLast().startOffset+" in text ["+textToSearch+"]");
                            }
                        } else {
                            offset.add(offsetAttribute.startOffset() - offsetInside, offsetAttribute.endOffset() - offsetInside);
                        }
                    } else {
                        this.nodesWithMatch.put(nodeId, new LuceneMatchListener.Offset(offsetAttribute.startOffset() - offsetInside, offsetAttribute.endOffset() - offsetInside));
                    }

                    lastIdx = index;
                }
~~~

**Comment by adamretter** [comment]
I am going to close this as we were not able to find or reproduce the problem. Feel free to reopen it with more information relevant to a new release.
