### ISSUE TITLE
xdb:restore doesn't support the "dir" attribute

### ISSUE THREAD

**Issue by MikeJ1971** [eXist-db/exist#1453]
### What is the problem

When using the ant task to restore a directory I get the following error:

```
BUILD FAILED
/home/mike/exist_ant_tasks/build.xml:28: xdb:restore doesn't support the "dir" attribute
```

### What did you expect
I'd expect the task to work and the data to be restored.

### Describe how to reproduce or add a test

According to the documentation "dir" is an acceptable attribute for the restore task:
http://www.exist-db.org/exist/apps/doc/ant-tasks.xml#D2.2.14

I'm using the following build file:

```
<?xml version="1.0" encoding="UTF-8"?>
<project default="Backup" xmlns:xdb="http://exist-db.org/ant">

    <!-- the properties file -->
    <property file="build.properties"/>

    <!-- classpath with eXist jars -->
    <path id="classpath.core">
        <fileset dir="${server.dir}/lib/core">
            <include name="*.jar"/>
        </fileset>
        <pathelement path="${server.dir}/exist.jar"/>
        <pathelement path="${server.dir}/exist-optional.jar"/>
    </path>

    <!-- include exist ant tasks -->
    <typedef resource="org/exist/ant/antlib.xml" uri="http://exist-db.org/ant">
        <classpath refid="classpath.core"/>
    </typedef>

    <!-- backup (collection) -->
    <target name="Backup" description="Backup collection to a directory">
        <xdb:backup uri="${backup.uri}" dir="${backup.dir}" user="${backup.user}" password="${backup.pass}"/>
    </target>

    <!-- restore (collection) -->
    <target name="Restore" description="Restore collection to a directory">
        <xdb:restore uri="${backup.uri}" user="${backup.user}" password="${backup.pass}" dir="${backup.dir}"/>
    </target>
</project>
```

Can Ant correctly convert an attribute value to a java.nio.file.Path, as used in the public setter method for the custom task?

https://github.com/eXist-db/exist/blob/develop/src/org/exist/ant/RestoreTask.java

### Context information

- 3.1.1 / fe05cf7527db943ae6f936c263f744e24fdae2c7
- Apache Ant(TM) version 1.9.7 compiled on April 9 2016
- openjdk version "1.8.0_131"
- OpenJDK Runtime Environment (build 1.8.0_131-b12)
- OpenJDK 64-Bit Server VM (build 25.131-b12, mixed mode)
- centos-release-7-3.1611.el7.centos.x86_64

**Comment by MikeJ1971** [comment]
Also on the mailing list archives:

https://sourceforge.net/p/exist/mailman/message/35698134/

**Comment by MikeJ1971** [comment]
Using the following ant properties:

```
server.dir=/Users/mikejones/Development/workspaces/exist_src/exist
backup.uri=xmldb:exist://localhost:8080/exist/xmlrpc/db/test
backup.dir=/Users/mikejones/Desktop/exist_backup/db/test
backup.user=admin
backup.pass=sosecret
```

The backup creates a db and test folder under exist_backup:

```
mike$ cd db/test
mike$ ls
__contents__.xml	test.xml		test2.xml
```

If I modify the RestoreTask.java file, importing the java.nio.file.Paths class and modifying the setDir method parameter to take a String ...
```
public void setDir( String dir )
    {
        this.dir = Paths.get(dir);
    }
```
... I get a little further:

```
[xdb:restore] Database driver registered.
[xdb:restore] Restoring from /Users/mikejones/Desktop/exist_backup
[xdb:restore] Could not find file /Users/mikejones/Desktop/exist_backup/__contents__.xml
[xdb:restore] 	at org.exist.ant.RestoreTask.execute(RestoreTask.java:85)
[xdb:restore] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[xdb:restore] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[xdb:restore] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[xdb:restore] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[xdb:restore] 	at java.lang.reflect.Method.invoke(Method.java:483)
[xdb:restore] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[xdb:restore] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[xdb:restore] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[xdb:restore] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[xdb:restore] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
[xdb:restore] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
[xdb:restore] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[xdb:restore] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
[xdb:restore] 	at org.apache.tools.ant.Main.runBuild(Main.java:857)
[xdb:restore] 	at org.apache.tools.ant.Main.startAnt(Main.java:236)
[xdb:restore] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
[xdb:restore] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
```

It fails at this point because it looks like RestoreTask.java expects the __contents__.xml to be at the path provided:

```
final Path file = dir.resolve("__contents__.xml" );

if( !Files.exists(file)) {
    final String msg = "Could not find file " + file.toAbsolutePath().toString();
```
In this case:

```
/Users/mikejones/Desktop/exist_backup/__contents__.xml
```

Therefore you can't use the path given to the backup task to the restore task, you have to look at the directory structure created by backup. If I modify the build.properties:

```
backup.dir=/Users/mikejones/Desktop/exist_backup/db/test
```
The restore works (with the modifications to the setter above)

```
xdb:restore] Database driver registered.
[xdb:restore] Restoring from /Users/mikejones/Desktop/exist_backup/db/test
[xdb:restore] Starting restore of backup...
[xdb:restore] Processing backup: /Users/mikejones/Desktop/exist_backup/db/test/__contents__.xml
[xdb:restore] Creating collection /db/test
[xdb:restore] Restored test.xml
[xdb:restore] Restored test2.xml
[xdb:restore] Finished restore of backup.
```

Would it be reasonable to expect the Restore task to use the path given to the original Backup task, i.e. search the folder structure until it finds the __contents__.xml?
