### ISSUE TITLE
Clean-up lucene initialisation logging

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#1461]
In the log, the following exceptions are printed, but these are not necessarily  a problem: code code is actually probing which Constructers can be used.

I'd vote for either put these in debug mode, or remove the exception and add a 'for INFO'.

```java
private static Analyzer createInstance(Class<?> clazz, Class<?>[] vcParamClasses, Object[] vcParamValues) {

        String className = clazz.getName();

        try {
            final Constructor<?> cstr = clazz.getDeclaredConstructor(vcParamClasses);
            cstr.setAccessible(true);

            if (LOG.isDebugEnabled()) {
                LOG.debug(String.format("Using analyzer %s", className));
            }

            return (Analyzer) cstr.newInstance(vcParamValues);

        } catch (IllegalArgumentException | IllegalAccessException | InstantiationException | InvocationTargetException | SecurityException e) {
            LOG.info(String.format("Ignored: Exception while instantiating analyzer class %s: %s", className, e.getMessage()));
        } catch (NoSuchMethodException ex) {
            LOG.info(String.format("Ignored: Could not find matching analyzer class constructor%s: %s", className, ex.getMessage()));
        }

        return null;
    }
```

```
18:16:39.199 [main] ERROR org.exist.indexing.lucene.AnalyzerConfig - Could not find matching analyzer class constructororg.apache.lucene.analysis.core.KeywordAnalyzer: org.apache.lucene.analysis.core.KeywordAnalyzer.<init>(org.apache.lucene.util.Version)
java.lang.NoSuchMethodException: org.apache.lucene.analysis.core.KeywordAnalyzer.<init>(org.apache.lucene.util.Version)
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_131]
	at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[?:1.8.0_131]
	at org.exist.indexing.lucene.AnalyzerConfig.createInstance(AnalyzerConfig.java:254) ~[eXist-db/:?]
	at org.exist.indexing.lucene.AnalyzerConfig.configureAnalyzer(AnalyzerConfig.java:221) ~[eXist-db/:?]
	at org.exist.indexing.lucene.AnalyzerConfig.addAnalyzer(AnalyzerConfig.java:115) ~[eXist-db/:?]
	at org.exist.indexing.lucene.LuceneConfig.parseConfig(LuceneConfig.java:260) ~[eXist-db/:?]
	at org.exist.indexing.lucene.LuceneConfig.parseConfig(LuceneConfig.java:256) ~[eXist-db/:?]
	at org.exist.indexing.lucene.LuceneConfig.<init>(LuceneConfig.java:75) ~[eXist-db/:?]
	at org.exist.indexing.lucene.LuceneIndexWorker.configure(LuceneIndexWorker.java:154) ~[eXist-db/:?]
	at org.exist.indexing.IndexController.configure(IndexController.java:82) ~[eXist-db/:?]
	at org.exist.storage.IndexSpec.read(IndexSpec.java:107) ~[eXist-db/:?]
	at org.exist.storage.IndexSpec.<init>(IndexSpec.java:68) ~[eXist-db/:?]
```

**Comment by adamretter** [comment]
I am pretty sure these are genuine errors. If you specify an analyzer in the collection.xconf and we can't instantiate it, then that is a problem.

**Comment by dizzzz** [comment]
there is a fallback ... the code tries a few different constructors .... to provide compatibility with older classes. There is always a fallback, when that does not work, this is reported....
