### ISSUE TITLE
expath http client issue 

### ISSUE THREAD

**Issue by windauer** [eXist-db/exist#1618]
### What is the problem
NPE in 3.6.0-SNAPSHOT for EXPath HTTP request which works perfectly fine on 3.4.x

### What did you expect
Expected was a response sequnce with header information in response[1] and the response itself in response[2]

### Describe how to reproduce or add a test
```
import module namespace http="http://expath.org/ns/http-client";

let $user := "user"
let $pass:= "pass
let $url := "https://some-https-url-with-basic-auth"

let $request := <http:request method="GET" href="{$url}" timeout="120"  username="{$user}" password="{$pass}"
                        auth-method="basic" send-authorization="true" override-media-type="application/octet-stream">
            <http:header name="accept" value="application/xml"/>
        </http:request>

return
    <result>{ http:send-request($request) }</result>
```

From the log files: 

```
2017-11-16 16:27:24,267 [qtp1999415998-103] ERROR (XQueryServlet.java [process]:534) - null 
java.lang.NullPointerException: null
        at org.expath.httpclient.impl.ApacheHttpConnection.setCredentials(ApacheHttpConnection.java:415) ~[http-client-java-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.expath.httpclient.impl.ApacheHttpConnection.connect(ApacheHttpConnection.java:98) ~[http-client-java-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.expath.httpclient.impl.HttpRequestImpl.send(HttpRequestImpl.java:56) ~[http-client-java-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.expath.exist.SendRequestFunction.sendOnceWithAuth(SendRequestFunction.java:206) ~[exist-expath-20130805.jar:3.6.0-SNAPSHOT]
        at org.expath.exist.SendRequestFunction.sendOnce(SendRequestFunction.java:172) ~[exist-expath-20130805.jar:3.6.0-SNAPSHOT]
        at org.expath.exist.SendRequestFunction.sendRequest(SendRequestFunction.java:151) ~[exist-expath-20130805.jar:3.6.0-SNAPSHOT]
        at org.expath.exist.SendRequestFunction.eval(SendRequestFunction.java:133) ~[exist-expath-20130805.jar:3.6.0-SNAPSHOT]
        at org.exist.xquery.BasicFunction.eval(BasicFunction.java:74) ~[exist.jar:3.6.0-SNAPSHOT]
        at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:41) ~[exist.jar:3.6.0-SNAPSHOT]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist.jar:3.6.0-SNAPSHOT]
        at org.exist.xquery.PathExpr.eval(PathExpr.java:276) ~[exist.jar:3.6.0-SNAPSHOT]
        at org.exist.xquery.EnclosedExpr.eval(EnclosedExpr.java:82) ~[exist.jar:3.6.0-SNAPSHOT]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist.jar:3.6.0-SNAPSHOT]
        at org.exist.xquery.PathExpr.eval(PathExpr.java:276) ~[exist.jar:3.6.0-SNAPSHOT]
        at org.exist.xquery.ElementConstructor.eval(ElementConstructor.java:329) ~[exist.jar:3.6.0-SNAPSHOT]
        at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58) ~[exist.jar:3.6.0-SNAPSHOT]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:111) ~[exist.jar:3.6.0-SNAPSHOT]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:111) ~[exist.jar:3.6.0-SNAPSHOT]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:111) ~[exist.jar:3.6.0-SNAPSHOT]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:111) ~[exist.jar:3.6.0-SNAPSHOT]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist.jar:3.6.0-SNAPSHOT]
        at org.exist.xquery.PathExpr.eval(PathExpr.java:276) ~[exist.jar:3.6.0-SNAPSHOT]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist.jar:3.6.0-SNAPSHOT]
        at org.exist.xquery.XQuery.execute(XQuery.java:261) ~[exist.jar:3.6.0-SNAPSHOT]
        at org.exist.xquery.XQuery.execute(XQuery.java:185) ~[exist.jar:3.6.0-SNAPSHOT]
        at org.exist.http.servlets.XQueryServlet.process(XQueryServlet.java:470) [exist-optional.jar:3.6.0-SNAPSHOT]
        at org.exist.http.servlets.XQueryServlet.doPost(XQueryServlet.java:191) [exist-optional.jar:3.6.0-SNAPSHOT]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [servlet-api-3.1.jar:3.1.0]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [servlet-api-3.1.jar:3.1.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841) [jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535) [jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566) [jetty-security-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:163) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:73) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.exist.http.urlrewrite.Forward.doRewrite(Forward.java:50) [exist-optional.jar:3.6.0-SNAPSHOT]
        at org.exist.http.urlrewrite.XQueryURLRewrite.doRewrite(XQueryURLRewrite.java:548) [exist-optional.jar:3.6.0-SNAPSHOT]
        at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:352) [exist-optional.jar:3.6.0-SNAPSHOT]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [servlet-api-3.1.jar:3.1.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:833) [jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535) [jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524) [jetty-security-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [jetty-servlet-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:454) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.Server.handle(Server.java:564) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:289) [jetty-io-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:149) [jetty-io-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128) [jetty-util-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222) [jetty-util-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294) [jetty-util-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199) [jetty-util-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673) [jetty-util-9.4.6.v20170531.jar:9.4.6.v20170531]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591) [jetty-util-9.4.6.v20170531.jar:9.4.6.v20170531]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

### Context information
Please always add the following information
- eXistdb: 3.6.0
- Java: 8
- MacOs and CentOS
- 64 bit
- multiple custom changes in configs but nothing related to EXPath http client.

Haven't found the time to debug this myself, since I'm fighting with some 3.4.x eXistdb issues which I hoped would be solved with 3.6.0.

**Comment by windauer** [comment]
Forgot to mention: I'm download binary files here (mainly PDFs, DOCX, ZIP) and store these in the database followed by CEX operations.. but I was able to bring it down to this single http:send-request which does work in 3.4 but not 3.6

**Comment by adamretter** [comment]
Can you add version="1.1" to work around the known issue please?

**Comment by joewiz** [comment]
@windauer I think you have encountered the regression noted here: https://github.com/eXist-db/exist/pull/1566. You'll see the workaround in the PR description.

**Comment by windauer** [comment]
@adamretter, @joewiz thanks a lot and sorry I did not notice myself. But unfortunately this does not do the trick. I added a http-version attribute but still doesn't work and I see the same NPE in my logs.

**Comment by adamretter** [comment]
@windauer Got it. Please test - https://github.com/eXist-db/exist/pull/1619
