### ISSUE TITLE
Trace at startup: (NoClassDefFoundError): TarArchiveOutputStream

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#162]
The tracelog explains it all

```
2014-03-06 14:57:33,968 [main] INFO  (Configuration.java [<init>]:183) - Reading configuration from file C:\Localdata\Development\GitHub\exist\conf.xml 
2014-03-06 14:57:34,060 [main] INFO  (Configuration.java [configureStartup]:1258) - Registered StartupTrigger: org.exist.extensions.exquery.restxq.impl.RestXqStartupTrigger 
2014-03-06 14:57:34,061 [main] INFO  (Configuration.java [configureStartup]:1258) - Registered StartupTrigger: org.exist.repo.AutoDeploymentTrigger 
2014-03-06 14:57:34,335 [main] ERROR (Configuration.java [lookupModuleClass]:462) - Module http://exist-db.org/xquery/compression could not be initialized due to a missing dependancy (NoClassDefFoundError): org/apache/commons/compress/archivers/tar/TarArchiveOutputStream 
java.lang.NoClassDefFoundError: org/apache/commons/compress/archivers/tar/TarArchiveOutputStream
	at org.exist.xquery.modules.compression.CompressionModule.<clinit>(CompressionModule.java:47)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:190)
	at org.exist.util.Configuration.lookupModuleClass(Configuration.java:446)
	at org.exist.util.Configuration.loadModuleClasses(Configuration.java:412)
	at org.exist.util.Configuration.configureXQuery(Configuration.java:348)
	at org.exist.util.Configuration.<init>(Configuration.java:253)
	at org.exist.xmldb.DatabaseImpl.configure(DatabaseImpl.java:107)
	at org.exist.xmldb.DatabaseImpl.getLocalCollection(DatabaseImpl.java:183)
	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:162)
	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:153)
	at org.xmldb.api.DatabaseManager.getCollection(Unknown Source)
	at org.exist.client.InteractiveClient.connect(InteractiveClient.java:329)
	at org.exist.client.InteractiveClient.connectToDatabase(InteractiveClient.java:2339)
	at org.exist.client.InteractiveClient.run(InteractiveClient.java:2427)
	at org.exist.client.InteractiveClient.main(InteractiveClient.java:291)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.exist.start.Main.invokeMain(Main.java:126)
	at org.exist.start.Main.run(Main.java:448)
	at org.exist.start.Main.main(Main.java:50)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.archivers.tar.TarArchiveOutputStream
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 23 more
2014-03-06 14:57:34,355 [main] INFO  (eXistURLStreamHandlerFactory.java [init]:53) - Succesfully registered eXistURLStreamHandlerFactory. 
```

**Comment by dizzzz** [comment]
fixed by https://github.com/eXist-db/exist/commit/dca4b93318e25968abfb4cbd68db1d4b845d94ad
