### ISSUE TITLE
TransactionManager error

### ISSUE THREAD

**Issue by alebastrov** [eXist-db/exist#1651]
I got OOM error. Just before (2 minutes) that I saw an exception

### What is the problem
~~~
2017-11-12 10:26:49,520 [pool-3-thread-2] WARN  (TransactionManager.java [close]:238) - Transaction was not committed or aborted! 
java.lang.Throwable
	at org.exist.storage.txn.TransactionManager.close(TransactionManager.java:238)
	at org.exist.xmldb.LocalXUpdateQueryService.updateResource(LocalXUpdateQueryService.java:127)
	at org.exist.xmldb.LocalXUpdateQueryService.update(LocalXUpdateQueryService.java:139)
	at com.sdl.cd.livecontent.repository.DBDAO.executeXUpdate(DBDAO.java:134)
	at com.sdl.cd.livecontent.repository.impl.PublicationDaoImpl.createLangConfigItem(PublicationDaoImpl.java:681)
	at com.sdl.cd.livecontent.repository.impl.CachedPublicationDao.createLangConfigItem(CachedPublicationDao.java:288)
	at com.sdl.cd.livecontent.services.publang.impl.PubLangServiceImpl.langConfigItemUpdate(PubLangServiceImpl.java:217)
	at com.sdl.cd.livecontent.services.publang.impl.PubLangServiceImpl.setConfig(PubLangServiceImpl.java:184)
	at com.sdl.cd.livecontent.services.prepare.impl.EndPrepareServiceImpl.pubSetConfig(EndPrepareServiceImpl.java:580)
	at com.sdl.cd.livecontent.services.prepare.impl.EndPrepareServiceImpl.lambda$setConfigVariables$71(EndPrepareServiceImpl.java:519)
	at com.sdl.cd.livecontent.services.prepare.impl.EndPrepareServiceImpl.executeSubStepWithLogTiming(EndPrepareServiceImpl.java:363)
	at com.sdl.cd.livecontent.services.prepare.impl.EndPrepareServiceImpl.setConfigVariables(EndPrepareServiceImpl.java:517)
	at com.sdl.cd.livecontent.services.prepare.impl.EndPrepareServiceImpl.stepExecution(EndPrepareServiceImpl.java:399)
	at com.sdl.cd.livecontent.services.prepare.impl.AbstractPrepareStepService.localPrepare(AbstractPrepareStepService.java:228)
	at com.sdl.cd.livecontent.services.prepare.impl.AbstractPrepareStepService.prepareStep(AbstractPrepareStepService.java:189)
	at com.sdl.cd.livecontent.services.publishing.impl.PublishingFacadeImpl.lambda$prepare$29(PublishingFacadeImpl.java:91)
	at com.sdl.cd.livecontent.services.publishing.impl.PublishingFacadeImpl.executePublishingStepsViaCallables(PublishingFacadeImpl.java:106)
	at com.sdl.cd.livecontent.services.publishing.impl.PublishingFacadeImpl.prepare(PublishingFacadeImpl.java:94)
	at com.sdl.cd.livecontent.services.eventBusImpl.MessageListenerImpl$1.call(MessageListenerImpl.java:79)
	at com.sdl.cd.livecontent.services.eventBusImpl.MessageListenerImpl$1.call(MessageListenerImpl.java:66)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

~~~

### What did you expect
> Describe what you expected to happen. Add for example a reference to a [specification](https://www.w3.org/TR/xquery-3/).

When you begin transaction with broken journal it looks as if it started
See org.exist.storage.txn.TransactionManager#beginTransaction()
~~~
final Txn txn = new Txn(TransactionManager.this, txnId);
                try {
                    journal.writeToLog(new TxnStart(txnId));
                } catch (final TransactionException e) {
                    LOG.error("Failed to create transaction. Error writing to log file.", e);
                }
                transactions.put(txn.getId(), new TxnCounter());
                return txn;
~~~

After that when we want to close/abort transaction we will get the exception I mentioned abowe.

### Describe how to reproduce or add a test
- Brake transaction journal
- begin transaction
- write something
- commit transaction

AR: got error on commit phase
ER: got error on begin phase

### Context information
Please always add the following information
- eXist-db version + Git Revision hash e.g. eXist-db 2.2 /  97bbbdd (any newest versions too)
- Java version Java8u121
- Operating system Windows 10
- 64 bit
- No matter

**Comment by alebastrov** [comment]
If you ask me how it is possible to call close() without commit() I will suggest to look at AtomProtocol
~~~
try{
...
} catch (final IOException ex) {
					transact.abort(transaction);
					throw new EXistException("IO error: " + ex.getMessage(), ex);
				} catch (final TriggerException ex) {
					transact.abort(transaction);
					throw new EXistException("Trigger failed: " + ex.getMessage(), ex);
				} catch (final SAXException ex) {
					transact.abort(transaction);
					throw new EXistException("SAX error: " + ex.getMessage(), ex);
				} catch (final LockException ex) {
					transact.abort(transaction);
					throw new EXistException("Cannot acquire write lock.", ex);
				} finally {
                    transact.close(transaction);
                }
~~~ If there is NPE thrown then transact.close(transaction); will be called without transact.abort()

**Comment by adamretter** [comment]
I think this is a non-issue.

If you do not call `abort` or `commit` on a transaction (which could happen if an exception is thrown for some unexpected condition, such as an OOM), when `close` is called (usually via try-with-resources) then the transaction will be auto-aborted, which is why the message in the log is only at `WARN` level.

**Comment by alebastrov** [comment]
Yes I know that, but I think the sooner we detect an error, the better, that's why I created it as a ticket.
I propose to change that in such way
~~~
try{
...
} catch (final Exception ex) {
					transact.abort(transaction);
					throw new EXistException("Uexpected exception", ex);
				} finally {
                    transact.close(transaction);
                }
~~~
It will also remove unnecessary log messages (which are obvious, because subclass of Exception is shown)
