### ISSUE TITLE
An IO exception occurred: Could not load cache for class: org.exist.util.io.FileFilterInputStreamCache

### ISSUE THREAD

**Issue by merenyics** [eXist-db/exist#1702]
### What is the problem
> With existdb 3.6.1 on Windows 10, exist running as a service, whenever I wake my computer from hibernation, exist stops functioning giving  ERROR An IO exception occurred: Could not load cache for class: org.exist.util.io.FileFilterInputStreamCache

After restarting the service (or windows) exist works properly again.

### What did you expect
> No problems after hibernation, never had this issue before 3.6.1

### Context information
Please always add the following information
- eXist-db version : 3.6.1
- Java version: Java8u161)
- Operating system (Windows 10, latest update)
- 64 bit
- No custom changes.
- data directory copied from existdb 3.4, but this is supposed to be a binary-compatible release, is it not?

**Comment by dizzzz** [comment]
Sure the data is binary compatible. Interesting issue as on macOS this issue does not happen. Please could you share/attach the full trace from the exist.log file?

**Comment by merenyics** [comment]
I have several of these in my log, just one example:
`2018-01-24 15:13:49,870 [qtp1872012709-201] ERROR (FilterInputStreamCacheFactory.java [instantiate]:81) - null 
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedConstructorAccessor151.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_161]
	at org.exist.util.io.FilterInputStreamCacheFactory.instantiate(FilterInputStreamCacheFactory.java:72) [exist.jar:3.6.1]
	at org.exist.util.io.FilterInputStreamCacheFactory.getCacheInstance(FilterInputStreamCacheFactory.java:60) [exist.jar:3.6.1]
	at org.exist.xquery.value.BinaryValueFromInputStream.<init>(BinaryValueFromInputStream.java:33) [exist.jar:3.6.1]
	at org.exist.xquery.value.BinaryValueFromInputStream.getInstance(BinaryValueFromInputStream.java:45) [exist.jar:3.6.1]
	at org.exist.xquery.functions.request.GetData.eval(GetData.java:133) [exist-optional.jar:3.6.1]
	at org.exist.xquery.BasicFunction.eval(BasicFunction.java:74) [exist.jar:3.6.1]
	at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:41) [exist.jar:3.6.1]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:99) [exist.jar:3.6.1]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:3.6.1]
	at org.exist.xquery.PathExpr.eval(PathExpr.java:276) [exist.jar:3.6.1]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:3.6.1]
	at org.exist.xquery.XQuery.execute(XQuery.java:261) [exist.jar:3.6.1]
	at org.exist.xquery.XQuery.execute(XQuery.java:185) [exist.jar:3.6.1]
	at org.exist.http.RESTServer.executeXQuery(RESTServer.java:1539) [exist-optional.jar:3.6.1]
	at org.exist.http.RESTServer.checkForXQueryTarget(RESTServer.java:1224) [exist-optional.jar:3.6.1]
	at org.exist.http.RESTServer.doPut(RESTServer.java:1025) [exist-optional.jar:3.6.1]
	at org.exist.http.servlets.EXistServlet.doPut(EXistServlet.java:146) [exist-optional.jar:3.6.1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:710) [servlet-api-3.1.jar:3.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [servlet-api-3.1.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841) [jetty-servlet-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535) [jetty-servlet-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566) [jetty-security-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [jetty-servlet-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:163) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:73) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.exist.http.urlrewrite.Forward.doRewrite(Forward.java:50) [exist-optional.jar:3.6.1]
	at org.exist.http.urlrewrite.XQueryURLRewrite.doRewrite(XQueryURLRewrite.java:548) [exist-optional.jar:3.6.1]
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:352) [exist-optional.jar:3.6.1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [servlet-api-3.1.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841) [jetty-servlet-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650) [jetty-servlet-9.4.7.v20170914.jar:9.4.7.v20170914]
	at de.betterform.agent.web.filter.XFormsFilter.doFilter(XFormsFilter.java:171) [betterform-exist-5.1-SNAPSHOT-20160615.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1629) [jetty-servlet-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) [jetty-servlet-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524) [jetty-security-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [jetty-servlet-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:455) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.Server.handle(Server.java:561) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:334) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:104) [jetty-io-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247) [jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140) [jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243) [jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679) [jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597) [jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.nio.file.NoSuchFileException: C:\WINDOWS\TEMP\_mmtfm_d8729f9f-9052-47a1-a901-49bcf0b73c168261318144176977362\mmtf_1516803229868395367594306022138.tmp
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source) ~[?:1.8.0_161]
	at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:1.8.0_161]
	at java.nio.file.Files.createFile(Unknown Source) ~[?:1.8.0_161]
	at java.nio.file.TempFileHelper.create(Unknown Source) ~[?:1.8.0_161]
	at java.nio.file.TempFileHelper.createTempFile(Unknown Source) ~[?:1.8.0_161]
	at java.nio.file.Files.createTempFile(Unknown Source) ~[?:1.8.0_161]
	at org.exist.util.io.TemporaryFileManager.getTemporaryFile(TemporaryFileManager.java:95) ~[exist.jar:3.6.1]
	at org.exist.util.io.FileFilterInputStreamCache.<init>(FileFilterInputStreamCache.java:61) ~[exist.jar:3.6.1]
	at org.exist.util.io.FileFilterInputStreamCache.<init>(FileFilterInputStreamCache.java:55) ~[exist.jar:3.6.1]
	... 78 more`

**Comment by merenyics** [comment]
And I'm afraid, I cannot reproduce the problem consistently. It may have nothing to do with hibernation, I may have jumped to conclusions there. I've been getting these errors since I upgraded to 3.6.1, so far the problem has occurred only immediately after turning my computer back on, and I use hibernation.

**Comment by dizzzz** [comment]
I think the stack trace provides some clues; I can have a look a bit later in the week, but maybe @adamretter  can share some light here.


```
aused by: java.nio.file.NoSuchFileException: C:\WINDOWS\TEMP\_mmtfm_d8729f9f-9052-47a1-a901-49bcf0b73c168261318144176977362\mmtf_1516803229868395367594306022138.tmp
```

might indicate that e.g. a virus scanner is intercepting some writes..... (do you have one running? is something in the logs?)

**Comment by merenyics** [comment]
Thank you for looking into it. Only standard MS virus protection is running, and to the best of my knowledge, there is nothing on my machine that might interfere with the Windows temp folder.
Currently, with exist running and functioning properly, the _mmtfm_... folder is empty. I do not know what the tmp file does, and if this is OK, just adding this bit of info in case it might help.

**Comment by merenyics** [comment]
A quick update:
This time I got the error without the computer hibernating or going to sleep, so that is not the cause. I noticed that now there is no mmtfm folder at all in Windows/TEMP.
Should I maybe reinstall exist? I need it for urgent work. Any help appreciated.

**Comment by dizzzz** [comment]
It is al about creating temp files that are required for some caching...., 

for a short term, you could modify conf.xml: 

https://github.com/eXist-db/exist/blob/develop/conf.xml.tmpl#L364

use value " org.exist.util.io.MemoryFilterInputStreamCache" ....

**Comment by merenyics** [comment]
thanks, will try. I can see from the comments in conf.xml that windows temp files with java seem to be problematic. Maybe the issue has more to do with the 8.161 Java update than the exist version. I upgraded both in the past couple of days.

**Comment by dizzzz** [comment]
yes these can be factors;  switching the cache implementation might help you ; I am not sure even anymore if the windows warning is true ; @adamretter knows more about this I think.
I will monitor a windows dev server myself the coming few days

**Comment by adamretter** [comment]
The `mmtmf` files are used to cache transient binary input streams. It looks to me like some other process is deleting the files when eXist is still using them.

@merenyics Do you know what is deleting these temp files? Perhaps you could monitor them? I have found this tool useful in the past - http://www.nirsoft.net/utils/opened_files_view.html

**Comment by merenyics** [comment]
I switched to memory cache for the time being, as I am busy with a work project right now, but as soon as I have the time, I will investigate further with the tool you recommended, and will get back to you with the results. Might be a few days...

**Comment by dizzzz** [comment]
@merenyics any update on this subject?

**Comment by merenyics** [comment]
Finally, I found some time to investigate the problem using the tool @adamretter suggested. I switched back to disk cache, and I can see the _mmtfm... folders being recreated very frequently. This time, the folder is always empty when I check it, and I haven't encountered any problems so far. I will continue using disk cache from now on, and will get back to you once I have anything to report...

**Comment by merenyics** [comment]
I have a question related to the utility @adamretter recommended, though. So far as I can see, the program lists currently _open_ files and related processes. However, these temp files seem to be very short-lived, and the exception occurs when they are no longer there. How am I supposed to catch the offending process that deletes the temp file prematurely with this tool? Am I missing some functionality that allows tracking recent files?

**Comment by merenyics** [comment]
This is what I've found so far. The temp files normally get created and deleted by java.exe on every request I send to the database. The file is never really there for any noticeable length of time, however the directory usually remains.

The exception occurs when exist wants to **create** a new temp file, but the **directory** is missing, so it cannot create the file. 

I still don't know what process deleted the _mmtfm... directory from C:\WINDOWS\TEMP\, but hopefully I will find out next time. (procmon wasn't runnig at the time)

This is the relevant entry from my procmon log:

`01:31:00.2338990	java.exe	8720	CreateFile	C:\WINDOWS\TEMP\_mmtfm_f7474a4d-22a7-4ec6-9c0d-fd106a61eb363434713790261701561\mmtf_15205554602437331959807086690305.tmp	PATH NOT FOUND	Desired Access: Generic Write, Read Attributes, Disposition: Create, Options: Synchronous IO Non-Alert, Non-Directory File, Open Reparse Point, Attributes: N, ShareMode: Read, Write, Delete, AllocationSize: 0`

**Comment by merenyics** [comment]
I finally managed to find the culprit:

`00:29:48.0579556	cleanmgr.exe	5800	SetDispositionInformationFile	C:\Windows\Temp\_mmtfm_4112ca70-b820-4bb5-9992-1bf6278aedbc6908829687310904157	SUCCESS	Delete: True
`
It appears that the standard windows disk cleanup tool (cleanmgr.exe) periodically deletes empty folders in `WINDOWS\temp`.

Exist seems to assume that the `mmtf` folder created earlier is still there when trying to open a new tmp file, which is not necessarily the case. The code responsible for handling the disk cache should check for the presence of the tmp folder before attempting to create the tmp file.

I hope this is enough information for you to be able to track down and eliminate the bug. If there's anything else I could do to help you, please let me know.
