### ISSUE TITLE
Possible problem with scheduled jobs

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#1723]
### What is the problem

This is a placeholder issue while we gather more information about a problem we have observed on our server. We have seen the following scenario:

We have two scheduled jobs. One scheduled job (rebuilding sort indexes) fails with NPE. After this NPE, the other scheduled job (polling twitter) no longer runs. From @tuurma's notes:

> Twitter feed updates are properly scheduled, and I see no trace of problems in the scheduler logs but still twitter posts are not pulled in. What worries me in scheduler.log is dates sort index rebuild causing NPE every time it is triggered. Do you think the two can be connected? Excerpt from status.xml:
```xml
<jmx:row>
    <jmx:action>eXist.User</jmx:action>
    <jmx:id>
        XQuery: /db/apps/hsg-shell/modules/rebuild-dates-sort-index.xql
    </jmx:id>
    <jmx:info>600000</jmx:info>
</jmx:row>
<jmx:row>
    <jmx:action>eXist.User</jmx:action>
    <jmx:id>REST_TimeoutCheck</jmx:id>
    <jmx:info>2000</jmx:info>
</jmx:row>
<jmx:row>
    <jmx:action>eXist.User</jmx:action>
    <jmx:id>
        XQuery: /db/apps/twitter/jobs/download-recent-twitter-posts.xq
    </jmx:id>
    <jmx:info>600000</jmx:info>
</jmx:row>
```

> Excerpt from scheduler.log:
> 2018-01-20 01:23:16,423 [DefaultQuartzScheduler_Worker-4] ERROR (JobRunShell.java [run]:211) - Job eXist.User.XQuery: /db/apps/hsg-shell/modules/rebuild-dates-sort-index.xql threw an unhandled Exception: java.lang.NullPointerException: null at org.exist.storage.btree.BTree$BTreeNode.split(BTree.java:1583) ~[exist.jar:3.4.1]

### What did you expect

The failure of one scheduled job should not cause other scheduled jobs to fail.

### Describe how to reproduce or add a test

Not yet available.

### Context information

- eXist-db version + Git Revision hash: eXist 3.4.1 release
- Java version (e.g. Java8u121): 1.8.0_131
- Operating system (Windows 7, Linux, MacOs): Amazon Linux
- 32 or 64 bit: 64 bit
- Any custom changes in e.g. conf.xml: scheduled jobs

**Comment by adamretter** [comment]
@joewiz Have you set `unschedule-on-exception` to `false` for the job? The default is `true`.

Also, I would suggest that `java.lang.NullPointerException: null at org.exist.storage.btree.BTree$BTreeNode.split(BTree.java:1583)` is a serious problem and should not be ignored

**Comment by duncdrum** [comment]
see #256 #274

**Comment by duncdrum** [comment]
@joewiz any new on this?
