### ISSUE TITLE
severe startup warning: Invalid byte tag in log4j-api-2.1.10.jar?

### ISSUE THREAD

**Issue by rvdb** [eXist-db/exist#1762]
### What is the problem
When deploying an eXist-4.0.0 WAR build in Tomcat-7.0.50 (with jdk1.8.0_161 on Windows 7 64 bit), following warning is spawn in the console window (converted from a screenshot, and checked; hopefully I didn't miss any OCR errors):

    mrt 05, 2018 10:24:00 AM org.apache.catalina.startup.ContextConfig processAnnotationsJar
    SEVERE: Unable to process Jar entry [module-info.class] from Jar [jar:file:/F:/tomcat/exist-4.4.0/WEB-INF/lib/log4j-api-2.10.0.jar!/] for annotations
    org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
      at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant.java:137)
      at org.apache.tomcat.util.bcel.classfile.ConstantPool.<init>(ConstantPool.java:60)
      at org.apache.tomcat.util.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:209)
      at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:119)
      at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2147)
      at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:2023)
      at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1989)
      at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1974)
      at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1321)
      at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:880)
      at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:378)
      at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
      at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
      at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5343)
      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
      at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
      at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
      at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:634)
      at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1230)
      at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1876)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      at java.lang.Thread.run(Thread.java:748)

It seems that something is wrong w.r.t `log4j-api-2.1.10.jar`. Yet, the webapp does seem to start.

### What did you expect
I'd expect the class loading to run without this warning.

### Describe how to reproduce or add a test

1. build WAR file from eXist-4.0.0 with the command `build dist-war`
2. copy WAR file to Tomcat webapps folder
3. start Tomcat

### Context information
Please always add the following information
- eXist-db 4.0.0 /  cc66ebc 
- jdk1.8.0_161
- Windows 7
- 64 bit
- Tomcat-7.0.50

**Comment by rvdb** [comment]
On closer examination, this is probably a minor issue. When updating to Tomcat-7.0.85, the warning disappears.

**Comment by adamretter** [comment]
@rvdb So we are okay to close?

**Comment by rvdb** [comment]
@adamretter sure
