### ISSUE TITLE
eXist-db 4.0.0 Connecting to SQL

### ISSUE THREAD

**Issue by Frederic-P** [eXist-db/exist#1778]
### What is the problem
In the browser when pointing to the url: http://localhost:8080/exist/apps/dashboard/ 

I get:
This site can’t be reached
localhost refused to connect.
Search Google for localhost 8080 exist apps dashboard
ERR_CONNECTION_REFUSED

### What did you expect
I expected the dashboard to be there as it was before server restart.

### Describe how to reproduce or add a test
My goal is to add the JDBC-MYSQL connector. For this I have only found documentation dating back from 2007: https://exist-db.org/exist/apps/wiki/HowTo/SQLDatabases/ 

1. Open conf.xml
2. append <code> \<module class="org.exist.xquery.modules.sql.SQLModule" uri="http://exist-db.org/xquery/sql" /> </code> to this file.
  - The documentation does not provide information where this code needs to be pasted... Since it is a module I placed the code between the <code>\<modules> \</modules></code> tag which start at line 418.
  - Save conf.xml & close conf.xml
3. Stop server and quit eXist-db
4. Restart service
5. Launch eXist-db
6 go to http://localhost:8080/exist/apps/dashboard/

### Context information
Please always add the following information
- eXist-db version: 4.0.0.
- Java version: Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
- Windows 10 Enterprise
- 64 bit
- Yes: added  <code>\<module class="org.exist.xquery.modules.sql.SQLModule" uri="http://exist-db.org/xquery/sql" /></code>  in between the <code>\<modules>\</modules></code>tags.

### Log information
The eXist-db Log has the following error message: 
2018-03-22 13:43:12,959 [main] INFO  (Configuration.java [<init>]:175) - Reading configuration from file .\conf.xml 
2018-03-22 13:43:13,006 [main] ERROR (JettyStart.java [run]:177) - configuration error: Required attribute id is missing for module 
org.exist.util.DatabaseConfigurationException: Required attribute id is missing for module
	at org.exist.util.Configuration.configureIndexer(Configuration.java:1429) ~[exist.jar:4.0.0]
	at org.exist.util.Configuration.<init>(Configuration.java:199) ~[exist.jar:4.0.0]
	at org.exist.util.SingleInstanceConfiguration.<init>(SingleInstanceConfiguration.java:57) ~[exist.jar:4.0.0]
	at org.exist.util.SingleInstanceConfiguration.<init>(SingleInstanceConfiguration.java:49) ~[exist.jar:4.0.0]
	at org.exist.jetty.JettyStart.run(JettyStart.java:162) [exist-optional.jar:4.0.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.exist.yajsw.Main.start(Main.java:47) [classes/:?]
	at org.exist.yajsw.Main.main(Main.java:65) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60) [wrapperApp.jar:?]
	at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43) [wrapperApp.jar:?]

### Note
- Removing the added code and restarting the server allows eXist to work again.
- Is there an up to date reference to connect eXist to MYSQL?

**Comment by dizzzz** [comment]
<modules>is not the right location.  please check the conf.xml file, and find the sql module*S* below;

https://github.com/eXist-db/exist/blob/develop/conf.xml.tmpl#L916

**Comment by Frederic-P** [comment]
@dizzzz that line was enabled by default, so that step could be skipped. All is in working order now. Thanks! Shall I open a ticket in the documentation-section?

**Comment by duncdrum** [comment]
@dizzzz see #1779

**Comment by duncdrum** [comment]
@Frederic-P please take a look at exist-db/documentation#102 and let us know what changes to the wiki article should be made when incorporating it into the docs.

**Comment by Frederic-P** [comment]
@duncdrum 
This is the wiki-article I'm referring to: https://exist-db.org/exist/apps/wiki/HowTo/SQLDatabases/ 

**Things that need to be changed as I found them to be for eXist-db version 4**:
1. Remove section 1.1 (eXist Configuration)
  - There's no need for this section anymore as the code is already present and active in the conf.xml file.

2. Section 1.2: JDBC Drivers.
  - All in all in order, though the path EXIST_HOME/lib/user can be changed to something else as EXIST_HOME is not present on my system... An example could be _JDBC Drivers should be placed in /lib/user folder which is found in your eXist-db install directory._

3. Section 1.3: The SQL module.
  - There's a markup inconsistency in this section (i.e. 1.3.1 get-connection() is wrapped in <code>/<h3>/</h3> tags, whereas section 1.3.2.  execute() is wrapped in <code>/<h2>/</h2></code> tags.
  - Suggestion for improvement: in stead of only giving the JDBC Driver Class for MySQL one could provide an outbound link to the other classes. 
  - The<code>$useColumnNames</code> parameter would benefit from a more in-depth explanation. What datatype is it (I'm guessing it's a bool?) and if a user decides not to use the Column Names as node names, what are the alternatives? i;e. can a user declare the node names autonomously, or does eXist then uses numbers to refer to columns rather than the names?


**Overall additions**

There should be at least a link referencing the documentation of eXide where users are informed about. The current reference material at http://exist-db.org/exist/apps/eXide/docs/doc.html and https://exist-db.org/exist/apps/doc/learning-xquery.xml Do not cover the following things:
1. The different types of output; what do they do/ what is the recommended use for each type of output?
2. Give the users a warning about the Live Preview, if you query large databases and have Live Preview enabled it causes slow-downs of eXist and time-outs... This feature was also enabled by default, perhaps one would benefit from having this feature disabled by default?

Hopefully this helps

**Comment by duncdrum** [comment]
@dizzzz can you move this please, to the documentation repo.
