### ISSUE TITLE
RestXQ preparing new registry fails again

### ISSUE THREAD

**Issue by pherk** [eXist-db/exist#1831]
### What is the problem

restxq.log:
```
2018-04-15 11:07:21,150 [qtp1985280051-25] INFO  (RestXqServiceRegistryPersistence.java [updateRegistryOnDisk]:149) - Preparing new RESTXQ registry on disk: /tmp/_mmtfm_8c11733d-d670-4893-9c42-b90f7a67736e710650012148238812/mmtf_15237832411501691396891179318576.tmp
2018-04-15 11:07:21,153 [qtp1985280051-25] ERROR (RestXqServiceRegistryPersistence.java [updateRegistryOnDisk]:192) - /home/peter/devel/exist/webapp/WEB-INF/data
java.nio.file.FileAlreadyExistsException: /home/peter/devel/exist/webapp/WEB-INF/data
        at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:551) ~[?:1.8.0_161]
        at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253) ~[?:1.8.0_161]
        at java.nio.file.Files.copy(Files.java:1274) ~[?:1.8.0_161]
        at org.exist.extensions.exquery.restxq.impl.RestXqServiceRegistryPersistence.updateRegistryOnDisk(RestXqServiceRegistryPersistence.java:184) ~[exist-restxq.jar:4.1.0-SNAPSHOT]
        at org.exist.extensions.exquery.restxq.impl.RestXqServiceRegistryPersistence.registered(RestXqServiceRegistryPersistence.java:129) ~[exist-restxq.jar:4.1.0-SNAPSHOT]
```
### What did you expect

shouldn't fail (silently)

### Describe how to reproduce or add a test

- save restxq file from eXide
- exrest:register-module()

### Context information

- eXist 4.1.0-SNAPSHOT+201804151103 build
- Git commit: abdce9b
- Git branch: develop
- Java8u162
- Ubuntu 64bit

- Any custom changes in e.g. conf.xml : none

**Comment by pherk** [comment]
after reading the docs for nio.copy(), it seems that the 'new' filename is missing
line 184           final Path localTmpNewRegistry = Files.copy(tmpNewRegistry, registry.getParent().resolve(tmpNewRegistry.getFileName()));

... somewhat convoluted ;-)

**Comment by dizzzz** [comment]
I do not know the "exrest:register-module()" module, in which module namespace is it? how do you invoke  it? (whole  query please)

**Comment by pherk** [comment]
pardon,
I thought exrest is an 'official' namespace and Adam will spot the error cause at once (his own pull request last week) ...
my exrest:register-module() lives in http://exquery.org/ns/restxq/exist and takes an xs:URI arg
NB: I'm quite happy with the above micro patch

**Comment by dizzzz** [comment]
There are more developers here than @adamretter and I was actually prepared (and did) to spend my time in this issue to get it fixed you you. Unfruitfully though as I still doe not have sufficient hooks to get started.

**Comment by adamretter** [comment]
@pherk Thanks for reporting. I just sent a PR.
