### ISSUE TITLE
eXist 4.0.0: user and group disappeared from running server (out of the blue)

### ISSUE THREAD

**Issue by marc-karnovgroup** [eXist-db/exist#1884]
### What is the problem

I have created a local user and group `ilse:ilse` this way on the exist-db:

```
/opt/eXist400/bin/client.sh
# create user:group ilse:ilse in X-admin interface
# cant't be done in cli client interface (!!!)
quit
```

```
/opt/eXist400/bin/client.sh -u admin -P ************ -s
exist:/db>mkcol karnovgroup
exist:/db>mkcol karnovgroup/ilse
exist:/db>chown ilse ilse karnovgroup/ilse
exist:/db>quit
```

```
/opt/eXist400/bin/client.sh -u ilse -P ****** -s
exist:/db>mkcol karnovgroup/ilse/dk
exist:/db>mkcol karnovgroup/ilse/se
exist:/db>quit
```

Check collections and `user:group` rights using rest interfaces showed OK
```
    http://dc0xmldb01:8080/exist/rest/db/system/security/exist/groups/ilse.xml
    http://dc0xmldb01:8080/exist/rest/db/system/security/exist/accounts/ilse.xml
    http://dc0xmldb01:8080/exist/rest/db/karnovgroup/
    http://dc0xmldb01:8080/exist/rest/db/karnovgroup/ilse/
```

Uploading docs through REST interface to these collections went fine for weeks.
```
2018-05-14T11:57:27.197Z HTTP/1.1 PUT /exist/rest/db/karnovgroup/ilse/dk/32/7000322232.xml 10.64.1.23  201 ''
2018-05-14T11:57:27.327Z HTTP/1.1 PUT /exist/rest/db/karnovgroup/ilse/dk/32/7000322232.xml 10.64.1.23  201 ''
2018-05-14T12:04:57.188Z HTTP/1.1 PUT /exist/rest/db/karnovgroup/ilse/se/53/2516753.xml 10.64.1.23  201 ''
...
but then:
...

2018-05-14T13:04:57.247Z HTTP/1.1 PUT /exist/rest/db/karnovgroup/ilse/se/58/2514958.xml 10.64.1.23  401 ''
...
2018-05-23T11:01:19.328Z HTTP/1.1 DELETE /exist/rest/db/karnovgroup/ilse/dk/29/7000820429.xml 10.64.1.23  401 ''
...
2018-05-24T13:51:21.614Z HTTP/1.1 DELETE /exist/rest/db/karnovgroup/ilse/dk/99/7000368899.xml 10.64.1.23  401 ''
...
2018-05-25T06:37:27.299Z HTTP/1.1 PUT /exist/rest/db/karnovgroup/ilse/dk/96/7000821196.xml 10.64.1.23  401 ''
```

The server was reactling sluggish, and I did stop and restart it. No change.

Investigation shows that the user and group `ilse:ilse` had disappeared, and all documents owned by `ilse:ilse` now where owned by `SYSTEM:dba`:

Ownership of XML files with REST HTTP connection errors 401 are now
```
exist:/db/karnovgroup/ilse/dk/29>ls
-rw-r--r--	SYSTEM	dba	7000438529.xml	Tue Apr 24 17:41:35 CEST 2018
-rw-r--r--	SYSTEM	dba	7000438729.xml	Tue Apr 24 17:41:35 CEST 2018
```

Also the admin password has been erased somehow: earlier I had to log in like this:
```
/opt/eXist400/bin/client.sh -u admin -P ************ -s
```

Now this does not work any more, but it works with an empty password:
```
/opt/eXist400/bin/client.sh -u admin -s
```

This gets more and more fishy: in one side we do have an enabled user ilse in the REST interface:
```
    http://dc0xmldb01:8080/exist/rest/db/system/security/exist/accounts/ilse.xml

<account id="13">
<password>{RIPEMD160}G3Ni951iKAhr5djbl/Z1YxBjrAU=</password>
<digestPassword>34408be4e89d635136a4d069a1ad3fa3a04c31ec</digestPassword>
<group name="ilse"/>
<expired>false</expired>
<enabled>true</enabled>
<umask>022</umask>
<metadata key="http://axschema.org/namePerson"/>
<metadata key="http://exist-db.org/security/description">ilse data read and write</metadata>
<name>ilse</name>
</account>
```

On the other hand, changing ownership to this user can not be done:
```
/opt/eXist400/bin/client.sh -u admin -s
exist:/db>cd karnovgroup
exist:/db/karnovgroup>chown ilse ilse ilse
unknown user
```

WORK-AROUND:

An arbitrarily combination of
   * logging into X-userinterface using `/opt/eXist400/bin/client.sh -u admin`
   * changing admin password back in X-interface
   * logging into X-userinterface using `/opt/eXist400/bin/client.sh -u admin -P ********`
   * recreation of user:group `ilse:ilse` which original permissions
   * logging out,
   * restarting exist-db,
   * logging in again,
   * and once more for the fun
   * logging in X-interface as admin and issuing
     ```
      exist:/db>cd karnovgroup
      exist:/db/karnovgroup>chown ilse ilse ilse
    ```

seems to have done the trick of re-establishing user and ownership. There seems to be a caching problem in the X-clinet-interface, since I needed to re-do stuff multiple times ??!?

See HTTP REST client logs:

```
 tail -f rack-stdout.log
2018-05-25T10:37:27.422Z HTTP/1.1 PUT /exist/rest/db/karnovgroup/ilse/dk/33/7000820733.xml 10.64.1.23  401 ''
2018-05-25T10:37:27.602Z HTTP/1.1 PUT /exist/rest/db/karnovgroup/ilse/dk/82/7000756582.xml 10.64.1.23  401 ''

# manipulating server as described above

2018-05-25T10:57:27.166Z HTTP/1.1 PUT /exist/rest/db/karnovgroup/ilse/dk/50/7000819250.xml 10.64.1.23  500 'Couldn't connect to server'
2018-05-25T10:57:27.295Z HTTP/1.1 PUT /exist/rest/db/karnovgroup/ilse/dk/50/7000819250.xml 10.64.1.23  500 'Couldn't connect to server'
2018-05-25T10:57:27.435Z HTTP/1.1 PUT /exist/rest/db/karnovgroup/ilse/dk/92/7000804192.xml 10.64.1.23  500 'Couldn't connect to server'
2018-05-25T11:05:00.109Z HTTP/1.1 PUT /exist/rest/db/karnovgroup/ilse/se/92/478092.xml 10.64.1.23  500 'Timeout was reached'

# finished restart of server - now REST PUT works as expected

2018-05-25T11:07:27.880Z HTTP/1.1 PUT /exist/rest/db/karnovgroup/ilse/dk/74/7000819974.xml 10.64.1.23  201 ''
2018-05-25T11:07:28.203Z HTTP/1.1 PUT /exist/rest/db/karnovgroup/ilse/dk/97/7000821197.xml 10.64.1.23  201 ''
2018-05-25T11:07:28.390Z HTTP/1.1 PUT /exist/rest/db/karnovgroup/ilse/dk/74/7000819974.xml 10.64.1.23  201 ''
2018-05-25T11:07:28.568Z HTTP/1.1 PUT /exist/rest/db/karnovgroup/ilse/dk/99/7000821199.xml 10.64.1.23  201 ''
```

### What did you expect

I did expect that a user:group combonation never disappears in the blue air. Promise, there have not been any manual config manipulations! 

### Describe how to reproduce or add a test
Sorry, can't describe how to reproduce the problem. Except defining a new user and group, assign collections to them and keep uploading and refreshing 200.000 docs over weeks. Until it maybe happens again.

### Context information

  *  eXist-db version 4.0.0 as downloaded from release page
  *  Java version
```
java -version
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)
```
  *  Operating system Red Hat Enterprise Linux Server release 7.4 (Maipo)
  *   Kernel 3.10.0-693.21.1.el7.x86_64 64 bit
   *  Any custom changes in e.g. conf.xml
```
grep validation /opt/eXist400/conf.xml
<validation mode="no">
grep validation /opt/eXist400/webapp/WEB-INF/conf.xml
<validation mode="no">
```

**Comment by duncdrum** [comment]
hmm i m wondering if this is related to #101. If i understood you correctly, there is a single user in the group initially, if somehow that user is corrupted, that could explain the follow up problems with the group.

**Comment by adamretter** [comment]
I can see a couple reasons why this might have occurred:

1. A database corruption.
2. A problem with synchronization between the in-memory and on-disk representations of users and groups (which is managed via the Configurator).

Unfortunately with out a way to reproduce, it is very difficult to determine what actually caused this.

@marc-karnovgroup was there any information in `exist.log`?

**Comment by marc-karnovgroup** [comment]
I find things like this in the logs:
[exist.20180523124201.log.gz](https://github.com/eXist-db/exist/files/2043981/exist.20180523124201.log.gz)

After restart of the server:
```
2018-05-14 14:42:23,121 [main] ERROR (BrokerPools.java [configure]:187) - Unable to initialize database instance 'exist': org.exist.storage.BrokerPoolServiceException: org.exist.util.DatabaseConfigurationException: Exception while reading lucene index directory: Lock obtain timed out: NativeFSLock@/data/eXist400/lucene/write.lock 
org.exist.EXistException: org.exist.storage.BrokerPoolServiceException: org.exist.util.DatabaseConfigurationException: Exception while reading lucene index directory: Lock obtain timed out: NativeFSLock@/data/eXist400/lucene/write.lock
        at org.exist.storage.BrokerPool._initialize(BrokerPool.java:507) ~[exist.jar:4.0.0]
        at org.exist.storage.BrokerPool.initialize(BrokerPool.java:415) ~[exist.jar:4.0.0]
        at org.exist.storage.BrokerPools.configure(BrokerPools.java:181) [exist.jar:4.0.0]
        at org.exist.storage.BrokerPools.configure(BrokerPools.java:110) [exist.jar:4.0.0]
```

Next day I see this the first time:
```
2018-05-18 11:31:46,239 [DefaultQuartzScheduler_Worker-2] INFO  (BFile.java [printStatistics]:419) - values.dbx DATA Buffers occupation : 0% (0 out of 64) Cache effic
iency : N/A 
2018-05-18 11:33:06,366 [qtp252247502-28] FATAL (UnixStylePermission.java [getOwner]:87) - Detected a Security Database corruption. Could not find account for id: 13.
 
2018-05-18 11:33:06,366 [qtp252247502-28] FATAL (UnixStylePermission.java [getGroup]:169) - Detected a Security Database corruption. Could not find group for id: 13. 
2018-05-18 11:33:26,287 [qtp252247502-27] FATAL (UnixStylePermission.java [getOwner]:87) - Detected a Security Database corruption. Could not find account for id: 13.
 
```

I attach the relevant zipped log, notice that  the above mentioned HTTP REST client logs are UTC, whereas I suspect the eXist logs to be Copenhagen summertime (= UTC + 2hours).

**Comment by marc-karnovgroup** [comment]
Sorry. did hit the wrong button. Here the log is attached now:
[exist.20180523124201.log.gz](https://github.com/eXist-db/exist/files/2043989/exist.20180523124201.log.gz)

**Comment by adamretter** [comment]
@marc-karnovgroup So it looks to me like you might have experienced some sort of database corruption. I would recommend a full backup, delete and restore.

**Comment by marc-karnovgroup** [comment]
Well, I have - it seems - only experienced a security database corruption. The actual XML data is still there and is as far as I can tell, well-functioning.

Also, a  security database corruption should never happen when one has not added/deleted users/groups for weeks, right?

I would expect all added user/group data to be synced between memory and disc once, and never touched or corrupted since.

**Comment by joewiz** [comment]
It appears this report has been addressed. Please open a new issue if there are any other concerns.
