### ISSUE TITLE
New issue with eXist 4.2.0: Restore indefinitely hangs with no error message

### ISSUE THREAD

**Issue by iampopuri** [eXist-db/exist#1913]
### What is the problem 
> Problem: Restore indefinitely hangs with no error message
> Description: After importing very few files then it just hangs forever without any error message

### What did you expect
> Restore should continue till all files import is completed

### Describe how to reproduce or add a test
> Take small set of data backup from old eXist database and try to restore them via client or linux command line with ant script then it just hangs. The problem seems to be in RemoteCollection.java Line # 624. It might be going to indefinite while loop.
### Context information
Please always add the following information
- eXist-db version + Git Revision hash - eXist-db 4.2.0 
- Java version - 1.8.0_161-b14
- Operating system - (Windows 7, Linux) - 64 bit
- How is eXist-db installed? - JAR installer
- Any custom changes in e.g. conf.xml - No

![restore-hangs](https://user-images.githubusercontent.com/39523509/41048624-6d58762a-69af-11e8-8cc9-8244371c170b.jpg)

**Comment by duncdrum** [comment]
phew I wonder if this is related to #1874 both times RemoteCollection seems to be throwing itself a party.

**Comment by iampopuri** [comment]
Few more points from my colleague....might helpful for you.

Seems like some changes made to optimize the chunk size in the RemoveCollection.java are causing these issues: See below picture.

![code_bug](https://user-images.githubusercontent.com/39523509/41089585-7ae5cfa2-6a42-11e8-9418-ef02235b062c.jpg)

At line 602 the chunk size resolves to 0, therefore a database is created of 0 length.
When entering the wile loop at 612, the len will therefore always be 0 – as it never reads any bytes – and thus hangs indefinitely.

If we comment the chunk size changes and revert back to the original we get the following error at line 670 which seems to be a problem in the RpcConnection: 

![code_bug_1 jpg](https://user-images.githubusercontent.com/39523509/41089600-86bec108-6a42-11e8-8344-60c60d4e41f0.png)

09:16:47.070 [pool-3-thread-1] ERROR org.exist.backup.restore.RestoreHandler - networking error
org.xmldb.api.base.XMLDBException: networking error
       at org.exist.xmldb.RemoteCollection.uploadAndStore(RemoteCollection.java:704) ~[classes/:?]
       at org.exist.xmldb.RemoteCollection.storeResource(RemoteCollection.java:504) ~[classes/:?]
       at org.exist.backup.restore.RestoreHandler.restoreResourceEntry(RestoreHandler.java:392) [classes/:?]
       at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:122) [classes/:?]
       at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source) [xercesImpl-2.11.0.jar:?]
       at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source) [xercesImpl-2.11.0.jar:?]
       at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source) [xercesImpl-2.11.0.jar:?]
       at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) [xercesImpl-2.11.0.jar:?]
       at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) [xercesImpl-2.11.0.jar:?]
       at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) [xercesImpl-2.11.0.jar:?]
       at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) [xercesImpl-2.11.0.jar:?]
       at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) [xercesImpl-2.11.0.jar:?]
       at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) [xercesImpl-2.11.0.jar:?]
       at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) [xercesImpl-2.11.0.jar:?]
       at org.exist.backup.restore.RestoreHandler.restoreSubCollectionEntry(RestoreHandler.java:255) [classes/:?]
       at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:128) [classes/:?]
       at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source) [xercesImpl-2.11.0.jar:?]
       at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source) [xercesImpl-2.11.0.jar:?]
       at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source) [xercesImpl-2.11.0.jar:?]
       at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) [xercesImpl-2.11.0.jar:?]
       at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) [xercesImpl-2.11.0.jar:?]
       at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) [xercesImpl-2.11.0.jar:?]
       at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) [xercesImpl-2.11.0.jar:?]
       at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) [xercesImpl-2.11.0.jar:?]
       at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) [xercesImpl-2.11.0.jar:?]
       at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) [xercesImpl-2.11.0.jar:?]
       at org.exist.backup.Restore.restore(Restore.java:87) [classes/:?]
       at org.exist.client.ClientFrame.lambda$16(ClientFrame.java:1097) [classes/:?]
       at org.exist.client.ClientFrame$$Lambda$113/850456772.call(Unknown Source) [classes/:?]
       at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: org.apache.xmlrpc.XmlRpcException: Failed to invoke method parseLocalExt in class org.exist.xmlrpc.RpcConnection: org.xml.sax.SAXException: The XML parser reported a problem: fatal error at (-1,-1) : Premature end of file.
org.xml.sax.SAXException: fatal error at (-1,-1) : Premature end of file.
org.xml.sax.SAXParseException; Premature end of file.
       at org.apache.xmlrpc.client.XmlRpcStreamTransport.readResponse(XmlRpcStreamTransport.java:197) ~[xmlrpc-client-3.1.3.jar:3.1.3]
       at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:156) ~[xmlrpc-client-3.1.3.jar:3.1.3]
       at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143) ~[xmlrpc-client-3.1.3.jar:3.1.3]
       at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69) ~[xmlrpc-client-3.1.3.jar:3.1.3]
       at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56) ~[xmlrpc-client-3.1.3.jar:3.1.3]
       at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167) ~[xmlrpc-client-3.1.3.jar:3.1.3]
       at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:158) ~[xmlrpc-client-3.1.3.jar:3.1.3]
       at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:147) ~[xmlrpc-client-3.1.3.jar:3.1.3]
       at org.exist.xmldb.RemoteCollection.uploadAndStore(RemoteCollection.java:691) ~[classes/:?]
       ... 32 more

**Comment by duncdrum** [comment]
@dizzzz any ideas what going on here?

**Comment by dizzzz** [comment]
@duncdrum not yet.  Maybe the client provides no content-length (0?) .... could be validated by putting
