### ISSUE TITLE
Cannot import DTD to Exist server using "RemoteCollection" API (Exist 4.3.0)

### ISSUE THREAD

**Issue by raducoravu** [eXist-db/exist#2036]
Using Oxygen XML Editor with Exist 4.3.0 to import a local DTD to an Exist DB.
Code looks like this:

```java
    /**
     * Creates a eXist resource into the eXist collection.
     * 
     * @see ro.sync.db.nxd.NXDContainer.ImportCollection#createResource(java.io.File)
     */
    @Override
    public void createResource(File file) throws DBException {
      
      XmldbURI filenameUri;
      try {
          filenameUri = URIUtils.encodeXmldbUriFor(file.getName());
      } catch (URISyntaxException e1) {
          throw new DBException(file.getAbsolutePath()+ " could not be encoded as a URI");
      }

      // The unit is a file, add the file as a resource.
      MimeType mimeType = ((ExistSession) getDBLink()).getContentType(file.getName());
      if (mimeType == null || mimeType.getXMLDBType() == null) {
        if (logger.isDebugEnabled()) {
          logger.debug("\nFile " + file.getName()
              + " has an unknown suffix. Assuming binary type.\n");
        }
        mimeType = MimeType.BINARY_TYPE;
      }
      try {
        Resource document = existCollection.createResource(filenameUri.toString(), mimeType.getXMLDBType());
        ((EXistResource) document).setMimeType(mimeType.getName());
        //EXM-39520 Try to close the input streams ourselves, as Exist does not do that...
        InputSource is = new InputSource();
        FileInputStream fis = null;
        try{
          fis = new FileInputStream(file);
          is.setByteStream(fis);
          try {
            is.setSystemId(URLUtil.correct(file).toString());
          } catch (MalformedURLException e) {
            //Ignore
          }
          document.setContent(is);
          existCollection.storeResource(document);
        } finally {
          if(fis != null){
            try{
              fis.close();
            } catch(IOException ex){
              //Ignore
            }
          }
        }
      } catch (XMLDBException e) {
        throw new DBException(getCause(e), ExistContainer.this);
      } catch (FileNotFoundException e) {
        throw new DBException(e, ExistContainer.this);
      }
    }
```
and throws this error:

        org.apache.xmlrpc.XmlRpcException: Failed to invoke method parseLocalExt in class org.exist.xmlrpc.RpcConnection: null
        	at ro.sync.db.nxd.exist.ExistContainer$ExistImportCollection.createResource(ExistContainer.java:674)
        	at ro.sync.db.nxd.NXDContainer.importUnit(NXDContainer.java:369)
        	at ro.sync.db.nxd.NXDContainer.importUnits(NXDContainer.java:465)
        	at ro.sync.db.nxd.NXDContainer.internalImport(NXDContainer.java:435)
        	at ro.sync.db.DBDnDTreeHandler$1.appRun(DBDnDTreeHandler.java:421)
        	at ro.sync.ui.application.ApplicationThread.run(ApplicationThread.java:135)
        Caused by: org.apache.xmlrpc.XmlRpcException: Failed to invoke method parseLocalExt in class org.exist.xmlrpc.RpcConnection: null
        	at org.apache.xmlrpc.client.XmlRpcStreamTransport.readResponse(XmlRpcStreamTransport.java:197)
        	at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:156)
        	at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
        	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
        	at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
        	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
        	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:158)
        	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:147)
        	at org.exist.xmldb.RemoteCollection.uploadAndStore(RemoteCollection.java:686)
        	at org.exist.xmldb.RemoteCollection.storeResource(RemoteCollection.java:502)
        	at org.exist.xmldb.RemoteCollection.storeResource(RemoteCollection.java:471)
        	at ro.sync.db.nxd.exist.ExistContainer$ExistImportCollection.createResource(ExistContainer.java:663)
        	... 5 more

**Comment by raducoravu** [comment]
This used to work with any previous Exist server versions.

**Comment by adamretter** [comment]
Hi @raducoravu can you provide the relevant parts from the eXist-db server logs please as the stack-traces from the client dont' help much. You should take a look in `exist.log` and `xml-rpc.log` in `$EXIST_HOME/webapp/WEB-INF/data`.

**Comment by raducoravu** [comment]
I found something interesting in the xmlrpc.log, I'm attaching it:

[xmlrpc.log](https://github.com/eXist-db/exist/files/2197033/xmlrpc.log)

**Comment by adamretter** [comment]
So the interesting bit from `xml-rpc.log` is:

```
Caused by: java.lang.NullPointerException
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:98) ~[?:1.8.0_102]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:1.8.0_102]
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94) ~[?:1.8.0_102]
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255) ~[?:1.8.0_102]
	at java.nio.file.Paths.get(Paths.java:84) ~[?:1.8.0_102]
	at org.exist.xmlrpc.RpcConnection.lambda$parseLocal$44(RpcConnection.java:1463) ~[exist.jar:4.3.0]
```

The interesting thing here is that line 1463 will only be invoked if there is a `NumberFormatException` thrown by `Integer.parseInt(localFile)`.

So it seems that somehow your call to `existCollection.storeResource(document);` on the client side is either doing something wrong or something that causes a fault in the server side.

@raducoravu Is it possible that you could share with me the file that causes this issue, so that I can reproduce it here?

**Comment by raducoravu** [comment]
@adamretter Funny that I did not have the idea to look inside the file until now. It's an empty file (0 bytes) called "log4j.dtd".

**Comment by adamretter** [comment]
@raducoravu Okay interesting. I just want to check, are you certain this is with eXist-db 4.3.0? It may well be, but I wanted to check as we fixed some problems with 0-byte files in the XML-RPC API in
374cb35d.

**Comment by raducoravu** [comment]
@adamretter, this particular automated test we have on our side started failing after upgrading our servers to Exist 4.3.0. Our previous Exist test server version was "4.0.0" build "201802140047".

**Comment by adamretter** [comment]
@raducoravu Okay, from your code I have managed to reproduce the issue. Thanks

**Comment by raducoravu** [comment]
👍
