### ISSUE TITLE
5.0.0RC3 does not install from JAR file

### ISSUE THREAD

**Issue by zopyx** [eXist-db/exist#2123]
Starting process Setting admin password ... (1/1)
--- Starting embedded database instance ---
Caught an exception while initializing db: configuration error: Duplicate field name "ajc$initFailureCause" with signature "Ljava.lang.Throwable;" in class file org/exist/security/PermissionRequiredAspect
org.xmldb.api.base.XMLDBException: configuration error: Duplicate field name "ajc$initFailureCause" with signature "Ljava.lang.Throwable;" in class file org/exist/security/PermissionRequiredAspect
	at org.exist.xmldb.DatabaseImpl.configure(DatabaseImpl.java:129)
	at org.exist.xmldb.DatabaseImpl.getLocalCollection(DatabaseImpl.java:192)
	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:178)
	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:169)
	at org.xmldb.api.DatabaseManager.getCollection(Unknown Source)
	at org.exist.installer.Setup.initDb(Setup.java:77)
	at org.exist.installer.Setup.main(Setup.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.exist.start.Main.invokeMain(Main.java:140)
	at org.exist.start.Main.run(Main.java:453)
	at org.exist.start.Main.main(Main.java:64)
Caused by: org.exist.EXistException: Duplicate field name "ajc$initFailureCause" with signature "Ljava.lang.Throwable;" in class file org/exist/security/PermissionRequiredAspect
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:674)
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:417)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:176)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:133)
	at org.exist.xmldb.DatabaseImpl.configure(DatabaseImpl.java:123)
	... 13 more
Caused by: java.lang.ClassFormatError: Duplicate field name "ajc$initFailureCause" with signature "Ljava.lang.Throwable;" in class file org/exist/security/PermissionRequiredAspect
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1009)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:545)
	at java.base/java.net.URLClassLoader.access$100(URLClassLoader.java:83)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:453)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:447)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:446)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at org.exist.security.UnixStylePermission.setMode(UnixStylePermission.java:257)
	at org.exist.security.PermissionFactory.chmod_impl(PermissionFactory.java:441)
	at org.exist.security.PermissionFactory.chmod(PermissionFactory.java:356)
	at org.exist.collections.MutableCollection.setPermissions(MutableCollection.java:1697)
	at org.exist.security.internal.SecurityManagerImpl.attach(SecurityManagerImpl.java:200)
	at org.exist.security.internal.SecurityManagerImpl.startSystem(SecurityManagerImpl.java:150)
	at org.exist.storage.BrokerPoolServicesManager.startSystemServices(BrokerPoolServicesManager.java:186)
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:581)
	... 17 more
[B@18539cb1org.exist.EXistException: Duplicate field name "ajc$initFailureCause" with signature "Ljava.lang.Throwable;" in class file org/exist/security/PermissionRequiredAspect
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:674)
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:417)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:176)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:133)
	at org.exist.xmldb.DatabaseImpl.configure(DatabaseImpl.java:123)
	at org.exist.xmldb.DatabaseImpl.getLocalCollection(DatabaseImpl.java:192)
	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:178)
	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:169)
	at org.xmldb.api.DatabaseManager.getCollection(Unknown Source)
	at org.exist.installer.Setup.initDb(Setup.java:77)
	at org.exist.installer.Setup.main(Setup.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.exist.start.Main.invokeMain(Main.java:140)
	at org.exist.start.Main.run(Main.java:453)
	at org.exist.start.Main.main(Main.java:64)
Caused by: java.lang.ClassFormatError: Duplicate field name "ajc$initFailureCause" with signature "Ljava.lang.Throwable;" in class file org/exist/security/PermissionRequiredAspect
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1009)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:545)
	at java.base/java.net.URLClassLoader.access$100(URLClassLoader.java:83)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:453)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:447)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:446)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at org.exist.security.UnixStylePermission.setMode(UnixStylePermission.java:257)
	at org.exist.security.PermissionFactory.chmod_impl(PermissionFactory.java:441)
	at org.exist.security.PermissionFactory.chmod(PermissionFactory.java:356)
	at org.exist.collections.MutableCollection.setPermissions(MutableCollection.java:1697)
	at org.exist.security.internal.SecurityManagerImpl.attach(SecurityManagerImpl.java:200)
	at org.exist.security.internal.SecurityManagerImpl.startSystem(SecurityManagerImpl.java:150)
	at org.exist.storage.BrokerPoolServicesManager.startSystemServices(BrokerPoolServicesManager.java:186)
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:581)
	... 17 more
Caused by: org.exist.EXistException: Duplicate field name "ajc$initFailureCause" with signature "Ljava.lang.Throwable;" in class file org/exist/security/PermissionRequiredAspect
--- Initialization complete. Shutdown embedded database instance ---
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:674)
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:417)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:176)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:133)
	at org.exist.xmldb.DatabaseImpl.configure(DatabaseImpl.java:123)
	at org.exist.xmldb.DatabaseImpl.getLocalCollection(DatabaseImpl.java:192)
	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:178)
	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:169)
	at org.xmldb.api.DatabaseManager.getCollection(Unknown Source)
	at org.exist.installer.Setup.initDb(Setup.java:77)
	at org.exist.installer.Setup.main(Setup.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.exist.start.Main.invokeMain(Main.java:140)
	at org.exist.start.Main.run(Main.java:453)
	at org.exist.start.Main.main(Main.java:64)
Caused by: java.lang.ClassFormatError: Duplicate field name "ajc$initFailureCause" with signature "Ljava.lang.Throwable;" in class file org/exist/security/PermissionRequiredAspect
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1009)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:545)
	at java.base/java.net.URLClassLoader.access$100(URLClassLoader.java:83)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:453)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:447)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:446)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at org.exist.security.UnixStylePermission.setMode(UnixStylePermission.java:257)
	at org.exist.security.PermissionFactory.chmod_impl(PermissionFactory.java:441)
	at org.exist.security.PermissionFactory.chmod(PermissionFactory.java:356)
	at org.exist.collections.MutableCollection.setPermissions(MutableCollection.java:1697)
	at org.exist.security.internal.SecurityManagerImpl.attach(SecurityManagerImpl.java:200)
	at org.exist.security.internal.SecurityManagerImpl.startSystem(SecurityManagerImpl.java:150)
	at org.exist.storage.BrokerPoolServicesManager.startSystemServices(BrokerPoolServicesManager.java:186)
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:581)
	... 17 more
Caught an exception while initializing db: configuration error: org.exist.storage.BrokerPoolServiceException: org.exist.util.DatabaseConfigurationException: Exception while reading lucene index directory: Lock obtain timed out: NativeFSLock@/tmp/xx/webapp/WEB-INF/data/lucene/write.lock
org.xmldb.api.base.XMLDBException: configuration error: org.exist.storage.BrokerPoolServiceException: org.exist.util.DatabaseConfigurationException: Exception while reading lucene index directory: Lock obtain timed out: NativeFSLock@/tmp/xx/webapp/WEB-INF/data/lucene/write.lock
	at org.exist.xmldb.DatabaseImpl.configure(DatabaseImpl.java:129)
	at org.exist.xmldb.DatabaseImpl.getLocalCollection(DatabaseImpl.java:192)
	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:178)
	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:169)
	at org.xmldb.api.DatabaseManager.getCollection(Unknown Source)
	at org.exist.installer.Setup.shutdown(Setup.java:95)
	at org.exist.installer.Setup.main(Setup.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.exist.start.Main.invokeMain(Main.java:140)
	at org.exist.start.Main.run(Main.java:453)
	at org.exist.start.Main.main(Main.java:64)
Caused by: org.exist.EXistException: org.exist.storage.BrokerPoolServiceException: org.exist.util.DatabaseConfigurationException: Exception while reading lucene index directory: Lock obtain timed out: NativeFSLock@/tmp/xx/webapp/WEB-INF/data/lucene/write.lock
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:510)
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:417)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:176)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:133)
	at org.exist.xmldb.DatabaseImpl.configure(DatabaseImpl.java:123)
	... 13 more
Caused by: org.exist.storage.BrokerPoolServiceException: org.exist.util.DatabaseConfigurationException: Exception while reading lucene index directory: Lock obtain timed out: NativeFSLock@/tmp/xx/webapp/WEB-INF/data/lucene/write.lock
	at org.exist.indexing.IndexManager.prepare(IndexManager.java:131)
	at org.exist.storage.BrokerPoolServicesManager.prepareServices(BrokerPoolServicesManager.java:157)
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:508)
	... 17 more
Caused by: org.exist.util.DatabaseConfigurationException: Exception while reading lucene index directory: Lock obtain timed out: NativeFSLock@/tmp/xx/webapp/WEB-INF/data/lucene/write.lock
	at org.exist.indexing.lucene.LuceneIndex.open(LuceneIndex.java:134)
	at org.exist.indexing.IndexManager.initIndex(IndexManager.java:146)
	at org.exist.indexing.IndexManager.prepare(IndexManager.java:119)
	... 19 more
Caused by: org.apache.lucene.store.LockObtainFailedException: Lock obtain timed out: NativeFSLock@/tmp/xx/webapp/WEB-INF/data/lucene/write.lock
	at org.apache.lucene.store.Lock.obtain(Lock.java:89)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:755)
	at org.exist.indexing.lucene.LuceneIndex.open(LuceneIndex.java:128)
	... 21 more
[B@2c2a027corg.exist.EXistException: org.exist.storage.BrokerPoolServiceException: org.exist.util.DatabaseConfigurationException: Exception while reading lucene index directory: Lock obtain timed out: NativeFSLock@/tmp/xx/webapp/WEB-INF/data/lucene/write.lock
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:510)
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:417)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:176)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:133)
	at org.exist.xmldb.DatabaseImpl.configure(DatabaseImpl.java:123)
	at org.exist.xmldb.DatabaseImpl.getLocalCollection(DatabaseImpl.java:192)
	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:178)
	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:169)
	at org.xmldb.api.DatabaseManager.getCollection(Unknown Source)
	at org.exist.installer.Setup.shutdown(Setup.java:95)
	at org.exist.installer.Setup.main(Setup.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.exist.start.Main.invokeMain(Main.java:140)
	at org.exist.start.Main.run(Main.java:453)
	at org.exist.start.Main.main(Main.java:64)
Caused by: org.exist.storage.BrokerPoolServiceException: org.exist.util.DatabaseConfigurationException: Exception while reading lucene index directory: Lock obtain timed out: NativeFSLock@/tmp/xx/webapp/WEB-INF/data/lucene/write.lock
	at org.exist.indexing.IndexManager.prepare(IndexManager.java:131)
	at org.exist.storage.BrokerPoolServicesManager.prepareServices(BrokerPoolServicesManager.java:157)
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:508)
	... 17 more
Caused by: org.exist.util.DatabaseConfigurationException: Exception while reading lucene index directory: Lock obtain timed out: NativeFSLock@/tmp/xx/webapp/WEB-INF/data/lucene/write.lock
	at org.exist.indexing.lucene.LuceneIndex.open(LuceneIndex.java:134)
	at org.exist.indexing.IndexManager.initIndex(IndexManager.java:146)
	at org.exist.indexing.IndexManager.prepare(IndexManager.java:119)
	... 19 more
Caused by: org.apache.lucene.store.LockObtainFailedException: Lock obtain timed out: NativeFSLock@/tmp/xx/webapp/WEB-INF/data/lucene/write.lock
	at org.apache.lucene.store.Lock.obtain(Lock.java:89)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:755)
	at org.exist.indexing.lucene.LuceneIndex.open(LuceneIndex.java:128)
	... 21 more
Caused by: org.exist.EXistException: org.exist.storage.BrokerPoolServiceException: org.exist.util.DatabaseConfigurationException: Exception while reading lucene index directory: Lock obtain timed out: NativeFSLock@/tmp/xx/webapp/WEB-INF/data/lucene/write.lock
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:510)
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:417)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:176)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:133)
	at org.exist.xmldb.DatabaseImpl.configure(DatabaseImpl.java:123)
	at org.exist.xmldb.DatabaseImpl.getLocalCollection(DatabaseImpl.java:192)
	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:178)
	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:169)
	at org.xmldb.api.DatabaseManager.getCollection(Unknown Source)
	at org.exist.installer.Setup.shutdown(Setup.java:95)
	at org.exist.installer.Setup.main(Setup.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.exist.start.Main.invokeMain(Main.java:140)
	at org.exist.start.Main.run(Main.java:453)
	at org.exist.start.Main.main(Main.java:64)
Caused by: org.exist.storage.BrokerPoolServiceException: org.exist.util.DatabaseConfigurationException: Exception while reading lucene index directory: Lock obtain timed out: NativeFSLock@/tmp/xx/webapp/WEB-INF/data/lucene/write.lock
	at org.exist.indexing.IndexManager.prepare(IndexManager.java:131)
	at org.exist.storage.BrokerPoolServicesManager.prepareServices(BrokerPoolServicesManager.java:157)
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:508)
	... 17 more
Caused by: org.exist.util.DatabaseConfigurationException: Exception while reading lucene index directory: Lock obtain timed out: NativeFSLock@/tmp/xx/webapp/WEB-INF/data/lucene/write.lock
	at org.exist.indexing.lucene.LuceneIndex.open(LuceneIndex.java:134)
	at org.exist.indexing.IndexManager.initIndex(IndexManager.java:146)
	at org.exist.indexing.IndexManager.prepare(IndexManager.java:119)
	... 19 more
Caused by: org.apache.lucene.store.LockObtainFailedException: Lock obtain timed out: NativeFSLock@/tmp/xx/webapp/WEB-INF/data/lucene/write.lock
	at org.apache.lucene.store.Lock.obtain(Lock.java:89)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:755)
	at org.exist.indexing.lucene.LuceneIndex.open(LuceneIndex.java:128)
	... 21 more

**Comment by duncdrum** [comment]
Can you give us a more details on the steps to reproduce? OS version, Java version etc. RC3 building seems to work fine for me.

**Comment by adamretter** [comment]
@zopyx This line looks very suspicious: `org.apache.lucene.store.LockObtainFailedException: Lock obtain timed out: NativeFSLock@/tmp/xx/webapp/WEB-INF/data/lucene/write.lock`

Are you trying to install over an existing install that is running? Do you have stuff already in `/tmp/xx` ? What is the output from the `jps` command?
