### ISSUE TITLE
Module import via remote URL is broken

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#2157]
### What is the problem

eXist used to support loading modules over the web, but doing so with 4.3.1 raises an error:

```xquery
xquery version "3.1";

import module namespace functx = "http://www.functx.com" 
    at "http://www.xqueryfunctions.com/xq/functx-1.0-doc-2007-01.xq";

"hello"
```

The error raised is:

> Invalid URI: xmldb URI scheme does not start with xmldb:: http://www.xqueryfunctions.com/xq/functx-1.0-doc-2007-01.xq

Under 4.0.0 (release), this query does not raise an error, but instead returns the expected result, `"hello"`.

### What did you expect

Loading modules via URI is discussed at https://exist-db.org/exist/apps/doc/xquery#module-system.

### Describe how to reproduce or add a test

See test query above. The stack trace is:

```text
2018-09-15 15:16:56,737 [qtp2000015086-35] ERROR (XQueryServlet.java [process]:552) - Invalid URI: xmldb URI scheme does not start with xmldb:: http://www.xqueryfunctions.com/xq/functx-1.0-doc-2007-01.xq 
java.lang.IllegalArgumentException: Invalid URI: xmldb URI scheme does not start with xmldb:: http://www.xqueryfunctions.com/xq/functx-1.0-doc-2007-01.xq
	at org.exist.xmldb.XmldbURI.create(XmldbURI.java:219) ~[exist.jar:4.3.1]
	at org.exist.xmldb.XmldbURI.append(XmldbURI.java:595) ~[exist.jar:4.3.1]
	at org.exist.source.SourceFactory.getSource(SourceFactory.java:98) ~[exist.jar:4.3.1]
	at org.exist.xquery.XQueryContext.importModule(XQueryContext.java:2846) ~[exist.jar:4.3.1]
	at org.exist.xquery.parser.XQueryTreeParser.importDecl(XQueryTreeParser.java:6312) ~[exist.jar:4.3.1]
	at org.exist.xquery.parser.XQueryTreeParser.prolog(XQueryTreeParser.java:5340) ~[exist.jar:4.3.1]
	at org.exist.xquery.parser.XQueryTreeParser.mainModule(XQueryTreeParser.java:4042) ~[exist.jar:4.3.1]
	at org.exist.xquery.parser.XQueryTreeParser.module(XQueryTreeParser.java:3987) ~[exist.jar:4.3.1]
	at org.exist.xquery.parser.XQueryTreeParser.xpath(XQueryTreeParser.java:3642) ~[exist.jar:4.3.1]
	at org.exist.xquery.XQuery.compile(XQuery.java:128) ~[exist.jar:4.3.1]
        ...
```

### Context information

- eXist-db version + Git Revision hash: eXist 4.3.1 release
- Java version: 10.0.2+13
- Operating system: macOS 10.13.6
- 32 or 64 bit: 64 bit
- How is eXist-db installed? DMG installer
- Any custom changes in e.g. conf.xml: none

**Comment by dizzzz** [comment]
is it a bug or a design change?

**Comment by joewiz** [comment]
I sure hope it wasn’t a design change, as it was made without incrementing major versions, and without discussion or announcement.

I should also add that the sample code above works in Saxon and BaseX.

I also depend on this feature in my forthcoming XQuery book, and would appreciate it if anyone could help resolve this soon.

**Comment by joewiz** [comment]
Looking at the stack trace, I think the problem is in `getSource` in `SourceFactory.java`, specifically https://github.com/eXist-db/exist/blob/develop/src/org/exist/source/SourceFactory.java#L76-L139. Instead of getting to lines 123-134 (where "any other URL" should be handled), the code thinks the URL is an xmldb URI and so tries to handle the URI up above in lines 90-100. I think the change was introduced by @adamretter in https://github.com/eXist-db/exist/commit/f07db94aad4e1685f30ccd10532df3e1899199a4#diff-ef7f3227bbd557c4b7b9605cc4a74521. Seeing as that was an attempt to fix https://github.com/eXist-db/exist/issues/1927, it's clear that we introduced an unintentional assumption that module imports without `xmldb:exist:` actually should be handled as xmldb URIs.

**Comment by joewiz** [comment]
Perhaps the solution is to reorder the logic for resolving resource URIs: first, see if there's an explicit scheme (http, file, xmldb), and only if there isn't one assume that the URI is an xmldb URI.

**Comment by joewiz** [comment]
Related: #1031

**Comment by dizzzz** [comment]
it look slike `contextPath` has in [line 83](https://github.com/eXist-db/exist/blob/be7cb57cbc410a3e29a32de46518f7584bcffb7a/src/org/exist/source/SourceFactory.java#L82)somedifferent content than expected....

**Comment by dizzzz** [comment]
Personally, I would like to be able to switch-off these remote dependencies; I think it will slow down the database, and potentially harmful code is loaded...

**Comment by joewiz** [comment]
@dizzzz Agreed that it has to do with something involving `contextPath`.

Also, this issue is possibly related to https://github.com/eXist-db/exist/issues/1853.

**Comment by joewiz** [comment]
@adamretter I just stumbled onto a similar odd issue in which (1) a query that imports (2) a module on the filesystem that imports (3) a module from a remote URL fails.  If this bothers you and strikes you as something that should be fixed, I could adapt this into a new issue, or am happy to let this one lie as an unlikely scenario... 

(1) query run in eXide:

```xquery
xquery version "3.1";

import module namespace funkx="funkx" at "file:/Users/joe/Downloads/funkx.xqm";

funkx:capitalize-first("funk")
```

(2) module on filesystem that imports functx remotely:

```xquery
xquery version "3.1";

module namespace funkx="funkx";

import module namespace functx = "http://www.functx.com" 
    at "http://www.xqueryfunctions.com/xq/functx-1.0-doc-2007-01.xq";

declare function funkx:capitalize-first($string) {
    funkx:capitalize-first($string)
};
```


Error:

> Cannot compile xquery: err:XQST0059 error found while loading module funkx: Error while loading module file:/Users/joe/Downloads/funkx.xqm: error found while loading module functx: Source for module 'http://www.functx.com' could not be read, module location hint URI 'http://www.xqueryfunctions.com/xq/functx-1.0-doc-2007-01.xq'.

**Comment by joewiz** [comment]
The relevant portion of exist.log:

```text
Caused by: java.io.FileNotFoundException: cannot read module source from file at http://www.xqueryfunctions.com/xq/functx-1.0-doc-2007-01.xq. 

	at org.exist.source.SourceFactory.getSource(SourceFactory.java:137) ~[exist.jar:4.5.0-SNAPSHOT]
	at org.exist.xquery.XQueryContext.importModule(XQueryContext.java:2277) ~[exist.jar:4.5.0-SNAPSHOT]
	at org.exist.xquery.parser.XQueryTreeParser.importDecl(XQueryTreeParser.java:6312) ~[exist.jar:4.5.0-SNAPSHOT]
        ...
```
