### ISSUE TITLE
random java.util.ConcurrentModificationException in 4.4.0 during xupdate via REST call

### ISSUE THREAD

**Issue by bkcsfi** [eXist-db/exist#2185]
### What is the problem
a java.util.ConcurrentModificationException exception is randomly raised while processing an xupdate statement submitted via REST POST, returns 5xx status code

This has happened 3 times in 3 weeks, perhaps 1 out of every 2000 xupdate calls.

### What did you expect
I expect the documents to be updated and get back a 200 response code

### Describe how to reproduce or add a test

send an HTTP POST to 
```
http://host:port/exist/servlet/db/orgs/il/customs/pending_shipments/QIL1505643/shiprequest.xml
```
with contents as shown (contents of Quote element have been redacted)

```
<?xml version="1.0"?>
<xupdate:modifications xmlns:xupdate="http://www.xmldb.org/xupdate" version="1.0">
  <xupdate:remove select="/shiprequest[@key='QIL1505643']/@commit_batch"/>
  <xupdate:remove select="/shiprequest[@key='QIL1505643']/quotes"/>
  <xupdate:append select="/shiprequest[@key='QIL1505643']">
    <xupdate:element name="quotes">
      <xupdate:attribute name="python.type">list</xupdate:attribute>
      <Quote version="1">
        <valid_quote python.type="bool">True</valid_quote>
      </Quote>
    </xupdate:element>
  </xupdate:append>
</xupdate:modifications>
```

### Context information

running official docker image 4.4.0

```
eXist Version: | 4.4.0
eXist Build: | 201809252010
Operating System: | Linux 4.4.0-133-generic amd64
Java Version: | 1.8.0_171
```

[exception.txt](https://github.com/eXist-db/exist/files/2439267/exception.txt)

**Comment by bkcsfi** [comment]
just happened again.. 

```
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList.forEach(ArrayList.java:1260) ~[?:1.8.0_171]
        at org.exist.xquery.XQueryContext$ContextUpdateListener.documentUpdated(XQueryContext.java:3033) ~[exist.jar:4.4.0]
        at org.exist.storage.NotificationService.notifyUpdate(NotificationService.java:80) ~[exist.jar:4.4.0]
        at org.exist.xupdate.Append.process(Append.java:89) ~[exist.jar:4.4.0]
        at org.exist.http.RESTServer.doPost(RESTServer.java:918) ~[exist-optional.jar:4.4.0]
```

**Comment by bkcsfi** [comment]
Hmm, frequency appears to be a lot higher than I first  reported

```
2018-09-26 11:57:58,643 [qtp964981922-5762] ERROR (EXistServlet.java [doPost]:478) - java.util.ConcurrentModificationException 
2018-09-26 13:35:51,717 [qtp964981922-6925] ERROR (EXistServlet.java [doPost]:478) - java.util.ConcurrentModificationException 
2018-09-27 07:27:05,208 [qtp964981922-13652] ERROR (EXistServlet.java [doPut]:169) - java.util.ConcurrentModificationException 
2018-09-27 07:55:59,560 [qtp964981922-13655] ERROR (EXistServlet.java [doPost]:478) - java.util.ConcurrentModificationException 
2018-09-27 10:07:02,915 [qtp964981922-15138] ERROR (EXistServlet.java [doPut]:169) - java.util.ConcurrentModificationException 
2018-09-27 14:14:58,227 [qtp964981922-17871] ERROR (EXistServlet.java [doPost]:478) - java.util.ConcurrentModificationException 
2018-09-27 14:30:12,796 [qtp964981922-17945] ERROR (EXistServlet.java [doPut]:169) - java.util.ConcurrentModificationException 
2018-09-27 14:56:44,333 [qtp964981922-18503] ERROR (EXistServlet.java [doPost]:478) - java.util.ConcurrentModificationException 
2018-09-27 15:17:19,182 [qtp964981922-18727] ERROR (EXistServlet.java [doPost]:478) - java.util.ConcurrentModificationException 
2018-09-27 16:05:53,549 [qtp964981922-18856] ERROR (EXistServlet.java [doPost]:478) - java.util.ConcurrentModificationException 
2018-09-27 16:17:45,714 [qtp964981922-18856] ERROR (EXistServlet.java [doPost]:478) - java.util.ConcurrentModificationException 
2018-09-28 10:16:32,169 [qtp964981922-25640] ERROR (EXistServlet.java [doPost]:478) - java.util.ConcurrentModificationException 
2018-09-28 11:48:38,741 [qtp964981922-26506] ERROR (EXistServlet.java [doPut]:169) - java.util.ConcurrentModificationException 
2018-09-28 14:53:02,791 [qtp964981922-28754] ERROR (EXistServlet.java [doPost]:478) - java.util.ConcurrentModificationException 
2018-10-01 07:56:37,984 [qtp964981922-50573] ERROR (EXistServlet.java [doPost]:478) - java.util.ConcurrentModificationException 
2018-10-01 10:17:16,787 [qtp964981922-52212] ERROR (EXistServlet.java [doPut]:169) - java.util.ConcurrentModificationException 
2018-10-01 11:30:12,596 [qtp964981922-52676] ERROR (EXistServlet.java [doPost]:478) - java.util.ConcurrentModificationException 
2018-10-01 12:17:47,254 [qtp964981922-53768] ERROR (EXistServlet.java [doPost]:478) - java.util.ConcurrentModificationException 
2018-10-01 12:27:19,003 [qtp964981922-53985] ERROR (EXistServlet.java [doPut]:169) - java.util.ConcurrentModificationException 
2018-10-01 13:23:11,151 [qtp964981922-54472] ERROR (EXistServlet.java [doPost]:478) - java.util.ConcurrentModificationException 
2018-10-01 14:15:02,772 [qtp964981922-55227] ERROR (EXistServlet.java [doPost]:478) - java.util.ConcurrentModificationException 
2018-10-01 14:18:09,511 [qtp964981922-55287] ERROR (EXistServlet.java [doPut]:169) - java.util.ConcurrentModificationException 
2018-10-01 16:35:01,624 [qtp964981922-56476] ERROR (EXistServlet.java [doPost]:478) - java.util.ConcurrentModificationException 
2018-10-01 17:14:19,162 [qtp964981922-57283] ERROR (EXistServlet.java [doPost]:478) - java.util.ConcurrentModificationException 
2018-10-02 09:57:03,170 [qtp964981922-63010] ERROR (EXistServlet.java [doPost]:478) - java.util.ConcurrentModificationException 
2018-10-02 12:59:42,610 [qtp964981922-65013] ERROR (EXistServlet.java [doPost]:478) - java.util.ConcurrentModificationException 
2018-10-02 13:40:58,604 [qtp964981922-65485] ERROR (EXistServlet.java [doPost]:478) - java.util.ConcurrentModificationException 
2018-10-02 15:03:20,523 [qtp964981922-66556] ERROR (EXistServlet.java [doPost]:478) - java.util.ConcurrentModificationException 
```

**Comment by bkcsfi** [comment]
I see in the above list doPut operations also failing.  Those are not xquery operations, they are just putting an xml document to the server.

I've attached a traceback

[put-exception.txt](https://github.com/eXist-db/exist/files/2442377/put-exception.txt)

We've had 3 doPost exceptions this morning. I was able to wrap a retry around our code for the xupdate/doPost that's failing. 

However there are quite a lot of distinct PUT operations in the code I now need to wrap w/ retry code, though doPUT failures seem to be fewer (8 out of 33)

**Comment by bkcsfi** [comment]
I have implemented retry code for PUT operations as a workaround.

**Comment by joewiz** [comment]
Any chance you could test your application with the 5.0.0 release candidate? A big focus of the work in 5.x was addressing concurrency and locking.

**Comment by bkcsfi** [comment]
I might be able to do some limited testing. Unfortunately I don't have any  automated testing that can simulate the regular load and random operations experienced in production.

**Comment by adamretter** [comment]
Okay so it looks like there is insufficient synchronization around the state held by `XQueryContext$ContextUpdateListener`.
