### ISSUE TITLE
array:get IndexOutOfBoundsException

### ISSUE THREAD

**Issue by median1st** [eXist-db/exist#2317]
While accessing an out-of-bound index of array in XQuery using the parentheses notation correctly throws XQuery error, using array:get() function for the same purpose ends with an IndexOutOfBoundsException thrown within the servlet.

**Steps to reproduce:**

1.  Open new XQuery 3.1 window
2. evaluate the following expression:
```
  let $a := [ 1, 2, 3 ]
  return $a(10)
```
This correctly ends with **err:FOAY0001 Position 10 does not exist in this array.**  being reported.
3.   Change the second line of the expression to
 ` return array:get($a, 10)`
4. Evaluate the expression again. This time a successful query returing 0 items is repoted, while the log of the database contains an exception dump with this cause:
```
2018-11-30 13:08:35,603 [qtp1502843539-99] ERROR (XQueryServlet.java [process]:552) - null 
java.lang.IndexOutOfBoundsException: null
        at com.github.krukow.clj_lang.PersistentVector.arrayFor(PersistentVector.java:126) ~[clj-ds-0.0.4.jar:?]
        at com.github.krukow.clj_lang.PersistentVector.nth(PersistentVector.java:130) ~[clj-ds-0.0.4.jar:?]
        at org.exist.xquery.functions.array.ArrayType.get(ArrayType.java:67) ~[exist.jar:4.4.0]
        at org.exist.xquery.functions.array.ArrayFunction.eval(ArrayFunction.java:252) ~[exist.jar:4.4.0]
        at org.exist.xquery.BasicFunction.eval(BasicFunction.java:74) ~[exist.jar:4.4.0]
        at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:41) ~[exist.jar:4.4.0]
        at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58) ~[exist.jar:4.4.0]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:111) ~[exist.jar:4.4.0]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:111) ~[exist.jar:4.4.0]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist.jar:4.4.0]
        at org.exist.xquery.PathExpr.eval(PathExpr.java:276) ~[exist.jar:4.4.0]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist.jar:4.4.0]
        at org.exist.xquery.XQuery.execute(XQuery.java:261) ~[exist.jar:4.4.0]
        at org.exist.xquery.XQuery.execute(XQuery.java:185) ~[exist.jar:4.4.0]
        at org.exist.http.servlets.XQueryServlet.process(XQueryServlet.java:488) [exist-optional.jar:4.4.0]
        at org.exist.http.servlets.XQueryServlet.doPost(XQueryServlet.java:192) [exist-optional.jar:4.4.0]
```

The second query should behave the same way as the first one - reporting an XQuery error.

### Context information
- eXist-db version **exist-4.4.0 stable**
- Java version **openjdk version "1.8.0_131"**
- Operating system **Linux Centos 7**
- **64 bit**
- Standard installation by eXist-setup.jar
- One custom module for Levenshtein function, two custom analyzers for Lucene

**Comment by duncdrum** [comment]
confirmed on `4.5.0` via docker
