### ISSUE TITLE
Error handling in tomcat not working

### ISSUE THREAD

**Issue by andbue** [eXist-db/exist#2354]
### What is the problem
exist-5.0.0-RC5.war deployed in a tomcat8 server doesn't return 404 pages when an \<error-handler\> containing a \<forward\> is present in controller.xql, line 86-87. Instead, a request to e.g. /exist/apps/dashboard/someurl.html is answered with 500 - Internal Server Error: Cannot forward after response has been committed.

### What did you expect
Redirect to  error-page.html or Http Error 404.

### Context information
Please always add the following information
- eXist-db 5.0.0-RC5
- Linux
- 64 bit
- WAR file, tomcat8

**Comment by dizzzz** [comment]
Is there an error logged in `catalina.out` or `exist.log`

**Comment by andbue** [comment]
Nothing in catalina.out, but in /var/log/tomcat8/localhost.2018-12-18.log:
```
18-Dec-2018 16:25:33.874 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [XQueryURLRewrite] in context with path [/exist] threw exception [An error occurred while processing request to /exist/apps/dashboard/someurl.html: Cannot forward after response has been committed] with root cause
 java.lang.IllegalStateException: Cannot forward after response has been committed
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:322)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:311)
        at org.exist.http.urlrewrite.Forward.doRewrite(Forward.java:51)
        at org.exist.http.urlrewrite.XQueryURLRewrite.doRewrite(XQueryURLRewrite.java:525)
        at org.exist.http.urlrewrite.XQueryURLRewrite.applyViews(XQueryURLRewrite.java:410)
        at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:362)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1458)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by dizzzz** [comment]
committed response...... ouch....

**Comment by dizzzz** [comment]
which tomcat version are you using ? Maybe this specific version has an issue?

**Comment by andbue** [comment]
It's the standard tomcat8 on debian. I'm trying to figure out how to find the version of this thing...

**Comment by andbue** [comment]
Server version: Apache Tomcat/8.5.14 (Debian)

**Comment by andbue** [comment]
Same with tomcat8 8.0.53-1.

**Comment by andbue** [comment]
The same error occurs with exist-4.5.0 stable version.

**Comment by dizzzz** [comment]
ok thnx....

**Comment by duncdrum** [comment]
we no longer produce war files for 5.0.0 good to close?
