### ISSUE TITLE
self:: axis inside predicate throws XPST0005

### ISSUE THREAD

**Issue by rvdb** [eXist-db/exist#2445]
### What is the problem
When used inside a predicate, the `self::` axis throws error XPST0005 in some cirumstances, even though nothing is wrong with the expression. This happens with the most recent eXist releases 4.5.0 and 5.0.0-RC5 (and earlier releases).

### What did you expect
I would expect the query to run without errors (confirmed with Saxon).

### Describe how to reproduce or add a test
Behaviour is the same for in-memory and stored nodes, so these stand-alone test cases will illustrate the problem.

#### [1]
    let $node := 
      <test>
        <el>test <el1>test</el1> test <el2>test</el2></el>
      </test>
    return 
        $node/el[self::el1]

This should return an empty result set. Instead following error is being thrown: 

    org.xmldb.api.base.XMLDBException: exerr:ERROR err:XPST0005 Self::{}el1 called on set of nodes which do not contain any nodes of this name. [at line 5, column 23, source: let $node := 
      <test>
        <el>test <el1>test</el1> test <el2>test</el2></el>
      </test>
    return $node/el[self::el1]] [at line 5, column 23]
      at org.exist.xmldb.RemoteXPathQueryService.compile(RemoteXPathQueryService.java:130)
      at org.exist.client.QueryDialog$QueryThread.run(QueryDialog.java:558)
    Caused by: org.exist.xquery.XPathException: exerr:ERROR err:XPST0005 Self::{}el1 called on set of nodes which do not contain any nodes of this name. [at line 5, column 23, source: let $node := 
      <test>
        <el>test <el1>test</el1> test <el2>test</el2></el>
      </test>
    return $node/el[self::el1]] [at line 5, column 23]
      at org.exist.xmldb.RemoteXPathQueryService.throwXPathException(RemoteXPathQueryService.java:179)
      at org.exist.xmldb.RemoteXPathQueryService.compileAndCheck(RemoteXPathQueryService.java:155)
      at org.exist.xmldb.RemoteXPathQueryService.compile(RemoteXPathQueryService.java:128)
      ... 1 more
    Caused by: org.exist.xquery.XPathException: exerr:ERROR err:XPST0005 Self::{}el1 called on set of nodes which do not contain any nodes of this name. [at line 5, column 23, source: let $node := 
      <test>
        <el>test <el1>test</el1> test <el2>test</el2></el>
      </test>
    return $node/el[self::el1]] [at line 5, column 23]
      at org.exist.xmldb.RemoteXPathQueryService.throwXPathException(RemoteXPathQueryService.java:179)
      at org.exist.xmldb.RemoteXPathQueryService.compileAndCheck(RemoteXPathQueryService.java:155)
      at org.exist.xmldb.RemoteXPathQueryService.compile(RemoteXPathQueryService.java:128)
      at org.exist.client.QueryDialog$QueryThread.run(QueryDialog.java:558)

Of course, this example is contrived, in order to present a simple test case. It seems, however, that the empty node set returned by the test condition in the predicate is significant. If the `self::` axis does select a node (e.g. `$node/el[self::el]`), the query does run without error.

#### [2]
I've found another failing variant XQuery where the `self::` axis occurs inside a predicate and doesn't select a node. Here, parentheses seem to be triggering the same error:

    let $node := 
      <test>
        <el>test <el1>test</el1> test <el2>test</el2></el>
      </test>
    return $node/el[descendant::*/(self::el1)]

This should return the <el> node:

    <el>test <el1>test</el1> test <el2>test</el2></el>

Instead, above error XPST0005 is being thrown. 

Here, the parentheses seem to be crucial. Compare with the same predicate without parentheses:

    let $node := 
      <test>
        <el>test <el1>test</el1> test <el2>test</el2></el>
      </test>
    return $node/el[descendant::*/self::el1]

...which does return the correct result:

    <el>test <el1>test</el1> test <el2>test</el2></el>

I've found a reference to this error message in the ML archives (https://sourceforge.net/p/exist/mailman/message/32496312/), and a bug fix in Github. So there's a chance this issue is related to https://github.com/eXist-db/exist/pull/249.

### Context information
Please always add the following information
- eXist-db version + Git Revision hash:
    - eXist-4.5.0 / e29b409
    - eXist-5.0.0-RC5 / 4414b1a
- Java version: oracle 1.8.0_191
- Operating system: Windows 10
- 32 or 64 bit: 64 bit
- How is eXist-db installed? JAR installer
- Any custom changes in e.g. conf.xml: none

**Comment by duncdrum** [comment]
@wolfgangmm as the author of #249 could you chime in here. I can reproduce these errors, but i am not sure what the optimal fix is here, should [1] really return an empty sequence?

**Comment by line-o** [comment]
Retested with e2bf08c00eb20e7590ab64ebd12a4f433c1838ca
Putting `./` in front of the SELF-axis XPath-(sub-)expressions mitigates the problem.
Maybe, this can also help in tracking down the root-cause.

```xquery
let $node := 
  <test>
    <el>test <el1>test</el1> test <el2>test</el2></el>
  </test>

return (
    $node/el[./self::el1],
    $node/el[./descendant::*/self::el1],
    $node/el[descendant::*/self::el1],
    $node/el[descendant::*/(./self::el1)]
)
```

**Comment by line-o** [comment]
That also confirms that the optimisation added in #249 is the culprit. While `[self::el1]` is considered a simple query `[./self::el1]` is not.

**Comment by line-o** [comment]
@wolfgang @adamretter Maybe it would be enough to return an empty sequence instead of throwing an error in these two cases?

https://github.com/eXist-db/exist/blob/34767fa9b5f221504d4c02a107b4e973fdd4bd0f/exist-core/src/main/java/org/exist/xquery/LocationStep.java#L273-L281

**Comment by joewiz** [comment]
A simplified test:

```xquery
<foo><bar/></foo>/bar[self::baz]
```

Returns a static error:

> Self::{}baz called on set of nodes which do not contain any nodes of this name.

The same query returns the empty sequence in BaseX and Saxon. Only eXist raises this error.

**Comment by line-o** [comment]
I have a fix in the making.

**Comment by line-o** [comment]
The question whether this is a bug or the expected behaviour is a general decision the existdb community has to answer: Do we provide the StaticTyping feature or not.

Even if we decide to adhere to provide the StaticTyping feature it is:
1. not fully implemented
2. needs to be clearly communicated to users

**Comment by joewiz** [comment]
As discussed during the Community Call, eXist doesn't implement the Static Typing optional feature (https://www.w3.org/TR/xquery-31/#id-static-typing-feature). Next actions: 
- [ ] Update documentation to note this: https://exist-db.org/exist/apps/doc/xquery#unsupported-features
- [ ] Update exist-xqts-runner to set flag to disable static typing tracing: https://github.com/eXist-db/exist-xqts-runner/blob/master/src/main/scala/org/exist/xqts/runner/XQTSRunner.scala#L84-L97
