### ISSUE TITLE
EXPath Packages fail to install due to improper checking of semver-* dependencies

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#2449]
### What is the problem

eXist is treating the `semver-max` dependency restriction in the EXPath Package descriptor as `<` (exclusive) instead of `<=` (inclusive). As a result, EXPath Packages with a dependency expressed via the `semver-max` restriction fail to install on systems that meet the stated dependency requirements.

For example, given a package with a dependency on eXist of `semver-max="4.5.0"`:

```xml
<dependency processor="http://exist-db.org" semver-min="4.1.0" semver-max="4.5.0"/>
```

... eXist 4.5.0 refuses to install the package, with the following error (see detailed exist.log output below):

> Package requires eXist-db version > 4.1.0 < 4.5.0. Installed version is 4.5.0.

### What did you expect

The `semver-max` dependency restriction is defined in the EXPath Package spec's section on versioning (http://expath.org/spec/pkg#versioning) as follows:

> If semver-max is used, the secondary package version must be either compatible with that SemVer template, or lower than it.

In other words, semver-max is supposed to mean `<=` (inclusive), not `<` (exclusive), but eXist is treating semver-max as `<` (exclusive) instead of `<=` (inclusive).

I suspect the issue is in our implementation the EXPath Package spec - specifically: https://github.com/eXist-db/expath-pkg-java/blob/master/pkg-java/src/org/expath/pkg/repo/deps/Semver.java.  

If we could confirm this, we could move this issue to that repo.  But for now, the stack trace appears to only reference classes in the eXist core.

From exist.log:

```text
2019-01-31 08:11:12,854 [qtp1611266232-53] ERROR (Deploy.java [installAndDeployFromDb]:216) - Package requires eXist-db version > 4.1.0 < 4.5.0. Installed version is 4.5.0 
org.expath.pkg.repo.PackageException: Package requires eXist-db version > 4.1.0 < 4.5.0. Installed version is 4.5.0
	at org.exist.repo.Deployment.checkProcessorVersion(Deployment.java:294) ~[exist.jar:4.5.0]
	at org.exist.repo.Deployment.installAndDeploy(Deployment.java:218) ~[exist.jar:4.5.0]
	at org.exist.repo.Deployment.installAndDeploy(Deployment.java:164) ~[exist.jar:4.5.0]
	at org.exist.xquery.modules.expathrepo.Deploy.installAndDeployFromDb(Deploy.java:214) [exist-modules.jar:4.5.0]
	at org.exist.xquery.modules.expathrepo.Deploy.eval(Deploy.java:170) [exist-modules.jar:4.5.0]
	at org.exist.xquery.BasicFunction.eval(BasicFunction.java:74) [exist.jar:4.5.0]
	at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:41) [exist.jar:4.5.0]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:4.5.0]
	at org.exist.xquery.PathExpr.eval(PathExpr.java:276) [exist.jar:4.5.0]
	at org.exist.xquery.SequenceConstructor.eval(SequenceConstructor.java:84) [exist.jar:4.5.0]
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58) [exist.jar:4.5.0]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:4.5.0]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:4.5.0]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:4.5.0]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:4.5.0]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:4.5.0]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:4.5.0]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:4.5.0]
	at org.exist.xquery.PathExpr.eval(PathExpr.java:276) [exist.jar:4.5.0]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:4.5.0]
	at org.exist.xquery.XQuery.execute(XQuery.java:261) [exist.jar:4.5.0]
```

### Describe how to reproduce or add a test

Modify `expath-pkg.xml` in any package to have a dependency with `semver-max` on the version of eXist you are currently running, build the package, and try to deploy it to eXist.

### Context information

- eXist-db version + Git Revision hash: eXist 4.5.0 release
- Java version: OpenJDK 11.0.2+9
- Operating system: macOS 10.13.6
- 32 or 64 bit: 64 bit
- How is eXist-db installed? DMG installer
- Any custom changes in e.g. conf.xml: none

**Comment by adamretter** [comment]
I rewrote this stuff - https://github.com/eXist-db/expath-pkg-java/commit/5363301e887eea76318902ab370169f4a8aa2d71

**Comment by joewiz** [comment]
@adamretter Thanks for pointing me to the develop branch of eXist-db/expath-pkg-java and your work there. Your changes all look good to me. Upon further study, though, I believe the problem described here occurs in a portion of the code that you hadn't touched.

Since the PackageException here is thrown by checkProcessorVersion in Deployment.java line 294, I believe the actual processor version check that is failing is this one: https://github.com/eXist-db/exist/blob/develop/src/org/exist/repo/Deployment.java#L289. Tracing that back to the relevant code used in eXist, I think we find it here, where we check the processor's version against *both* a min and a max: https://github.com/eXist-db/expath-pkg-java/blob/develop/pkg-java/src/main/java/org/expath/pkg/repo/deps/DepSemverMinMax.java#L30-L35. 

In the case of this issue, the values of the variables are:

- `myMin` = 4.1.0
- `myMax` = 4.5.0
- `rhs` = 4.5.0

The three checks must all return true for the dependency check to pass:

- `myMin.matchesMin(rhs)` = true
- `myMax.matchesMax(rhs)` = true
- `!myMax.matches(rhs)` = false

Unless I'm reading this wrong, isn't this 3rd check totally extraneous and the cause of the checkProcessorVersion throwing a PackageException here?

**Comment by joewiz** [comment]
I notice that https://github.com/eXist-db/expath-pkg-java/blob/develop/pkg-java/src/test/java/org/expath/pkg/repo/deps/SemverTest.java lacks any tests for the relevant code I linked to in my last comment. I wish I knew how to write such a test, but I hope that the info here contains the important elements of a test to demonstrate the flaw in the current implementation.

**Comment by plutonik-a** [comment]
I agree with @joewiz: checking the [third condition](https://github.com/eXist-db/expath-pkg-java/blob/develop/pkg-java/src/main/java/org/expath/pkg/repo/deps/DepSemverMinMax.java#L34) in 
```myMin.matchesMin(rhs) && myMax.matchesMax(rhs) && !myMax.matches(rhs)```
doesn't seem to be right to me. 
Because of the negation of `myMax.matches()` it assumes that there **is always** a difference between `myMax` and the current value, if I understand the code correctly. 

```
/**
 * Does {@code rhs} (a SemVer version) match this SemVer template?
 */
public boolean matches(final Semver rhs)
    throws PackageException {
    return compareTo(rhs) == 0;
}
```
