### ISSUE TITLE
the configuration connection existdb 4.x(tested on 4.5.0) dont work

### ISSUE THREAD

**Issue by rpompaideasoft** [eXist-db/exist#2526]
### What is the problem
 The configuration connection existdb 4.x(tested on 4.5.0) dont work on Oxigen XML Developer
Error:
`Check datasource configuration. Could not instantiate: ro.sync.db.nxd.exist.ExistSession due to: java.lang.NoClassDefFoundError: Could not initialize class org.exist.xmldb.DatabaseImpl`

### What did you expect
Cnnect with existdb

### Describe how to reproduce or add a test
https://www.oxygenxml.com/doc/versions/20.1/ug-developer/topics/configure-exist-datasource.html#configure-exist-datasource__step_2_configure_an_exist_connection

### Context information
Please always add the following information
- eXist-db 4.5
- jdk1.8.0_192
- Windows 10
- 64 bit

**Comment by lguariento** [comment]
Hello, is it a xmlrpc connection? Have you already deleted the old one, closed oXygen, reopened it, and created a new xmlrpc connection so that oXygen loads the new .jar libraries form eXist-db?

**Comment by rpompaideasoft** [comment]
> 
> 
> Hello, is it a xmlrpc connection? Have you already deleted the old one, closed oXygen, reopened it, and created a new xmlrpc connection so that oXygen loads the new .jar libraries form eXist-db?

Yes, is xmlrpc. I have two configuration connections. One for existdb 2.2 and other existdb 4.5. Is that e problem?

**Comment by lguariento** [comment]
Have you already recreated the 4.5 one? If yes, and still have issues, it might be worth it double-checking with support@oxygenxml.com too.

**Comment by rpompaideasoft** [comment]
Ok. thanks

**Comment by joewiz** [comment]
I agree with @lguariento. With XML-RPC-based connections to eXist in oXygen, best to create a new data source whenever you upgrade to a new version of eXist. Keep your data sources aligned with the exact version of eXist. (If all you're doing is editing database contents, then you can avoid this XML-RPC headache and switch your data source to WebDAV. But you may need some XML-RPC-specific feature, like xquery validation/execution.)

**Comment by rpompaideasoft** [comment]
In fact I tested with the exist 3.6.1, 4.5.0 and 4.6.0 drivers. None connected to the database.

**Comment by joewiz** [comment]
Please provide the exact steps you used to test each scenario.

**Comment by rpompaideasoft** [comment]
I follow this instructions:
https://www.oxygenxml.com/doc/versions/20.1/ug-developer/topics/configure-exist-datasource.html#configure-exist-datasource__step_2_configure_an_exist_connection

with:
oxygen: 21.0 build 2019022207
Windows 10 64 bit
eXist-db: 4.5
java: jdk1.8.0_192

**Comment by joewiz** [comment]
What values did you provide for the Connection Details in step 5? (Obviously you may leave out password and domain name.) 

At what point in the steps do you encounter the error referenced above?

**Comment by rpompaideasoft** [comment]
Right now change the data source from existdb 2.2 to 4.5.0 and the error is is:
Check datasource configuration. Could not instantiate: ro.sync.db.nxd.exist.ExistSession due to: java.lang.NoClassDefFoundError: org/xmldb/api/base/XMLDBException
java.io.IOException: Could not instantiate: ro.sync.db.nxd.exist.ExistSession due to: java.lang.NoClassDefFoundError: org/xmldb/api/base/XMLDBException
	at ro.sync.db.nxd.o.l(Unknown Source)
	at ro.sync.db.b.i.x(Unknown Source)
	at ro.sync.db.b.i.getChildren(Unknown Source)
	at ro.sync.db.h$_d.b(Unknown Source)
	at ro.sync.db.h$_d.treeWillExpand(Unknown Source)
	at javax.swing.JTree.fireTreeWillExpand(Unknown Source)
	at javax.swing.JTree.setExpandedState(Unknown Source)
	at ro.sync.ui.application.rb.setExpandedState(Unknown Source)
	at javax.swing.JTree.expandPath(Unknown Source)
	at javax.swing.plaf.basic.BasicTreeUI.toggleExpandState(Unknown Source)
	at javax.swing.plaf.basic.BasicTreeUI.handleExpandControlClick(Unknown Source)
	at javax.swing.plaf.basic.BasicTreeUI.checkForClickInExpandControl(Unknown Source)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(Unknown Source)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressedDND(Unknown Source)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(Unknown Source)
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at ro.sync.ui.application.rb.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.io.IOException: Could not instantiate: ro.sync.db.nxd.exist.ExistSession due to: java.lang.NoClassDefFoundError: org/xmldb/api/base/XMLDBException
	at ro.sync.db.nxd.o.e(Unknown Source)
	at ro.sync.db.nxd.o.c(Unknown Source)
	... 49 more
Caused by: java.lang.NoClassDefFoundError: org/xmldb/api/base/XMLDBException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)

**Comment by lguariento** [comment]
Hello, do you mean that you have two data sources, one 2.2 and one 4.5, in the same instance of oXygen? If yes, what happens if you open oXygen and click on only one of them without touching the other? Can't you open them at all, or is the issue only happening when want to open them both?

**Comment by rpompaideasoft** [comment]
Hello
Q: do you mean that you have two data sources, one 2.2 and one 4.5, in the same instance of oXygen?
A: Yes
Q: what happens if you open oXygen and click on only one of them without touching the other?
A: With DS 2.2 work fine. With DS 4.5 throw the error above.
Q: Can't you open them at all, or is the issue only happening when you want to open them both?
A: Always try with one of then.

**Comment by lguariento** [comment]
So, if you open oXygen and select the 4.5 first thing it throws the error straight-away, yes? Have you already deleted it, closed oXygen, opened oXygen, and created it from scratch?

**Comment by lguariento** [comment]
This could be linked to this issue: https://github.com/eXist-db/exist/issues/2311 . It was fixed in 4.6. 4.6.1 should be out soon: can you upgrade your eXist-db installation and then delete/create the oXygen connection? That should solve your problem.

**Comment by rpompaideasoft** [comment]
where find 4.5.1?

**Comment by rpompaideasoft** [comment]
Where find 4.5.1? don't see on website

**Comment by lguariento** [comment]
Sorry, 4.5.1 never happened, it went directly to 4.6. Can you upgrade to 4.6?

**Comment by rpompaideasoft** [comment]
4.6.1 is not available yet...

**Comment by lguariento** [comment]
I know; 4.6.0 is :)

**Comment by dizzzz** [comment]
sorry for stepping in late: `java.lang.NoClassDefFoundError: org/xmldb/api/base/XMLDBException` was fixed with https://github.com/eXist-db/exist/pull/2411 ; it is part of 4.6.1 but please note that there was another issue with JNLP/webstart/"the mechanism oxygen uses to download libraries" in v4.6.0 ;

v4.6.1 is hot and fix and released tonight!
