### ISSUE TITLE
eXist-db dashboard showing error: Invalid qname text:groups

### ISSUE THREAD

**Issue by shidmeisiew** [eXist-db/exist#2597]
Hi,

I'm trying to access the dashboard but was presented with errors like such:
How can I see the Dashboard again?
Please advise.

javax.servlet.ServletException: An error occurred while processing request to /exist/apps/dashboard/index.html: err:XPST0081 error found while loading module restxq: Error while loading module modules/restxq.xql: Invalid qname text:groups
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:381)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at de.betterform.agent.web.filter.XFormsFilter.doFilter(XFormsFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1629)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:521)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.exist.xquery.XPathException: err:XPST0081 error found while loading module restxq: Error while loading module modules/restxq.xql: Invalid qname text:groups
	at org.exist.xquery.FunctionFactory.createFunction(FunctionFactory.java:49)
	at org.exist.xquery.parser.XQueryTreeParser.functionCall(XQueryTreeParser.java:10429)
	at org.exist.xquery.parser.XQueryTreeParser.primaryExpr(XQueryTreeParser.java:7348)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:3561)
	at org.exist.xquery.parser.XQueryTreeParser.functionCall(XQueryTreeParser.java:10408)
	at org.exist.xquery.parser.XQueryTreeParser.primaryExpr(XQueryTreeParser.java:7348)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:3561)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:1879)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:423)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:2620)
	at org.exist.xquery.parser.XQueryTreeParser.functionDecl(XQueryTreeParser.java:5773)
	at org.exist.xquery.parser.XQueryTreeParser.prolog(XQueryTreeParser.java:4905)
	at org.exist.xquery.parser.XQueryTreeParser.libraryModule(XQueryTreeParser.java:4028)
	at org.exist.xquery.parser.XQueryTreeParser.module(XQueryTreeParser.java:3860)
	at org.exist.xquery.parser.XQueryTreeParser.xpath(XQueryTreeParser.java:3642)
	at org.exist.xquery.XQueryContext.compileModule(XQueryContext.java:2900)
	at org.exist.xquery.XQueryContext.compileOrBorrowModule(XQueryContext.java:2832)
	at org.exist.xquery.XQueryContext.importModule(XQueryContext.java:2743)
	at org.exist.xquery.parser.XQueryTreeParser.importDecl(XQueryTreeParser.java:5884)
	at org.exist.xquery.parser.XQueryTreeParser.prolog(XQueryTreeParser.java:4912)
	at org.exist.xquery.parser.XQueryTreeParser.mainModule(XQueryTreeParser.java:4040)
	at org.exist.xquery.parser.XQueryTreeParser.module(XQueryTreeParser.java:3985)
	at org.exist.xquery.parser.XQueryTreeParser.xpath(XQueryTreeParser.java:3642)
	at org.exist.xquery.XQuery.compile(XQuery.java:128)
	at org.exist.xquery.XQuery.compile(XQuery.java:79)
	at org.exist.xquery.XQuery.compile(XQuery.java:71)
	at org.exist.http.urlrewrite.XQueryURLRewrite.runQuery(XQueryURLRewrite.java:687)
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:256)
	... 36 more

**Comment by duncdrum** [comment]
Could you please fill out the template, what version of exist, OS, install methode, etc.

**Comment by dizzzz** [comment]
yeah we need this info. I think I remember that this `text:groups()` has been removed..... or later added :-)

**Comment by shidmeisiew** [comment]
Hi Duncan and Dannes,

Thank you very much for your reply.  This is the eXist-db info:

#eXist build info
project.version=3.5.0
project.built=201709271535
scm.branch=refs/tags/eXist-3.5.0
scm.revision=12aea86

I’m installing it using the Headless Installation and running it as a service using yajsw.

Your advice is appreciated.

Thanks.

With best regards,
Mei


On 22 Mar 2019, at 7:31 PM, Dannes Wessels <notifications@github.com<mailto:notifications@github.com>> wrote:


yeah we need this info. I think I remember that this text:groups() has been removed..... or later added :-)
