### ISSUE TITLE
Not able to remove/upload the document on exist-db 

### ISSUE THREAD

**Issue by sbhusala** [eXist-db/exist#2634]
Please fill in the following sections:

### What is the problem
Not able to remove/upload the document on exist-db :

2019-04-11 12:31:47,866 [P1-7] ERROR (XmlRpcErrorLogger.java [log]:36) - Failed to invoke method remove in class org.exist.xmlrpc.RpcConnection: java.lang.NullPointerException
org.apache.xmlrpc.common.XmlRpcInvocationException: Failed to invoke method remove in class org.exist.xmlrpc.RpcConnection: java.lang.NullPointerException
        at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:129)
        at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.execute(ReflectiveXmlRpcHandler.java:106)
        at org.apache.xmlrpc.server.XmlRpcServerWorker.execute(XmlRpcServerWorker.java:46)
        at org.apache.xmlrpc.server.XmlRpcServer.execute(XmlRpcServer.java:86)
        at org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:200)
        at org.apache.xmlrpc.webserver.XmlRpcServletServer.execute(XmlRpcServletServer.java:112)
        at org.apache.xmlrpc.webserver.XmlRpcServlet.doPost(XmlRpcServlet.java:196)
        at org.exist.xmlrpc.RpcServlet.doPost(RpcServlet.java:57)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:763)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:856)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
        at org.mortbay.jetty.servlet.WebApplicationHandler.dispatch(WebApplicationHandler.java:473)
        at org.mortbay.jetty.servlet.Dispatcher.dispatch(Dispatcher.java:263)
        at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:171)
        at org.exist.http.urlrewrite.Forward.doRewrite(Forward.java:47)
        at org.exist.http.urlrewrite.XQueryURLRewrite.doFilter(XQueryURLRewrite.java:212)
        at org.mortbay.jetty.servlet.WebApplicationHandler$CachedChain.doFilter(WebApplicationHandler.java:821)
        at org.mortbay.jetty.servlet.WebApplicationHandler.dispatch(WebApplicationHandler.java:471)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:568)
        at org.mortbay.http.HttpContext.handle(HttpContext.java:1530)
        at org.mortbay.jetty.servlet.WebApplicationContext.handle(WebApplicationContext.java:633)
        at org.mortbay.http.HttpContext.handle(HttpContext.java:1482)
        at org.mortbay.http.HttpServer.service(HttpServer.java:909)

> Describe exactly what you see (e.g. an output of an XQuery) 

### What did you expect
Kindly provide the suggestions to remove/upload the document which causing the issues while accessing from application.

### Describe how to reproduce or add a test
Login exist database and select the file. it may not possible you to test this .

### Context information
Please always add the following information
- eXist-db version 
Version: 1.4.3
SVN Revision: 17131
Build: 20120913
- Java version 
OpenJDK Runtime Environment (IcedTea6 1.13.13) (rhel-1.13.13.1.el6_8-x86_64)
OpenJDK 64-Bit Server VM (build 23.41-b41, mixed mode)

- Operating system  Linux
- 32 or 64 bit
- How is eXist-db installed -JAR installer
<img width="449" alt="issue" src="https://user-images.githubusercontent.com/46970364/55953937-b3d05680-5c5d-11e9-9535-629ba6986fc2.png">

**Comment by joewiz** [comment]
This is quite an old version of eXist. Are you trying to work with an old installation that cannot be upgraded? (The current stable version is 4.6.1; http://exist-db.org.) If working with 1.4.3 is critical, please provide a more detailed list of steps you take that we can also take with a fresh installation of eXist 1.4.3. Starting with which jar you install from https://sourceforge.net/projects/exist/files/Stable/1.4.3/ and leading all the way to the error. Thanks.

**Comment by dizzzz** [comment]
> OpenJDK Runtime Environment (IcedTea6 1.13.13) (rhel-1.13.13.1.el6_8-x86_64) 

As documented in the past, OpenJDK6 is very unsuitable to run eXist-db; this OpenJDK is incompatible and contains IMO many flaws. So either grab and Oracle JDK 6, but better is -when possible- to switch to the v4.6.1 as @joewiz suggests.

I (personal opinion) consider v1.4.x as old and deprecated. We invested 7 years of development in the product since then :-P
