### ISSUE TITLE
ArrayIndexOutOfBoundsException in DocumentImpl.hasIdAttribute

### ISSUE THREAD

**Issue by craigberry** [eXist-db/exist#2636]
### What is the problem
> Describe exactly what you see (e.g. an output of an XQuery) 

8

That's right, the number 8 is returned by the XQuery file eightball.xql in the attachment.  My guess would be that's an 8-byte offset from a null pointer or element 8 of a 7-element sequence or something like that.  The exist log shows this:

```
2019-04-12 21:01:34,129 [qtp1390430007-859] ERROR (XQueryServlet.java [process]:552) - 8
java.lang.ArrayIndexOutOfBoundsException: 8
	at org.exist.dom.memtree.DocumentImpl.hasIdAttribute(DocumentImpl.java:724) ~[exist.jar:4.7.0-SNAPSHOT]
	at org.exist.dom.memtree.DocumentImpl.selectById(DocumentImpl.java:691) ~[exist.jar:4.7.0-SNAPSHOT]
...
```

### What did you expect

The attached reproducer works fine in eXist 4.3.1, but fails in the current develop and develop-4.x.x branches, e.g., 

```
$ git describe
eXist-4.6.1-113-gb3b578bcf
```

### Describe how to reproduce or add a test

Restore the attached backup.  It contains one 7-line XML file (eightball.xml) and one 83-line XQuery script (eightball.xql).  Here's the details of what's in it:

```
$ unzip -l eightball-backup.zip
Archive:  eightball-backup.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
      612  04-12-2019 21:24   db/apps/eightball/eightball.xml
     2888  04-12-2019 21:24   db/apps/eightball/eightball.xql
      869  04-12-2019 21:24   db/apps/eightball/__contents__.xml
---------                     -------
     4369                     3 files
```

Run eightball.xql in eXide (or whatever) and check your exist.log for the exception.  The reproducer is boiled down from thousands of lines of code, mostly from tei-simple.  The code won't make a great deal of sense as-is because of how much has been eliminated, but this is the smallest reproducer I could come up with, and obviously whatever is happening should not be exceeding an array bound.

### Context information

Java 1.8.0_201

11 Apr 2019 12:13:19,007 [main] INFO  (JettyStart.java [run]:158) - [eXist Version : 4.7.0-SNAPSHOT]
11 Apr 2019 12:13:19,008 [main] INFO  (JettyStart.java [run]:159) - [eXist Build : 201904111213]
11 Apr 2019 12:13:19,008 [main] INFO  (JettyStart.java [run]:160) - [Git commit : b3b578bcf]
11 Apr 2019 12:13:19,008 [main] INFO  (JettyStart.java [run]:162) - [Operating System : Mac OS X 10.14.4 x86_64]

[eightball-backup.zip](https://github.com/eXist-db/exist/files/3075646/eightball-backup.zip)

**Comment by craigberry** [comment]
A manual bisect (since I couldn't figure out how to script everything well enough to use git bisect) shows that the following commit introduced the problem:

```
$ git show a0b355438
commit a0b35543899e001d4a74adfb0d52b92463e264bc (HEAD)
Author: Wolfgang Meier <wolfgang@existsolutions.com>
Date:   Thu Nov 15 22:49:40 2018 +0100

    [bugfix] Fix failing xml:id tests by using proper checks for xs:NCName
...
```

Perhaps some of the new name checking got confused by the attribute value beginning with a hash character like so: `rendition="#hi"` though I'm not sure that makes sense since I don't think attribute values need to be valid NCNames or XML names.  In any case, I hope this helps someone who understands the Java code sort out what's going on.
