### ISSUE TITLE
diacritics in filenames make deploy fail

### ISSUE THREAD

**Issue by eduarddrenth** [eXist-db/exist#2666]
### What is the problem

A file with a diacritic in the name (i.e. tweeënhalf.xml) makes deploy of a xar fail

### What did you expect

the xar deployed

### Describe how to reproduce or add a test

- create an empty app
- put a file tweeënhalf.xml in a dir
- call ant to create a xar
- try to deploy it

### Please always add the following information

- eXist-db 4.6.1
- Java version: openjdk version "1.8.0_191"
- Operating system: ubuntu 1804
- 64 bit
- JAR installer

**Comment by joewiz** [comment]
Could you attach such a `.xar` to this issue and specify the method you use for deploying? Is any error shown in the process? Do you see any error in `exist.log` or `expath-repo.log`?

**Comment by eduarddrenth** [comment]
Cannot reproduce anymore. Tomorrow I'll do a full rebuild/deploy with diacritics in filenames to check if then I encounter problems.

**Comment by eduarddrenth** [comment]
Got it:

use this xar: [xar.zip](https://github.com/eXist-db/exist/files/3145204/xar.zip)

execute this:

```/bin/bash
git clone git@bitbucket.org:fryske-akademy/exist-db.git
cd exist-db/docker
# move xar here
export APPNAME=onfw
export VOLUMEROOT=${HOME}/volumes
export VERSION=0.3
docker build -t ${APPNAME}:${VERSION} .
docker stack deploy -c docker-compose.yml ${APPNAME}
docker service logs onfw_onfw 
```
You will now see an error in the log:
```
onfw_onfw.1.i9jubxryeo91@eduard-X756UB    | 05 May 2019 06:32:04,426 [main] WARN  (StartupTriggersManager.java [startPreMultiUserSystem]:62) - StartupTrigger threw RuntimeException: Malformed input or input contains unmappable characters: data/tweeënhalf.xml. IGNORING! 
onfw_onfw.1.i9jubxryeo91@eduard-X756UB    | java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: data/tweeënhalf.xml
```
Perhaps locale or something in the docker container, autodeploy on my laptop with ubuntu 1804 succeeds.

Probably https://github.com/eXist-db/eXide/issues/222#issue-439977764 is as well related to docker.

**Comment by dizzzz** [comment]
@eduarddrenth for me, latest eXist-db v5 from github: your XAR installs perfectly well *via the package manager* including the diacritics file. However, there is an other issue in your app:

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/1700062/57193453-78af0380-6f3b-11e9-89bd-ce43adada752.png">

**Comment by eduarddrenth** [comment]
did you miss my comment about the docker route?
further I use 461 and never saw the parse issue and the app runs perfectly
fine

Op zo 5 mei 2019 13:41 schreef Dannes Wessels <notifications@github.com>:

**Comment by dizzzz** [comment]
yes I saw the docker statement.... but in that context I have nothing to add :-P

**Comment by eduarddrenth** [comment]
when v5 arrives I will, thanks

**Comment by duncdrum** [comment]
using the xar linked in the comment i get
```
05 May 2019 18:56:48,597 [qtp1483155688-25] ERROR (Deploy.java [installAndDeployFromDb]:240) - Missing descriptor from package: /db/system/repo/xar.xar 
org.expath.pkg.repo.PackageException: Missing descriptor from package: /db/system/repo/xar.xar
        at org.exist.repo.Deployment.installAndDeploy(Deployment.java:175) ~[exist.jar:5.0.0-SNAPSHOT]
        at org.exist.repo.Deployment.installAndDeploy(Deployment.java:158) ~[exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.modules.expathrepo.Deploy.installAndDeployFromDb(Deploy.java:238) [exist-expathrepo-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.modules.expathrepo.Deploy.eval(Deploy.java:182) [exist-expathrepo-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.BasicFunction.eval(BasicFunction.java:74) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:41) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:99) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:100) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.UserDefinedFunction.eval(UserDefinedFunction.java:162) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.DynamicCardinalityCheck.eval(DynamicCardinalityCheck.java:74) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.Atomize.eval(Atomize.java:67) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.DynamicTypeCheck.eval(DynamicTypeCheck.java:61) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:302) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.FunctionCall.eval(FunctionCall.java:223) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:99) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.PathExpr.eval(PathExpr.java:276) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.TryCatchExpression.eval(TryCatchExpression.java:142) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.PathExpr.eval(PathExpr.java:276) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.EnclosedExpr.eval(EnclosedExpr.java:85) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.PathExpr.eval(PathExpr.java:276) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.ElementConstructor.eval(ElementConstructor.java:331) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:100) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.UserDefinedFunction.eval(UserDefinedFunction.java:162) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:302) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.FunctionCall.eval(FunctionCall.java:223) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.value.FunctionReference.eval(FunctionReference.java:82) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.DynamicFunctionCall.eval(DynamicFunctionCall.java:76) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:100) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.UserDefinedFunction.eval(UserDefinedFunction.java:162) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:302) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.FunctionCall.eval(FunctionCall.java:223) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.PathExpr.eval(PathExpr.java:276) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.XQuery.execute(XQuery.java:261) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.XQuery.execute(XQuery.java:185) [exist.jar:5.0.0-SNAPSHOT]
        at org.exist.http.RESTServer.executeXQuery(RESTServer.java:1512) [exist-optional.jar:5.0.0-SNAPSHOT]
        at org.exist.http.RESTServer.doPost(RESTServer.java:685) [exist-optional.jar:5.0.0-SNAPSHOT]
        at org.exist.http.servlets.EXistServlet.doPost(EXistServlet.java:460) [exist-optional.jar:5.0.0-SNAPSHOT]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [servlet-api-3.1.jar:3.1.0]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [servlet-api-3.1.jar:3.1.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:867) [jetty-servlet-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542) [jetty-servlet-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566) [jetty-security-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480) [jetty-servlet-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:168) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:78) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.exist.http.urlrewrite.Forward.doRewrite(Forward.java:51) [exist-optional.jar:5.0.0-SNAPSHOT]
        at org.exist.http.urlrewrite.XQueryURLRewrite.doRewrite(XQueryURLRewrite.java:525) [exist-optional.jar:5.0.0-SNAPSHOT]
        at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:344) [exist-optional.jar:5.0.0-SNAPSHOT]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [servlet-api-3.1.jar:3.1.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:859) [jetty-servlet-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542) [jetty-servlet-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524) [jetty-security-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480) [jetty-servlet-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:703) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.Server.handle(Server.java:502) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

on a fresh pull of `existdb/existdb:latest`, however when i rename one of my own apps: to `reådçhinä.xar` i have no problems on uploading a xar with diacrits on docker.

**Comment by eduarddrenth** [comment]
Looks like you didn't unzip? Further I am using 461 until 5 is in production.

**Comment by dizzzz** [comment]
@duncdrum there is a XAR file in the ZIP file :-)

**Comment by duncdrum** [comment]
@dizzzz i realized that later too, without instructions i assumed i had to rename the `.zip`.

**Comment by dizzzz** [comment]
@duncdrum  yes that is why it is so important that an issue describes *all* detailed steps how to reproduce.
