### ISSUE TITLE
IllegalMonitorState in LockTable

### ISSUE THREAD

**Issue by wolfgangmm** [eXist-db/exist#2685]
I encountered the following exception using current develop. Any idea what could cause it?

```java
Caused by: java.lang.IllegalMonitorStateException
        at java.util.concurrent.locks.StampedLock.unlockRead(StampedLock.java:563) ~[?:1.8.0_181]
        at org.exist.storage.lock.LockTable$Entries.unmerge(LockTable.java:385) ~[exist.jar:5.0.0-SNAPSHOT]
        at org.exist.storage.lock.LockTable.event(LockTable.java:230) ~[exist.jar:5.0.0-SNAPSHOT]
        at org.exist.storage.lock.LockTable.released(LockTable.java:126) ~[exist.jar:5.0.0-SNAPSHOT]
        at org.exist.storage.lock.LockManager.lambda$null$2(LockManager.java:201) ~[exist.jar:5.0.0-SNAPSHOT]
        at org.exist.storage.lock.LockManager.unlockAll(LockManager.java:249) ~[exist.jar:5.0.0-SNAPSHOT]
        at org.exist.storage.lock.LockManager.lambda$acquireCollectionReadLock$3(LockManager.java:201) ~[exist.jar:
5.0.0-SNAPSHOT]
        at org.exist.storage.lock.ManagedLock.close(ManagedLock.java:186) ~[exist.jar:5.0.0-SNAPSHOT]
        at org.exist.collections.LockedCollection.close(LockedCollection.java:90) ~[exist.jar:5.0.0-SNAPSHOT]
        at org.exist.storage.NativeBroker.getXMLResource(NativeBroker.java:2233) ~[exist.jar:5.0.0-SNAPSHOT]
        at org.exist.source.DBSource.isValid(DBSource.java:91) ~[exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.ExternalModuleImpl.moduleIsValid(ExternalModuleImpl.java:267) ~[exist.jar:5.0.0-SNAPSHO
T]
        at org.exist.xquery.XQueryContext.checkModulesValid(XQueryContext.java:1487) ~[exist.jar:5.0.0-SNAPSHOT]
        at org.exist.xquery.PathExpr.isValid(PathExpr.java:526) ~[exist.jar:5.0.0-SNAPSHOT]
        at org.exist.storage.XQueryPool.lambda$borrowCompiledXQuery$1(XQueryPool.java:183) ~[exist.jar:5.0.0-SNAPSH
OT]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$remap$16(BoundedLocalCache.java:2228) ~[caff
eine-2.6.2.jar:?]
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877) ~[?:1.8.0_181]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.remap(BoundedLocalCache.java:2194) ~[caffeine-2.6.2
.jar:?]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfPresent(BoundedLocalCache.java:2132) ~[caf
feine-2.6.2.jar:?]
        at org.exist.storage.XQueryPool.borrowCompiledXQuery(XQueryPool.java:163) ~[exist.jar:5.0.0-SNAPSHOT]
```

**Comment by dizzzz** [comment]
exist v4.x ?

**Comment by wolfgangmm** [comment]
no, current develop and 5.0.0.

**Comment by adamretter** [comment]
Looks like a small bug in the concurrent locking code, there is a path where `unlockRead` can be called on a lock which has been upgraded from read to write mode. I will send a patch ASAP...
