### ISSUE TITLE
Memory assertion when doing backup with 4.7.0 

### ISSUE THREAD

**Issue by reinhapa** [eXist-db/exist#2743]
Reading a XML document exceeding 16 MB in size via remote connection triggers the following error:
```
java.lang.AssertionError: memory values bigger than 16MB not supported
	at org.exist.util.io.MemoryContentsImpl.ensureCapacity(MemoryContentsImpl.java:114)
	at org.exist.util.io.MemoryContentsImpl.write(MemoryContentsImpl.java:194)
	at org.exist.util.io.MemoryContentsImpl.writeAtEnd(MemoryContentsImpl.java:216)
	at org.exist.util.io.OverflowToDiskStream.write(OverflowToDiskStream.java:106)
```
The reason for the problem is a typo within the definition of the default in memory buffer of remote resources before buffering them to the local file system of the client. It declares a 64 MB buffer size instead of 4 MB

More details also available on the [Exist-open mailing list entry](https://github.com/eXist-db/exist/issues/2743)

**Comment by craigberry** [comment]
Thanks for your work on this.  I just have a correction to the mailing list report link, which is actually [here](https://sourceforge.net/p/exist/mailman/message/36677004/).
