### ISSUE TITLE
NPE with MimeTable when running xq suite tests

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#2811]
### What is the problem
When running the Mongrel XAR test suite, There is a NPE stack trace, shown below

### What did you expect
Clean build

### Describe how to reproduce or add a test
Checkout mongrel, change exist-db to version 4.6.0 or 5.0.0-RC6 and run `mvn clean install`

### Context information
Please always add the following information
- eXist-db version: 4.6.0 or 5.0.0-RC6 // mongrel from git@github.com:weXsol/Mongrel.git 
- Java version (e.g. Java8u201)
- Operating system ( MacOs)
- 64 bit
- How is eXist-db installed? n/a - man dependency
- Any custom changes in e.g. conf.xml -  none

```
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
21:29:02.442 [main] ERROR org.exist.util.MimeTable - Failed to load mime-type table from class loader
21:29:02.506 [main] ERROR org.exist.util.MimeTable - Failed to load mime-type table from class loader
java.net.MalformedURLException: null
	at java.net.URL.<init>(URL.java:627) ~[?:1.8.0_212]
	at java.net.URL.<init>(URL.java:490) ~[?:1.8.0_212]
	at java.net.URL.<init>(URL.java:439) ~[?:1.8.0_212]
	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source) ~[xercesImpl-2.12.0.jar:2.12.0]
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source) ~[xercesImpl-2.12.0.jar:2.12.0]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.12.0.jar:?]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.12.0.jar:?]
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl-2.12.0.jar:?]
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.12.0.jar:?]
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.12.0.jar:?]
	at org.exist.util.MimeTable.loadMimeTypes(MimeTable.java:290) ~[exist-core-5.0.0-RC6.jar:5.0.0-RC6]
	at org.exist.util.MimeTable.load(MimeTable.java:263) [exist-core-5.0.0-RC6.jar:5.0.0-RC6]
	at org.exist.util.MimeTable.load(MimeTable.java:214) [exist-core-5.0.0-RC6.jar:5.0.0-RC6]
	at org.exist.util.MimeTable.<init>(MimeTable.java:115) [exist-core-5.0.0-RC6.jar:5.0.0-RC6]
	at org.exist.util.MimeTable.getInstance(MimeTable.java:83) [exist-core-5.0.0-RC6.jar:5.0.0-RC6]
	at org.exist.util.XMLFilenameFilter.asPredicate(XMLFilenameFilter.java:20) [exist-core-5.0.0-RC6.jar:5.0.0-RC6]
	at org.exist.test.runner.XSuite.getRunner(XSuite.java:196) [exist-testkit-5.0.0-RC6.jar:5.0.0-RC6]
	at org.exist.test.runner.XSuite.getRunners(XSuite.java:176) [exist-testkit-5.0.0-RC6.jar:5.0.0-RC6]
	at org.exist.test.runner.XSuite.<init>(XSuite.java:135) [exist-testkit-5.0.0-RC6.jar:5.0.0-RC6]
	at org.exist.test.runner.XSuite.<init>(XSuite.java:103) [exist-testkit-5.0.0-RC6.jar:5.0.0-RC6]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [?:1.8.0_212]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_212]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_212]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_212]
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:107) [junit-4.12.jar:4.12]
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86) [junit-4.12.jar:4.12]
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59) [junit-4.12.jar:4.12]
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26) [junit-4.12.jar:4.12]
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59) [junit-4.12.jar:4.12]
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33) [junit-4.12.jar:4.12]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:250) [surefire-junit4-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141) [surefire-junit4-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112) [surefire-junit4-2.12.4.jar:2.12.4]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189) [surefire-api-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165) [surefire-booter-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85) [surefire-booter-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115) [surefire-booter-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) [surefire-booter-2.12.4.jar:2.12.4]
Caused by: java.lang.NullPointerException
	at java.net.URL.<init>(URL.java:532) ~[?:1.8.0_212]
	... 41 more
```

**Comment by dizzzz** [comment]
interesting as the following line does not match the code archive:

```
org.exist.util.MimeTable.loadMimeTypes(MimeTable.java:290)
```

**Comment by adamretter** [comment]
For 4.6.0 and it seems that `exist-core/src/main/resources/org/exist/util/mime-types.xml` was missed from the `exist-core-4.6.0.jar`.

It is present in 4.7.0 and 5.0.0-RC8. So you should likely just upgrade as we can't modify a past release anyway ;-)

**Comment by dizzzz** [comment]
ok thnx

**Comment by dizzzz** [comment]
4.7.0 yields into another issue :-(
