### ISSUE TITLE
unattended install does not set the admin password to the value I want

### ISSUE THREAD

**Issue by lddubeau** [eXist-db/exist#2850]
### Context information

- eXist-db 4.7.0 downloaded from [here](https://bintray.com/existdb/releases/download_file?file_path=eXist-db-setup-4.7.0.jar)

- Java version

```
$ java --version
openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+1-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.3+1-Debian-1, mixed mode, sharing)
```
- OS: Debian buster 64 bit

- How is eXist-db installed? Jar installer

### What is the problem

After doing an unattended installation of eXist, I cannot log as administrator because the password is wrong.

### What did you expect

I expect the password to be set to the options I specified to the installer.

### Describe how to reproduce or add a test

This is all using [IzPack's documentation on unattended installs](https://izpack.atlassian.net/wiki/spaces/IZPACK/pages/491726/Unattended+Installations+Using+Properties). That page mentions a new method for unattended installs but that method is not available to users of eXist-db 4.7.0 since the IzPack version used by eXist-db 4.7.0 is too old.

Create a properties file template:

```
$ java -jar [...]/eXist-db-setup-4.7.0.jar -options-template exist.properties
```

Check the file's content:

```
$ cat exist.properties 
INSTALL_PATH=
dataDir=
divider=
space=
MAX_MEMORY=
cacheSize=
```

Well, that's bizarre... what are the `divider` and `space` properties supposed to be? If I look into the source code for 4.7.0 there's an `adminPasswd` value associated with the admin password. So let's try that. Edit the file to:

```
INSTALL_PATH=/tmp/glurb
dataDir=/tmp/glurb-data
MAX_MEMORY=2048
cacheSize=600
adminPasswd=foo
```

Then run:

```
$ java -jar [...]/eXist-db-setup-4.7.0.jar -options exist.properties
```

The installer runs to completion without error, and it did install what I wanted in `INSTALL_PATH`.

However, I cannot login as `admin`:

```
$ cd /tmp/glurb
$ ./bin/client.sh -s -l -u admin -P 'foo'
-s -l -u admin -P foo
Using locale: en_US.UTF-8
eXist version 4.7.0 (64ba51345), Copyright (C) 2001-2019 The eXist-db Project
eXist-db comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; for details read the license file.

Connecting to database...
Connection to database failed; message: Wrong password for user [admin] 
org.xmldb.api.base.XMLDBException: Wrong password for user [admin] 
        at org.exist.xmldb.DatabaseImpl.getUser(DatabaseImpl.java:292)
        at org.exist.xmldb.DatabaseImpl.getLocalCollection(DatabaseImpl.java:189)
        at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:167)
        at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:158)
        at org.xmldb.api.DatabaseManager.getCollection(DatabaseManager.java:235)
        at org.exist.client.InteractiveClient.connect(InteractiveClient.java:300)
        at org.exist.client.InteractiveClient.connectToDatabase(InteractiveClient.java:2116)
        at org.exist.client.InteractiveClient.run(InteractiveClient.java:2213)
        at org.exist.client.InteractiveClient.main(InteractiveClient.java:243)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.exist.start.Main.invokeMain(Main.java:140)
        at org.exist.start.Main.run(Main.java:453)
        at org.exist.start.Main.main(Main.java:64)
Caused by: org.exist.security.AuthenticationException: Wrong password for user [admin] 
        at org.exist.security.internal.RealmImpl.authenticate(RealmImpl.java:269)
        at org.exist.security.internal.SecurityManagerImpl.authenticate(SecurityManagerImpl.java:436)
        at org.exist.xmldb.DatabaseImpl.getUser(DatabaseImpl.java:290)
        ... 15 more
```

I also tried setting `divider` and `space` to the admin password I want but that did not work either.

### Observations

The password is actually set to `$adminPasswd`, because this works:

```
$ ./bin/client.sh -s -l -u admin -P '$adminPasswd'
-s -l -u admin -P $adminPasswd
Using locale: en_US.UTF-8
eXist version 4.7.0 (64ba51345), Copyright (C) 2001-2019 The eXist-db Project
eXist-db comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; for details read the license file.

Connecting to database...
Connected :-)

type help or ? for help.
exist:/db> 
```

:rofl: 

Well at least it is possible to fix the issue immediately after installation with:

```
$ ./bin/client.sh -s -l -u admin -P '$adminPasswd' --xpath 'let $_ := sm:passwd("admin", "foo") return "Ok"'
```

(Note that the installer ignores `dataDir` and `cacheSize` but that's an issue that plagues the installer no matter whether it is used through the GUI interface, the console interface, or unattended. See #1711 )

**Comment by adamretter** [comment]
I am closing this, as I believe this is fixed in 5.0.0-RC8
