### ISSUE TITLE
After patching, my 4.5 install fails to start

### ISSUE THREAD

**Issue by oberoc** [eXist-db/exist#2856]
### What is the problem
When `systemctl eXist-db start`, it fails with an jetty throwing an exception

### What did you expect
The eXist to startup without incident

### Describe how to reproduce or add a test
Will have to work with the eXist team to figure out the best way of troubleshooting

exist.log below:
2019-01-12 07:21:56,749 [qtp726107869-39] INFO  (BrokerPool.java [shutdown]:1675) - shutdown complete ! 
2019-01-12 07:21:56,749 [qtp726107869-39] INFO  (JettyStart.java [shutdown]:602) - Database shutdown: stopping server in 1sec ... 
2019-01-12 07:21:56,759 [qtp726107869-39] WARN  (FillInterest.java [register]:57) - Read pending for AC.ReadCB@446e885f{HttpConnection@446e885f[p=HttpParser{s=START,0 of -1},g=HttpGenerator@296fdcec{s=START}]=>HttpChannelOverHttp@5fdc5294{r=2,c=false,a=IDLE,uri=null,age=0}<-SocketChannelEndPoint@1256b2da{/127.0.0.1:49978<->/127.0.0.1:8080,OPEN,fill=FI,flush=-,to=1/30000}{io=1/1,kio=1,kro=1}->HttpConnection@446e885f[p=HttpParser{s=START,0 of -1},g=HttpGenerator@296fdcec{s=START}]=>HttpChannelOverHttp@5fdc5294{r=2,c=false,a=IDLE,uri=null,age=0}} prevented AC.ReadCB@446e885f{HttpConnection@446e885f[p=HttpParser{s=START,0 of -1},g=HttpGenerator@296fdcec{s=START}]=>HttpChannelOverHttp@5fdc5294{r=2,c=false,a=IDLE,uri=null,age=0}<-SocketChannelEndPoint@1256b2da{/127.0.0.1:49978<->/127.0.0.1:8080,OPEN,fill=FI,flush=-,to=2/30000}{io=1/1,kio=1,kro=1}->HttpConnection@446e885f[p=HttpParser{s=START,0 of -1},g=HttpGenerator@296fdcec{s=START}]=>HttpChannelOverHttp@5fdc5294{r=2,c=false,a=IDLE,uri=null,age=0}} 
2019-01-12 07:21:56,759 [qtp726107869-39] WARN  (EatWhatYouKill.java [runTask]:337) -  
java.nio.channels.ReadPendingException: null
	at org.eclipse.jetty.io.FillInterest.register(FillInterest.java:58) ~[jetty-io-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.io.AbstractEndPoint.fillInterested(AbstractEndPoint.java:361) ~[jetty-io-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.io.AbstractConnection.fillInterested(AbstractConnection.java:134) ~[jetty-io-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:271) ~[jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281) ~[jetty-io-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) ~[jetty-io-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) ~[jetty-io-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
2019-01-12 07:21:57,752 [jetty shutdown schedule] INFO  (JettyStart.java [lifeCycleStopping]:684) - Jetty server stopping... 
2019-01-12 07:21:57,758 [jetty shutdown schedule] INFO  (AbstractConnector.java [doStop]:332) - Stopped ServerConnector@3f29e26{HTTP/1.1,[http/1.1]}{0.0.0.0:8080} 
2019-01-12 07:21:57,759 [jetty shutdown schedule] INFO  (AbstractConnector.java [doStop]:332) - Stopped ServerConnector@1ab6718{SSL,[ssl, http/1.1]}{0.0.0.0:8443} 
2019-01-12 07:21:57,760 [jetty shutdown schedule] INFO  (HouseKeeper.java [stopScavenging]:167) - node0 Stopped scavenging 
2019-01-12 07:21:57,766 [jetty shutdown schedule] INFO  (ContextHandler.java [doStop]:957) - Stopped o.e.j.w.WebAppContext@7a7cc52c{/,null,UNAVAILABLE}{/portal} 
2019-01-12 07:21:57,769 [jetty shutdown schedule] INFO  (ContextHandler.java [doStop]:957) - Stopped eXist-db Open Source Native XML Database 
2019-01-12 07:21:57,772 [jetty shutdown schedule] INFO  (JettyStart.java [lifeCycleStopped]:691) - Jetty server stopped 
2019-01-12 09:05:28,824 [global.BrokerPools.ShutdownHook] INFO  (BrokerPools.java [lambda$static$0]:67) - Executing shutdown thread 

### Context information
Please always add the following information
- eXist-4.5
- OpenJDK 1.8.0_212
- RHEL 7.6
- 64 bit
- From a tar.gz file from bintray
- No changes to conf.xml

**Comment by duncdrum** [comment]
do you still experience problems with 4.7.1 or can we close this?

**Comment by oberoc** [comment]
You can close it
