### ISSUE TITLE
changing admin password in Java client throws unauthorized exception

### ISSUE THREAD

**Issue by craigberry** [eXist-db/exist#2918]
With a fresh install of 5.0-RC8 on macOS Mojave using the DMG installer, I used the Java Admin client to change the admin password from its default (blank) value to a new non-blank value (after first logging in with the blank value).  As soon as I clicked Save, it threw the exception below and was unable to perform any other operations.  

The password change had apparently succeeded since after quitting the client and restarting I could log in with the password I had entered.  I guess what I'm asking is would it be possible to have the client re-authenticate you after it's successfully updated the password for the account under which you are logged in.

```
org.xmldb.api.base.XMLDBException: HTTP server returned unexpected status: Unauthorized
	at org.exist.xmldb.RemoteCollection.instance(RemoteCollection.java:109)
	at org.exist.xmldb.RemoteCollection.instance(RemoteCollection.java:85)
	at org.exist.xmldb.DatabaseImpl.readCollection(DatabaseImpl.java:278)
	at org.exist.xmldb.DatabaseImpl.getRemoteCollection(DatabaseImpl.java:240)
	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:180)
	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:169)
	at org.xmldb.api.DatabaseManager.getCollection(DatabaseManager.java:235)
	at org.exist.client.InteractiveClient.connect(InteractiveClient.java:300)
	at org.exist.client.ClientFrame.reconnectClient(ClientFrame.java:514)
	at org.exist.client.security.UserManagerDialog.reconnectClientAndUserManager(UserManagerDialog.java:370)
	at org.exist.client.security.UserManagerDialog.lambda$8(UserManagerDialog.java:384)
	at org.exist.client.security.EditUserDialog.createUser(EditUserDialog.java:104)
	at org.exist.client.security.UserDialog.btnCreateActionPerformed(UserDialog.java:329)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: org.apache.xmlrpc.client.XmlRpcHttpTransportException: HTTP server returned unexpected status: Unauthorized
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.getInputStream(XmlRpcSunHttpTransport.java:94)
	at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:152)
	at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
	at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:158)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:147)
	at org.exist.xmldb.RemoteCollection.instance(RemoteCollection.java:97)
	... 48 more
```

**Comment by dizzzz** [comment]
@craigberry  please could you describe steps while how to reproduce? I ask as the 'story' seems to step back in time.

**Comment by craigberry** [comment]
Log in as admin, change the password on the admin account, and click Save.  That's a full reproducer. 

But that's what I already said, so I'm not sure what's confusing you.  Obviously changing the password is not what's throwing the exception since later login attempts work with the new password.  So the exception must be thrown by something else the client is doing after the Save button gets clicked and the password gets changed but before anything else.  Perhaps it's simply trying to refresh its browse window using cached credentials that are no longer valid, but I can only speculate about the why.
