### ISSUE TITLE
[4.7.0] Restore fails if contextPath is "/"

### ISSUE THREAD

**Issue by claudius108** [eXist-db/exist#2919]
Restore of a database contents from command line fails if contextPath is "/",instead of "/exist".

Context:
latest eXist 4.7.0, ubuntu, java 1.8, 64 bit, JAR installer,.

Error message:
Problems occured found during restore:
ERROR: HTTP server returned unexpected status: Not Found

If you restored collections inside /db/apps, you may want
to rebuild the application repository. To do so, run the following query
as admin:

import module namespace repair="http://exist-db.org/xquery/repo/repair"
at "resource:org/exist/xquery/modules/expathrepo/repair.xql";
repair:clean-all(),
repair:repair()

org.xmldb.api.base.XMLDBException: HTTP server returned unexpected status: Not Found
	at org.exist.xmldb.RemoteCollection.instance(RemoteCollection.java:99)
	at org.exist.xmldb.RemoteCollection.instance(RemoteCollection.java:75)
	at org.exist.xmldb.DatabaseImpl.readCollection(DatabaseImpl.java:267)
	at org.exist.xmldb.DatabaseImpl.getRemoteCollection(DatabaseImpl.java:229)
	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:169)
	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:158)
	at org.xmldb.api.DatabaseManager.getCollection(DatabaseManager.java:235)
	at org.exist.backup.Main.process(Main.java:261)
	at org.exist.backup.Main.main(Main.java:406)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.exist.start.Main.invokeMain(Main.java:140)
	at org.exist.start.Main.run(Main.java:453)
	at org.exist.start.Main.main(Main.java:64)
Caused by: org.apache.xmlrpc.client.XmlRpcHttpTransportException: HTTP server returned unexpected status: Not Found
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.getInputStream(XmlRpcSunHttpTransport.java:94)
	at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:152)
	at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
	at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:158)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:147)
	at org.exist.xmldb.RemoteCollection.instance(RemoteCollection.java:87)
	... 15 more
caused by 
org.apache.xmlrpc.client.XmlRpcHttpTransportException: HTTP server returned unexpected status: Not Found
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.getInputStream(XmlRpcSunHttpTransport.java:94)
	at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:152)
	at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
	at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:158)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:147)
	at org.exist.xmldb.RemoteCollection.instance(RemoteCollection.java:87)
	at org.exist.xmldb.RemoteCollection.instance(RemoteCollection.java:75)
	at org.exist.xmldb.DatabaseImpl.readCollection(DatabaseImpl.java:267)
	at org.exist.xmldb.DatabaseImpl.getRemoteCollection(DatabaseImpl.java:229)
	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:169)
	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:158)
	at org.xmldb.api.DatabaseManager.getCollection(DatabaseManager.java:235)
	at org.exist.backup.Main.process(Main.java:261)
	at org.exist.backup.Main.main(Main.java:406)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.exist.start.Main.invokeMain(Main.java:140)
	at org.exist.start.Main.run(Main.java:453)
	at org.exist.start.Main.main(Main.java:64)

**Comment by duncdrum** [comment]
does this still apply to 5.0.0?

**Comment by claudius108** [comment]
I have not tested in 5.0.0.
