### ISSUE TITLE
xml-rpc-client does not work with exist-db 5.0.0

### ISSUE THREAD

**Issue by stexandev** [eXist-db/exist#3055]
### What is the problem
When calling `client.sh -s -u admin -p password -ouri=xmldb:exist://localhost:8090/exist/xmlrpc` the client is refused the connection although credentials given are correct. 
(in my setup, exist is running on ports 8090/8443)

### What did you expect
I expected the client to connect and start in shell mode.

### Describe how to reproduce or add a test
Tested it several times including a fresh install etc. error persists.

### Context information
- eXist version 5.0.0 (5a27d10ba1710c1df751344b53ac6e4cb4778e3b) 
- openjdk version "1.8.0_222"
- OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
- OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
- Linux 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- installed from exist-distribution-5.0.0-unix.tar.bz2

### xmldb.log
```
2019-10-16 18:29:02,313 [main] ERROR (DatabaseImpl.java [getRemoteCollection]:254) - Failed to read server's response$
org.xmldb.api.base.XMLDBException: Failed to read server's response: Connection refused (Connection refused)
        at org.exist.xmldb.RemoteCollection.instance(RemoteCollection.java:109) ~[exist-core-5.0.0.jar:5.0.0]
        at org.exist.xmldb.RemoteCollection.instance(RemoteCollection.java:85) ~[exist-core-5.0.0.jar:5.0.0]
        at org.exist.xmldb.DatabaseImpl.readCollection(DatabaseImpl.java:278) ~[exist-core-5.0.0.jar:5.0.0]
        at org.exist.xmldb.DatabaseImpl.getRemoteCollection(DatabaseImpl.java:240) [exist-core-5.0.0.jar:5.0.0]
        at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:180) [exist-core-5.0.0.jar:5.0.0]
        at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:169) [exist-core-5.0.0.jar:5.0.0]
        at org.xmldb.api.DatabaseManager.getCollection(DatabaseManager.java:235) [xmldb-api-1.7.0.jar:1.7.0]
        at org.exist.client.InteractiveClient.connect(InteractiveClient.java:301) [exist-core-5.0.0.jar:5.0.0]
        at org.exist.client.InteractiveClient.connectToDatabase(InteractiveClient.java:2125) [exist-core-5.0.0.jar:5.$
        at org.exist.client.InteractiveClient.run(InteractiveClient.java:2229) [exist-core-5.0.0.jar:5.0.0]
        at org.exist.client.InteractiveClient.main(InteractiveClient.java:244) [exist-core-5.0.0.jar:5.0.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at org.exist.start.Main.invokeMain(Main.java:118) [exist-start-5.0.0.jar:5.0.0]
        at org.exist.start.Main.runEx(Main.java:248) [exist-start-5.0.0.jar:5.0.0]
        at org.exist.start.Main.run(Main.java:123) [exist-start-5.0.0.jar:5.0.0]
        at org.exist.start.Main.main(Main.java:60) [exist-start-5.0.0.jar:5.0.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.executeMain(AppassemblerBooter.java:257) [appasse$
        at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.main(AppassemblerBooter.java:77) [appassembler-bo$
Caused by: org.apache.xmlrpc.XmlRpcException: Failed to read server's response: Connection refused (Connection refuse$
        at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:161) ~[xmlrpc-client$
        at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143) ~[xmlrpc-client-3.1$
        at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69) ~[xmlrpc-clien$
        at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56) ~[xmlrpc-client-3.1.3.jar:$
       at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167) ~[xmlrpc-client-3.1.3.jar:3.1.3]
        at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:158) ~[xmlrpc-client-3.1.3.jar:3.1.3]
        at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:147) ~[xmlrpc-client-3.1.3.jar:3.1.3]
        at org.exist.xmldb.RemoteCollection.instance(RemoteCollection.java:97) ~[exist-core-5.0.0.jar:5.0.0]
        ... 24 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_222]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_222]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_222]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_222]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_222]
        at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_222]
        at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_222]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:1.8.0_222]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_222]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_222]
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:1.8.0_222]
        at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[?:1.8.0_222]
        at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[?:1.8.0_222]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226) ~[?:1.8.0_222]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162) ~[?:1.8.0_222]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056) ~[?:1.8.0_222]
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990) ~[?:1.8.0_222]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340) ~[?:1.8.0_222]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315) ~[?:1.8.0_222]
        at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.writeRequest(XmlRpcSunHttpTransport.java:104) ~[xmlrpc-cli$
        at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:151) ~[xmlrpc-client$
       at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143) ~[xmlrpc-client-3.1$
        at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69) ~[xmlrpc-clien$
        at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56) ~[xmlrpc-client-3.1.3.jar:$
        at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167) ~[xmlrpc-client-3.1.3.jar:3.1.3]
        at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:158) ~[xmlrpc-client-3.1.3.jar:3.1.3]
        at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:147) ~[xmlrpc-client-3.1.3.jar:3.1.3]
        at org.exist.xmldb.RemoteCollection.instance(RemoteCollection.java:97) ~[exist-core-5.0.0.jar:5.0.0]
        ... 24 more
```

**Comment by adamretter** [comment]
@stexandev do you have the correct port number? By default eXist-db runs on port 8080, unless you have changed that?

**Comment by dizzzz** [comment]
Yea I don't think this an eXist-db issue ; maybe a firewall one, or as you said a off port number.

**Comment by stexandev** [comment]
sorry, forgot to mention the different setup, changed my description, see above.

**Comment by line-o** [comment]
@stexandev node-exist uses XML-RPC and works with eXist 5 instances.

**Comment by line-o** [comment]
@stexandev so it could be an issue with `client.sh`

**Comment by line-o** [comment]
or the combination of `xmldb:exist` protocol with XML-RPC

**Comment by adamretter** [comment]
@stexandev did you resolve your issue?

**Comment by stexandev** [comment]
@adamretter i will need some more time to look into this issue again but it is still on my agenda. thank you for the reminder

**Comment by adamretter** [comment]
Closing due to a lack of response.
