### ISSUE TITLE
Unable to execute queries on Linux command line

### ISSUE THREAD

**Issue by hrvanderlingen** [eXist-db/exist#3115]
### What is the problem

Unable to execute queries on Linux command line

### What did you expect

startup works

 ./startup.sh
 Running with Java 1.8.0_232 [Oracle Corporation (OpenJDK 64-Bit Server VM) in /usr/lib/jv
[eXist Version : 5.0.0]
[eXist Build : 20190902160649]
[Git commit : 5a27d10ba1710c1df751344b53ac6e4cb4778e3b]
[Operating System : Linux 3.10.0-1062.1.1.el7.x86_64 amd64]

importing xml file works

bin/client.sh -m /db/products -p /home/orinoco/eXist-data/products
eXist version 5.0.0 (5a27d10ba1710c1df751344b53ac6e4cb4778e3b),
Connecting to database...
Using config: /home/orinoco/eXist-db/etc/conf.xml
Connected :-)
creating '/db/products'
storing document products.xml (1 of 1) ...done.
parsing 137655 bytes took 394ms.

Any query fails, if the xml file is correctly imported a database error would not be expected

### Describe how to reproduce or add a test

echo "//collection/products/product//productCode" | bin/client.sh -x  -c"/db/products"
eXist version 5.0.0 (5a27d10ba1710c1df751344b53ac6e4cb4778e3b), Copyright (C) 2001-2019 The eXist-db Project
eXist-db comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; for details read the license file.

Connecting to database...
Using config: /home/orinoco/eXist-db/etc/conf.xml
Connected :-)
XMLDBException during query: exerr:ERROR err:XPDY0002 Undefined context sequence for 'child::{}c' [at line 1, column 2, source: -c/db/products] [at line 1, column 2]
org.xmldb.api.base.XMLDBException: err:XPDY0002 Undefined context sequence for 'child::{}c' [at line 1, column 2, source: -c/db/products]
        at org.exist.xmldb.RemoteXPathQueryService.throwException(RemoteXPathQueryService.java:175)
        at org.exist.xmldb.RemoteXPathQueryService.query(RemoteXPathQueryService.java:112)
        at org.exist.xmldb.RemoteXPathQueryService.query(RemoteXPathQueryService.java:81)
        at org.exist.client.InteractiveClient.find(InteractiveClient.java:1220)
        at org.exist.client.InteractiveClient.processCommandLineActions(InteractiveClient.java:2052)
        at org.exist.client.InteractiveClient.run(InteractiveClient.java:2241)
        at org.exist.client.InteractiveClient.main(InteractiveClient.java:244)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.exist.start.Main.invokeMain(Main.java:118)
        at org.exist.start.Main.runEx(Main.java:248)
        at org.exist.start.Main.run(Main.java:123)
        at org.exist.start.Main.main(Main.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.executeMain(AppassemblerBooter.java:257)
        at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.main(AppassemblerBooter.java:77)
Caused by: org.exist.xquery.XPathException: exerr:ERROR err:XPDY0002 Undefined context sequence for 'child::{}c' [at line 1, column 2, source: -c/db/products] [at line 1, column 2]
        at org.exist.xmldb.RemoteXPathQueryService.throwException(RemoteXPathQueryService.java:174)
        ... 20 more

### Context information

cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)
Install via jar installer
default configuration

**Comment by joewiz** [comment]
@hrvanderlingen I notice in your code sample that you're missing a space between the `-c` flag and the collection, `"/db/products"`:

> `echo "//collection/products/product//productCode" | bin/client.sh -x -c"/db/products"`

Could this be the cause of your error, `Undefined context sequence for 'child::{}c'`?

**Comment by hrvanderlingen** [comment]
Thanks for your time,
initially that resulted in
 echo "//collection/products/product//productCode" | bin/client.sh -x  -c "/db/products"
Unexpected argument: /db/products, previous argument: -c

I found out since the next query does produce results
 bin/client.sh -c /db/products -x "//collection/products/product//productCode"
