### ISSUE TITLE
NPE during restore

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#3118]
### What is the problem
A NPE occurs while restoring from a ZIP file.

### What did you expect
A restore without issues

### Describe how to reproduce or add a test

```
./bin/backup.sh -r ~/Downloads/full20190710-0300.zip -P MyPassword -R -ouri=xmldb:exist:///
java.lang.NullPointerException
	at org.expath.pkg.repo.deps.Semver.compareTo(Semver.java:185)
	at org.exist.backup.restore.AppRestoreUtils.checkApps(AppRestoreUtils.java:62)
	at org.exist.backup.Restore.restore(Restore.java:70)
	at org.exist.xmldb.LocalRestoreService.lambda$0(LocalRestoreService.java:56)
	at org.exist.xmldb.function.LocalXmldbFunction.apply(LocalXmldbFunction.java:46)
	at org.exist.xmldb.AbstractLocal.withDb(AbstractLocal.java:263)
	at org.exist.xmldb.LocalRestoreService.restore(LocalRestoreService.java:54)
	at org.exist.backup.Main.restoreWithoutGui(Main.java:278)
	at org.exist.backup.Main.process(Main.java:248)
	at org.exist.backup.Main.main(Main.java:448)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.exist.start.Main.invokeMain(Main.java:118)
	at org.exist.start.Main.runEx(Main.java:248)
	at org.exist.start.Main.run(Main.java:123)
	at org.exist.start.Main.main(Main.java:60)
```

### Context information
Please always add the following information
- eXist-db version : 5.2.0-SNAPSHOT (aka 5.1.0) 
- Java version : OpenJDK Runtime Environment (Zulu 8.42.0.23-CA-macosx) (build 1.8.0_232-b18) 
- Operating system (Windows 7, Linux, MacOs): MacOS
- 32 or 64 bit : 64bit
- How is eXist-db installed? (JAR installer, DMG, WAR file, clone from GitHub):  local build
- Any custom changes in e.g. conf.xml - none

**Comment by adamretter** [comment]
Can you put a breakpoint in `org.expath.pkg.repo.deps.Semver.compareTo(Semver.java:185)` and work up the stack and tell us which packages it is trying to compare? It looks like one of them is missing a version number or something?

**Comment by dizzzz** [comment]
OK I will do (if I can get the app started mimicking  the scripts; found it complex some time ago).

**Comment by adamretter** [comment]
@dizzzz It's very easy to use JDWP, just do something like:

```
JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005 /bin/backup.sh -r ~/Downloads/full20190710-0300.zip -P MyPassword -R -ouri=xmldb:exist:///
```

You can then connect to the remote debugger from IntelliJ ;-)

**Comment by craigberry** [comment]
If you want to scan quickly through a zip backup for package versions that don't seem up to snuff, something like the following should do the trick.  If expath-pkg.xml were missing entirely, this wouldn't catch it, but I don't know if that's possible.

```sh
$ zipgrep '<package' full20190802-1444.zip *expath-pkg.xml | perl -ne '$_=~m/name="(\S+)".*version="(\S+)"/; print qq/$2\t$1\n/;'
1.0.0	http://earlyprint.org/EarlyPrintAnnotations
1.0.0	http://earlyprint.org/EarlyPrintTexts
1.4.6	http://existsolutions.com/annotation-service
1.0.0	http://exist-db.org/apps/atom-editor
1.1.0	http://exist-db.org/apps/dashboard
0.4.1	http://exist-db.org/apps/demo
4.2.0	http://exist-db.org/apps/doc
2.4.8	http://exist-db.org/apps/eXide
1.1.0	http://exist-db.org/apps/fundocs
0.6	http://exist-db.org/apps/markdown
0.9.16	http://exist-db.org/apps/monex
0.3.2	http://exist-db.org/apps/shakes
0.8.3	http://exist-db.org/apps/shared
1.25.7	https://texts.earlyprint.org/
0.7.0	http://pib.at.northwestern.edu/apps/annotation-client
0.16.5	http://exist-db.org/apps/usermanager
1.0-SNAPSHOT	http://expath.org/ns/binary
1.0	http://www.functx.com
1.0-SNAPSHOT	http://exist-db.org/xquery/memsort
2.7.0	http://existsolutions.com/apps/tei-publisher-lib
```
