### ISSUE TITLE
xslfo broken in 5.1.0

### ISSUE THREAD

**Issue by craigberry** [eXist-db/exist#3125]
The attached 47-line query successfully produces PDF output in 5.0.0 but throws an NPE in 5.1.0.  The error is just this:

Oracle JDK 8:

`An exception occurred during query execution: exerr:ERROR exerr:ERROR Error. [at line 46, column 13] [at line 46, column 13]`

OpenJDK 11:

`An exception occurred during query execution: exerr:ERROR exerr:ERROR java.lang.NullPointerException [at line 46, column 13] [at line 46, column 13]
`

and the stack trace from OpenJDK 11 is the following:

```
org.xmldb.api.base.XMLDBException: exerr:ERROR java.lang.NullPointerException [at line 46, column 13]
	at org.exist.xmldb.RemoteXPathQueryService.throwException(RemoteXPathQueryService.java:175)
	at org.exist.xmldb.RemoteXPathQueryService.query(RemoteXPathQueryService.java:112)
	at org.exist.xmldb.RemoteXPathQueryService.query(RemoteXPathQueryService.java:81)
	at org.exist.xmldb.RemoteXPathQueryService.execute(RemoteXPathQueryService.java:349)
	at org.exist.client.QueryDialog$QueryRunnable.run(QueryDialog.java:577)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.exist.xquery.XPathException: exerr:ERROR exerr:ERROR java.lang.NullPointerException [at line 46, column 13] [at line 46, column 13]
	at org.exist.xmldb.RemoteXPathQueryService.throwException(RemoteXPathQueryService.java:174)
	... 5 more
```

There is nothing in exist.log.

### Context information

[eXist Version : 5.1.0] 
[eXist Build : 20191117145049] 
[Git commit : 1533551563661d2c2061d3ed1304cb257f216327] 
[Operating System : Mac OS X 10.14.6 x86_64] 

The problem happens with both Oracle JRE 1.8.0_231 and OpenJDK 11.0.4+11, though only the latter indicates the problem is an NPE.

- Any custom changes: no

[broken_xslfo.xql.zip](https://github.com/eXist-db/exist/files/3881625/broken_xslfo.xql.zip)

**Comment by craigberry** [comment]
In case anyone wants to see the XQuery code inline instead of downloading the zip, here ya go:

```XQuery
xquery version "3.1";

import module namespace xslfo="http://exist-db.org/xquery/xslfo";

let $config :=
<fop version="1.0">
    <strict-configuration>true</strict-configuration>
    <strict-validation>false</strict-validation>
    <base>./</base>
    <renderers>
        <renderer mime="application/pdf"></renderer>
    </renderers>
</fop>

let $fo :=
<fo:root xmlns:fo="http://www.w3.org/1999/XSL/Format">
    <fo:layout-master-set>
        <fo:simple-page-master master-name="page-left" page-height="297mm" page-width="210mm" margin-bottom="10mm" margin-top="10mm" margin-left="36mm" margin-right="18mm">
            <fo:region-body margin-bottom="10mm" margin-top="16mm"/>
            <fo:region-before region-name="head-left" extent="10mm"/>
        </fo:simple-page-master>
        <fo:simple-page-master master-name="page-right" page-height="297mm" page-width="210mm" margin-bottom="10mm" margin-top="10mm" margin-left="18mm" margin-right="36mm">
            <fo:region-body margin-bottom="10mm" margin-top="16mm"/>
            <fo:region-before region-name="head-right" extent="10mm"/>
        </fo:simple-page-master>
        <fo:page-sequence-master master-name="page-content">
            <fo:repeatable-page-master-alternatives>
                <fo:conditional-page-master-reference master-reference="page-right" odd-or-even="odd"/>
                <fo:conditional-page-master-reference master-reference="page-left" odd-or-even="even"/>
            </fo:repeatable-page-master-alternatives>
        </fo:page-sequence-master>
    </fo:layout-master-set>    <!--document (tei-TEI)-->
    <fo:page-sequence master-reference="page-content">
         <fo:flow flow-name="xsl-region-body" hyphenate="true" language="en" xml:lang="en">
                <fo:block id="A97060-t" line-height="16pt" font-size="11pt">
                    <fo:block id="A97060-e0" page-break-after="right">
                        <fo:block id="A97060-e100" text-align="justify" space-before=".5em" text-indent="1.5em" space-after=".5em">
                            MY Service in the Camp against the French Fleet hinder'd me from Writing the last Post
                        </fo:block>
                    </fo:block>
                </fo:block>
        </fo:flow>
    </fo:page-sequence>
</fo:root>

let $pdf := xslfo:render($fo, "application/pdf", (), $config)
return $pdf


```

**Comment by adamretter** [comment]
@craigberry thanks for the excellent error report, I have now submitted a fix for this.
