### ISSUE TITLE
[BUG] stats.dbx

### ISSUE THREAD

**Issue by pwin** [eXist-db/exist#3193]
**Describe the bug**
An error being reported when starting exist-db 5.1.1 on Windows 10 using Azul Java v11
```
13 Jan 2020 12:55:22,350 [main] INFO  (JettyStart.java [run]:200) - Configuring eXist from C:\exist-db\exist-db.5.1.1\db\etc\conf.xml
org.exist.storage.btree.DBException: Error while writing C:\exist-db\exist-db.5.1.1\data\stats.dbx: C:\exist-db\exist-db.5.1.1\data\stats.dbx
        at org.exist.storage.statistics.IndexStatistics.sync(IndexStatistics.java:114)
        at org.exist.indexing.IndexManager.sync(IndexManager.java:264)
        at org.exist.storage.NativeBroker.sync(NativeBroker.java:3710)
        at org.exist.storage.BrokerPool.sync(BrokerPool.java:1457)
        at org.exist.storage.BrokerPool._initialize(BrokerPool.java:655)
        at org.exist.storage.BrokerPool.initialize(BrokerPool.java:438)
        at org.exist.storage.BrokerPools.configure(BrokerPools.java:174)
        at org.exist.storage.BrokerPools.configure(BrokerPools.java:109)
        at org.exist.jetty.JettyStart.run(JettyStart.java:205)
        at org.exist.jetty.JettyStart.main(JettyStart.java:95)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.exist.start.Main.invokeMain(Main.java:118)
        at org.exist.start.Main.runEx(Main.java:248)
        at org.exist.start.Main.run(Main.java:123)
        at org.exist.start.Main.main(Main.java:60)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.executeMain(AppassemblerBooter.java:257)
        at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.main(AppassemblerBooter.java:77)
13 Jan 2020 12:55:24,880 [main] INFO  (JettyStart.java [run]:224) - [loading jetty configuration : C:\exist-db\exist-db.5.1.1\db\etc\jetty\jetty.xml]
```

There are then other errors written:
```
13 Jan 2020 12:55:26,589 [main] INFO  (JettyStart.java [run]:318) - -----------------------------------------------------
org.exist.storage.btree.DBException: Error while writing C:\exist-db\exist-db.5.1.1\data\stats.dbx: C:\exist-db\exist-db.5.1.1\data\stats.dbx
        at org.exist.storage.statistics.IndexStatistics.sync(IndexStatistics.java:114)
        at org.exist.indexing.IndexManager.sync(IndexManager.java:264)
        at org.exist.storage.NativeBroker.sync(NativeBroker.java:3710)
        at org.exist.storage.BrokerPool.sync(BrokerPool.java:1457)
        at org.exist.storage.sync.SyncTask.execute(SyncTask.java:95)
        at org.exist.storage.SystemTaskManager.runSystemTask(SystemTaskManager.java:103)
        at org.exist.storage.SystemTaskManager.processTasks(SystemTaskManager.java:88)
        at org.exist.storage.txn.TransactionManager.processSystemTasks(TransactionManager.java:570)
        at org.exist.storage.txn.TransactionManager.triggerSystemTask(TransactionManager.java:547)
        at org.exist.storage.BrokerPool.triggerSystemTask(BrokerPool.java:1554)
        at org.exist.scheduler.impl.SystemTaskJobImpl.execute(SystemTaskJobImpl.java:113)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
org.exist.storage.btree.DBException: Error while writing C:\exist-db\exist-db.5.1.1\data\stats.dbx: C:\exist-db\exist-db.5.1.1\data\stats.dbx
        at org.exist.storage.statistics.IndexStatistics.sync(IndexStatistics.java:114)
        at org.exist.indexing.IndexManager.sync(IndexManager.java:264)
        at org.exist.storage.NativeBroker.sync(NativeBroker.java:3710)
        at org.exist.storage.BrokerPool.sync(BrokerPool.java:1457)
        at org.exist.storage.sync.SyncTask.execute(SyncTask.java:95)
        at org.exist.storage.SystemTaskManager.runSystemTask(SystemTaskManager.java:103)
        at org.exist.storage.SystemTaskManager.processTasks(SystemTaskManager.java:88)
        at org.exist.storage.txn.TransactionManager.processSystemTasks(TransactionManager.java:570)
        at org.exist.storage.txn.TransactionManager.triggerSystemTask(TransactionManager.java:547)
        at org.exist.storage.BrokerPool.triggerSystemTask(BrokerPool.java:1554)
        at org.exist.scheduler.impl.SystemTaskJobImpl.execute(SystemTaskJobImpl.java:113)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
org.exist.storage.btree.DBException: Error while writing C:\exist-db\exist-db.5.1.1\data\stats.dbx: C:\exist-db\exist-db.5.1.1\data\stats.dbx
        at org.exist.storage.statistics.IndexStatistics.sync(IndexStatistics.java:114)
        at org.exist.indexing.IndexManager.sync(IndexManager.java:264)
        at org.exist.storage.NativeBroker.sync(NativeBroker.java:3710)
        at org.exist.storage.BrokerPool.sync(BrokerPool.java:1457)
        at org.exist.storage.sync.SyncTask.execute(SyncTask.java:95)
        at org.exist.storage.SystemTaskManager.runSystemTask(SystemTaskManager.java:103)
        at org.exist.storage.SystemTaskManager.processTasks(SystemTaskManager.java:88)
        at org.exist.storage.txn.TransactionManager.processSystemTasks(TransactionManager.java:570)
        at org.exist.storage.txn.TransactionManager.triggerSystemTask(TransactionManager.java:547)
        at org.exist.storage.BrokerPool.triggerSystemTask(BrokerPool.java:1554)
        at org.exist.scheduler.impl.SystemTaskJobImpl.execute(SystemTaskJobImpl.java:113)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
org.exist.storage.btree.DBException: Error while writing C:\exist-db\exist-db.5.1.1\data\stats.dbx: C:\exist-db\exist-db.5.1.1\data\stats.dbx
        at org.exist.storage.statistics.IndexStatistics.sync(IndexStatistics.java:114)
        at org.exist.indexing.IndexManager.sync(IndexManager.java:264)
        at org.exist.storage.NativeBroker.sync(NativeBroker.java:3710)
        at org.exist.storage.BrokerPool.sync(BrokerPool.java:1457)
        at org.exist.storage.sync.SyncTask.execute(SyncTask.java:95)
        at org.exist.storage.SystemTaskManager.runSystemTask(SystemTaskManager.java:103)
        at org.exist.storage.SystemTaskManager.processTasks(SystemTaskManager.java:88)
        at org.exist.storage.txn.TransactionManager.processSystemTasks(TransactionManager.java:570)
        at org.exist.storage.txn.TransactionManager.triggerSystemTask(TransactionManager.java:547)
        at org.exist.storage.BrokerPool.triggerSystemTask(BrokerPool.java:1554)
        at org.exist.scheduler.impl.SystemTaskJobImpl.execute(SystemTaskJobImpl.java:113)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

**Expected behavior**
I would expect a stats.dbx file to be written

**To Reproduce**
uncomment the line 553 in conf.xml
```xml
<module id="index-stats" file="stats.dbx" class="org.exist.storage.statistics.IndexStatistics" />
```

Then start the database by running bin\startup.bat as administrator and look at the output

**Context (please always complete the following information):**
 - OS: Windows 10 - 64 bit
 - eXist-db version: 5.1.1
 - Java Version Azul 11

**Additional context**
- How is eXist-db installed? jar installer
- Any custom changes in e.g. `conf.xml`?
uncomment the line for the stats.dbx

**Comment by duncdrum** [comment]
Does this happen on a fresh install of exist, or is this after restoration of a backup?
