### ISSUE TITLE
Build failure when building the package with Maven

### ISSUE THREAD

**Issue by lguariento** [eXist-db/exist#3225]
I get this error:

```
WARNING: Error injecting: org.apache.maven.plugin.surefire.SurefirePlugin
com.google.inject.ProvisionException: Guice provision errors:

1) No implementation for org.codehaus.plexus.languages.java.jpms.LocationManager was bound.
  while locating org.apache.maven.plugin.surefire.SurefirePlugin

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1006)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1032)
	at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:45)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:55)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
	at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:138)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:47)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:997)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1047)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:993)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
	at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:253)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:245)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:455)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] eXist-db Parent ................................... SUCCESS [37.027s]
[INFO] eXist-db Startup .................................. FAILURE [1:34.939s]
[INFO] eXist-db Jetty Configuration ...................... SKIPPED
[INFO] eXist-db Data Samples ............................. SKIPPED
[INFO] eXist-db Core ..................................... SKIPPED
[INFO] eXist-db Ant Tasks ................................ SKIPPED
[INFO] eXist-db Core JCStress Tests ...................... SKIPPED
[INFO] eXist-db Core JMH benchmarks ...................... SKIPPED
[INFO] eXist-db Service .................................. SKIPPED
[INFO] eXist-db Content Extraction Extension ............. SKIPPED
[INFO] eXist-db EXIF Tool Extension ...................... SKIPPED
[INFO] eXist-db EXPath Extensions ........................ SKIPPED
[INFO] eXist-db EXQuery Request Module ................... SKIPPED
[INFO] eXist-db RESTXQ Extension ......................... SKIPPED
[INFO] eXist-db WebDAV Extension ......................... SKIPPED
[INFO] eXist-db xqDoc Extension .......................... SKIPPED
[INFO] eXist-db Lucene Index ............................. SKIPPED
[INFO] eXist-db NGram Index .............................. SKIPPED
[INFO] eXist-db Lucene Range Index ....................... SKIPPED
[INFO] eXist-db Sort Index ............................... SKIPPED
[INFO] eXist-db Spatial Index ............................ SKIPPED
[INFO] eXist-db Cache Module ............................. SKIPPED
[INFO] eXist-db Compression Module ....................... SKIPPED
[INFO] eXist-db Counter Module ........................... SKIPPED
[INFO] eXist-db CQL Parser Module ........................ SKIPPED
[INFO] eXist-db EXPath Repository Module ................. SKIPPED
[INFO] eXist-db File Module .............................. SKIPPED
[INFO] eXist-db Image Module ............................. SKIPPED
[INFO] eXist-db JNDI Module .............................. SKIPPED
[INFO] eXist-db Email Module ............................. SKIPPED
[INFO] eXist-db Persistent Login Module .................. SKIPPED
[INFO] eXist-db Process Module ........................... SKIPPED
[INFO] eXist-db Scheduler Module ......................... SKIPPED
[INFO] eXist-db SimpleQL Module .......................... SKIPPED
[INFO] eXist-db SQL Module ............................... SKIPPED
[INFO] eXist-db XML Diff Module .......................... SKIPPED
[INFO] eXist-db XSL:FO Module ............................ SKIPPED
[INFO] eXist-db LDAP Security Module ..................... SKIPPED
[INFO] eXist-db Active Directory Security Module ......... SKIPPED
[INFO] eXist-db IP Range Security Module ................. SKIPPED
[INFO] eXist-db Distributions ............................ SKIPPED
[INFO] eXist-db IzPack Installer ......................... SKIPPED
[INFO] eXist-db EXQuery Extension Modules ................ SKIPPED
[INFO] eXist-db EXQuery Extensions ....................... SKIPPED
[INFO] eXist-db Index Extensions ......................... SKIPPED
[INFO] eXist-db Example Module ........................... SKIPPED
[INFO] eXist-db EXI Module ............................... SKIPPED
[INFO] eXist-db Extension XQuery Modules ................. SKIPPED
[INFO] eXist-db Extension Security Modules ............... SKIPPED
[INFO] eXist-db Extensions ............................... SKIPPED
[INFO] eXist-db .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6:01.566s
[INFO] Finished at: Thu Jan 23 17:16:21 GMT 2020
[INFO] Final Memory: 30M/115M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-test) on project exist-start: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test failed: Unable to load the mojo 'test' (or one of its required components) from the plugin 'org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4': com.google.inject.ProvisionException: Guice provision errors:
[ERROR] 
[ERROR] 1) No implementation for org.codehaus.plexus.languages.java.jpms.LocationManager was bound.
[ERROR] while locating org.apache.maven.plugin.surefire.SurefirePlugin
[ERROR] at ClassRealm[plugin>org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4, parent: sun.misc.Launcher$AppClassLoader@7852e922]
[ERROR] while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test)
[ERROR] 
[ERROR] 1 error
[ERROR] role: org.apache.maven.plugin.Mojo
[ERROR] roleHint: org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :exist-start
```
when executing `mvn -DskipTests package` in an installation from the GitHub code.

CentOS 7-7.1908.0.el7.centos.x86_64
git clone https://github.com/eXist-db/exist.git (version 5.2)
java-1.8.0-openjdk-1.8.0.232.b09-0.el7_7.x86_64
Apache Maven 3.0.5 (Red Hat 3.0.5-17)

**Comment by adamretter** [comment]
@lguariento which version of Maven do you have?

**Comment by lguariento** [comment]
It's in the post, 3.0.5, which is the latest available via yum. I've now uninstalled it and installed version 3.6 from source, and I've restarted the mvn command, I've read that its an issue between Sunfire and Maven 3.0.x. I'll keep you posted if eXist-db compiles successfully now.

**Comment by lguariento** [comment]
Yes, it was apparently the Maven version (we might want to add this information the documentation).

I now get this, though:

`[ERROR] Failed to execute goal com.github.monkeywie:copy-rename-maven-plugin:1.0:rename (rename-jetty-etc-dir-for-appassembler) on project exist-distribution: could not rename /var/www/html/exist/exist-distribution/target/exist-distribution-5.2.0-dir/etc/org/exist/jetty/etc to /var/www/html/exist/exist-distribution/target/exist-distribution-5.2.0-dir/etc/jetty: Failed to delete /var/www/html/exist/exist-distribution/target/exist-distribution-5.2.0-dir/etc/jetty while trying to rename /var/www/html/exist/exist-distribution/target/exist-distribution-5.2.0-dir/etc/org/exist/jetty/etc -> [Help 1]`

Any idea?

**Comment by adamretter** [comment]
Looks like a permissions thing. I would start with a fresh git clone if I was you

**Comment by lguariento** [comment]
I'm using this command as sudo (and that's how I created all the files in the first instance). I'll start afresh and keep you posted.

**Comment by lguariento** [comment]
Yes, all working great, thanks! :)

**Comment by Grosskopferter** [comment]
It seems that this is the root cause of the problem: https://issues.apache.org/jira/browse/SUREFIRE-1628
