### ISSUE TITLE
[BUG] format-number throws IndexOutofBoundsException

### ISSUE THREAD

**Issue by line-o** [eXist-db/exist#3346]
**Describe the bug**

Calling format-number with a certain picture string throws an java.lang.IndexOutOfBoundsException

`format-number($i, "#.###,##")`

**Expected behavior**

Either the appropriate XQuery-error is thrown or the number to be formatted according to the picture string.

**To Reproduce**

```Xquery
xquery version "3.1";

module namespace fd="http://exist-db.org/xquery/test/format-numbers";

declare namespace test="http://exist-db.org/xquery/xqsuite";

declare
    %test:args("12345.6")
    %test:args("#.###,##")
    %test:assertEquals("12.345,6")
function fd:simple-number-1($number as numeric, $picture) {
    format-number($number, $picture)
};
```

**Context (please always complete the following information):**
 - OS: macOS 10.15.4
 - eXist-db version: 5.3.0-SNAPSHOT
 - Java Version Java 1.8.0_152

**Additional context**
- How is eXist-db installed? built from commit: 093c4c0726e02868acadbce9583ec5809f462b33
- Any custom changes in e.g. `conf.xml`? no

**Stack Trace**

```
2020-04-08 14:54:48,995 [qtp1126112943-134] ERROR (XQueryServlet.java [process]:559) - null
java.lang.IndexOutOfBoundsException: null
	at org.exist.util.CodePointString.insert(CodePointString.java:293) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.functions.fn.FnFormatNumbers.format(FnFormatNumbers.java:633) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.functions.fn.FnFormatNumbers.eval(FnFormatNumbers.java:109) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.BasicFunction.eval(BasicFunction.java:74) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:41) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:65) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.ForExpr.processItem(ForExpr.java:251) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.ForExpr.eval(ForExpr.java:189) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.PathExpr.eval(PathExpr.java:280) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.XQuery.execute(XQuery.java:261) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.XQuery.execute(XQuery.java:185) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
...
```

**Comment by adamretter** [comment]
@line-o Shouldn't the result of your test be `12345.6`

**Comment by line-o** [comment]
@adamretter Well, at least it should NOT throw a java exception.
I would expect the above picture string to format the number "ze German" way.
