### ISSUE TITLE
[BUG] Exception with in-scope-prefixes

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#3436]
```xquery
<parameters>{
let $root := <a:b xmlns:a="ans" xmlns:c="cns"/>
     for $prefix in in-scope-prefixes($root)[not(. = ('xml', 'xsi'))]
      return 
          namespace-uri-for-prefix($prefix,$root) ! 
              <param name="{$prefix}" value="{.}"/>
}</parameters>
```

Raises this error:

```
Caused by: java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:752)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:750)
	at org.exist.xquery.functions.fn.FunInScopePrefixes.collectPrefixes(FunInScopePrefixes.java:199)
	at org.exist.xquery.functions.fn.FunInScopePrefixes.eval(FunInScopePrefixes.java:78)
```

When the query is run in eXide, the error is hidden and eXide wrongly returns 0 results. I have reported that separately - https://github.com/eXist-db/eXide/issues/260

To reproduce run the query from the REST API or Java Admin Client.

**Comment by joewiz** [comment]
Besides the error itself, we discovered in https://github.com/eXist-db/eXide/issues/260#issuecomment-636993274 that this error does not contain an error code or description. If possible in the course of the fix of this bug, please consider adding a code or description for this scenario.
