### ISSUE TITLE
Fluent: NPE in Trigger.java (junit)

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#345]
While running the junit/fluents tests, there are stacktraces visible; the tests pass nevertheless. This is the NPE, but there is more.

```
   [junit] 2014-09-29 21:27:14,968 ERROR [org.exist.collections.triggers.Trigger] : 
    [junit]  java.lang.NullPointerException
    [junit] 	at org.exist.dom.ElementImpl.getFirstChild(ElementImpl.java:959)
    [junit] 	at org.exist.config.ProxyNode.getFirstChild(ProxyNode.java:91)
    [junit] 	at org.exist.config.ConfigurationImpl.cache(ConfigurationImpl.java:125)
    [junit] 	at org.exist.config.ConfigurationImpl.getProperty(ConfigurationImpl.java:169)
    [junit] 	at org.exist.config.ConfigurationImpl.equals(ConfigurationImpl.java:463)
    [junit] 	at java.util.concurrent.ConcurrentHashMap.containsValue(ConcurrentHashMap.java:1066)
    [junit] 	at org.exist.config.Configurator.unregister(Configurator.java:1304)
    [junit] 	at org.exist.config.ConfigurationDocumentTrigger.afterDeleteDocument(ConfigurationDocumentTrigger.java:211)
    [junit] 	at org.exist.collections.triggers.DocumentTriggers.afterDeleteDocument(DocumentTriggers.java:326)
    [junit] 	at org.exist.storage.NativeBroker.removeCollection(NativeBroker.java:1546)
    [junit] 	at org.exist.storage.NativeBroker.removeCollection(NativeBroker.java:1417)
    [junit] 	at org.exist.storage.NativeBroker.removeCollection(NativeBroker.java:1417)
    [junit] 	at org.exist.storage.NativeBroker.removeCollection(NativeBroker.java:1417)
    [junit] 	at org.exist.storage.NativeBroker.removeCollection(NativeBroker.java:1417)
    [junit] 	at org.exist.storage.NativeBroker.removeCollection(NativeBroker.java:1417)
    [junit] 	at org.exist.fluent.Folder.delete(Folder.java:929)
    [junit] 	at org.exist.fluent.FolderTest.deleteRoot1(FolderTest.java:328)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:606)
    [junit] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    [junit] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    [junit] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    [junit] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    [junit] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    [junit] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    [junit] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    [junit] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    [junit] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    [junit] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    [junit] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    [junit] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    [junit] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    [junit] 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    [junit] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    [junit] 	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:532)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1165)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1016)
```

**Comment by shabanovd** [comment]
here potential fix for that https://github.com/shabanovd/exist/commit/3aff5bffb0bb83577111588daad0f9c666176658
