### ISSUE TITLE
Feature request: configure saxon to use webapp/WEB-INF/catalog.xml

### ISSUE THREAD

**Issue by wshager** [eXist-db/exist#350]
Currently it's not possible to set the catalog file for Saxon. Please configure it so it uses the same catalog file as eXist does.

**Comment by adamretter** [comment]
@dizzzz If you want to put the catalog resolve in the database, then could you open a different ticket please?

**Comment by adamretter** [comment]
@wshager Can you test out the branch https://github.com/adamretter/exist/tree/saxon-resolvers and let me know if it works for what you need.

**Comment by wshager** [comment]
I get an error when merging the code with current develop:

javax.xml.transform.TransformerFactoryConfigurationError: Class org.exist.validation.resolver.eXistXMLCatalogResolver is not a SAX2 XMLReader or SAXParserFactory
	at net.sf.saxon.Configuration.makeParser(Configuration.java:2904)
	at net.sf.saxon.Configuration.getStyleParser(Configuration.java:2386)
	at net.sf.saxon.style.StylesheetModule.loadStylesheetModule(StylesheetModule.java:126)
	at net.sf.saxon.style.Compilation.compilePackage(Compilation.java:131)
	at net.sf.saxon.style.Compilation.compileSingletonPackage(Compilation.java:94)
	at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:543)
	at net.sf.saxon.jaxp.TemplatesHandlerImpl.getTemplates(TemplatesHandlerImpl.java:104)
	at org.exist.xquery.functions.transform.Transform$CachedStylesheet.getSource(Transform.java:602)
	at org.exist.xquery.functions.transform.Transform$CachedStylesheet.getTemplates(Transform.java:564)
	at org.exist.xquery.functions.transform.Transform$CachedStylesheet.<init>(Transform.java:554)
	at org.exist.xquery.functions.transform.Transform.getSource(Transform.java:514)
	at org.exist.xquery.functions.transform.Transform.createHandler(Transform.java:381)
	at org.exist.xquery.functions.transform.Transform.eval(Transform.java:221)
	at org.exist.xquery.BasicFunction.eval(BasicFunction.java:70)
	at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:56)
	at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:100)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111)
	at org.exist.xquery.UserDefinedFunction.eval(UserDefinedFunction.java:155)
	at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:330)
	at org.exist.xquery.FunctionCall.eval(FunctionCall.java:234)
	at org.exist.xquery.UserDefinedFunction.eval(UserDefinedFunction.java:155)
	at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:330)
	at org.exist.xquery.FunctionCall.eval(FunctionCall.java:234)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:102)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:102)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:102)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:102)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:102)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:102)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:102)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:102)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:102)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:102)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:102)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:102)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:102)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111)
	at org.exist.xquery.UserDefinedFunction.eval(UserDefinedFunction.java:155)
	at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:330)
	at org.exist.xquery.FunctionCall.eval(FunctionCall.java:234)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:267)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.XQuery.execute(XQuery.java:279)
	at org.exist.xquery.XQuery.execute(XQuery.java:199)
	at org.exist.http.urlrewrite.XQueryURLRewrite.runQuery(XQueryURLRewrite.java:699)
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:258)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)

**Comment by dizzzz** [comment]
for sure the resolver class is not an XML parser nor such a factory.

**Comment by wshager** [comment]
@dizzzz is your comment meant for me? If so, what can I do?

**Comment by wshager** [comment]
@adamretter did you check this? It seems rather obvious from http://www.saxonica.com/html/documentation/javadoc/net/sf/saxon/lib/FeatureKeys.html#SOURCE_PARSER_CLASS

**Comment by duncdrum** [comment]
see #41

**Comment by line-o** [comment]
#4328 introduced a new XMLresolver.
Does this affect catalog resolution of Saxon embedded in eXist?
@dizzzz @adamretter
