### ISSUE TITLE
[BUG] missing location info in error from array:put

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#3519]
**Describe the bug**

In eXist, errors involving operations on empty arrays caused by expressions like `array:put([], 1, "foo")` lack location information.

**Expected behavior**

I expected the errors to report the location of the error in the query, as they do in BaseX and Saxon. As shown below, Saxon locates the error best of all.

**To Reproduce**

```xquery
xquery version "3.1";

declare namespace array="http://www.w3.org/2005/xpath-functions/array";

array:put([], 1, "foo")
```

eXist error:

> Index 0 out of bounds for length 0

BaseX error:

> Stopped at /Users/joe/basex/file, 5/10: [FOAY0001] Array has no entries.

Saxon error:

> Requested 0, actual size 0
> 
> Start location: 5:12

**Context (please always complete the following information):**
 - OS: macOS 10.15.6
 - eXist-db version: eXist 5.3.0-SNAPSHOT 2e983c7a95fa4f8bde6b3e5a44fda59326d1de3b 20200816082230
 - Java Version: openjdk version "14.0.2" 2020-07-14 (build 14.0.2+12-46)

**Additional context**
- How is eXist-db installed? 5.3.0-SNAPSHOT built from source 
- Any custom changes in e.g. `conf.xml`? None.

**Comment by dizzzz** [comment]
```
org.xmldb.api.base.XMLDBException: err:FOAY0001 Index of item to insert (1) is out of bounds [at line 5, column 1, source: xquery version "3.1";

declare namespace array="http://www.w3.org/2005/xpath-functions/array";

array:put([], 1, "foo")]
	at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:203)
	at org.exist.xmldb.LocalXPathQueryService.lambda$execute$2(LocalXPathQueryService.java:167)
	at org.exist.xmldb.function.LocalXmldbFunction.apply(LocalXmldbFunction.java:48)
	at org.exist.xmldb.AbstractLocal.withDb(AbstractLocal.java:265)
	at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:166)
	at org.exist.client.QueryDialog$QueryRunnable.run(QueryDialog.java:589)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.exist.xquery.XPathException: err:FOAY0001 Index of item to insert (1) is out of bounds [at line 5, column 1, source: xquery version "3.1";

declare namespace array="http://www.w3.org/2005/xpath-functions/array";

array:put([], 1, "foo")]
	at org.exist.xquery.functions.array.ArrayFunction.eval(ArrayFunction.java:329)
	at org.exist.xquery.BasicFunction.eval(BasicFunction.java:73)
	at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:62)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:279)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.XQuery.execute(XQuery.java:261)
	at org.exist.xquery.XQuery.execute(XQuery.java:185)
	at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:200)
	... 6 more

```

**Comment by dizzzz** [comment]
`err:FOAY0001 Index of item to insert (1) is out of bounds` make sense to me (develop)

**Comment by joewiz** [comment]
@dizzzz I rebuilt with current develop (eXist 5.3.0-SNAPSHOT e92ea8f70512dd6dbb49bc1fc059f64944bee045 20200915110349) and can confirm the issue is no longer present. Great!
