### ISSUE TITLE
[BUG] Java11 compiled code not running in Java8

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#3541]
When eXist-db is compiled with Java11, it does not start with Java8...

```
27 Sep 2020 14:40:27,201 [main] INFO  (JettyStart.java [run]:204) - Configuring eXist from /Users/wessels/Development/GitHub/exist/exist-distribution/target/exist-distribution-5.3.0-SNAPSHOT-dir/etc/conf.xml 
27 Sep 2020 14:40:27,457 [main] ERROR (JettyStart.java [run]:217) - configuration error: java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer; 
org.exist.EXistException: java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:454) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:177) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:112) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.jetty.JettyStart.run(JettyStart.java:209) [exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.jetty.JettyStart.main(JettyStart.java:96) [exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.exist.start.Main.invokeMain(Main.java:152) [exist-start-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.start.Main.runEx(Main.java:282) [exist-start-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.start.Main.run(Main.java:157) [exist-start-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.start.Main.main(Main.java:94) [exist-start-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.executeMain(AppassemblerBooter.java:257) [appassembler-booter-2.1.0.jar:?]
	at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.main(AppassemblerBooter.java:77) [appassembler-booter-2.1.0.jar:?]
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at org.exist.storage.lock.FileLock.save(FileLock.java:240) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.storage.lock.FileLock.tryLock(FileLock.java:158) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.storage.lock.FileLockService.prepare(FileLockService.java:104) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.storage.BrokerPoolServicesManager.prepareServices(BrokerPoolServicesManager.java:170) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:533) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:440) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	... 18 more
org.exist.EXistException: java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:454)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:177)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:112)
	at org.exist.jetty.JettyStart.run(JettyStart.java:209)
	at org.exist.jetty.JettyStart.main(JettyStart.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.exist.start.Main.invokeMain(Main.java:152)
	at org.exist.start.Main.runEx(Main.java:282)
	at org.exist.start.Main.run(Main.java:157)
	at org.exist.start.Main.main(Main.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.executeMain(AppassemblerBooter.java:257)
	at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.main(AppassemblerBooter.java:77)
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at org.exist.storage.lock.  .save(FileLock.java:240)
	at org.exist.storage.lock.FileLock.tryLock(FileLock.java:158)
	at org.exist.storage.lock.FileLockService.prepare(FileLockService.java:104)
	at org.exist.storage.BrokerPoolServicesManager.prepareServices(BrokerPoolServicesManager.java:170)
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:533)
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:440)
	... 18 more
```

It turns out to be a known issue: [link](https://duckduckgo.com/?q=java.lang.NoSuchMethodError:+java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;&t=osx&ia=web).

The problem is in `FileLock.java`:

![image](https://user-images.githubusercontent.com/1700062/94367198-5f34cb80-00dd-11eb-971c-9f4b3b9bfc16.png)

Question: shall we update this code accordingly?

**Comment by adamretter** [comment]
@dizzzz I would not expect code compiled on Java 11 to run on JDK 8. Is this the only fix you would have to make?

**Comment by dizzzz** [comment]
I 'd expect to have this working as we set -source and -target to javac effectively. This issue should not have happened :-)
It looks to me that this is the only change..... but Intellij was blocking me yesterday to investigate further.

**Comment by adamretter** [comment]
@dizzzz On JDK 9+ you also would have to set the flag `-release 8`. Perhaps that helps you?

**Comment by dizzzz** [comment]
hmmm no as it requires a reference to the java8 compiler: https://stackoverflow.com/questions/43102787/what-is-the-release-flag-in-the-java-9-compiler#43103038

**Comment by dizzzz** [comment]
Hmm no that does not help, as it needs additional files. I checked the documentation and tried it, no success.
But as the call is used at more locations.... I am not so confident to make modifications here;

<img width="515" alt="image" src="https://user-images.githubusercontent.com/1700062/95656625-e8052b80-0b0f-11eb-83ba-f328ae85bdfb.png">

<img width="568" alt="image" src="https://user-images.githubusercontent.com/1700062/95656660-1be05100-0b10-11eb-88fd-e69a8b36dbbb.png">

**Comment by dizzzz** [comment]
i will just force compilation with Java8 on command line (JAVA_HOME);
