### ISSUE TITLE
[BUG] Compression module fails with empty files

### ISSUE THREAD

**Issue by gmella** [eXist-db/exist#3565]
**Describe the bug**
Zipping a sequence of entries with an empty file does not end and push eXistDB to out of memory.

**Expected behavior**
I expect to get a zip with every entries even some of them are 0 length.

**To Reproduce**

```Xquery
xquery version "3.1";

let $collection-uri :="/db/"
let $resource-name :="empty"
let $contents :=""

let $empty-file := xmldb:store-as-binary($collection-uri, $resource-name, $contents)

let $xar := compression:zip(<entry type="uri" name="{$collection-uri}">{$collection-uri||$resource-name}</entry>, true())

return count($xar)
```

I discovered that just downloading an app that was previously packaged from a source dir where an empty tmp file was stored.

**Context (please always complete the following information):**
 - OS: docker
 - eXist-db version:  last table release of  4 and 5

**Comment by dizzzz** [comment]
from `exist.log':

```
2020-10-17 17:24:14,627 [qtp655059806-49] ERROR (XQueryServlet.java [process]:558) - Java heap space 
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3181) ~[?:1.8.0_262]
        at java.util.ArrayList.grow(ArrayList.java:267) ~[?:1.8.0_262]
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:241) ~[?:1.8.0_262]
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:233) ~[?:1.8.0_262]
        at java.util.ArrayList.add(ArrayList.java:464) ~[?:1.8.0_262]
        at org.apache.commons.io.output.AbstractByteArrayOutputStream.needNewBuffer(AbstractByteArrayOutputStream.java:107) ~[commons-io-2.8.0.jar:2.8.0]
        at org.apache.commons.io.output.AbstractByteArrayOutputStream.writeImpl(AbstractByteArrayOutputStream.java:197) ~[commons-io-2.8.0.jar:2.8.0]
        at org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.write(UnsynchronizedByteArrayOutputStream.java:71) ~[commons-io-2.8.0.jar:2.8.0]
        at org.exist.xquery.modules.compression.AbstractCompressFunction.compressResource(AbstractCompressFunction.java:409) ~[classes/:?]
        at org.exist.xquery.modules.compression.AbstractCompressFunction.compressFromUri(AbstractCompressFunction.java:196) ~[classes/:?]
        at org.exist.xquery.modules.compression.AbstractCompressFunction.compressElement(AbstractCompressFunction.java:291) ~[classes/:?]
        at org.exist.xquery.modules.compression.AbstractCompressFunction.eval(AbstractCompressFunction.java:132) ~[classes/:?]
        at org.exist.xquery.BasicFunction.eval(BasicFunction.java:73) ~[classes/:?]
        at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:62) ~[classes/:?]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:98) ~[classes/:?]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:110) ~[classes/:?]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:110) ~[classes/:?]
```

**Comment by dizzzz** [comment]
![Uploading image.png…]()

**Comment by dizzzz** [comment]
bugfix in #3566

**Comment by dizzzz** [comment]
Fixed
