### ISSUE TITLE
[BUG] NPE in Backup.java

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#3677]
reported by Alberto.

Point of discussion: should the backup "silently" continue or should we throw an eXist specific exception?

```
java.lang.NullPointerException
        at org.exist.backup.Backup.backup(Backup.java:415)
        at org.exist.backup.Backup.backup(Backup.java:304)
        at org.exist.backup.Backup.backup(Backup.java:278)
        at org.exist.backup.Main.process(Main.java:214)
        at org.exist.backup.Main.main(Main.java:448)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.exist.start.Main.invokeMain(Main.java:118)
        at org.exist.start.Main.runEx(Main.java:248)
        at org.exist.start.Main.run(Main.java:123)
        at org.exist.start.Main.main(Main.java:60)
```

<img width="736" alt="image" src="https://user-images.githubusercontent.com/1700062/102763659-46555280-437a-11eb-9346-28c71eb6ddc4.png">

**Comment by ambs** [comment]
An exception looks nice for me. It could just tell what gone wrong.
In this case, some issue with a strange filename. That file could be printed somehow.
(just my 5 cents)

**Comment by dizzzz** [comment]
PR is there
