### ISSUE TITLE
[BUG] sm:is-account-enabled('unknown_user') leads to NPE

### ISSUE THREAD

**Issue by ahenket** [eXist-db/exist#3688]
**Describe the bug**
I'm trying to find out if a user is active. If a given username does not exist at all you would expect this function to return false():

```xquery
sm:is-account-enabled('administrator')
```

However the result is:

```
java.lang.NullPointerException: null
	at org.exist.xquery.functions.securitymanager.AccountStatusFunction.eval(AccountStatusFunction.java:86) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.xquery.BasicFunction.eval(BasicFunction.java:74) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:41) ~[exist-core-5.2.0.jar:5.2.0]
...
```

**Expected behavior**
Expected was "false()"

**To Reproduce**
```xquery
xquery version "3.1";
sm:is-account-enabled('administrator')
```

**Context (please always complete the following information):**
 - OS: Mac OS Big Sur
 - eXist-db version: 5.2.0
 - java version "14.0.1" 2020-04-14
Java(TM) SE Runtime Environment (build 14.0.1+7)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

**Comment by joewiz** [comment]
I can reproduce the NPE. 

In the meantime, you might see if `sm:user-exists()` performs the desired function.
