### ISSUE TITLE
[BUG] NPE on number( $issue ) eq 1 when $issue is empty-sequence()

### ISSUE THREAD

**Issue by PieterLamers** [eXist-db/exist#3723]
**Describe the bug**
We get an NPE on a value comparison where we would expect a boolean (false) value

**Expected behavior**
We would expect a boolean (false) value

**To Reproduce**

```
let $issue := ()
return number($issue) eq 1
```

**Context (please always complete the following information):**
 - OS: linux,windows
 - eXist-db version: 5.3-SNAPSHOT (20210103202635) 303ca0db511ee93bac1b50ccede357fde9658e7b

n.b. this is not a problem on 4.7.1, or in saxon, where `false()` is returned.

**Comment by joewiz** [comment]
I can confirm the report. When running the query via eXide, the NPE that appears in exist.log is:

```text
2021-02-03 12:26:02,378 [qtp2029364291-73] ERROR (XQueryServlet.java [process]:550) - null 
java.lang.NumberFormatException: null
	at java.math.BigDecimal.<init>(BigDecimal.java:497) ~[?:1.8.0_282]
	at java.math.BigDecimal.<init>(BigDecimal.java:383) ~[?:1.8.0_282]
	at java.math.BigDecimal.<init>(BigDecimal.java:809) ~[?:1.8.0_282]
	at java.math.BigDecimal.valueOf(BigDecimal.java:1277) ~[?:1.8.0_282]
	at org.exist.xquery.value.DoubleValue.lambda$0(DoubleValue.java:133) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.value.NumericValue.compareTo(NumericValue.java:90) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
```

Variants of this appear when running it via REST or Java Admin Client.
