### ISSUE TITLE
Getting URI Encoding, paths, filenames, etc. right

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#3795]
This issue is about more than just URI encoding it is about naming things and defining concepts. This stuff is fundamental.
It will likely also fix a bunch of issues that have been opened about URI encoding and non-ascii character encoding bugs, but it is not a bug report in and of itself.

I will use `xmldb:create-collection` only to demonstrate problems...

Currently:
```xquery
xmldb:create-collection("/db", "hello world")
```

Raises the error:
```java
org.xmldb.api.base.XMLDBException: err:FORG0001 failed to convert adam retter into an XmldbURI: Illegal character in path at index 5: hello world [at line 1, column 1, source: String/2869744519086207067]
```

However, the signature of `xmldb:create-collection` is:
```xquery
xmldb:create-collection($target-collection-uri as xs:string, $new-collection as xs:string) as xs:string?
```

$new-collection is documented as: `The name of the new collection to create`. 

A "Collection" is technically **ONLY** a mapping from an `xs:string` (interpreted as an `xs:anyURI`) to a `item()*`.
https://www.w3.org/TR/xpath-functions-31/#func-collection

TBC---

These concepts in the context of eXist-db need to be properly defined:

* Collection Name
* Document Name
* Path
* File name
* URI as an xs:string
* URI as a xs:anyURI

**Comment by adamretter** [comment]
If we were to transition to Collection Names and Document Names being names, then eXist-db needs some fixes. At the moment it unnecessarily stores just the Collection Name (not the Collection URI) as an XmldbURI.

**Comment by eduarddrenth** [comment]
This may also be related to this issue:
```
#10 1571.6 Caused by: java.net.URISyntaxException: Malformed escape pair at index 5: 80-20%-regeling.xml
#10 1571.6      at java.net.URI$Parser.fail(URI.java:2913) ~[?:?]
#10 1571.6      at java.net.URI$Parser.scanEscape(URI.java:3041) ~[?:?]
#10 1571.6      at java.net.URI$Parser.scan(URI.java:3064) ~[?:?]
#10 1571.6      at java.net.URI$Parser.checkChars(URI.java:3082) ~[?:?]
#10 1571.6      at java.net.URI$Parser.parseHierarchical(URI.java:3166) ~[?:?]
#10 1571.6      at java.net.URI$Parser.parse(URI.java:3125) ~[?:?]
#10 1571.6      at java.net.URI.<init>(URI.java:600) ~[?:?]
#10 1571.6      at org.exist.xmldb.XmldbURI.xmldbUriFor(XmldbURI.java:202) ~[exist-core-6.2.0.jar:6.2.0]
```
