### ISSUE TITLE
[BUG] NPE on empty sequence in predicate

### ISSUE THREAD

**Issue by line-o** [eXist-db/exist#3797]
**Describe the bug**

The following XQuery leads to a NullPointerException `(1)[()]`

**Expected behavior**

If this is an error, an exception with a meaningful error message and location date should be thrown.

**To Reproduce**

evaluate the XQuery snippet above

**Context (please always complete the following information):**
 - eXist-db version: latest develop 4415b13d
 - Java Version recent Adopt Open JDK 8

**Additional context**
- How is eXist-db installed? built from source
- Any custom changes in e.g. `conf.xml`? none

**Comment by joewiz** [comment]
I can confirm the NPE. Running the query in eXide, exist.log reports:

```
2021-04-02 02:23:23,034 [qtp1343729447-2512] ERROR (XQueryServlet.java [process]:550) - null 
java.lang.NullPointerException: null
	at org.exist.xquery.Predicate.evalPredicate(Predicate.java:200) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.FilteredExpression.processPredicate(FilteredExpression.java:153) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.FilteredExpression.eval(FilteredExpression.java:137) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.PathExpr.eval(PathExpr.java:279) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.XQuery.execute(XQuery.java:261) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.XQuery.execute(XQuery.java:185) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.http.servlets.XQueryServlet.process(XQueryServlet.java:486) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        ...
```

**Comment by joewiz** [comment]
More worrying, the test did not affect 4.7.1, 5.1.0, or 5.2.0. I **only** see it in 5.3.0-SNAPSHOT. (Specifically, I'm running eXist 5.3.0-SNAPSHOT 4415b13d1c4809407c64477370ce826f1f3a0f13 20210331024327, under OpenJDK 1.8.0_28 (Liberica) on macOS 11.2.3.

**Comment by joewiz** [comment]
Searching the commit history for [predicate](https://github.com/eXist-db/exist/search?q=predicate&type=commits) and looking for likely candidates, I traced the introduction of the NPE to 2a4816de10623fc3ee728452296bb1e5c4be49a1. The bug is not present in that commit's parent, 5a210d3614a040326a1a06cb182a789a9169b326.

**Comment by line-o** [comment]
@joewiz thanks for the thorough research! That really helps in finding the fix too.

**Comment by line-o** [comment]
In Saxon 10 HE an empty sequence in a predicate will compile and run. 
`(1)[()]` evaluates to an empty sequence.

**Comment by line-o** [comment]
That is much more in line with the behaviour in previous exist versions and will therefore be restored to keep backwards compatibility.

**Comment by line-o** [comment]
BaseX 9.5 also returns an empty sequence
