### ISSUE TITLE
[BUG] Move / rename operations on collections can leave DB in an unusable state

### ISSUE THREAD

**Issue by dariok** [eXist-db/exist#3804]
**Describe the bug**
Sometimes, renaming/moving/deleting a collection seems to fail and leave the DB in an undefined state that may immediately or after a certain time lead to a complete crash.
It seems that some references to the collection are removed but not all. The collection cannot be removed by path, created in its original collection or `cd`ed to.

**Expected behavior**
The collection should be handled properly, not creating an undefined state.

**To Reproduce**
I encountered this several times but could not really put my finger on it. Just now, it happened again though I cannot yet tell which of these steps actually cause the problem.

1. via eXide’s “Manage”, uploaded a directory `gTeX` (actually a git repo) with subdirs `.git` and `w2tei` (a git submodule) to `/db/apps` – upload works smoothly, even for `.git`
2. via eXide’s “Manage”, removed `.git` subcollection – no errors
3. via eXide’s “Manage”, upload 3 XSLT to `w2tei` subcollection – no errors
4. via eXide’s “Manage”, renamed `gTeX` to `googleTex` – an empty dialog was opened
5. via eXide’s “directory”, opened `googleTex` – files are present but `w2tei` subcollection is missing
6. via eXide’s “Manage”, tried to remove `googleTex` entirely – fails
7. via eXide, without errors:
    ```let $collection-uri := "/db/apps/googleTex"
    
    return for $resource in xmldb:get-child-resources($collection-uri)
        return xmldb:remove($collection-uri, $resource)```
8. via eXide: `xmldb:remove("/db/apps/googleTex")` – result `w2tei`
9. via eXide: `xmldb:remove("/db/apps/googleTex/w2tei")` – result: `exerr:ERROR Could not locate collection: /db/apps/googleTex/w2tei`
10. `return xmldb:create-collection("/db/apps/googleTex", "w2tei")` – result: `exerr:ERROR failed to create new collection w2tei: Collection /db/apps/googleTex/w2tei not found` – exist.log:
    ```[qtp1234435772-23] ERROR (XMLDBCreateCollection.java [evalWithCollection]:84) - Unable to create new collection w2tei 
    org.xmldb.api.base.XMLDBException: Collection /db/apps/googleTex/w2tei not found
        at org.exist.xmldb.AbstractLocal.lambda$6(AbstractLocal.java:213) ~[exist-core-5.2.0.jar:5.2.0]
        at org.exist.xmldb.LocalCollection.lambda$25(LocalCollection.java:833) ~[exist-core-5.2.0.jar:5.2.0]
        at org.exist.xmldb.LocalCollection.lambda$0(LocalCollection.java:135) ~[exist-core-5.2.0.jar:5.2.0]
    ```
    [remainder left out for reasons of legibility]
11. Steps 6 to 10 yield the same results after restarting eXist
12. Java Admin Client: `cd "/db/apps/googleTex"` result in error “Failed to invoke method getSubCollectionPermissions in class org.exist.xmlrpc.RpcConnection: java.io.IOException: Could not find collection entry for: /db/apps/googleTex/w2tei“ – trace:
    ```rg.xmldb.api.base.XMLDBException: Failed to invoke method getSubCollectionPermissions in class org.exist.xmlrpc.RpcConnection: java.io.IOException: Could not find collection entry for: /db/apps/googleTex/w2tei
	at org.exist.xmldb.RemoteCollection.execute(RemoteCollection.java:127)
	at org.exist.xmldb.RemoteCollection.getSubCollectionPermissions(RemoteCollection.java:336)
	at org.exist.xmldb.RemoteUserManagementService.getSubCollectionPermissions(RemoteUserManagementService.java:319)
	at org.exist.client.InteractiveClient.getResources(InteractiveClient.java:382)
	at org.exist.client.InteractiveClient.process(InteractiveClient.java:581)
	at org.exist.client.ClientFrame$ProcessRunnable.run(ClientFrame.java:1465)
	at java.base/java.lang.Thread.run(Thread.java:832)
    Caused by: org.apache.xmlrpc.XmlRpcException: Failed to invoke method getSubCollectionPermissions in class org.exist.xmlrpc.RpcConnection: java.io.IOException: Could not find collection entry for: /db/apps/googleTex/w2tei
	at org.apache.xmlrpc.client.XmlRpcStreamTransport.readResponse(XmlRpcStreamTransport.java:197)
	at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:156)
	at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
	at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:158)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:147)
	at org.exist.xmldb.RemoteCollection.execute(RemoteCollection.java:125)
	... 6 more
    ```

In my experience with similar incidents, this will render the DB unusable within the next few days, depending on the number of write operations.

**Context (please always complete the following information):**
For the incident described above
 - OS: Ubuntu 16.04 LTS
 - eXist-db version: 5.2 stable
 - Java Version: 1.8.0_181-b13 (openJDK)

**Additional context**
- How is eXist-db installed?  — JAR installer
- Any custom changes in e.g. `conf.xml`? — none

**Comment by dariok** [comment]
Additional observations:
- renaming `googleTex` to `gTeX` is not possible
- creating a new collection `/db/apps/gTeX` works, as does upload files there
- creating a subcollection `w2tei` in there does not work – no error dialog and nothing in exist.log, though

**Comment by line-o** [comment]
This is very likely a known issue in eXist 5.2.0 and will be fixed in the next release.

duplicate of #3310

**Comment by dariok** [comment]
Not sure whether it is. 
I've just checked exist.log, xmldb.log and xmlrpc.log; neither has any errors logged related to `moveCollection` as in that issue.

The first error in **xmlrpc.log** possibly related to this is
```
2021-04-06 18:47:55,135 [qtp1234435772-22] ERROR (XmlRpcErrorLogger.java [log]:36) - Failed to invoke method getSubCollectionPermissions in class org.exist.xmlrpc.RpcConnection: java.io.IOException: Could not find collection entry for: /db/apps/googleTex/w2tei
org.apache.xmlrpc.common.XmlRpcInvocationException: Failed to invoke method getSubCollectionPermissions in class org.exist.xmlrpc.RpcConnection: java.io.IOException: Could not find collection entry for: /db/apps/googleTex/w2tei
```
(the previous entries are from earlier this afternoon)

---

While checking, I found the first error logged regarding this operation in **exist.log**:
```
2021-04-06 17:29:19,764 [qtp620261614-1184] ERROR (NativeBroker.java [checkCollectionAncestorPermissions]:940) - Parent collection /db/apps/gTeX was null for collection /db/apps/gTeX/w2tei
2021-04-06 17:29:19,767 [qtp620261614-1184] WARN  (TransactionManager.java [close]:409) - Transaction was not committed or aborted, auto aborting!
```

Could it be that moving the parent left the child “dangling”?
It is known that there is supposed to be a subcollection by that name (hence it shows via `get-child-collections`) but it cannot be accessed as the parent collection has already been renamed.

**Comment by dizzzz** [comment]
@dariok do you have the possibility to check with 5.3-develop?

**Comment by dariok** [comment]
@dizzzz Thanks! I’ll see that I can run tests over the weekend.

**Comment by dizzzz** [comment]
@dariok  any success with testing?

**Comment by joewiz** [comment]
@dariok With 5.3.0 out now, have you experienced this again using 5.3.0?

**Comment by dariok** [comment]
I've set up a few instances recently and not had any problems so far. I haven’t repeated these steps, tough; will report back.

**Comment by duncdrum** [comment]
@dariok please reopen of the issue exists on current version.
