### ISSUE TITLE
[BUG] eXist crashes with pageSize>=32768

### ISSUE THREAD

**Issue by sideeffect42** [eXist-db/exist#3938]
**Describe the bug**
eXist fails to start with either

`pageSize=65536`:
```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0
	at org.exist.util.ByteConversion.byteToShort(ByteConversion.java:98)
	at org.exist.storage.btree.Paged$FileHeader.read(Paged.java:720)
	at org.exist.storage.btree.BTree$BTreeFileHeader.read(BTree.java:2678)
	at org.exist.storage.index.BFile$BFileHeader.read(BFile.java:1458)
	at org.exist.storage.btree.Paged$FileHeader.read(Paged.java:714)
	at org.exist.storage.btree.Paged.open(Paged.java:345)
	at org.exist.storage.btree.BTree.open(BTree.java:212)
	at org.exist.storage.index.BFile.<init>(BFile.java:154)
	at org.exist.indexing.ngram.NGramIndex.open(NGramIndex.java:73)
	at org.exist.indexing.IndexManager.initIndex(IndexManager.java:146)
	at org.exist.indexing.IndexManager.prepare(IndexManager.java:119)
	at org.exist.storage.BrokerPoolServicesManager.prepareServices(BrokerPoolServicesManager.java:157)
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:531)
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:438)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:174)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:109)
	at org.exist.jetty.JettyStart.run(JettyStart.java:205)
	at org.exist.jetty.JettyStart.main(JettyStart.java:95)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.exist.start.Main.invokeMain(Main.java:118)
	at org.exist.start.Main.runEx(Main.java:248)
	at org.exist.start.Main.run(Main.java:123)
	at org.exist.start.Main.main(Main.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.executeMain(AppassemblerBooter.java:257)
	at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.main(AppassemblerBooter.java:77)
21 Jun 2021 15:18:58,108 [main] ERROR (JettyStart.java [run]:213) - configuration error: org.exist.storage.BrokerPoolServiceException: org.exist.util.DatabaseConfigurationException: Failed to create index file: /opt/existdb/5.2.0/etc/../data/ngram.dbx: Error opening ngram.dbx: Index 1 out of bounds for length 0
org.exist.EXistException: org.exist.storage.BrokerPoolServiceException: org.exist.util.DatabaseConfigurationException: Failed to create index file: /opt/existdb/5.2.0/etc/../data/ngram.dbx: Error opening ngram.dbx: Index 1 out of bounds for length 0
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:533) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:438) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:174) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:109) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.jetty.JettyStart.run(JettyStart.java:205) [exist-core-5.2.0.jar:5.2.0]
	at org.exist.jetty.JettyStart.main(JettyStart.java:95) [exist-core-5.2.0.jar:5.2.0]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.exist.start.Main.invokeMain(Main.java:118) [exist-start-5.2.0.jar:5.2.0]
	at org.exist.start.Main.runEx(Main.java:248) [exist-start-5.2.0.jar:5.2.0]
	at org.exist.start.Main.run(Main.java:123) [exist-start-5.2.0.jar:5.2.0]
	at org.exist.start.Main.main(Main.java:60) [exist-start-5.2.0.jar:5.2.0]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.executeMain(AppassemblerBooter.java:257) [appassembler-booter-2.1.0.jar:?]
	at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.main(AppassemblerBooter.java:77) [appassembler-booter-2.1.0.jar:?]
Caused by: org.exist.storage.BrokerPoolServiceException: org.exist.util.DatabaseConfigurationException: Failed to create index file: /opt/existdb/5.2.0/etc/../data/ngram.dbx: Error opening ngram.dbx: Index 1 out of bounds for length 0
	at org.exist.indexing.IndexManager.prepare(IndexManager.java:131) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.BrokerPoolServicesManager.prepareServices(BrokerPoolServicesManager.java:157) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:531) ~[exist-core-5.2.0.jar:5.2.0]
	... 19 more
Caused by: org.exist.util.DatabaseConfigurationException: Failed to create index file: /opt/existdb/5.2.0/etc/../data/ngram.dbx: Error opening ngram.dbx: Index 1 out of bounds for length 0
	at org.exist.indexing.ngram.NGramIndex.open(NGramIndex.java:76) ~[exist-index-ngram-5.2.0.jar:5.2.0]
	at org.exist.indexing.IndexManager.initIndex(IndexManager.java:146) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.indexing.IndexManager.prepare(IndexManager.java:119) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.BrokerPoolServicesManager.prepareServices(BrokerPoolServicesManager.java:157) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:531) ~[exist-core-5.2.0.jar:5.2.0]
	... 19 more
org.exist.EXistException: org.exist.storage.BrokerPoolServiceException: org.exist.util.DatabaseConfigurationException: Failed to create index file: /opt/existdb/5.2.0/etc/../data/ngram.dbx: Error opening ngram.dbx: Index 1 out of bounds for length 0
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:533)
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:438)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:174)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:109)
	at org.exist.jetty.JettyStart.run(JettyStart.java:205)
	at org.exist.jetty.JettyStart.main(JettyStart.java:95)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.exist.start.Main.invokeMain(Main.java:118)
	at org.exist.start.Main.runEx(Main.java:248)
	at org.exist.start.Main.run(Main.java:123)
	at org.exist.start.Main.main(Main.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.executeMain(AppassemblerBooter.java:257)
	at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.main(AppassemblerBooter.java:77)
Caused by: org.exist.storage.BrokerPoolServiceException: org.exist.util.DatabaseConfigurationException: Failed to create index file: /opt/existdb/5.2.0/etc/../data/ngram.dbx: Error opening ngram.dbx: Index 1 out of bounds for length 0
	at org.exist.indexing.IndexManager.prepare(IndexManager.java:131)
	at org.exist.storage.BrokerPoolServicesManager.prepareServices(BrokerPoolServicesManager.java:157)
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:531)
	... 19 more
Caused by: org.exist.util.DatabaseConfigurationException: Failed to create index file: /opt/existdb/5.2.0/etc/../data/ngram.dbx: Error opening ngram.dbx: Index 1 out of bounds for length 0
	at org.exist.indexing.ngram.NGramIndex.open(NGramIndex.java:76)
	at org.exist.indexing.IndexManager.initIndex(IndexManager.java:146)
	at org.exist.indexing.IndexManager.prepare(IndexManager.java:119)
	... 21 more
```

or e.g. `pageSize=32768`:
```
org.exist.EXistException: java.lang.NegativeArraySizeException: -32768
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:452) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:174) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:109) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.jetty.JettyStart.run(JettyStart.java:205) [exist-core-5.2.0.jar:5.2.0]
	at org.exist.jetty.JettyStart.main(JettyStart.java:95) [exist-core-5.2.0.jar:5.2.0]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.exist.start.Main.invokeMain(Main.java:118) [exist-start-5.2.0.jar:5.2.0]
	at org.exist.start.Main.runEx(Main.java:248) [exist-start-5.2.0.jar:5.2.0]
	at org.exist.start.Main.run(Main.java:123) [exist-start-5.2.0.jar:5.2.0]
	at org.exist.start.Main.main(Main.java:60) [exist-start-5.2.0.jar:5.2.0]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.executeMain(AppassemblerBooter.java:257) [appassembler-booter-2.1.0.jar:?]
	at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.main(AppassemblerBooter.java:77) [appassembler-booter-2.1.0.jar:?]
Caused by: java.lang.NegativeArraySizeException: -32768
	at org.exist.storage.btree.Paged$FileHeader.<init>(Paged.java:584) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.btree.BTree$BTreeFileHeader.<init>(BTree.java:2673) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.index.BFile$BFileHeader.<init>(BFile.java:1428) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.index.BFile.createFileHeader(BFile.java:294) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.btree.Paged.<init>(Paged.java:143) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.btree.BTree.<init>(BTree.java:165) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.btree.BTree.<init>(BTree.java:187) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.index.BFile.<init>(BFile.java:145) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.indexing.ngram.NGramIndex.open(NGramIndex.java:73) ~[exist-index-ngram-5.2.0.jar:5.2.0]
	at org.exist.indexing.IndexManager.initIndex(IndexManager.java:146) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.indexing.IndexManager.prepare(IndexManager.java:119) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.BrokerPoolServicesManager.prepareServices(BrokerPoolServicesManager.java:157) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:531) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:438) ~[exist-core-5.2.0.jar:5.2.0]
	... 18 more
org.exist.EXistException: java.lang.NegativeArraySizeException: -32768
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:452)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:174)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:109)
	at org.exist.jetty.JettyStart.run(JettyStart.java:205)
	at org.exist.jetty.JettyStart.main(JettyStart.java:95)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.exist.start.Main.invokeMain(Main.java:118)
	at org.exist.start.Main.runEx(Main.java:248)
	at org.exist.start.Main.run(Main.java:123)
	at org.exist.start.Main.main(Main.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.executeMain(AppassemblerBooter.java:257)
	at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.main(AppassemblerBooter.java:77)
Caused by: java.lang.NegativeArraySizeException: -32768
	at org.exist.storage.btree.Paged$FileHeader.<init>(Paged.java:584)
	at org.exist.storage.btree.BTree$BTreeFileHeader.<init>(BTree.java:2673)
	at org.exist.storage.index.BFile$BFileHeader.<init>(BFile.java:1428)
	at org.exist.storage.index.BFile.createFileHeader(BFile.java:294)
	at org.exist.storage.btree.Paged.<init>(Paged.java:143)
	at org.exist.storage.btree.BTree.<init>(BTree.java:165)
	at org.exist.storage.btree.BTree.<init>(BTree.java:187)
	at org.exist.storage.index.BFile.<init>(BFile.java:145)
	at org.exist.indexing.ngram.NGramIndex.open(NGramIndex.java:73)
	at org.exist.indexing.IndexManager.initIndex(IndexManager.java:146)
	at org.exist.indexing.IndexManager.prepare(IndexManager.java:119)
	at org.exist.storage.BrokerPoolServicesManager.prepareServices(BrokerPoolServicesManager.java:157)
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:531)
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:438)
	... 18 more
```

**Expected behavior**
eXist starts up successfully…

**To Reproduce**

Set the `db-connection/@pageSize` XML attribute in `etc/conf.xml` to a value >=32768

**Context (please always complete the following information):**
 - OS: Devuan GNU/Linux 3 (beowulf)
 - eXist-db version: 5.2.0
 - Java Version: OpenJDK 64-Bit Server VM (build 11.0.11+9-post-Debian-1deb10u1, mixed mode)

**Additional context**
- How is eXist-db installed? dist-tarball
- Any custom changes in e.g. `conf.xml`?
  `db-connection/@pageSize` XML attribute as described above.

**Comment by dizzzz** [comment]
I can't see a reason why one wants to use such a large page size (maybe you can elaborate on this?); my change proposal would be to handle the cornercases, either to the default value or the int (?) max ?

**Comment by dizzzz** [comment]
I agree on the better message :-)

I need to remember (@wolfgangmm @adamretter ?) but I think that enlarging the page size will make storing smaller documents inefficient.
