### ISSUE TITLE
[BUG] Restore of backup file stops : parser pool issue

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#4045]
Whilst restoring a full.zip backup file, the restore process halts; stack shows that it might be related to parser pooling;

# how to reproduce
- obtain backup
  - create backup
    - start database
    - fill with applications
    - create backup 
    - stop database
    - clean `data/*` folder
  - or download backup file from https://www.dropbox.com/s/2ou33s0ms8x1vw9/full20210925-1600.zip?raw=1 
- restore database
  - start `client.sh -l` and restore created backup file.
  - restore process stops :-(

# details 
```
"java-admin-client-0.restore" #49 prio=6 os_prio=31 tid=0x00007f9ef9374800 nid=0x1674b waiting on condition [0x0000700003dae000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0d9b738> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at org.apache.commons.pool2.impl.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:1323)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:306)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223)
	at org.exist.util.XMLReaderPool.borrowXMLReader(XMLReaderPool.java:65)
	at org.exist.backup.restore.RestoreHandler.restoreSubCollectionEntry(RestoreHandler.java:424)
	at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:148)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.exist.backup.restore.RestoreHandler.restoreSubCollectionEntry(RestoreHandler.java:432)
	at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:148)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.exist.backup.restore.RestoreHandler.restoreSubCollectionEntry(RestoreHandler.java:432)
	at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:148)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.exist.backup.restore.RestoreHandler.restoreSubCollectionEntry(RestoreHandler.java:432)
	at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:148)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.exist.backup.restore.RestoreHandler.restoreSubCollectionEntry(RestoreHandler.java:432)
	at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:148)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.exist.backup.restore.RestoreHandler.restoreSubCollectionEntry(RestoreHandler.java:432)
	at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:148)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.exist.backup.restore.RestoreHandler.restoreSubCollectionEntry(RestoreHandler.java:432)
	at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:148)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.exist.backup.restore.RestoreHandler.restoreSubCollectionEntry(RestoreHandler.java:432)
	at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:148)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.exist.backup.Restore.restore(Restore.java:97)
	at org.exist.xmldb.LocalRestoreService.lambda$0(LocalRestoreService.java:58)
	at org.exist.xmldb.LocalRestoreService$$Lambda$666/665967369.applyXmldb(Unknown Source)
	at org.exist.xmldb.function.LocalXmldbFunction.apply(LocalXmldbFunction.java:48)
	at org.exist.xmldb.AbstractLocal.withDb(AbstractLocal.java:265)
	at org.exist.xmldb.LocalRestoreService.restore(LocalRestoreService.java:56)
	at org.exist.client.ClientFrame.lambda$39(ClientFrame.java:1130)
	at org.exist.client.ClientFrame$$Lambda$665/665306664.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
```

[stack.txt](https://github.com/eXist-db/exist/files/7229858/stack.txt)

**Comment by dizzzz** [comment]
From the trace I see two routes:
- Be sure that the pool get populated upon request; this does not seem to happenb
- Refactor code so during XML parsing not another parser is instantiated; my guesstimate is that during XML parsing of __ content__.xml another file is being parsed?

**Comment by dizzzz** [comment]
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/1700062/134815645-310516bf-885b-4600-abdc-bd2e4f6636ca.png">

**Comment by dizzzz** [comment]
caching was done..

<img width="821" alt="image" src="https://user-images.githubusercontent.com/1700062/134815861-05f467f2-8c61-4fc2-a3f8-7c39e3468bd6.png">

<img width="1605" alt="image" src="https://user-images.githubusercontent.com/1700062/134815887-4a2eed9b-e68e-4581-afe6-29e6f7ff330a.png">
