### ISSUE TITLE
Variables in library modules are not correctly analyzed

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#4096]
The following query produces a `NullPointerException`.

I have observed that:

1. If you place all the code in an XQuery Main Module, everything works and you do not get an error.
2. If you remove the cross-reference (e.g. remove `$mod1:PUBLICATIONS` from within `$mod1:OPEN_GRAPH` or vice-versa), then everything works and you do not get an error.

As this appears to work in a Main Module but not a Library Module, then the issue seems to be with initialising variables in a Library Module.

Spending some time with the Java debugger reveals that `analyze` is never called on the `map:merge` Java `BasicFunction`, which it should have been. Monkey-patching that fixes the error, but I am not yet sure of the correct fix...

It would be interesting to know if the code below also works on Saxon and BaseX in a library module...

## To Reproduce
Store `/db/mod1.xqm`:
```xquery
module namespace mod1 = "http://mod1";

declare variable $mod1:OPEN_GRAPH as map(xs:string, function(*)) := map {
    "og:title" : function($node, $model) {
		<meta property="og:title" content="{map:get($mod1:PUBLICATIONS, 'some-id')}"/>
    }
};

declare variable $mod1:PUBLICATIONS := map {
	"open-graph" : map:merge((
		$mod1:OPEN_GRAPH,
		map {
			"og:image" : function($node, $model) {
				<meta property="og:image" content="https://some/uri/some/image.png"/>
			}
		}
	))
};
```

Execute:
```xquery
import module namespace mod1 = "http://mod1" at "xmldb:exist:///db/mod1.xqm";

$mod1:PUBLICATIONS("open-graph")
```

## Error Stacktrace:
```java
Caused by: java.lang.NullPointerException
	at org.exist.xquery.AnalyzeContextInfo.<init>(AnalyzeContextInfo.java:69) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.InlineFunction.eval(InlineFunction.java:82) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.functions.map.MapExpr.eval(MapExpr.java:82) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.PathExpr.eval(PathExpr.java:279) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.SequenceConstructor.eval(SequenceConstructor.java:82) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.BasicFunction.eval(BasicFunction.java:61) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:62) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.functions.map.MapExpr.eval(MapExpr.java:82) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.PathExpr.eval(PathExpr.java:279) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.VariableDeclaration.eval(VariableDeclaration.java:146) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.ExternalModuleImpl.resolveVariable(ExternalModuleImpl.java:229) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.ModuleContext.resolveVariable(ModuleContext.java:343) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.VariableReference.getVariable(VariableReference.java:104) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.VariableReference.analyze(VariableReference.java:55) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.Function.analyze(Function.java:413) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.functions.map.MapFunction.analyze(MapFunction.java:157) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.InternalFunctionCall.analyze(InternalFunctionCall.java:105) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.PathExpr.analyze(PathExpr.java:186) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.AttributeConstructor.analyze(AttributeConstructor.java:80) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.ElementConstructor.analyze(ElementConstructor.java:174) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.UserDefinedFunction.analyze(UserDefinedFunction.java:115) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.FunctionCall.analyze(FunctionCall.java:119) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.InlineFunction.eval(InlineFunction.java:82) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.functions.map.MapExpr.eval(MapExpr.java:82) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.PathExpr.eval(PathExpr.java:279) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.VariableDeclaration.eval(VariableDeclaration.java:146) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.ExternalModuleImpl.resolveVariable(ExternalModuleImpl.java:229) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.ModuleContext.resolveVariable(ModuleContext.java:343) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.VariableReference.getVariable(VariableReference.java:104) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.VariableReference.analyze(VariableReference.java:55) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.PathExpr.analyze(PathExpr.java:186) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.SequenceConstructor.analyze(SequenceConstructor.java:52) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.Function.analyze(Function.java:413) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.functions.map.MapFunction.analyze(MapFunction.java:157) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.InternalFunctionCall.analyze(InternalFunctionCall.java:105) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.functions.map.MapExpr.analyze(MapExpr.java:62) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.PathExpr.analyze(PathExpr.java:186) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.VariableDeclaration.analyzeExpression(VariableDeclaration.java:123) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.VariableDeclaration.analyze(VariableDeclaration.java:92) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.PathExpr.analyze(PathExpr.java:186) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.XQueryContext.analyzeAndOptimizeIfModulesChanged(XQueryContext.java:1589) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.XQueryContext.analyzeAndOptimizeIfModulesChanged(XQueryContext.java:1585) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.XQuery.compile(XQuery.java:247) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.XQuery.compile(XQuery.java:175) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xquery.XQuery.compile(XQuery.java:133) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xmlrpc.RpcConnection.compile(RpcConnection.java:354) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xmlrpc.RpcConnection.lambda$127(RpcConnection.java:3833) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xmlrpc.RpcConnection.lambda$51(RpcConnection.java:1704) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xmlrpc.function.XmlRpcFunction.apply(XmlRpcFunction.java:47) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xmlrpc.RpcConnection.withDb(RpcConnection.java:4081) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xmlrpc.RpcConnection.withDb(RpcConnection.java:4065) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xmlrpc.RpcConnection.compile(RpcConnection.java:1701) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at org.exist.xmlrpc.RpcConnection.compile(RpcConnection.java:3584) ~[exist-core-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:115) ~[xmlrpc-server-3.1.3.jar:3.1.3]
	... 71 more
```

## Context
 - OS: `macOS 12.0.1`
 - eXist-db version: `5.4.0-SNAPSHOT` (similar issue occurs on `5.3.0`)
 - Java Version `1.8.0_292-b10`

This was discovered when modifying hsg-shell (CC @joewiz @yamahito)

----
The monkey patch to hack the issue:
```diff
diff --git a/exist-core/src/main/java/org/exist/xquery/ExternalModuleImpl.java b/exist-core/src/main/java/org/exist/xquery/ExternalModuleImpl.java
index 11d123006f..4841d22d54 100644
--- a/exist-core/src/main/java/org/exist/xquery/ExternalModuleImpl.java
+++ b/exist-core/src/main/java/org/exist/xquery/ExternalModuleImpl.java
@@ -222,7 +222,11 @@ public class ExternalModuleImpl implements ExternalModule {
         final VariableDeclaration decl = mGlobalVariables.get(qname);
         Variable var = mStaticVariables.get(qname);
         if (isReady && decl != null && (var == null || var.getValue() == null)) {
-            decl.eval(getContext().getContextItem());
+
+            //decl.analyze(context);
+            //decl.analyzeExpression(new AnalyzeContextInfo());
+
+            decl.eval(getContext().getContextItem());  //TODO(AR) analyze has not been called!
             var = mStaticVariables.get(qname);
         }
         if (var == null) {
```

**Comment by duncdrum** [comment]
`"og:image" : function($node, $model)` should be `"og:image": function($node, $model)`

`at "xmldb:exist:///db/config.xqm"` should be `at "xmldb:exist:///db/mod1.xqm"`

but yeah no joy 

```
30 Nov 2021 08:58:21,911 [qtp260620222-43] ERROR (XQueryServlet.java [process]:549) - null java.lang.NullPointerException: null
```

**Comment by adamretter** [comment]
> `"og:image" : function($node, $model)` should be `"og:image": function($node, $model)`

Is the only change the formatting? If so either is perfectly valid.

**Comment by duncdrum** [comment]
xquery key value pairs should not be separated with two whitespaces `key : value` but with one `key: value` to avoid namespace separator confusion. We've been bitten by that in the past, so I figured we eliminate it from the equation

**Comment by adamretter** [comment]
>with two whitespaces key : value but with one key: value to avoid namespace separator confusion. We've been bitten by that in the past

Do you mean as a Human reading the code?

The parser has no issue.
Also "key":"value" is not a valid prefix reference anyway, it would have to be without the quotes... no?

**Comment by duncdrum** [comment]
https://www.w3.org/TR/xquery-31/#id-map-constructors 

> Changing the expression to map{a :b} or map{a: b} will prevent this, resulting in the intended parse.

we had stuff break with `key : value` in the past, certainly `key:value` is addressed in the specs

**Comment by yamahito** [comment]
I think it's only an issue if either the key or the value is a qualified name, rather than a string, but it sounds like it's not the worst habit to adopt.
