### ISSUE TITLE
[BUG] NPE in Lucene

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#4128]
**Describe the bug**
When searching in de documentation app, there is a NullPointerException:

`https://hostname/exist/apps/doc/search.html?q=systemd`

![image](https://user-images.githubusercontent.com/1700062/146350919-2f9d2926-2544-461a-9a6c-798a4488df72.png)

in exist.log

```
Caused by: java.lang.NullPointerException
        at org.exist.indexing.lucene.LuceneMatchListener.scanMatches(LuceneMatchListener.java:223) ~[exist-index-lucene-5.3.1.jar:5.3.1]
        at org.exist.indexing.lucene.LuceneMatchListener.startElement(LuceneMatchListener.java:133) ~[exist-index-lucene-5.3.1.jar:5.3.1]
        at org.exist.storage.serializers.NativeSerializer.serializeToReceiver(NativeSerializer.java:270) ~[exist-core-5.3.1.jar:5.3.1]
        at org.exist.storage.serializers.NativeSerializer.serializeToReceiver(NativeSerializer.java:98) ~[exist-core-5.3.1.jar:5.3.1]
        at org.exist.storage.serializers.Serializer.serializeToReceiver(Serializer.java:1078) ~[exist-core-5.3.1.jar:5.3.1]
        at org.exist.storage.serializers.Serializer.toSAX(Serializer.java:883) ~[exist-core-5.3.1.jar:5.3.1]
        at org.exist.dom.persistent.NodeProxy.toSAX(NodeProxy.java:701) ~[exist-core-5.3.1.jar:5.3.1]
        at org.exist.xquery.functions.util.Expand.eval(Expand.java:112) ~[exist-core-5.3.1.jar:5.3.1]
        at org.exist.xquery.BasicFunction.eval(BasicFunction.java:73) ~[exist-core-5.3.1.jar:5.3.1]
```

**Expected behavior**
Search results to be visible.

**To Reproduce**
- upgrade from 4.1(backup-restore), correct doc.xar file is installed
- run https://localhost/exist/apps/doc/search.html?q=systemd

**Screenshots**
![image](https://user-images.githubusercontent.com/1700062/146350919-2f9d2926-2544-461a-9a6c-798a4488df72.png)

**Context (please always complete the following information):**
 - OS: [e.g. macOS 10.14.6] ; RHEL 6
 - eXist-db version: [e.g. 5.1.1] : 5.3.1
 - Java Version [e.g. Java8u121] : 1.8.0_171 

**Additional context**
- How is eXist-db installed? tar.bz
- Any custom changes in e.g. `conf.xml`? - no

**Comment by joewiz** [comment]
Installing a fresh copy of eXist 5.3.1 on macOS 12.1 with OpenJDK 1.8.0_312 (liberica-jdk8-full), when I open http://localhost:8080/exist/apps/doc/search.html?q=systemd, I see the expected results and am not able to reproduce an NPE.

> <img width="1203" alt="Screen Shot 2021-12-16 at 1 54 24 PM" src="https://user-images.githubusercontent.com/59118/146431605-bd86d568-5cc0-4f68-b711-9ab0147ab5ac.png">

Could it be that there is an issue with running a restored version of the 4.1-era documentation app in eXist 5.3.1?
