### ISSUE TITLE
Failed to write commit record to journal: Journal can only support 32767 log files

### ISSUE THREAD

**Issue by nsincaglia** [eXist-db/exist#4189]
**Describe the bug**
My eXist-db v5.2.0 instance was running for a fairly long time without being rebooted. One day I started to receive the following error:
```
2022-01-14 16:31:24,410 [main] ERROR (JettyStart.java [run]:213) - configuration error: Failed to write commit record to journal: Journal can only support 32767 log files 
org.exist.storage.txn.TransactionException: Failed to write commit record to journal: Journal can only support 32767 log files
	at org.exist.storage.txn.TransactionManager.doCommitTransaction(TransactionManager.java:301) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.txn.TransactionManager.commit(TransactionManager.java:276) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.txn.Txn.commit(Txn.java:138) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:605) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:438) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:174) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:109) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.jetty.JettyStart.run(JettyStart.java:205) [exist-core-5.2.0.jar:5.2.0]
	at org.exist.jetty.JettyStart.main(JettyStart.java:95) [exist-core-5.2.0.jar:5.2.0]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.exist.start.Main.invokeMain(Main.java:118) [exist-start-5.2.0.jar:5.2.0]
	at org.exist.start.Main.runEx(Main.java:248) [exist-start-5.2.0.jar:5.2.0]
	at org.exist.start.Main.run(Main.java:123) [exist-start-5.2.0.jar:5.2.0]
	at org.exist.start.Main.main(Main.java:60) [exist-start-5.2.0.jar:5.2.0]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.executeMain(AppassemblerBooter.java:257) [appassembler-booter-2.1.0.jar:?]
	at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.main(AppassemblerBooter.java:77) [appassembler-booter-2.1.0.jar:?]
Caused by: org.exist.storage.journal.JournalException: Journal can only support 32767 log files
	at org.exist.storage.journal.Journal.writeToLog(Journal.java:342) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.journal.JournalManager.journalGroup(JournalManager.java:106) ~[exist-core-5.2.0.jar:5.2.0]
	at org.exist.storage.txn.TransactionManager.doCommitTransaction(TransactionManager.java:299) ~[exist-core-5.2.0.jar:5.2.0]
	... 22 more
```
I currently have a log in $EXIST_HOME/data which is called 0000008001.log

The server parses this file using the code:
```java
Short fileNum = Integer.parseInt(0000008001, 16)
```
So `0000008001` in Base16 is `32769` which is greater than the permitted maximum of `32767`

I think there are two questions in my mind here:
1). Why is it using Base16 for this instead of Base10?!? - is that a bug?
2). Does it correctly support wrap-around once it reaches 32767? or is that also a bug?

**Comment by adamretter** [comment]
Hi @nsincaglia to have worked through 32,767 log files of between 1MB and 100MB each means, writes of between 32GB and 3 TB of log data.
Out of interest, has this server been online for quite some time, or experiencing a heavy write load?

----
I have some improvements here - https://github.com/evolvedbinary/exist/tree/hotfix/journal-rotation

> Why is it using Base16 for this instead of Base10?!? - is that a bug?

Actually, on further review that looks fine. For whatever reason (that was decided in the past) the number of the log file is encoded in hexadecimal in the name of the log file. It is also correctly decoded from hexadecimal.

> Does it correctly support wrap-around once it reaches 32767? or is that also a bug?

It did not support wrap-around, and so it was possible to run out of log file numbers one you got to 32767. This is fixed in my branch linked above.

**Comment by nsincaglia** [comment]
Adam,This server has been online for a a reasonably long time. I can't say when the last time I restarted that system. The write load is probably higher than average but not extremely high.NickNick Sincaglia President/FounderNueMeta, LLCDigital Media & TechnologyPhone: ***@***.*** http://www.nuemeta.comSkype: nsincaglia
-------- Original message --------From: Adam Retter ***@***.***> Date: 1/16/22  6:40 PM  (GMT-06:00) To: eXist-db/exist ***@***.***> Cc: nsincaglia ***@***.***>, Mention ***@***.***> Subject: Re: [eXist-db/exist] Failed to write commit record to journal:
  Journal can only support 32767 log files (Issue #4189) 
Hi @nsincaglia to have worked through 32,767 log files of between 1MB and 100MB each means, writes of between 32GB and 3 TB of log data.
Out of interest, has this server been online for quite some time, or experiencing a heavy write load?

I have some improvements here - https://github.com/evolvedbinary/exist/tree/hotfix/journal-rotation

Why is it using Base16 for this instead of Base10?!? - is that a bug?

Actually, on further review that looks fine. For whatever reason (that was decided in the past) the number of the log file is encoded in hexadecimal in the name of the log file. It is also correctly decoded from hexadecimal.

Does it correctly support wrap-around once it reaches 32767? or is that also a bug?

It did not support wrap-around, and so it was possible to run out of log file numbers one you got to 32767. This is fixed in my branch linked above.
