### ISSUE TITLE
[BUG] NPE when calling xmldb:size

### ISSUE THREAD

**Issue by line-o** [eXist-db/exist#4218]
**Describe the bug**

Attempting to get the size of a collection using xmld:size results in a null pointer exception.

```xquery
try {
    xmldb:size("/db", "apps")
}
catch * {
    $err:code, $err:description
}
```

**Expected behavior**

Since a collection does not really have a size I expect this to return `0`.

**To Reproduce**

```Xquery
xquery version "3.1";

module namespace t="http://exist-db.org/xquery/test";

declare namespace test="http://exist-db.org/xquery/xqsuite";

declare
    %test:assertEquals(0)
function t:test() {
    xmldb:size("/db", "apps")
};
```

 - eXist-db version: 5.4.0-SNAPSHOT

**Additional context**
- How is eXist-db installed? built from source
- Any custom changes in e.g. `conf.xml`? none

**Comment by line-o** [comment]
Stacktrace
```
2022-01-31 19:32:19,631 [qtp946884592-29] ERROR (XQueryServlet.java [process]:549) - null
java.lang.NullPointerException: null
	at org.exist.xquery.functions.xmldb.XMLDBSize.evalWithCollection(XMLDBSize.java:73) ~[classes/:?]
	at org.exist.xquery.functions.xmldb.XMLDBAbstractCollectionManipulator.eval(XMLDBAbstractCollectionManipulator.java:166) ~[classes/:?]
	at org.exist.xquery.BasicFunction.eval(BasicFunction.java:73) ~[classes/:?]
	at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:62) ~[classes/:?]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[classes/:?]
	at org.exist.xquery.PathExpr.eval(PathExpr.java:279) ~[classes/:?]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[classes/:?]
	at org.exist.xquery.XQuery.execute(XQuery.java:373) ~[classes/:?]
```

**Comment by adamretter** [comment]
The documentation for xmldb:size states:

```
Returns the estimated size of the resource $resource
```

This function is not designed to operate on a Collection. It probably should not throw an NPE or return 0, instead it should probably raise an XQuery Error.

**Comment by line-o** [comment]
exist v7 beta 5 is still affected
