### ISSUE TITLE
[BUG] Java Client becomes confused when changing collection

### ISSUE THREAD

**Issue by paulmer** [eXist-db/exist#4243]
**Describe the bug**
A change somewhere back around eXist 4 (I'm uncertain exactly when) has resulted in the Java Client become confused if a resource editing window is open when navigating to a different collection.  By confused, I mean attempting to perform any operation on the resource window other than closing the window results in an error.  For example, attempting to save a change made to the window throws an exception without saving, as does attempting to execute a script.  This is the case regardless of the Context set in the window.

This bug makes it virtually impossible to simultaneously work on resources stored in different directories at the same time.  (For example, attempting to configure indexes while editing the corresponding data.)

**Expected behavior**
Query Dialog (resource editing window) should continue to work regardless of what collection is displayed in the client window.

**To Reproduce**
1. Create two collections, /db/a and /db/b.  
2. In /db/a, create a new xml resource, 1.xml and open the resource for editing.
3. In the client window navigate to collection /db/b.
4. Attempt to save 1.xml this exception is thrown (eXist-db 6.0.0):

```
org.xmldb.api.base.XMLDBException: 
	at org.exist.xmldb.RemoteCollection.execute(RemoteCollection.java:124)
	at org.exist.xmldb.RemoteCollection.store(RemoteCollection.java:547)
	at org.exist.xmldb.RemoteCollection.storeResource(RemoteCollection.java:510)
	at org.exist.xmldb.RemoteCollection.storeResource(RemoteCollection.java:471)
	at org.exist.client.QueryDialog.saveToDb(QueryDialog.java:149)
	at org.exist.client.QueryDialog.lambda$1(QueryDialog.java:169)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
**Context (please always complete the following information):**
 - OS: Mac, Linux
 - eXist-db version: 6.0.0 and earlier versions.  (Not 2.x, if I recall correctly.)
 - Java Version 8,11,14, 17.

**Additional context**
- How is eXist-db installed?  JAR installer
- Any custom changes in e.g. `conf.xml`? NO

**Comment by duncdrum** [comment]
@reinhapa we should check this with the latest changes, and think about regression test
