### ISSUE TITLE
[BUG] FileLock has insufficient synchronisation

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#4334]
```
Caused by: java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244) ~[?:1.8.0_292]
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:196) ~[?:1.8.0_292]
	at java.nio.ByteBuffer.put(ByteBuffer.java:867) ~[?:1.8.0_292]
	at org.exist.storage.lock.FileLock.save(FileLock.java:241) ~[exist-core-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
	at org.exist.storage.lock.FileLockHeartBeat.execute(FileLockHeartBeat.java:71) ~[exist-core-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
```

and

```
java.nio.BufferOverflowException: null
	at java.nio.Buffer.nextPutIndex(Buffer.java:533) ~[?:1.8.0_292]
	at java.nio.HeapByteBuffer.putLong(HeapByteBuffer.java:438) ~[?:1.8.0_292]
	at org.exist.storage.lock.FileLock.save(FileLock.java:242) ~[exist-core-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
	at org.exist.storage.lock.FileLockHeartBeat.execute(FileLockHeartBeat.java:71) ~[exist-core-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
```

**Comment by duncdrum** [comment]
Without reproduction steps the log excerpts aren't very helpful. 

I don't doubt that there are issues with lock synchronization. But the issue report does little to help us address them.

**Comment by duncdrum** [comment]
Ping @eXist-db/core

**Comment by line-o** [comment]
I agree that the issue report is not sufficient. I would throw this into a prompt and see what falls out :)
