### ISSUE TITLE
jvm remains open when database is shutdown

### ISSUE THREAD

**Issue by meshkin** [eXist-db/exist#435]
hello,
the java process remains open, when i shutdown exist from dashboard "Shutdown" button (or xquery), !! it assigns 200mb to itself!
how can I close java process or close jvm when shutdown db?
thanks all;

**Comment by dizzzz** [comment]
Exist version? Platform/os? Java vendor + version? How do you start Existdb? What is in the logs?=

**Comment by meshkin** [comment]
eXist version : 2.2RC2
Platform/os : windows 7 - 32/64 bits
java:
    java version "1.8.0_25"
    Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
    Java HotSpot(TM) Client VM (build 25.25-b02, mixed mode)
I run startup.bat
I don't see logs; i will report it tomorrow;
thanks for reply.

**Comment by meshkin** [comment]
excuse me for long delay time.
when i run system:shutdown() command in eXide, following lines written in log files:

2015-02-19 16:47:59,344 [eXistThread-30] INFO  (XQueryServlet.java [init]:158) - encoding = UTF-8 
2015-02-19 16:47:59,346 [eXistThread-30] DEBUG (XQueryContext.java [importModule]:2680) - Module http://exist-db.org/xquery/os already present. 
2015-02-19 16:47:59,346 [eXistThread-30] DEBUG (XQuery.java [compile]:175) - Query diagnostics:
system:shutdown() 
2015-02-19 16:47:59,346 [eXistThread-30] DEBUG (XQuery.java [compile]:183) - Compilation took 1 ms 
2015-02-19 16:47:59,346 [eXistThread-30] DEBUG (HttpRequestWrapper.java [<init>]:142) - Retrieved 2 parameters. 
2015-02-19 16:47:59,347 [eXistThread-30] INFO  (Shutdown.java [eval]:105) - Shutting down now. 
2015-02-19 16:47:59,347 [eXistThread-30] INFO  (BrokerPool.java [shutdown]:1890) - Database is shutting down ... 
2015-02-19 16:47:59,347 [eXistThread-30] DEBUG (NotificationService.java [debug]:94) - Registered UpdateListeners: 
2015-02-19 16:47:59,348 [eXistThread-30] DEBUG (ProcessMonitor.java [killAll]:229) - Killing query: system:shutdown() 
2015-02-19 16:47:59,349 [eXistThread-30] INFO  (BrokerPool.java [printSystemInfo]:2103) - SYSTEM INFO
Database instance: exist
-------------------------------------------------------------------
Threads currently waiting for a lock:
=====================================
 
2015-02-19 16:47:59,349 [eXistThread-30] INFO  (BrokerPool.java [shutdown]:1950) - Waiting 120000ms for remaining threads to shut down... 
2015-02-19 16:49:59,367 [eXistThread-30] WARN  (BrokerPool.java [shutdown]:1961) - Not all threads returned. Forcing shutdown ... 
2015-02-19 16:49:59,368 [eXistThread-30] DEBUG (BrokerPool.java [shutdown]:1966) - Calling shutdown ... 
2015-02-19 16:49:59,370 [eXistThread-30] DEBUG (NGramIndex.java [close]:86) - SYNC NGRAM 
2015-02-19 16:49:59,371 [eXistThread-30] DEBUG (NGramIndex.java [sync]:92) - SYNC NGRAM 
2015-02-19 16:49:59,371 [eXistThread-30] INFO  (NativeBroker.java [sync]:3596) - Memory: 368,640K total; 932,352K max; 178,741K free 
2015-02-19 16:49:59,372 [eXistThread-30] INFO  (BTree.java [printStatistics]:2549) - dom.dbx INDEX Buffers occupation : 73% (47 out of 64) Cache efficiency : 99% 
2015-02-19 16:49:59,372 [eXistThread-30] INFO  (DOMFile.java [printStatistics]:1360) - dom.dbx DATA Buffers occupation : 20% (52 out of 256) Cache efficiency : 99% 
2015-02-19 16:49:59,372 [eXistThread-30] INFO  (BTree.java [printStatistics]:2549) - collections.dbx INDEX Buffers occupation : 38% (24 out of 64) Cache efficiency : 89% 
2015-02-19 16:49:59,373 [eXistThread-30] INFO  (BFile.java [printStatistics]:436) - collections.dbx DATA Buffers occupation : 45% (29 out of 64) Cache efficiency : 87% 
2015-02-19 16:49:59,373 [eXistThread-30] INFO  (BTree.java [printStatistics]:2549) - values.dbx INDEX Buffers occupation : 0% (0 out of 64) Cache efficiency : N/A 
2015-02-19 16:49:59,373 [eXistThread-30] INFO  (BFile.java [printStatistics]:436) - values.dbx DATA Buffers occupation : 0% (0 out of 64) Cache efficiency : N/A 
2015-02-19 16:49:59,374 [eXistThread-30] DEBUG (TransactionManager.java [shutdown]:299) - Shutting down transaction manager. Uncommitted transactions: 0 
2015-02-19 16:49:59,374 [eXistThread-30] INFO  (Journal.java [shutdown]:484) - Transaction journal cleanly shutting down with checkpoint... 
2015-02-19 16:49:59,375 [eXistThread-30] INFO  (FileLock.java [release]:189) - Deleting lock file: /usr/local/eXist/webapp/WEB-INF/data/journal.lck 
2015-02-19 16:49:59,402 [eXistThread-30] DEBUG (JMXAgent.java [closeDBInstance]:123) - deregistering JMX MBean: org.exist.management.exist:type=ProcessReport 
2015-02-19 16:49:59,403 [eXistThread-30] DEBUG (JMXAgent.java [closeDBInstance]:123) - deregistering JMX MBean: org.exist.management.exist:type=DiskUsage 
2015-02-19 16:49:59,403 [eXistThread-30] DEBUG (JMXAgent.java [closeDBInstance]:123) - deregistering JMX MBean: org.exist.management.exist.tasks:type=SanityReport 
2015-02-19 16:49:59,404 [eXistThread-30] DEBUG (JMXAgent.java [closeDBInstance]:123) - deregistering JMX MBean: org.exist.management.exist:type=Database 
2015-02-19 16:49:59,404 [eXistThread-30] DEBUG (JMXAgent.java [closeDBInstance]:123) - deregistering JMX MBean: org.exist.management.exist:type=CacheManager.Cache,name=values.dbx,cache-type=BTREE 
2015-02-19 16:49:59,404 [eXistThread-30] DEBUG (JMXAgent.java [closeDBInstance]:123) - deregistering JMX MBean: org.exist.management.exist:type=CacheManager.Cache,name=values.dbx,cache-type=DATA 
2015-02-19 16:49:59,404 [eXistThread-30] DEBUG (JMXAgent.java [closeDBInstance]:123) - deregistering JMX MBean: org.exist.management.exist:type=CacheManager.Cache,name=collections.dbx,cache-type=BTREE 
2015-02-19 16:49:59,405 [eXistThread-30] DEBUG (JMXAgent.java [closeDBInstance]:123) - deregistering JMX MBean: org.exist.management.exist:type=CacheManager.Cache,name=collections.dbx,cache-type=DATA 
2015-02-19 16:49:59,405 [eXistThread-30] DEBUG (JMXAgent.java [closeDBInstance]:123) - deregistering JMX MBean: org.exist.management.exist:type=CacheManager.Cache,name=dom.dbx,cache-type=BTREE 
2015-02-19 16:49:59,405 [eXistThread-30] DEBUG (JMXAgent.java [closeDBInstance]:123) - deregistering JMX MBean: org.exist.management.exist:type=CacheManager.Cache,name=dom.dbx,cache-type=DATA 
2015-02-19 16:49:59,405 [eXistThread-30] DEBUG (JMXAgent.java [closeDBInstance]:123) - deregistering JMX MBean: org.exist.management.exist:type=CacheManager.Cache,name=structure.dbx,cache-type=BTREE 
2015-02-19 16:49:59,406 [eXistThread-30] DEBUG (JMXAgent.java [closeDBInstance]:123) - deregistering JMX MBean: org.exist.management.exist:type=CacheManager.Cache,name=sort.dbx,cache-type=BTREE 
2015-02-19 16:49:59,406 [eXistThread-30] DEBUG (JMXAgent.java [closeDBInstance]:123) - deregistering JMX MBean: org.exist.management.exist:type=CacheManager.Cache,name=ngram.dbx,cache-type=BTREE 
2015-02-19 16:49:59,406 [eXistThread-30] DEBUG (JMXAgent.java [closeDBInstance]:123) - deregistering JMX MBean: org.exist.management.exist:type=CacheManager.Cache,name=ngram.dbx,cache-type=DATA 
2015-02-19 16:49:59,407 [eXistThread-30] DEBUG (JMXAgent.java [closeDBInstance]:123) - deregistering JMX MBean: org.exist.management.exist:type=CollectionCacheManager 
2015-02-19 16:49:59,407 [eXistThread-30] DEBUG (JMXAgent.java [closeDBInstance]:123) - deregistering JMX MBean: org.exist.management.exist:type=CacheManager 
2015-02-19 16:49:59,407 [eXistThread-30] INFO  (FileLock.java [release]:189) - Deleting lock file: /usr/local/eXist/webapp/WEB-INF/data/dbx_dir.lck 
2015-02-19 16:49:59,408 [eXistThread-30] INFO  (BrokerPool.java [shutdown]:2022) - shutdown complete ! 
2015-02-19 16:49:59,408 [eXistThread-30] DEBUG (BrokerPool.java [shutdown]:2028) - removing shutdown hook 
2015-02-19 16:49:59,408 [eXistThread-30] INFO  (JettyStart.java [shutdown]:374) - Database shutdown: stopping server in 1sec ... 
2015-02-19 16:49:59,410 [eXistThread-30] DEBUG (XQuery.java [execute]:300) - Execution took 120,063 ms 
2015-02-19 16:49:59,411 [eXistThread-30] ERROR (XQueryServlet.java [process]:566) -  
java.lang.NullPointerException
	at org.exist.http.servlets.XQueryServlet.process(XQueryServlet.java:493)
	at org.exist.http.servlets.XQueryServlet.doPost(XQueryServlet.java:195)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:457)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.handler.ResourceHandler.handle(ResourceHandler.java:386)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1077)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:229)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:103)
	at org.exist.http.urlrewrite.Forward.doRewrite(Forward.java:50)
	at org.exist.http.urlrewrite.XQueryURLRewrite.doRewrite(XQueryURLRewrite.java:567)
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:355)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1448)
	at de.betterform.agent.web.filter.XFormsFilter.doFilter(XFormsFilter.java:163)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.handler.ResourceHandler.handle(ResourceHandler.java:386)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1077)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:368)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:488)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:943)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1004)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:861)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
2015-02-19 16:50:00,409 [jetty shutdown schedule] INFO  (JettyStart.java [lifeCycleStopping]:426) - Jetty server stopping... 
2015-02-19 16:50:01,557 [jetty shutdown schedule] INFO  (JettyStart.java [lifeCycleStopped]:432) - Jetty server stopped 

the Jetty server stopped completely, but jvm is running and its process not killed!!
this issue there exist in linux too, and not only for windows!
but when press shutdown button in luncher, the jvm and jetty closed completely.
thus, I write a new xquery extenssion module for shutdown and in it write same luncher's shutdown button (hence System.exit(0);), then rebuild eXist-db and use that exuery function for quit db completely and it's working very well.
Is there any idea?

**Comment by rbotto-ids** [comment]
Same problem using exist 2.2 on openSuse 12.3 with Java 1.7.0_51 64 bits.
Exist-db started with startup.sh and tried to shutdown with shutdown.sh
I don't have the Exception on XQueryServlet, the other log is the same.
Temporary I made a change that seems to work, on JettyStart.java, on method shutdown, after server.join, forcing a System.exit(0), but I need confirmation of this change

**Comment by rbotto-ids** [comment]
Thread dump without code change after , JettyStart declare jetty is stopped:

Full thread dump Java HotSpot(TM) 64-Bit Server VM (24.51-b03 mixed mode):

"jetty shutdown schedule" daemon prio=10 tid=0x00007f386c004800 nid=0x139a in Object.wait() [0x00007f3907dfc000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000007c71b82b0> (a java.util.TaskQueue)
	at java.lang.Object.wait(Object.java:503)
	at java.util.TimerThread.mainLoop(Timer.java:526)
	- locked <0x00000007c71b82b0> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"DestroyJavaVM" prio=10 tid=0x00007f3914008000 nid=0x1354 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"org.eclipse.jetty.util.RolloverFileOutputStream" daemon prio=10 tid=0x00007f39150fe000 nid=0x136e in Object.wait() [0x00007f39079f2000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000007c2e3b2a0> (a java.util.TaskQueue)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x00000007c2e3b2a0> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"pool-1-thread-1" prio=10 tid=0x00007f3915043000 nid=0x136d waiting on condition [0x00007f3907af3000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007c16d5890> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1090)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:807)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

"Service Thread" daemon prio=10 tid=0x00007f3914203800 nid=0x1363 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" daemon prio=10 tid=0x00007f3914201000 nid=0x1362 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" daemon prio=10 tid=0x00007f39141fe000 nid=0x1361 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" daemon prio=10 tid=0x00007f39141f4000 nid=0x1360 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" daemon prio=10 tid=0x00007f39141d8800 nid=0x135f in Object.wait() [0x00007f390da0a000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000007c95442a8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
	- locked <0x00000007c95442a8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:189)

"Reference Handler" daemon prio=10 tid=0x00007f39141d4800 nid=0x135e in Object.wait() [0x00007f390db0b000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000007c95dacc8> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:503)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:133)
	- locked <0x00000007c95dacc8> (a java.lang.ref.Reference$Lock)

"VM Thread" prio=10 tid=0x00007f39141d2800 nid=0x135d runnable 

"GC task thread#0 (ParallelGC)" prio=10 tid=0x00007f391401e800 nid=0x1355 runnable 

"GC task thread#1 (ParallelGC)" prio=10 tid=0x00007f3914020800 nid=0x1356 runnable 

"GC task thread#2 (ParallelGC)" prio=10 tid=0x00007f3914022000 nid=0x1357 runnable 

"GC task thread#3 (ParallelGC)" prio=10 tid=0x00007f3914024000 nid=0x1358 runnable 

"GC task thread#4 (ParallelGC)" prio=10 tid=0x00007f3914026000 nid=0x1359 runnable 

"GC task thread#5 (ParallelGC)" prio=10 tid=0x00007f3914027800 nid=0x135a runnable 

"GC task thread#6 (ParallelGC)" prio=10 tid=0x00007f3914029800 nid=0x135b runnable 

"GC task thread#7 (ParallelGC)" prio=10 tid=0x00007f391402b800 nid=0x135c runnable 

"VM Periodic Task Thread" prio=10 tid=0x00007f3914216000 nid=0x1364 waiting on condition 

JNI global references: 223

Heap
 PSYoungGen      total 147456K, used 130508K [0x00000007c0000000, 0x00000007c9c00000, 0x0000000800000000)
  eden space 135168K, 90% used [0x00000007c0000000,0x00000007c77da638,0x00000007c8400000)
  from space 12288K, 63% used [0x00000007c9000000,0x00000007c9798cc8,0x00000007c9c00000)
  to   space 12288K, 0% used [0x00000007c8400000,0x00000007c8400000,0x00000007c9000000)
 ParOldGen       total 87552K, used 21039K [0x0000000740000000, 0x0000000745580000, 0x00000007c0000000)
  object space 87552K, 24% used [0x0000000740000000,0x000000074148bd18,0x0000000745580000)
 PSPermGen       total 33280K, used 33027K [0x000000073ae00000, 0x000000073ce80000, 0x0000000740000000)
  object space 33280K, 99% used [0x000000073ae00000,0x000000073ce40d40,0x000000073ce80000)

**Comment by rbotto-ids** [comment]
Code change is at line 385 of JettyStart.java , on shutdown method of ShutdownListenerImpl, adding System.exit(0), after server.join()

**Comment by dizzzz** [comment]
@adamretter @shabanovd you have been working on the shutdown part, is this fixed in 2.3?

**Comment by adamretter** [comment]
@dizzzz There is still a shutdown issue in HEAD which I occasionally encounter. Seems to occur when Quartz Scheduler tries to shutdown at the same time that a System Task tries to take a broker. As System Tasks are scheduled with Quartz, this implies a concurrency issue in BrokerPool. Probably a good review and audit of that code could find the issue. When it occurs my stack looks like this:

```
2015-02-25 11:21:18
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.31-b07 mixed mode):

"Attach Listener" #47 daemon prio=9 os_prio=31 tid=0x00007fee2b11a000 nid=0x300b waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Thread-29" #46 prio=5 os_prio=31 tid=0x00007fee2b961000 nid=0x5f1f in Object.wait() [0x0000000121b97000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.exist.storage.BrokerPool$StatusReporter.run(BrokerPool.java:2143)
	- locked <0x00000007b6831f98> (a org.exist.storage.BrokerPool$StatusReporter)
	at java.lang.Thread.run(Thread.java:745)

"Thread-25" #42 prio=5 os_prio=31 tid=0x00007fee292d6000 nid=0x6113 waiting for monitor entry [0x0000000123568000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.exist.storage.BrokerPool.release(BrokerPool.java:1676)
	- waiting to lock <0x00000007a0a8b7a0> (a org.exist.storage.BrokerPool)
	at org.exist.protocolhandler.embedded.EmbeddedDownload.stream(EmbeddedDownload.java:159)
	at org.exist.protocolhandler.embedded.EmbeddedDownloadThread.run(EmbeddedDownloadThread.java:96)

"Checkpointer" #20 daemon prio=5 os_prio=31 tid=0x00007fee28ca9800 nid=0x5d03 in Object.wait() [0x0000000122360000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at com.sleepycat.je.utilint.DaemonThread.run(DaemonThread.java:174)
	- locked <0x00000007a0d48f50> (a java.lang.Object)
	at java.lang.Thread.run(Thread.java:745)

"Cleaner-1" #19 daemon prio=5 os_prio=31 tid=0x00007fee28c36800 nid=0x5b03 in Object.wait() [0x000000012225d000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at com.sleepycat.je.utilint.DaemonThread.run(DaemonThread.java:174)
	- locked <0x00000007bdf3e428> (a java.lang.Object)
	at java.lang.Thread.run(Thread.java:745)

"INCompressor" #18 daemon prio=5 os_prio=31 tid=0x00007fee2a3f5800 nid=0x5903 in Object.wait() [0x0000000121d19000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at com.sleepycat.je.utilint.DaemonThread.run(DaemonThread.java:176)
	- locked <0x00000007a0497e98> (a java.lang.Object)
	at java.lang.Thread.run(Thread.java:745)

"Thread-3" #17 prio=5 os_prio=31 tid=0x00007fee29a2b000 nid=0x5703 in Object.wait() [0x000000012154a000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.exist.storage.journal.FileSyncThread.run(FileSyncThread.java:117)
	- locked <0x00000007a0a94070> (a org.exist.storage.journal.FileSyncThread)

"DefaultQuartzScheduler_Worker-4" #13 prio=5 os_prio=31 tid=0x00007fee28bf9000 nid=0x5103 waiting for monitor entry [0x0000000120f41000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.exist.storage.BrokerPool.get(BrokerPool.java:1586)
	- waiting to lock <0x00000007a0a8b7a0> (a org.exist.storage.BrokerPool)
	at org.exist.storage.txn.TransactionManager$RunWithLock.run(TransactionManager.java:397)
	at org.exist.storage.txn.TransactionManager.triggerSystemTask(TransactionManager.java:365)
	at org.exist.storage.BrokerPool.triggerSystemTask(BrokerPool.java:1877)
	at org.exist.scheduler.impl.SystemTaskJobImpl.execute(SystemTaskJobImpl.java:115)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
	- locked <0x00000007a0a96830> (a java.lang.Object)

"Service Thread" #8 daemon prio=9 os_prio=31 tid=0x00007fee2981f000 nid=0x4703 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007fee29813000 nid=0x4503 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007fee2903e800 nid=0x4303 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007fee2904c000 nid=0x4103 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007fee2904b800 nid=0x360b runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007fee28841800 nid=0x2d03 in Object.wait() [0x000000011da04000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:142)
	- locked <0x00000007a0a3a940> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:158)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007fee29030800 nid=0x2b03 in Object.wait() [0x000000011d901000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)
	- locked <0x00000007a0b51f08> (a java.lang.ref.Reference$Lock)

"main" #1 prio=5 os_prio=31 tid=0x00007fee2a000000 nid=0x1303 in Object.wait() [0x000000010b21e000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool.shutdown(SimpleThreadPool.java:371)
	- locked <0x00000007a0a95e40> (a java.lang.Object)
	at org.quartz.core.QuartzScheduler.shutdown(QuartzScheduler.java:740)
	at org.quartz.impl.StdScheduler.shutdown(StdScheduler.java:206)
	at org.exist.scheduler.impl.QuartzSchedulerImpl.shutdown(QuartzSchedulerImpl.java:165)
	at org.exist.storage.BrokerPool.shutdown(BrokerPool.java:1935)
	- locked <0x00000007a0a8b7a0> (a org.exist.storage.BrokerPool)
	at org.exist.storage.BrokerPool.stopAll(BrokerPool.java:390)
	at org.exist.validation.ValidationFunctions_DTD_Test.shutdown(ValidationFunctions_DTD_Test.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:532)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1179)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1030)
```

You can see here that several threads are all blocked.

**Comment by shabanovd** [comment]
solution for that issue very simple: shutdown schedule before start-up shutdown sequence (or it can be called 'first step of it')

**Comment by adamretter** [comment]
@shabanovd I don't think that solves the issue... as the scheduler may already be running System Tasks when you request it to shutdown, it will wait for those system tasks to complete. However, those system tasks may be attempting to take brokers, of which there are none available and we wait. I think that is exactly what we already see here.

**Comment by shabanovd** [comment]
until `scheduler.shutdown(true);` 

http://quartz-scheduler.org/documentation/quartz-2.x/cookbook/ShutdownScheduler

**Comment by adamretter** [comment]
@shabanovd yeah we already do that.

**Comment by shabanovd** [comment]
with small note: it under `synchronized(this) {`. I said it must be outside it, before `processMonitor.stopRunningJobs();`. That small detail make big difference.

**Comment by shabanovd** [comment]
message at code quite clear, no?

> wait for currently running system tasks before we shutdown
> they will have a lock on the transactionManager

that looking must be after `scheduler.shutdown(true);`

**Comment by rbotto-ids** [comment]
The discussion here goes to a more complex problem. The case I noticed is that exist shutdowns correctly (no locks on database), jetty shutdowns correctly (no ports used by the process), but Java Process is still running, consuming process, system memory and some open files. 
In a system with many startups, we can arrive to user limits for processes or open files.

**Comment by adamretter** [comment]
Possibly related to https://github.com/eXist-db/exist/issues/464

**Comment by dizzzz** [comment]
should be fixed
