### ISSUE TITLE
Deleting a collection over WebDAV -> 500 error

### ISSUE THREAD

**Issue by zopyx** [eXist-db/exist#438]
Running exist-db 2.2.

I am trying to delete the collection 'onkopedia.old' over WebDAV.
This gives me a 500 HTTP error!?

Andreas

```
2015-01-05 08:03:50,158 [eXistThread-36] INFO  (MiltonResource.java [authorise]:350) - PROPFIND /db/onkopedia.old (write=false) 
2015-01-05 08:03:50,160 [eXistThread-36] INFO  (MiltonResource.java [authorise]:350) - PROPFIND /db/onkopedia.old (write=false) 
2015-01-05 08:03:50,189 [eXistThread-37] INFO  (HttpManager.java [process]:213) - DELETE :: http://dev1.veit-schiele.de:6080/exist/webdav/db/onkopedia.old/ - http://dev1.veit-schiele.de:6080/exist/webdav/db/onkopedia.old/ 
2015-01-05 08:03:50,190 [eXistThread-37] INFO  (MiltonResource.java [authorise]:350) - DELETE /db/onkopedia.old (write=true) 
2015-01-05 08:03:50,190 [eXistThread-37] ERROR (ExistCollection.java [initMetadata]:107) - Collection for /db/onkopedia.old/en cannot be opened for metadata 
2015-01-05 08:03:50,191 [eXistThread-37] ERROR (StandardFilter.java [process]:68) - process 
java.lang.NullPointerException
        at org.exist.webdav.ExistCollection.getCollectionURIs(ExistCollection.java:157)
        at org.exist.webdav.MiltonCollection.getCollectionResources(MiltonCollection.java:156)
        at org.exist.webdav.MiltonCollection.getChildren(MiltonCollection.java:177)
        at com.bradmcevoy.http.DeleteHelperImpl.isLockedOut(DeleteHelperImpl.java:61)
        at com.bradmcevoy.http.DeleteHelperImpl.isLockedOut(DeleteHelperImpl.java:65)
        at com.bradmcevoy.http.http11.DeleteHandler.processExistingResource(DeleteHandler.java:80)
        at com.bradmcevoy.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:149)
        at com.bradmcevoy.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:95)
        at com.bradmcevoy.http.http11.DeleteHandler.processResource(DeleteHandler.java:71)
        at com.bradmcevoy.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:91)
        at com.bradmcevoy.http.http11.DeleteHandler.process(DeleteHandler.java:66)
        at com.bradmcevoy.http.StandardFilter.process(StandardFilter.java:52)
        at com.bradmcevoy.http.FilterChain.process(FilterChain.java:40)
        at com.bradmcevoy.http.HttpManager.process(HttpManager.java:228)
        at com.bradmcevoy.http.MiltonServlet.service(MiltonServlet.java:195)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:457)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:229)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:103)
        at org.exist.http.urlrewrite.Forward.doRewrite(Forward.java:50)
        at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:221)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:457)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:368)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:488)
        at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:932)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:994)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:640)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Unknown Source)
```

---

Ok, it looks that the collection you refer to is not existent, but there is no check:

``` java
collection = broker.openCollection(xmldbUri, Lock.READ_LOCK);

// Get all collections
Iterator<XmldbURI> collections = collection.collectionIteratorNoLock(broker);
```

**Comment by line-o** [comment]
@joewiz would you be able to retest this reported issue?

**Comment by line-o** [comment]
@dizzzz could you retest this?

**Comment by duncdrum** [comment]
delete operation are covered by litmus, Milton is gone. I will close this as fixed on `develop` please reopen if the problem resurfaces.
