### ISSUE TITLE
[BUG] Update fails

### ISSUE THREAD

**Issue by karkraeg** [eXist-db/exist#4406]
**Describe the bug**
I installed https://github.com/eXist-db/exist/releases/download/eXist-6.0.1/exist-installer-6.0.1.jar into a new folder and moved the data dir from my shutdown eXist 5.2 installtion into the newly created eXist installation. After starting eXist with `startup.sh` I encounter the following error:

```
25 May 2022 12:09:21,129 [main] INFO  (JettyStart.java [run]:188) - Approximate maximum amount of memory for JVM: 60 GB
25 May 2022 12:09:21,130 [main] INFO  (JettyStart.java [run]:189) - Number of processors available to JVM: 4
25 May 2022 12:09:21,130 [main] INFO  (JettyStart.java [run]:191) - Running as user 'karl'
25 May 2022 12:09:21,130 [main] INFO  (JettyStart.java [run]:192) - [eXist Home : /mnt/maps_hdd/exist601]
25 May 2022 12:09:21,135 [main] INFO  (JettyStart.java [run]:193) - [eXist Version : 6.0.1]
25 May 2022 12:09:21,135 [main] INFO  (JettyStart.java [run]:194) - [eXist Build : 20220209234135]
25 May 2022 12:09:21,135 [main] INFO  (JettyStart.java [run]:195) - [Git commit : 51506fc97a9e5bb55fdea71fc76def2c9d402886]
25 May 2022 12:09:21,136 [main] INFO  (JettyStart.java [run]:197) - [Operating System : Linux 4.15.0-180-generic amd64]
25 May 2022 12:09:21,136 [main] INFO  (JettyStart.java [run]:198) - [log4j.configurationFile : /mnt/maps_hdd/exist601/etc/log4j2.xml]
25 May 2022 12:09:21,250 [main] INFO  (JettyStart.java [run]:199) - [jetty Version: 9.4.44.v20210927]
25 May 2022 12:09:21,250 [main] INFO  (JettyStart.java [run]:200) - [jetty.home : /mnt/maps_hdd/exist601]
25 May 2022 12:09:21,251 [main] INFO  (JettyStart.java [run]:201) - [jetty.base : /mnt/maps_hdd/exist601]
25 May 2022 12:09:21,251 [main] INFO  (JettyStart.java [run]:202) - [jetty configuration : /mnt/maps_hdd/exist601/etc/jetty/standard.enabled-jetty-configs]
25 May 2022 12:09:22,318 [main] INFO  (JettyStart.java [run]:211) - Configuring eXist from /mnt/maps_hdd/exist601/etc/conf.xml
25 May 2022 12:09:24,459 [main] ERROR (JettyStart.java [run]:224) - configuration error: org.exist.storage.BrokerPoolServiceException: Unable to prepare EXPath Package Repository: /mnt/maps_hdd/exist601/data/expathrepo
org.exist.EXistException: org.exist.storage.BrokerPoolServiceException: Unable to prepare EXPath Package Repository: /mnt/maps_hdd/exist601/data/expathrepo
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:548) ~[exist-core-6.0.1.jar:6.0.1]
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:451) ~[exist-core-6.0.1.jar:6.0.1]
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:177) ~[exist-core-6.0.1.jar:6.0.1]
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:112) ~[exist-core-6.0.1.jar:6.0.1]
	at org.exist.jetty.JettyStart.run(JettyStart.java:216) [exist-core-6.0.1.jar:6.0.1]
	at org.exist.jetty.JettyStart.main(JettyStart.java:103) [exist-core-6.0.1.jar:6.0.1]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.exist.start.Main.invokeMain(Main.java:153) [exist-start-6.0.1.jar:6.0.1]
	at org.exist.start.Main.runEx(Main.java:292) [exist-start-6.0.1.jar:6.0.1]
	at org.exist.start.Main.run(Main.java:158) [exist-start-6.0.1.jar:6.0.1]
	at org.exist.start.Main.main(Main.java:95) [exist-start-6.0.1.jar:6.0.1]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.executeMain(AppassemblerBooter.java:257) [appassembler-booter-2.1.0.jar:?]
	at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.main(AppassemblerBooter.java:77) [appassembler-booter-2.1.0.jar:?]
Caused by: org.exist.storage.BrokerPoolServiceException: Unable to prepare EXPath Package Repository: /mnt/maps_hdd/exist601/data/expathrepo
	at org.exist.repo.ExistRepository.prepare(ExistRepository.java:97) ~[exist-core-6.0.1.jar:6.0.1]
	at org.exist.storage.BrokerPoolServicesManager.prepareServices(BrokerPoolServicesManager.java:181) ~[exist-core-6.0.1.jar:6.0.1]
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:546) ~[exist-core-6.0.1.jar:6.0.1]
	... 19 more
Caused by: org.expath.pkg.repo.PackageException: Package descriptor does NOT exist in: eXide-3.3.0
	at org.expath.pkg.repo.Repository.parsePublicUris(Repository.java:499) ~[pkg-java-1.6.1.jar:1.6.1]
	at org.expath.pkg.repo.Repository.<init>(Repository.java:62) ~[pkg-java-1.6.1.jar:1.6.1]
	at org.exist.repo.ExistRepository.prepare(ExistRepository.java:94) ~[exist-core-6.0.1.jar:6.0.1]
	at org.exist.storage.BrokerPoolServicesManager.prepareServices(BrokerPoolServicesManager.java:181) ~[exist-core-6.0.1.jar:6.0.1]
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:546) ~[exist-core-6.0.1.jar:6.0.1]
	... 19 more
Caused by: org.expath.pkg.repo.Storage$NotExistException: File '/mnt/maps_hdd/exist601/data/expathrepo/eXide-3.3.0/expath-pkg.xml' does not exist
	at org.expath.pkg.repo.FileSystemStorage$FileSystemResolver.resolveWithin(FileSystemStorage.java:300) ~[pkg-java-1.6.1.jar:1.6.1]
	at org.expath.pkg.repo.FileSystemStorage$FileSystemResolver.resolveResource(FileSystemStorage.java:277) ~[pkg-java-1.6.1.jar:1.6.1]
	at org.expath.pkg.repo.FileSystemStorage$FileSystemResolver.resolveResource(FileSystemStorage.java:181) ~[pkg-java-1.6.1.jar:1.6.1]
	at org.expath.pkg.repo.Repository.parsePublicUris(Repository.java:496) ~[pkg-java-1.6.1.jar:1.6.1]
	at org.expath.pkg.repo.Repository.<init>(Repository.java:62) ~[pkg-java-1.6.1.jar:1.6.1]
	at org.exist.repo.ExistRepository.prepare(ExistRepository.java:94) ~[exist-core-6.0.1.jar:6.0.1]
	at org.exist.storage.BrokerPoolServicesManager.prepareServices(BrokerPoolServicesManager.java:181) ~[exist-core-6.0.1.jar:6.0.1]
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:546) ~[exist-core-6.0.1.jar:6.0.1]
	... 19 more
org.exist.EXistException: org.exist.storage.BrokerPoolServiceException: Unable to prepare EXPath Package Repository: /mnt/maps_hdd/exist601/data/expathrepo
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:548)
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:451)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:177)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:112)
	at org.exist.jetty.JettyStart.run(JettyStart.java:216)
	at org.exist.jetty.JettyStart.main(JettyStart.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.exist.start.Main.invokeMain(Main.java:153)
	at org.exist.start.Main.runEx(Main.java:292)
	at org.exist.start.Main.run(Main.java:158)
	at org.exist.start.Main.main(Main.java:95)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.executeMain(AppassemblerBooter.java:257)
	at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.main(AppassemblerBooter.java:77)
Caused by: org.exist.storage.BrokerPoolServiceException: Unable to prepare EXPath Package Repository: /mnt/maps_hdd/exist601/data/expathrepo
	at org.exist.repo.ExistRepository.prepare(ExistRepository.java:97)
	at org.exist.storage.BrokerPoolServicesManager.prepareServices(BrokerPoolServicesManager.java:181)
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:546)
	... 19 more
Caused by: org.expath.pkg.repo.PackageException: Package descriptor does NOT exist in: eXide-3.3.0
	at org.expath.pkg.repo.Repository.parsePublicUris(Repository.java:499)
	at org.expath.pkg.repo.Repository.<init>(Repository.java:62)
	at org.exist.repo.ExistRepository.prepare(ExistRepository.java:94)
	... 21 more
Caused by: org.expath.pkg.repo.Storage$NotExistException: File '/mnt/maps_hdd/exist601/data/expathrepo/eXide-3.3.0/expath-pkg.xml' does not exist
	at org.expath.pkg.repo.FileSystemStorage$FileSystemResolver.resolveWithin(FileSystemStorage.java:300)
	at org.expath.pkg.repo.FileSystemStorage$FileSystemResolver.resolveResource(FileSystemStorage.java:277)
	at org.expath.pkg.repo.FileSystemStorage$FileSystemResolver.resolveResource(FileSystemStorage.java:181)
	at org.expath.pkg.repo.Repository.parsePublicUris(Repository.java:496)
	... 23 more
```

How can I fix this? Thanks!

**Context (please always complete the following information):**
 - OS: ubuntu 18.04
 - eXist-db version: 5.2
 - Java Version: openjdk 11.0.15 2022-04-19

**Additional context**
- How is eXist-db installed? JAR installer
- Any custom changes in e.g. `conf.xml`? -> changed cache size

**Comment by adamretter** [comment]
@karkraeg It is not recommended to move data directories between major versions of eXist-db e.g. 5.x.x and 6.x.x. Instead you should perform a full database backup of the previous version, shut it down, install the new version, and then restore the database backup

**Comment by karkraeg** [comment]
Out dom.dbx is 538GB and the structure.dbx 272GB; wouldn’t that take ages to restore since eXist seems to only be using one CPU Core when we run it?

**Comment by karkraeg** [comment]
Seems to have been a problem with permissions. eXist 6 now starts up, but has other hiccups like `exerr:ERROR error found while loading module console: Cannot find module class from EXPath repository: org.exist.console.xquery.ConsoleModule`. I’ll see if I can fix that, but that is not a "normal" bug I guess. Thanks!

**Comment by joewiz** [comment]
@karkraeg For the error you just noted, you'll want to update to the latest version of Monex.
