### ISSUE TITLE
[BUG] Docker eXist-DB 5.3.1 and manually changed jetty ports

### ISSUE THREAD

**Issue by Kolophonium0** [eXist-db/exist#4442]
I use eXist-DB 5.3.1 from your official dockerhub distribution. I recently tried to change the jetty Port from within the database. After that the database refuses to start anymore. When starting it gives following error: 
`java.lang.IllegalStateException: No matching constructor class org.eclipse.jetty.server.ServerConnector in UNKNOWN-LOCATION
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:454)
        at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:380)
        at org.exist.jetty.JettyStart.run(JettyStart.java:242)
        at org.exist.jetty.JettyStart.main(JettyStart.java:103)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.exist.start.Main.invokeMain(Main.java:153)
        at org.exist.start.Main.runEx(Main.java:292)
        at org.exist.start.Main.run(Main.java:158)
        at org.exist.start.Main.main(Main.java:95)`
I checked the jetty-http.xml and jetty-https.xml but there are no inconsistencies. After that i copied new unchanged confs into the container but the database still refuses to start. Maybe there is something from jetty missing? Or is it some Java Env Problem? Help would be much appretiated.

**Comment by line-o** [comment]
@Kolophonium0 Would it be sufficient for you to just change the ports mapped by docker instead of the ports inside the container?

I mean starting the container with `-p 8080:12345` for example to have the HTTP port mapped to port 12345 on the host.

**Comment by Kolophonium0** [comment]
@line-o That doesn't seem to do the trick for me because i use some software 'ediarum' that uses a connector for oxygen xml-editor that seemingly does not like the port forwarding i do from docker - nginx - subnet in a university network. But most importantly i forgot to do a backup before this operation. So i need to try to save the container or at least the data within it.

**Comment by Kolophonium0** [comment]
Found the culprit a faulty jetty-ssl.xml configuration.
