### ISSUE TITLE
[BUG] eXist-db-setup-4.11.0.jar fails to install

### ISSUE THREAD

**Issue by peterstadler** [eXist-db/exist#4677]
**Describe the bug**

Running the file `eXist-db-setup-4.11.0.jar` from the GitHub release section fails to install eXist. The relevant section from the logs is:

```
#7 0.356 [ Starting to unpack ]
#7 0.378 [ Processing package: Sources (1/12) ]
#7 1.088 [ Processing package: Core (2/12) ]
#7 19.92 [ Processing package: Apps (3/12) ]
#7 19.97 [ Processing package: shared (4/12) ]
#7 20.02 [ Processing package: dashboard (5/12) ]
#7 20.08 [ Processing package: doc (6/12) ]
#7 20.44 [ Processing package: eXide (7/12) ]
#7 20.45 [ Processing package: functx (8/12) ]
#7 20.45 [ Processing package: fundocs (9/12) ]
#7 20.45 [ Processing package: markdown (10/12) ]
#7 20.49 [ Processing package: monex (11/12) ]
#7 20.52 [ Processing package: usermanager (12/12) ]
#7 20.70 [ Unpacking finished ]
#7 20.75 [ Starting processing ]
#7 20.75 Starting process Setting data dir... (1/2)
#7 21.06 Starting process Setting admin password ... (2/2)
#7 21.23 --- Starting embedded database instance ---
#7 22.14 Caught an exception while initializing db: configuration error: Duplicate field name "ajc$initFailureCause" with signature "Ljava.lang.Throwable;" in class file org/exist/security/PermissionRequiredAspect
#7 22.14 --- Initialization complete. Shutdown embedded database instance ---
#7 22.14 org.xmldb.api.base.XMLDBException: configuration error: Duplicate field name "ajc$initFailureCause" with signature "Ljava.lang.Throwable;" in class file org/exist/security/PermissionRequiredAspect
#7 22.14 	at org.exist.xmldb.DatabaseImpl.configure(DatabaseImpl.java:118)
#7 22.14 	at org.exist.xmldb.DatabaseImpl.getLocalCollection(DatabaseImpl.java:181)
#7 22.14 	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:167)
#7 22.14 	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:158)
#7 22.14 	at org.xmldb.api.DatabaseManager.getCollection(DatabaseManager.java:235)
#7 22.14 	at org.exist.installer.Setup.initDb(Setup.java:77)
#7 22.14 	at org.exist.installer.Setup.main(Setup.java:66)
#7 22.14 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#7 22.14 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#7 22.14 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#7 22.14 	at java.lang.reflect.Method.invoke(Method.java:498)
#7 22.14 	at org.exist.start.Main.invokeMain(Main.java:140)
#7 22.14 	at org.exist.start.Main.run(Main.java:453)
#7 22.14 	at org.exist.start.Main.main(Main.java:64)
#7 22.14 Caused by: org.exist.EXistException: Duplicate field name "ajc$initFailureCause" with signature "Ljava.lang.Throwable;" in class file org/exist/security/PermissionRequiredAspect
#7 22.14 	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:690)
#7 22.14 	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:435)
#7 22.14 	at org.exist.storage.BrokerPools.configure(BrokerPools.java:183)
#7 22.14 	at org.exist.storage.BrokerPools.configure(BrokerPools.java:131)
#7 22.14 	at org.exist.xmldb.DatabaseImpl.configure(DatabaseImpl.java:112)
#7 22.14 	... 13 more
#7 22.14 Caused by: java.lang.ClassFormatError: Duplicate field name "ajc$initFailureCause" with signature "Ljava.lang.Throwable;" in class file org/exist/security/PermissionRequiredAspect
#7 22.14 	at java.lang.ClassLoader.defineClass1(Native Method)
#7 22.14 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
#7 22.14 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
#7 22.14 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
#7 22.14 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
#7 22.14 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
#7 22.14 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
#7 22.14 	at java.security.AccessController.doPrivileged(Native Method)
#7 22.14 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
#7 22.14 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
#7 22.14 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
#7 22.14 	at org.exist.security.UnixStylePermission.setMode(UnixStylePermission.java:258)
#7 22.14 	at org.exist.collections.MutableCollection.setPermissions(MutableCollection.java:1755)
#7 22.14 	at org.exist.security.internal.SecurityManagerImpl.attach(SecurityManagerImpl.java:209)
#7 22.14 	at org.exist.security.internal.SecurityManagerImpl.startSystem(SecurityManagerImpl.java:150)
#7 22.14 	at org.exist.storage.BrokerPoolServicesManager.startSystemServices(BrokerPoolServicesManager.java:184)
#7 22.14 	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:599)
#7 22.14 	... 17 more
#7 23.17 Caught an exception while initializing db: configuration error: org.exist.storage.BrokerPoolServiceException: org.exist.util.DatabaseConfigurationException: Exception while reading lucene index directory: Lock obtain timed out: NativeFSLock@/opt/exist/webapp/WEB-INF/data/lucene/write.lock
#7 23.17 org.xmldb.api.base.XMLDBException: configuration error: org.exist.storage.BrokerPoolServiceException: org.exist.util.DatabaseConfigurationException: Exception while reading lucene index directory: Lock obtain timed out: NativeFSLock@/opt/exist/webapp/WEB-INF/data/lucene/write.lock
#7 23.17 	at org.exist.xmldb.DatabaseImpl.configure(DatabaseImpl.java:118)
#7 23.17 	at org.exist.xmldb.DatabaseImpl.getLocalCollection(DatabaseImpl.java:181)
#7 23.17 	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:167)
#7 23.17 	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:158)
#7 23.17 	at org.xmldb.api.DatabaseManager.getCollection(DatabaseManager.java:235)
#7 23.17 	at org.exist.installer.Setup.shutdown(Setup.java:95)
#7 23.17 	at org.exist.installer.Setup.main(Setup.java:67)
#7 23.17 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#7 23.17 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#7 23.17 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#7 23.17 	at java.lang.reflect.Method.invoke(Method.java:498)
#7 23.17 	at org.exist.start.Main.invokeMain(Main.java:140)
#7 23.17 	at org.exist.start.Main.run(Main.java:453)
#7 23.17 	at org.exist.start.Main.main(Main.java:64)
#7 23.17 Caused by: org.exist.EXistException: org.exist.storage.BrokerPoolServiceException: org.exist.util.DatabaseConfigurationException: Exception while reading lucene index directory: Lock obtain timed out: NativeFSLock@/opt/exist/webapp/WEB-INF/data/lucene/write.lock
#7 23.17 	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:528)
#7 23.17 	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:435)
#7 23.17 	at org.exist.storage.BrokerPools.configure(BrokerPools.java:183)
#7 23.17 	at org.exist.storage.BrokerPools.configure(BrokerPools.java:131)
#7 23.17 	at org.exist.xmldb.DatabaseImpl.configure(DatabaseImpl.java:112)
#7 23.17 	... 13 more
#7 23.17 Caused by: org.exist.storage.BrokerPoolServiceException: org.exist.util.DatabaseConfigurationException: Exception while reading lucene index directory: Lock obtain timed out: NativeFSLock@/opt/exist/webapp/WEB-INF/data/lucene/write.lock
#7 23.17 	at org.exist.indexing.IndexManager.prepare(IndexManager.java:131)
#7 23.17 	at org.exist.storage.BrokerPoolServicesManager.prepareServices(BrokerPoolServicesManager.java:156)
#7 23.17 	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:526)
#7 23.17 	... 17 more
#7 23.17 Caused by: org.exist.util.DatabaseConfigurationException: Exception while reading lucene index directory: Lock obtain timed out: NativeFSLock@/opt/exist/webapp/WEB-INF/data/lucene/write.lock
#7 23.17 	at org.exist.indexing.lucene.LuceneIndex.open(LuceneIndex.java:130)
#7 23.17 	at org.exist.indexing.IndexManager.initIndex(IndexManager.java:146)
#7 23.17 	at org.exist.indexing.IndexManager.prepare(IndexManager.java:119)
#7 23.17 	... 19 more
#7 23.17 Caused by: org.apache.lucene.store.LockObtainFailedException: Lock obtain timed out: NativeFSLock@/opt/exist/webapp/WEB-INF/data/lucene/write.lock
#7 23.17 	at org.apache.lucene.store.Lock.obtain(Lock.java:89)
#7 23.17 	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:755)
#7 23.17 	at org.exist.indexing.lucene.LuceneIndex.open(LuceneIndex.java:124)
#7 23.17 	... 21 more
```

**Expected behavior**

eXist should install just fine.

**To Reproduce**

Here's a simple Dockerfile that demonstrates the case:

```
FROM openjdk:8

ADD https://github.com/eXist-db/exist/releases/download/eXist-4.11.0/eXist-db-setup-4.11.0.jar .

RUN echo "INSTALL_PATH=/opt/exist" > "options.txt" \
    && java -jar eXist-db-setup-4.11.0.jar -options options.txt
```

Run it like `docker build -t test --progress=plain .` to reproduce the above error message

**Comment by adamretter** [comment]
@peterstadler Thanks for reporting. This would actually be a pretty cool test to add to CI! We will be releasing a 4.11.1 release shortly, and I will make sure to test it against this. I just checked a quick build here and it looks okay:

```
...

#6 [3/3] RUN echo "INSTALL_PATH=/opt/exist" > "options.txt"     && java -jar /eXist-db-setup-4.11.0.jar -options options.txt
#6 sha256:cc770fa92ce2111b416d078468d9cb0b143db439526831c0a51e584ecbb79826
#6 0.520 [ Starting to unpack ]
#6 0.553 [ Processing package: Sources (1/12) ]
#6 1.920 [ Processing package: Core (2/12) ]
#6 32.11 [ Processing package: Apps (3/12) ]
#6 32.20 [ Processing package: shared (4/12) ]
#6 32.40 [ Processing package: dashboard (5/12) ]
#6 32.48 [ Processing package: eXide (6/12) ]
#6 32.65 [ Processing package: exist-documentation (7/12) ]
#6 33.15 [ Processing package: fundocs (8/12) ]
#6 33.15 [ Processing package: functx (9/12) ]
#6 33.17 [ Processing package: markdown (10/12) ]
#6 33.25 [ Processing package: monex (11/12) ]
#6 33.36 [ Processing package: usermanager (12/12) ]
#6 33.72 [ Unpacking finished ]
#6 33.80 [ Starting processing ]
#6 33.80 Starting process Setting data dir... (1/2)
#6 34.33 Starting process Setting admin password ... (2/2)
#6 34.56 --- Starting embedded database instance ---
#6 36.64 Setting admin user password...
#6 36.65 --- Initialization complete. Shutdown embedded database instance ---
#6 37.19 [ Console installation done ]
#6 DONE 37.2s

#8 exporting to image
#8 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#8 exporting layers
#8 exporting layers 1.2s done
#8 writing image sha256:9f4db1b79d8ad742c55490307683357f0df7326cd2247a14377bf7ececcab1f9 done
#8 naming to docker.io/library/test done
#8 DONE 1.2s
```

**Comment by adamretter** [comment]
@peterstadler I think that https://github.com/eXist-db/exist/releases/tag/eXist-4.11.1 should solve your problem. Please let us know...

**Comment by peterstadler** [comment]
Thanks @adamretter for the quick fix!
I can confirm that the new release installs just fine!
