### ISSUE TITLE
[BUG] logging broken in windows

### ISSUE THREAD

**Issue by marmoure** [eXist-db/exist#4742]
the logging is not working in windows due to invalid file url `ERROR StatusLogger Invalid URL`

exist build: 118e6dda887edddfc5b9908c79410e6d3070c275
OS: windows 10
java: java version "17.0.6" 2023-01-17 LTS
the complete output when starting exist
```
$ ./exist-distribution/target/exist-distribution-7.0.0-SNAPSHOT-dir/bin/startup.sh 
[0.006s][warning][stringdedup] String Deduplication disabled: not supported by selected GC
Listening for transport dt_socket at address: 5005
ERROR StatusLogger Invalid URL C:/Users/z/Documents/work/exist/exist-distribution/target/exist-distribution-7.0.0-SNAPSHOT-dir/etc/log4j2.xml
 java.net.MalformedURLException: unknown protocol: c
        at java.base/java.net.URL.<init>(URL.java:681)
        at java.base/java.net.URL.fromURI(URL.java:748)
        at java.base/java.net.URI.toURL(URI.java:1139)
        at org.apache.logging.log4j.core.config.ConfigurationSource.fromUri(ConfigurationSource.java:342)
        at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:481)
        at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:474)
        at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:398)
        at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:318)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:690)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:711)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:599)
        at org.exist.jetty.JettyStart.<clinit>(JettyStart.java:77)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.exist.start.Main.invokeMain(Main.java:153)
        at org.exist.start.Main.runEx(Main.java:292)
        at org.exist.start.Main.run(Main.java:158)
        at org.exist.start.Main.main(Main.java:95)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.executeMain(AppassemblerBooter.java:257)
        at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.main(AppassemblerBooter.java:77)
ERROR StatusLogger Invalid URL C:/Users/z/Documents/work/exist/exist-distribution/target/exist-distribution-7.0.0-SNAPSHOT-dir/etc/log4j2.xml
 java.net.MalformedURLException: unknown protocol: c
        at java.base/java.net.URL.<init>(URL.java:681)
        at java.base/java.net.URL.fromURI(URL.java:748)
        at java.base/java.net.URI.toURL(URI.java:1139)
        at org.apache.logging.log4j.core.config.ConfigurationSource.fromUri(ConfigurationSource.java:342)
        at org.apache.logging.log4j.core.config.ConfigurationFactory.getInputFromString(ConfigurationFactory.java:353)
        at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:488)
        at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:474)
        at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:398)
        at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:318)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:690)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:711)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:599)
        at org.exist.jetty.JettyStart.<clinit>(JettyStart.java:77)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.exist.start.Main.invokeMain(Main.java:153)
        at org.exist.start.Main.runEx(Main.java:292)
        at org.exist.start.Main.run(Main.java:158)
        at org.exist.start.Main.main(Main.java:95)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.executeMain(AppassemblerBooter.java:257)
        at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.main(AppassemblerBooter.java:77)
ERROR StatusLogger Reconfiguration failed: No configuration found for '5ce65a89' at 'null' in 'null'
```

**Comment by reinhapa** [comment]
@marmoure  do you start exist with the bash shell script? Seems odd to me... On Windows eXist is normally being started using `startup.bat`

**Comment by marmoure** [comment]
i m using git bash

**Comment by reinhapa** [comment]
Well I guess this is not really a use case. Also I not really have an simple solution for that case... Normally the path would be something like `/cygdrive/c/Users/z/Documents/work/exist/exist-distribution/target/exist-distribution-7.0.0-SNAPSHOT-dir/etc/log4j2.xml` in your case...

**Comment by reinhapa** [comment]
@marmoure can you add some more context information on how exactly your installation process was to get to this state?

**Comment by dizzzz** [comment]
Please use the .bat file ; running bash/git/windows is a hackery solution and not a real unix environment;
I remember a project like tomcat has quite some changes in the .sh files to support running under Cygwin, but it is complex and ugly.
The best is... use .bat for windows.

**Comment by marmoure** [comment]
> @marmoure can you add some more context information on how exactly your installation process was to get to this state?

i built exist from source
not long ago it was working normally
but since we are not looking to support   `Cygwin` i assume this need to be closed as it's not the normal use case and discorged
