### ISSUE TITLE
[BUG] Admin Password not set during programmatic installation of existdb v4.10.0 (JAR installation with -console)

### ISSUE THREAD

**Issue by gsanapal** [eXist-db/exist#5010]
**Describe the bug**
We are installing ExistDB 4.10.0 on GCP instance running Redhat 7 as the operating system and Java 1.8.
We would like to fully automate the ExistDB installation in the user-data script in order to have the DB installed and running No manual intervention should be made to complete the installation.
In our case, the installation process completes successfully but the admin password is not set even if specified in the installation command.
This results in having the DB up and running but not secured by a password: it is in fact accessible only by providing admin as username and a blank (empty) password.
We would like to complete the installation, with the provided password set as admin password.
The issue seems to be present also in v 4.10.0.

**Expected behavior**
The database to be programmatically installed, and the admin password is set to the one provided.

**To Reproduce**

1. JAR installation with option files
java -jar exist-db-setup-4.10.0.jar -console -options ./existdb-options where the options files looks like below
```#TargetPanel.0
INSTALL_PATH=/opt/software/existdb

#DataDirPanel
dataDir=/opt/data/existdb

#AdminPasswordPanel
adminPasswd=Test123
```
This correctly installs the DB, but not able to login with the given password (Test123) in the existdb-options during the installation. some how the password is corrupting or something is happening and not able login at all.
2. update password using client.sh file
```
./bin/client.sh -s -l -u admin -P '$adminPasswd' --xpath 'let $_ := sm:passwd("admin", "foo") return "Ok"'
```
getting data base connection issue. it is not able to connect the database even if you provide correct password. We are able to login in browser with same password but not able to login with the password from client.sh 
```
[root@eps-em bin]# ./client.sh -s -l -u admin -P '$adminPasswd' --xpath 'let $_ := sm:passwd("admin", "foo") return "Ok"'
/opt/software/existdb/bin/./functions.d/getopt-settings.sh: line 93: [: too many arguments
/opt/software/existdb/bin/./functions.d/getopt-settings.sh: line 100: [: too many arguments
-s -l -u admin -P $adminPasswd --xpath let $_ := sm:passwd("admin", "foo") return "Ok"
WARNING: JAVA_HOME not found in your environment.

Please, set the JAVA_HOME variable in your enviroment to match the
location of the Java Virtual Machine you want to use in case of run
fail.
Using locale: en_US.UTF-8
eXist version 4.10.0 (0ad15ce448), Copyright (C) 2001-2023 The eXist-db Project
eXist-db comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; for details read the license file.

Connecting to database...
Connection to database failed; message: configuration error: null
org.xmldb.api.base.XMLDBException: configuration error: null
	at org.exist.xmldb.DatabaseImpl.configure(DatabaseImpl.java:118)
	at org.exist.xmldb.DatabaseImpl.getLocalCollection(DatabaseImpl.java:181)
	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:167)
	at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:158)
	at org.xmldb.api.DatabaseManager.getCollection(DatabaseManager.java:235)
	at org.exist.client.InteractiveClient.connect(InteractiveClient.java:301)
	at org.exist.client.InteractiveClient.connectToDatabase(InteractiveClient.java:2118)
	at org.exist.client.InteractiveClient.run(InteractiveClient.java:2215)
	at org.exist.client.InteractiveClient.main(InteractiveClient.java:244)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.exist.start.Main.invokeMain(Main.java:140)
	at org.exist.start.Main.run(Main.java:453)
	at org.exist.start.Main.main(Main.java:64)
Caused by: org.exist.EXistException
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:690)
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:435)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:183)
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:131)
	at org.exist.xmldb.DatabaseImpl.configure(DatabaseImpl.java:112)
	... 15 more
Caused by: java.lang.NullPointerException
	at org.exist.storage.journal.Journal.sync(Journal.java:434)
	at org.exist.storage.journal.Journal.flushToLog(Journal.java:417)
	at org.exist.storage.journal.JournalManager.flush(JournalManager.java:145)
	at org.exist.storage.BrokerPool.sync(BrokerPool.java:1431)
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:646)
	... 19 more
[root@eps-em bin]#
```
3. Run ant task to update the password  but did not worked.
```
<xdb:password xmlns:xdb="http://exist-db.org/ant" uri="${backup.uri}/db" user
="dba-user" password="dba-user-SecreT" name="guest" secret="Guest-Changed
-Secret"/>
```
4. Run ant task to process xpath expression
```
<xdb:xquery xmlns:xdb="http://exist-db.org/ant" uri="xmldb:exist://localhost
:8080/exist/xmlrpc/db" queryUri="http://www.example.com/query/xquery-task.xql" 
user="guest" password="guest-passwd">
      <variable name="beta" value="ϐ"/>
    </xdb:xquery>
```
6. Run ant task to process xquery
```
<xdb:xpath xmlns:xdb="http://exist-db.org/ant" uri="xmldb:exist://localhost:8080
/exist/xmlrpc/db" query="/example-queries/query"/>
```
**Context (please always complete the following information)**
 - Build: [eXist-4.10.0]
 - Java: [OpenJDK 64-Bit Server VM Corretto-8.265.01.1 (build 25.265-b01, mixed mode)]
 - OS: [Red Hat Enterprise Linux Server 7.7 (Maipo)]

**Additional context**

- How is eXist-db installed? JAR installer
- Please suggest how to use -options-template
- Please suggest if any other option to install existdb to set the password to the desired value.
- The issue seems to be present also in v 5.x.
- As a workaround, it would be OK also to understand how to programmatically set the password once the DB is installed, as an additional step in the user-data script. This would result in having the DB initially installed with empty password, and an additional command to set the password to the desired value.

Thank you in advance for any support.

**Comment by duncdrum** [comment]
You can find two ways of achieving your desired result on the readme of the docker file in this repo. 

https://github.com/eXist-db/exist/tree/develop/exist-docker/src/main/resources-filtered#a-slightly-more-complex-single-stage-image

There is also a xquery file doing the same thing among the test fixtures. Are you restarting exist, after changing the admin password ?
