### ISSUE TITLE
[BUG] Simple GroupBy throws NPE

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#5236]
The following query throws a `NullPointerException`:

```xquery
let $x := (10, 20, 30)
group by $y := $x < 30
return
  $x
```

The stack trace is:
```java
java.lang.NullPointerException: Cannot read field "initialized" because "data" is null
        at org.exist.xquery.GroupByClause.eval(GroupByClause.java:100) ~[exist-core-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:110) ~[exist-core-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist-core-7.0.0-SNAPSHOT.jar:7.0.0-S
NAPSHOT]
        at org.exist.xquery.PathExpr.eval(PathExpr.java:280) ~[exist-core-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist-core-7.0.0-SNAPSHOT.jar:7.0.0-S
NAPSHOT]
        at org.exist.xquery.XQuery.execute(XQuery.java:445) ~[exist-core-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.exist.xquery.XQuery.execute(XQuery.java:348) ~[exist-core-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.exist.xquery.XQuery.execute(XQuery.java:335) ~[exist-core-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
```

Tested on eXist-db 7.0.0.-SNAPSHOT

**Comment by line-o** [comment]
I could reproduce the issue and the NPE has to be fixed.
I am still wondering why one would write a query. As  $x in `group by $y := $x < 30` will always be the entire sequence. I also tested this in Saxon and baseX just to be sure.

The expected outcome is to receive all items of the sequence $x.
