### ISSUE TITLE
[BUG] NPE during startup 4.11.1

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#5264]
Context:
- migration v4.1 to v4.11.1 using backup-restore 
- standard conf.xml 
- openjdk version "1.8.0_402"

After restoring a backup from v4.1 into 4.11.1 I get the following NPE:

```
org.exist.EXistException: java.lang.NullPointerException
        at org.exist.storage.BrokerPool.initialize(BrokerPool.java:449) ~[exist.jar:4.11.1]
        at org.exist.storage.BrokerPools.configure(BrokerPools.java:183) [exist.jar:4.11.1]
        at org.exist.storage.BrokerPools.configure(BrokerPools.java:109) [exist.jar:4.11.1]
        at org.exist.jetty.JettyStart.run(JettyStart.java:181) [exist-optional.jar:4.11.1]
        at org.exist.jetty.JettyStart.main(JettyStart.java:98) [exist-optional.jar:4.11.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_402]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_402]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_402]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_402]
        at org.exist.start.Main.invokeMain(Main.java:140) [start.jar:4.11.1]
        at org.exist.start.Main.run(Main.java:453) [start.jar:4.11.1]
        at org.exist.start.Main.main(Main.java:64) [start.jar:4.11.1]
Caused by: java.lang.NullPointerException
        at org.expath.pkg.repo.deps.Semver.compareTo(Semver.java:167) ~[pkg-java-1.2.jar:1.2]
        at org.expath.pkg.repo.deps.Semver.matchesMin(Semver.java:137) ~[pkg-java-1.2.jar:1.2]
        at org.expath.pkg.repo.Packages.lower(Packages.java:110) ~[pkg-java-1.2.jar:1.2]
        at org.expath.pkg.repo.Packages.add(Packages.java:60) ~[pkg-java-1.2.jar:1.2]
        at org.expath.pkg.repo.Repository.addPackage(Repository.java:499) ~[pkg-java-1.2.jar:1.2]
        at org.expath.pkg.repo.Repository.parsePublicUris(Repository.java:478) ~[pkg-java-1.2.jar:1.2]
        at org.expath.pkg.repo.Repository.<init>(Repository.java:61) ~[pkg-java-1.2.jar:1.2]
        at org.exist.repo.ExistRepository.prepare(ExistRepository.java:84) ~[exist.jar:4.11.1]
        at org.exist.storage.BrokerPoolServicesManager.prepareServices(BrokerPoolServicesManager.java:156) ~[exist.jar:4.11.1]
        at org.exist.storage.BrokerPool._initialize(BrokerPool.java:526) ~[exist.jar:4.11.1]
        at org.exist.storage.BrokerPool.initialize(BrokerPool.java:435) ~[exist.jar:4.11.1]
        ... 11 more
2024-03-29 09:58:49,080 [main] ERROR (JettyStart.java [run]:189) - configuration error: java.lang.NullPointerException
org.exist.EXistException: java.lang.NullPointerException
        at org.exist.storage.BrokerPool.initialize(BrokerPool.java:449) ~[exist.jar:4.11.1]
        at org.exist.storage.BrokerPools.configure(BrokerPools.java:183) ~[exist.jar:4.11.1]
        at org.exist.storage.BrokerPools.configure(BrokerPools.java:109) ~[exist.jar:4.11.1]
        at org.exist.jetty.JettyStart.run(JettyStart.java:181) [exist-optional.jar:4.11.1]
        at org.exist.jetty.JettyStart.main(JettyStart.java:98) [exist-optional.jar:4.11.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_402]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_402]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_402]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_402]
        at org.exist.start.Main.invokeMain(Main.java:140) [start.jar:4.11.1]
        at org.exist.start.Main.run(Main.java:453) [start.jar:4.11.1]
        at org.exist.start.Main.main(Main.java:64) [start.jar:4.11.1]
Caused by: java.lang.NullPointerException
        at org.expath.pkg.repo.deps.Semver.compareTo(Semver.java:167) ~[pkg-java-1.2.jar:1.2]
        at org.expath.pkg.repo.deps.Semver.matchesMin(Semver.java:137) ~[pkg-java-1.2.jar:1.2]
        at org.expath.pkg.repo.Packages.lower(Packages.java:110) ~[pkg-java-1.2.jar:1.2]
        at org.expath.pkg.repo.Packages.add(Packages.java:60) ~[pkg-java-1.2.jar:1.2]
        at org.expath.pkg.repo.Repository.addPackage(Repository.java:499) ~[pkg-java-1.2.jar:1.2]
        at org.expath.pkg.repo.Repository.parsePublicUris(Repository.java:478) ~[pkg-java-1.2.jar:1.2]
        at org.expath.pkg.repo.Repository.<init>(Repository.java:61) ~[pkg-java-1.2.jar:1.2]
        at org.exist.repo.ExistRepository.prepare(ExistRepository.java:84) ~[exist.jar:4.11.1]
        at org.exist.storage.BrokerPoolServicesManager.prepareServices(BrokerPoolServicesManager.java:156) ~[exist.jar:4.11.1]
        at org.exist.storage.BrokerPool._initialize(BrokerPool.java:526) ~[exist.jar:4.11.1]
        at org.exist.storage.BrokerPool.initialize(BrokerPool.java:435) ~[exist.jar:4.11.1]
        ... 11 more
```

**Comment by dizzzz** [comment]
Solved: found 2 FunctX library versions in expathrepo;

How to fix:
- stop eXist-db when running
- go to `eXist-db-4.11.1/webapp/WEB-INF/data/expathrepo`
- remove `functx-1.0` directory
- go to `eXist-db-4.11.1/webapp/WEB-INF/data/expathrepo/.expath-pkg`
- edit `packages.txt` and `packages.xml`
  - edit files, remove `functx-1.0` entries from files

**Comment by dizzzz** [comment]
(documented for future references)

**Comment by line-o** [comment]
In my testing, duplicate entries in packages.txt and packages.xml do happen when installing an existing package A  with a smaller semver than the already installed one.

- package A installed in version 1.0.0
- install package A in version 0.8.0 💣
