### ISSUE TITLE
[BUG] Packagemanager does not work reliably on windows

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#5267]
**Describe the bug**
Whilst starting eXist v6.2 (from zip file, github) the app server does not correctly initialize, eg the dashboard is not present (redirect to 404.html)

**Expected behavior**
After startup the the dashboard can be visible in browser.

**To Reproduce**
- unzip `exist-distribution-6.2-windows.zip`
- run `bin/startup.sh`
- open browser 

note: behavior seems not to be 100% reproduceable, but in most cases it is.

**Screenshots**

![image](https://github.com/eXist-db/exist/assets/1700062/3c592ff4-4b25-40f5-a5b7-d8efb1e54044)

```
2024-04-02 13:45:00,429 [main] INFO  (Deployment.java [installAndDeploy]:267) - Installing package file:///D:/eXist-db/exist-distribution-6.2.0/autodeploy/packageservice-1.3.14.xar 
2024-04-02 13:45:00,542 [main] INFO  (FileSystemStorage.java [getContenDir]:229) - None of content dirs exist: 'D:\eXist-db\exist-distribution-6.2.0\etc\..\data\expathrepo\packageservice-1.3.14\content' and 'D:\eXist-db\exist-distribution-6.2.0\etc\..\data\expathrepo\packageservice-1.3.14\packageservice' 
2024-04-02 13:45:00,568 [main] INFO  (Deployment.java [installAndDeploy]:280) - Deploying package http://exist-db.org/apps/existdb-packageservice 
2024-04-02 13:45:03,363 [main] INFO  (Deployment.java [installAndDeploy]:267) - Installing package file:///D:/eXist-db/exist-distribution-6.2.0/autodeploy/dashboard-2.0.9.xar 
2024-04-02 13:45:03,771 [main] ERROR (AutoDeploymentTrigger.java [execute]:127) - Exception during deployment of app dashboard-2.0.9.xar: Copying 'D:\eXist-db\exist-distribution-6.2.0\etc\..\data\expathrepo\.expath-pkg\install-20240402-4498924286816122356' to 'D:\eXist-db\exist-distribution-6.2.0\etc\..\data\expathrepo\dashboard-2.0.9' failed 
org.expath.pkg.repo.PackageException: Copying 'D:\eXist-db\exist-distribution-6.2.0\etc\..\data\expathrepo\.expath-pkg\install-20240402-4498924286816122356' to 'D:\eXist-db\exist-distribution-6.2.0\etc\..\data\expathrepo\dashboard-2.0.9' failed
	at org.expath.pkg.repo.FileHelper.renameTmpDir(FileHelper.java:102) ~[pkg-java-2.0.0.jar:2.0.0]
	at org.expath.pkg.repo.FileSystemStorage.storeInstallDir(FileSystemStorage.java:111) ~[pkg-java-2.0.0.jar:2.0.0]
	at org.expath.pkg.repo.Repository.installPackage(Repository.java:407) ~[pkg-java-2.0.0.jar:2.0.0]
	at org.exist.repo.Deployment.installAndDeploy(Deployment.java:269) ~[exist-core-6.2.0.jar:6.2.0]
	at org.exist.repo.AutoDeploymentTrigger.execute(AutoDeploymentTrigger.java:125) ~[exist-core-6.2.0.jar:6.2.0]
	at org.exist.storage.StartupTriggersManager.startPreMultiUserSystem(StartupTriggersManager.java:61) ~[exist-core-6.2.0.jar:6.2.0]
	at org.exist.storage.BrokerPoolServicesManager.startPreMultiUserSystemServices(BrokerPoolServicesManager.java:264) ~[exist-core-6.2.0.jar:6.2.0]
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:682) ~[exist-core-6.2.0.jar:6.2.0]
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:451) ~[exist-core-6.2.0.jar:6.2.0]
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:177) ~[exist-core-6.2.0.jar:6.2.0]
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:112) ~[exist-core-6.2.0.jar:6.2.0]
	at org.exist.jetty.JettyStart.run(JettyStart.java:217) ~[exist-core-6.2.0.jar:6.2.0]
	at org.exist.jetty.JettyStart.main(JettyStart.java:103) ~[exist-core-6.2.0.jar:6.2.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_402]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_402]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_402]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_402]
	at org.exist.start.Main.invokeMain(Main.java:153) ~[exist-start-6.2.0.jar:6.2.0]
	at org.exist.start.Main.runEx(Main.java:292) ~[exist-start-6.2.0.jar:6.2.0]
	at org.exist.start.Main.run(Main.java:158) ~[exist-start-6.2.0.jar:6.2.0]
	at org.exist.start.Main.main(Main.java:95) ~[exist-start-6.2.0.jar:6.2.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_402]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_402]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_402]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_402]
	at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.executeMain(AppassemblerBooter.java:257) ~[appassembler-booter-2.1.0.jar:?]
	at org.codehaus.mojo.appassembler.booter.AppassemblerBooter.main(AppassemblerBooter.java:77) ~[appassembler-booter-2.1.0.jar:?]
Caused by: java.io.IOException: destination must be a directory
	at org.expath.pkg.repo.FileHelper.copyDirVisitor(FileHelper.java:143) ~[pkg-java-2.0.0.jar:2.0.0]
	at org.expath.pkg.repo.FileHelper.copy(FileHelper.java:134) ~[pkg-java-2.0.0.jar:2.0.0]
	at org.expath.pkg.repo.FileHelper.renameTmpDir(FileHelper.java:100) ~[pkg-java-2.0.0.jar:2.0.0]
	... 26 more
2024-04-02 13:45:03,778 [main] INFO  (Deployment.java [installAndDeploy]:267) - Installing package file:///D:/eXist-db/exist-distribution-6.2.0/autodeploy/eXide-3.5.0.xar 
2024-04-02 13:45:04,448 [main] INFO  (FileSystemStorage.java [getContenDir]:229) - None of content dirs exist: 'D:\eXist-db\exist-distribution-6.2.0\etc\..\data\expathrepo\eXide-3.5.0\content' and 'D:\eXist-db\exist-distribution-6.2.0\etc\..\data\expathrepo\eXide-3.5.0\eXide' 
2024-04-02 13:45:04,481 [main] INFO  (Deployment.java [installAndDeploy]:280) - Deploying package http://exist-db.org/apps/eXide 

```

**Context (please always complete the following information)**
 - Build: [eXist-6.2.0]
 - Java: [1.8.0_402]
 - OS: [Windows 10, VDI(citrix)]

**Additional context**
- How is eXist-db installed? [ZIP extract]
- Any custom changes in e.g. `conf.xml`? [no]

**Comment by dizzzz** [comment]
related to https://github.com/fgeorges/expath-pkg-java/blob/master/pkg-java/src/org/expath/pkg/repo/FileHelper.java#L78

**Comment by dizzzz** [comment]
this is the new location.... with java/nio2

https://github.com/expath/expath-pkg-java/blob/main/pkg-java/src/main/java/org/expath/pkg/repo/FileHelper.java

**Comment by dizzzz** [comment]
Actions
-  upgrade pkg-java to 2.1.1
- document to disable virusscanner
  - retry seems to work better with new version

**Comment by duncdrum** [comment]
I think this is fixed now. Please reopen if it reproduces on develop.
