### ISSUE TITLE
[BUG] 'other' is different type of Path

### ISSUE THREAD

**Issue by lguariento** [eXist-db/exist#5525]
**Describe the bug**
With a simple query, be it via Java Admin, via rest, or in eXide, one gets a `'other' is different type of Path` 
error under certain conditions.

**Expected behavior**
Getting the result of the query.

**To Reproduce**
Open eXide -> new XQuery. Query a collection of XML document with a simple for loop importing the `functx` module.

```xquery
xquery version "3.1";

declare namespace tei="http://www.tei-c.org/ns/1.0";
import module namespace functx = "http://www.functx.com";

for $x in collection("/db/apps/yourfolder")//tei:TEI
return $x
```

Copy-pasting the same query in the Java Admin console returns the same error.

Full error:

```txt
org.xmldb.api.base.XMLDBException: Failed to invoke method compile in class org.exist.xmlrpc.RpcConnection: 'other' is different type of Path
	at org.exist.xmldb.RemoteCollection.execute(RemoteCollection.java:129)
	at org.exist.xmldb.RemoteXPathQueryService.compileAndCheck(RemoteXPathQueryService.java:151)
	at org.exist.xmldb.RemoteXPathQueryService.compile(RemoteXPathQueryService.java:128)
	at org.exist.client.QueryDialog$QueryRunnable.run(QueryDialog.java:577)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.xmlrpc.XmlRpcException: Failed to invoke method compile in class org.exist.xmlrpc.RpcConnection: 'other' is different type of Path
	at org.apache.xmlrpc.client.XmlRpcStreamTransport.readResponse(XmlRpcStreamTransport.java:214)
	at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:173)
	at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:142)
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:70)
	at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:158)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:147)
	at org.exist.xmldb.RemoteCollection.execute(RemoteCollection.java:127)
	... 4 more
```

 - Build: [eXist-6.3.0]
 - Java: openjdk 17.0.13 2024-10-15
 - Debian

**Additional context**
- How is eXist-db installed? .jar
- Any custom changes in e.g. `conf.xml`? No

**Comment by line-o** [comment]
I had a moment to look at this issue and I can reproduce it.

Ad-hoc modules cannot import libraries without location hint:

```bash
; xst run "import module namespace functx='http://www.functx.com/';functx:atomic-type(4)"
Error executing your query
Failed to invoke method executeQuery in class org.exist.xmlrpc.RpcConnection: 'other' is different type of Path
```

**Comment by line-o** [comment]
As @lguariento also found out, saving the module to the database allows the library to be imported.

**Comment by line-o** [comment]
This affects eXist-6.3.0, develop, develop-6.x.x

**Comment by adamretter** [comment]
@lguariento Hi Luca, I have a fix for you that I prepared, and I was about to cut an eXist-db 6.3.1 release. I am sad to say that I can't do that now (see the Slack #community) channel for details - https://exist-db.slack.com/archives/CG2MRUZ35/p1730302049097909

**Comment by reinhapa** [comment]
> @lguariento Hi Luca, I have a fix for you that I prepared, and I was about to publish an eXist-db 6.3.1 release to address this. I am sad to say that I can't do that now;

@adamretter is there a PR/commit for this fix?

**Comment by lguariento** [comment]
Thank you. I'll apply that later and will report back.

**Comment by adamretter** [comment]
> is there a PR/commit for this fix

@reinhapa Yes.

**Comment by reinhapa** [comment]
> > is there a PR/commit for this fix
> 
> @reinhapa Yes.

 Could  you give me point me to the given PR in order to make sure it will be in the next release?
