### ISSUE TITLE
Question, perhaps bug in 6.3.0

### ISSUE THREAD

**Issue by eduarddrenth** [eXist-db/exist#5565]
Running my app, that is working fine in 6.2.0, in 6.3.0 I run into the error below.

Does this ring a bell with anyone?

```
Caused by: java.lang.NullPointerException
	at org.exist.indexing.lucene.LuceneMatch.getField(LuceneMatch.java:126)
	at org.exist.xquery.modules.lucene.Field.eval(Field.java:123)
	at org.exist.xquery.BasicFunction.eval(BasicFunction.java:73)
	at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:62)
	at org.exist.xquery.UserDefinedFunction.eval(UserDefinedFunction.java:161)
	at org.exist.xquery.DynamicCardinalityCheck.eval(DynamicCardinalityCheck.java:73)
	at org.exist.xquery.Atomize.eval(Atomize.java:66)
	at org.exist.xquery.DynamicTypeCheck.eval(DynamicTypeCheck.java:60)
	at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:289)
	at org.exist.xquery.FunctionCall.eval(FunctionCall.java:207)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:280)
	at org.exist.xquery.EnclosedExpr.eval(EnclosedExpr.java:80)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:280)
	at org.exist.xquery.ElementConstructor.eval(ElementConstructor.java:330)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:280)
	at org.exist.xquery.ElementConstructor.eval(ElementConstructor.java:330)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:280)
	at org.exist.xquery.ElementConstructor.eval(ElementConstructor.java:330)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:110)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:110)
	at org.exist.xquery.UserDefinedFunction.eval(UserDefinedFunction.java:161)
	at org.exist.xquery.DynamicCardinalityCheck.eval(DynamicCardinalityCheck.java:73)
	at org.exist.xquery.DynamicTypeCheck.eval(DynamicTypeCheck.java:60)
	at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:289)
	at org.exist.xquery.FunctionCall.eval(FunctionCall.java:207)
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
	at org.exist.xquery.OrderByClause.eval(OrderByClause.java:81)
	at org.exist.xquery.ForExpr.processItem(ForExpr.java:248)
	at org.exist.xquery.ForExpr.eval(ForExpr.java:187)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:110)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:280)
	at org.exist.xquery.EnclosedExpr.eval(EnclosedExpr.java:80)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:280)
	at org.exist.xquery.ElementConstructor.eval(ElementConstructor.java:330)
	at org.exist.xquery.UserDefinedFunction.eval(UserDefinedFunction.java:161)
	at org.exist.xquery.DynamicCardinalityCheck.eval(DynamicCardinalityCheck.java:73)
```

**Comment by tuurma** [comment]
Hi Eduard,

This has to do with reverting
<https://github.com/eXist-db/exist/commit/711cf32d42e2c391d3645f7436bd1bcd154df4c7>
this
PR <https://github.com/eXist-db/exist/pull/4541> and you can expect this to
be fixed in the upcoming hotfix release.

Best,

Magdalena

**Comment by adamretter** [comment]
@tuurma Just to make you aware that PR #4541 adds 3 additional new features:

1.
> As a consequence, users no longer need to specify the fields to retrieve at query time

2.
>  an additional configuration attribute is introduced to field definitions in collection.xconf: adding binary="yes"

3.
> Adds some missing atomic types to typed lucene fields (xs:decimal, xs:float, xs:short and more)

So I think according to the SemVer 2.0.0 standard that eXist-db follows, that PR would have to go into a Minor release and not a Hotfix release, which would mean an eXist-db 6.4.0 and not a 6.3.1.

@eduarddrenth For background information, it was decided not to include that in the 6.3.0 release due to an as yet unresolved memory leak that has been reported from #4541 in this issue - https://github.com/eXist-db/exist/issues/4890

**Comment by eduarddrenth** [comment]
Thanks for these details, I'll patiently await the minor

**Comment by line-o** [comment]
The fact that the code was running in 6.2.0 and leads to a NPE in 6.3.0 qualifies it as a regression.

**Comment by adamretter** [comment]
> qualifies this issue as a bug and a regression

The issue - yes, but the previous solution - no.

**Comment by line-o** [comment]
fixed in exist-6.4.0
