### ISSUE TITLE
[BUG] org.xmldb.api.base.XMLDBException: Failed to invoke method queryP in class org.exist.xmlrpc.RpcConnection: GC overhead limit exceeded

### ISSUE THREAD

**Issue by sanapalagiribabu** [eXist-db/exist#5584]
eXist database (4.10 version) throwing GC overhaed limit exceeded

**Describe the bug**

```
Caused by: RepositoryException: org.xmldb.api.base.XMLDBException: Failed to invoke method queryP in class org.exist.xmlrpc.RpcConnection: GC overhead limit exceeded
	at AbstractGenericExistRepository.runQuery(AbstractGenericExistRepository.java:230)
	at ProcedureDocumentStreamingRepositoryImpl.search(ProcedureDocumentStreamingRepositoryImpl.java:62)
	at sun.reflect.GeneratedMethodAccessor352.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
	at org.jboss.weld.proxies.ProcedureDocumentStreamingRepository$SearchStreamingDocument$87885769$Proxy$_$$_WeldClientProxy.search(Unknown Source)
	at ProcedureDocumentRepositoryImpl.search(ProcedureDocumentRepositoryImpl.java:51)
	at sun.reflect.GeneratedMethodAccessor351.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
	at org.jboss.weld.proxies.ProcedureDocumentRepository$200392795$Proxy$_$$_WeldClientProxy.search(Unknown Source)
	at SearchService.searchProcedures(SearchService.java:97)
	... 77 more
Caused by: org.xmldb.api.base.XMLDBException: Failed to invoke method queryP in class org.exist.xmlrpc.RpcConnection: GC overhead limit exceeded
	at org.exist.xmldb.RemoteXPathQueryService.query(RemoteXPathQueryService.java:113)
	at org.exist.xmldb.RemoteXPathQueryService.query(RemoteXPathQueryService.java:71)
	at org.exist.xmldb.RemoteXPathQueryService.execute(RemoteXPathQueryService.java:411)
	at AbstractGenericExistRepository.runQuery(AbstractGenericExistRepository.java:223)
	... 92 more
Caused by: org.apache.xmlrpc.XmlRpcException: Failed to invoke method queryP in class org.exist.xmlrpc.RpcConnection: GC overhead limit exceeded
	at org.apache.xmlrpc.client.XmlRpcStreamTransport.readResponse(XmlRpcStreamTransport.java:197)
	at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:156)
	at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:115)
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
	at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:158)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:147)
	at org.exist.xmldb.RemoteXPathQueryService.query(RemoteXPathQueryService.java:99)
	... 95 more
```

**Expected behavior**
exist db should respond with in timeout 600 sec

**Screenshots**

504-Gateway error

 - Build: [eXist-4.10.0]
 - Java: corretto [1.8.0_265]
 - OS: [Redhat 8]

**Additional context**
- How is eXist-db installed? [existdb.tar and un tar in installation folder ]
- Any custom changes in e.g. `conf.xml`?
cacheSize="512m" collectionCache="1024m"
- -Xms1024m -Xmx2048m -XX:+UseG1GC
-

**Comment by line-o** [comment]
Hi @sanapalagiribabu! I fear that it is impossible to find the root cause of your issue without more context.
Can you share the query that is executed via XML-RPC? The full stack-trace would also be interesting. The one you posted is missing 95 lines at the end.
