### ISSUE TITLE
package repo: unclear exception

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#748]
After restoring a backup file, during startup the following stacktrace appears:unfortunately it is not clear which ZIP file is corrupt......

```
2015-07-22 16:10:18,383 [eXistThread-31] ERROR (InstallFunction.java [eval]:126) - Error unziping the package 
org.expath.pkg.repo.PackageException: Error unziping the package
    at org.expath.pkg.repo.FileSystemStorage.install(FileSystemStorage.java:373) ~[pkg-repo.jar:?]
    at org.expath.pkg.repo.Repository.doInstall(Repository.java:237) ~[pkg-repo.jar:?]
    at org.expath.pkg.repo.Repository.installPackage(Repository.java:188) ~[pkg-repo.jar:?]
    at org.exist.xquery.modules.expathrepo.InstallFunction.eval(InstallFunction.java:109) [exist-modules.jar:?]
    at org.exist.xquery.BasicFunction.eval(BasicFunction.java:70) [exist.jar:?]
    at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:56) [exist.jar:?]
    at org.exist.xquery.LetExpr.eval(LetExpr.java:142) [exist.jar:?]
    at org.exist.xquery.BindingExpression.eval(BindingExpression.java:165) [exist.jar:?]
    at org.exist.xquery.UserDefinedFunction.eval(UserDefinedFunction.java:155) [exist.jar:?]
    at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:330) [exist.jar:?]
    at org.exist.xquery.FunctionCall.eval(FunctionCall.java:234) [exist.jar:?]
    at org.exist.xquery.LetExpr.eval(LetExpr.java:142) [exist.jar:?]
    at org.exist.xquery.LetExpr.eval(LetExpr.java:187) [exist.jar:?]
    at org.exist.xquery.BindingExpression.eval(BindingExpression.java:165) [exist.jar:?]
    at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:?]
    at org.exist.xquery.PathExpr.eval(PathExpr.java:267) [exist.jar:?]
    at org.exist.xquery.TryCatchExpression.eval(TryCatchExpression.java:127) [exist.jar:?]
    at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:100) [exist.jar:?]
    at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58) [exist.jar:?]
    at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:65) [exist.jar:?]
    at org.exist.xquery.LetExpr.eval(LetExpr.java:189) [exist.jar:?]
    at org.exist.xquery.BindingExpression.eval(BindingExpression.java:165) [exist.jar:?]
    at org.exist.xquery.UserDefinedFunction.eval(UserDefinedFunction.java:155) [exist.jar:?]
    at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:330) [exist.jar:?]
    at org.exist.xquery.FunctionCall.eval(FunctionCall.java:234) [exist.jar:?]
    at org.exist.xquery.UserDefinedFunction.eval(UserDefinedFunction.java:155) [exist.jar:?]
    at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:330) [exist.jar:?]
    at org.exist.xquery.FunctionCall.eval(FunctionCall.java:234) [exist.jar:?]
    at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:?]
    at org.exist.xquery.value.FunctionReference.eval(FunctionReference.java:81) [exist.jar:?]
    at org.exist.xquery.DynamicFunctionCall.eval(DynamicFunctionCall.java:75) [exist.jar:?]
    at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:?]
    at org.exist.xquery.PathExpr.eval(PathExpr.java:267) [exist.jar:?]
    at org.exist.xquery.SequenceConstructor.eval(SequenceConstructor.java:84) [exist.jar:?]
    at org.exist.xquery.UserDefinedFunction.eval(UserDefinedFunction.java:155) [exist.jar:?]
    at org.exist.xquery.FunctionCall$DeferredFunctionCallImpl.execute(FunctionCall.java:427) [exist.jar:?]
    at org.exist.xquery.DeferredFunctionCall.realize(DeferredFunctionCall.java:57) [exist.jar:?]
    at org.exist.xquery.DeferredFunctionCall.iterate(DeferredFunctionCall.java:230) [exist.jar:?]
    at org.exist.xquery.value.ValueSequence.addAll(ValueSequence.java:167) [exist.jar:?]
    at org.exist.xquery.ForExpr.eval(ForExpr.java:308) [exist.jar:?]
    at org.exist.xquery.BindingExpression.eval(BindingExpression.java:165) [exist.jar:?]
    at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:?]
    at org.exist.xquery.PathExpr.eval(PathExpr.java:267) [exist.jar:?]
    at org.exist.xquery.SequenceConstructor.eval(SequenceConstructor.java:84) [exist.jar:?]
    at org.exist.xquery.UserDefinedFunction.eval(UserDefinedFunction.java:155) [exist.jar:?]
    at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:330) [exist.jar:?]
    at org.exist.xquery.FunctionCall.eval(FunctionCall.java:234) [exist.jar:?]
    at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58) [exist.jar:?]
    at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:65) [exist.jar:?]
    at org.exist.xquery.LetExpr.eval(LetExpr.java:189) [exist.jar:?]
    at org.exist.xquery.LetExpr.eval(LetExpr.java:187) [exist.jar:?]
    at org.exist.xquery.BindingExpression.eval(BindingExpression.java:165) [exist.jar:?]
    at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:?]
    at org.exist.xquery.PathExpr.eval(PathExpr.java:267) [exist.jar:?]
    at org.exist.xquery.SequenceConstructor.eval(SequenceConstructor.java:84) [exist.jar:?]
    at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:?]
    at org.exist.xquery.PathExpr.eval(PathExpr.java:267) [exist.jar:?]
    at org.exist.xquery.EnclosedExpr.eval(EnclosedExpr.java:81) [exist.jar:?]
    at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:?]
    at org.exist.xquery.PathExpr.eval(PathExpr.java:267) [exist.jar:?]
    at org.exist.xquery.ElementConstructor.eval(ElementConstructor.java:318) [exist.jar:?]
    at org.exist.xquery.UserDefinedFunction.eval(UserDefinedFunction.java:155) [exist.jar:?]
    at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:330) [exist.jar:?]
    at org.exist.xquery.FunctionCall.eval(FunctionCall.java:234) [exist.jar:?]
    at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:?]
    at org.exist.xquery.PathExpr.eval(PathExpr.java:267) [exist.jar:?]
    at org.exist.xquery.SequenceConstructor.eval(SequenceConstructor.java:84) [exist.jar:?]
    at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:?]
    at org.exist.xquery.PathExpr.eval(PathExpr.java:267) [exist.jar:?]
    at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:?]
    at org.exist.xquery.XQuery.execute(XQuery.java:280) [exist.jar:?]
    at org.exist.xquery.XQuery.execute(XQuery.java:200) [exist.jar:?]
    at org.exist.http.servlets.XQueryServlet.process(XQueryServlet.java:492) [exist-optional.jar:?]
    at org.exist.http.servlets.XQueryServlet.doPost(XQueryServlet.java:198) [exist-optional.jar:?]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:755) [servlet-api-3.0.jar:?]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [servlet-api-3.0.jar:?]
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575) [jetty-security-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:229) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:103) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.exist.http.urlrewrite.Forward.doRewrite(Forward.java:50) [exist-optional.jar:?]
    at org.exist.http.urlrewrite.XQueryURLRewrite.doRewrite(XQueryURLRewrite.java:557) [exist-optional.jar:?]
    at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:357) [exist-optional.jar:?]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [servlet-api-3.0.jar:?]
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
    at de.betterform.agent.web.filter.XFormsFilter.doFilter(XFormsFilter.java:171) [betterform-exist-5.1-SNAPSHOT-20150603.jar:?]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533) [jetty-security-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.server.Server.handle(Server.java:370) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865) [jetty-http-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) [jetty-http-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696) [jetty-io-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53) [jetty-io-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [jetty-util-8.1.17.v20150415.jar:8.1.17.v20150415]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [jetty-util-8.1.17.v20150415.jar:8.1.17.v20150415]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.util.zip.ZipException: error in opening zip file
    at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_31]
    at java.util.zip.ZipFile.<init>(ZipFile.java:220) ~[?:1.8.0_31]
    at java.util.zip.ZipFile.<init>(ZipFile.java:150) ~[?:1.8.0_31]
    at java.util.zip.ZipFile.<init>(ZipFile.java:164) ~[?:1.8.0_31]
    at org.expath.pkg.repo.ZipHelper.unzip(ZipHelper.java:80) ~[pkg-repo.jar:?]
    at org.expath.pkg.repo.FileSystemStorage.install(FileSystemStorage.java:370) ~[pkg-repo.jar:?]
    ... 118 more
```

**Comment by ljo** [comment]
I am looking at some other exceptions in this are so should probably look at this too.

**Comment by dizzzz** [comment]
it is actually triggered by running 

```xquery
import module namespace repair="http://exist-db.org/xquery/repo/repair"
at "resource:org/exist/xquery/modules/expathrepo/repair.xql";
repair:clean-all(),
repair:repair()
```

**Comment by dizzzz** [comment]
maybe it is a virus scanner thing; i will continue to investigate but the error is..... vague

**Comment by dizzzz** [comment]
No the issue is real .... the ZIP files are corrupted, that is: not readable. I did some diagnosis but could not find the actual cause....

**Comment by dizzzz** [comment]
fixed
