### ISSUE TITLE
Lucene KeywordAnalyzer cannot be found

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#794]
Lucene's KeywordAnalyzer cannot be found on a standard trunk build.  When launching eXist with the following collection.xconf:

``` xml
<collection xmlns="http://exist-db.org/collection-config/1.0" xmlns:test="test">
    <index xmlns:xs="http://www.w3.org/2001/XMLSchema">
        <fulltext default="none" attributes="false"/>
        <lucene>
            <analyzer class="org.apache.lucene.analysis.standard.StandardAnalyzer"/>
            <analyzer id="ws" class="org.apache.lucene.analysis.core.WhitespaceAnalyzer"/>
            <analyzer id="keyword" class="org.apache.lucene.analysis.core.KeywordAnalyzer"/>
            <text qname="test:para"/>
            <text qname="test:para" field="para-standard"/>
            <text qname="test:para" field="para-ws" analyzer="ws"/>
            <text qname="test:para" field="para-keyword" analyzer="keyword"/>
        </lucene>
    </index>
</collection>
```

exist.log reports the following error:

```
23 Sep 2015 14:40:15,394 [main] DEBUG (AnalyzerConfig.java [createInstance]:261) - Using analyzer org.apache.lucene.analysis.standard.StandardAnalyzer
23 Sep 2015 14:40:15,395 [main] DEBUG (AnalyzerConfig.java [createInstance]:261) - Using analyzer org.apache.lucene.analysis.core.WhitespaceAnalyzer
23 Sep 2015 14:40:15,395 [main] ERROR (AnalyzerConfig.java [createInstance]:269) - Could not find matching analyzer class constructororg.apache.lucene.analysis.core.KeywordAnalyzer: org.apache.lucene.analysis.core.KeywordAnalyzer.<init>(org.apache.lucene.util.Version)
java.lang.NoSuchMethodException: org.apache.lucene.analysis.core.KeywordAnalyzer.<init>(org.apache.lucene.util.Version)
    at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_60]
    …
```

For a reproducible test, including files, see this thread from exist-open: http://markmail.org/message/heesn3keggjkkmbg.

**Comment by adamretter** [comment]
@joewiz Can you post a few more lines from the stacktrace? At least down to a few lines which are in the `org.exist` namespace.

**Comment by joewiz** [comment]
Sure, here is the full stacktrace:

```
2015-09-23 10:01:51,704 [Thread-3] ERROR (AnalyzerConfig.java [createInstance]:269) - Could not find matching analyzer class constructororg.apache.lucene.analysis.core.KeywordAnalyzer: org.apache.lucene.analysis.core.KeywordAnalyzer.<init>(org.apache.lucene.util.Version) 
java.lang.NoSuchMethodException: org.apache.lucene.analysis.core.KeywordAnalyzer.<init>(org.apache.lucene.util.Version)
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_45]
	at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[?:1.8.0_45]
	at org.exist.indexing.lucene.AnalyzerConfig.createInstance(AnalyzerConfig.java:257) [exist-index-lucene.jar:?]
	at org.exist.indexing.lucene.AnalyzerConfig.configureAnalyzer(AnalyzerConfig.java:224) [exist-index-lucene.jar:?]
	at org.exist.indexing.lucene.AnalyzerConfig.addAnalyzer(AnalyzerConfig.java:118) [exist-index-lucene.jar:?]
	at org.exist.indexing.lucene.LuceneConfig.parseConfig(LuceneConfig.java:260) [exist-index-lucene.jar:?]
	at org.exist.indexing.lucene.LuceneConfig.parseConfig(LuceneConfig.java:256) [exist-index-lucene.jar:?]
	at org.exist.indexing.lucene.LuceneConfig.<init>(LuceneConfig.java:75) [exist-index-lucene.jar:?]
	at org.exist.indexing.lucene.LuceneIndexWorker.configure(LuceneIndexWorker.java:156) [exist-index-lucene.jar:?]
	at org.exist.indexing.IndexController.configure(IndexController.java:83) [exist.jar:?]
	at org.exist.storage.IndexSpec.read(IndexSpec.java:106) [exist.jar:?]
	at org.exist.storage.IndexSpec.<init>(IndexSpec.java:67) [exist.jar:?]
	at org.exist.collections.CollectionConfiguration.read(CollectionConfiguration.java:152) [exist.jar:?]
	at org.exist.collections.CollectionConfigurationManager.loadConfiguration(CollectionConfigurationManager.java:287) [exist.jar:?]
	at org.exist.collections.CollectionConfigurationManager.loadAllConfigurations(CollectionConfigurationManager.java:261) [exist.jar:?]
	at org.exist.collections.CollectionConfigurationManager.loadAllConfigurations(CollectionConfigurationManager.java:269) [exist.jar:?]
	at org.exist.collections.CollectionConfigurationManager.loadAllConfigurations(CollectionConfigurationManager.java:269) [exist.jar:?]
	at org.exist.collections.CollectionConfigurationManager.loadAllConfigurations(CollectionConfigurationManager.java:253) [exist.jar:?]
	at org.exist.collections.CollectionConfigurationManager.<init>(CollectionConfigurationManager.java:86) [exist.jar:?]
	at org.exist.storage.BrokerPool.initCollectionConfigurationManager(BrokerPool.java:1360) [exist.jar:?]
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:939) [exist.jar:?]
	at org.exist.storage.BrokerPool.<init>(BrokerPool.java:720) [exist.jar:?]
	at org.exist.storage.BrokerPool.configure(BrokerPool.java:254) [exist.jar:?]
	at org.exist.storage.BrokerPool.configure(BrokerPool.java:228) [exist.jar:?]
	at org.exist.jetty.JettyStart.run(JettyStart.java:167) [exist-optional.jar:?]
	at org.exist.launcher.Launcher$4.run(Launcher.java:145) [exist.jar:?]
```

**Comment by joewiz** [comment]
(Using a fresh installation of eXist-db 3.0RC1, downloaded via exist-db.org.)

**Comment by ljo** [comment]
I am not shure there is any real problem here . The log just shows the default invocation (vith version) that fails which is followed by another attempt. I have changed this for the new Lucene version.
But I will check. Looking at other exceptions in this area anyway.

**Comment by joewiz** [comment]
Thanks, @ljo. If the error reported by the stacktrace isn't a problem, the original problem that prompted this thread is that the keyword analyzer — like the whitespace analyzer reported in #795 — isn't working.  For example, given a collection.xconf like this:

```
<collection xmlns="http://exist-db.org/collection-config/1.0" xmlns:test="test">
    <index xmlns:xs="http://www.w3.org/2001/XMLSchema">
        <fulltext default="none" attributes="false"/>
        <lucene>
            <analyzer="org.apache.lucene.analysis.standard.StandardAnalyzer"/>
            <analyzer id="ws" class="org.apache.lucene.analysis.core.WhitespaceAnalyzer"/>
            <analyzer id="keyword" class="org.apache.lucene.analysis.core.KeywordAnalyzer"/>
            <text qname="test:para"/>
            <text qname="test:para" field="para-standard"/>
            <text qname="test:para" field="para-ws" analyzer="ws"/>
            <text qname="test:para" field="para-keyword" analyzer="keyword"/>
        </lucene>
    </index>
</collection>
```

and a test file like this:

```xml
<doc xmlns="test">
    <para>Hello, my name is Joe.</para>
</doc>
```

The following query returns 0 results:

```xquery
ft:query-field('para-keyword', 'Hello, my name is Joe.')
```

**Comment by joewiz** [comment]
(Confirmed by @jensopetersen.)

**Comment by adamretter** [comment]
@joewiz Can you confirm if this is still a problem?

**Comment by duncdrum** [comment]
@joewiz ?

**Comment by joewiz** [comment]
Yes, I can confirm this is still a problem with develop-4.x.x. A quick self-contained adaptation of the test [from above](https://github.com/eXist-db/exist/issues/794#issuecomment-142620973) is:

```xquery
xquery version "3.1";

let $setup := 
    (
        xmldb:create-collection("/db", "test"),
        xmldb:create-collection("/db/system/config/db", "test")
    )
let $xconf := 
    <collection xmlns="http://exist-db.org/collection-config/1.0" xmlns:test="test">
        <index xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <fulltext default="none" attributes="false"/>
            <lucene>
                <analyzer class="org.apache.lucene.analysis.standard.StandardAnalyzer"/>
                <analyzer id="ws" class="org.apache.lucene.analysis.core.WhitespaceAnalyzer"/>
                <analyzer id="keyword" class="org.apache.lucene.analysis.core.KeywordAnalyzer"/>
                <text qname="test:para"/>
                <text qname="test:para" field="para-standard"/>
                <text qname="test:para" field="para-ws" analyzer="ws"/>
                <text qname="test:para" field="para-keyword" analyzer="keyword"/>
            </lucene>
        </index>
    </collection>
let $data := 
    <doc xmlns="test">
        <para>Hello, my name is Joe.</para>
    </doc>
let $store :=
    (
        xmldb:store("/db/system/config/db/test", "collection.xconf", $xconf),
        xmldb:store("/db/test", "test.xml", $data)
    )
return
    ft:query-field("para-keyword", "Hello, my name is Joe.")
```

This query returns 0 results, instead of the expected one result, `<para xmlns="test">Hello, my name is Joe.</para>`.

Thus, the problem remains that the keyword analyzer returns 0 results.

**Comment by duncdrum** [comment]
@joewiz can you prepare a PR with a pending test that mentions this issue pls?

**Comment by dizzzz** [comment]
Hmmm I need to check the code... again. I think we see a logging of a fallback mechanism. Step one fails and the second attempt, different interface probably works. I remember a discussion with @adamretter some time ago...

**Comment by joewiz** [comment]
The source of the problem refined in my most recent note above is that the Lucene query syntax parser tokenizes the query string, making the "query syntax" method incompatible with the keywordAnalyzer. This is a limitation of Lucene, not eXist, and it's described here: http://lucene.472066.n3.nabble.com/KeywordAnalyzer-still-getting-tokenized-on-spaces-td4157537.html.  Luckily, there is a workaround: using the XML syntax for supplying values for the keywordAnalyzer-backed indexes. Since the problem is gone and the functions used in my example will shortly be deprecated by https://github.com/eXist-db/exist/pull/2614 (specifically, see this test added in https://github.com/eXist-db/exist/pull/2614/commits/74e58c3c9f6dcd15a6ee79f4b9781c4ab621dd96#diff-440556e00f506de4aca56cb7e9f4eedeR413), there's absolutely no use in keeping this issue open. There are many other reasons for excitement about #2614, but this certainly is one!
