### ISSUE TITLE
NPE when uploading a file to replace an existing file over WebDAV

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#835]
Steps to reproduce: Using the current develop branch, upload any XML document (e.g., `test.xml`) to the db (e.g., `/db/test.xml`) via WebDAV. This works. Upload it a second time: error 500, with exist.log showing the following error:

```
2015-11-18 10:59:01,434 [eXistThread-41] INFO  (MiltonResource.java [authorise]:351) - PUT /db (write=true) 
2015-11-18 10:59:05,938 [eXistThread-42] INFO  (HttpManager.java [process]:213) - PUT :: http://localhost:8080/exist/webdav/db/test.xml - http://localhost:8080/exist/webdav/db/test.xml 
2015-11-18 10:59:05,939 [eXistThread-42] ERROR (StandardFilter.java [process]:68) - process 
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_45]
	at java.util.Optional.<init>(Optional.java:96) ~[?:1.8.0_45]
	at java.util.Optional.of(Optional.java:108) ~[?:1.8.0_45]
	at org.exist.webdav.ExistDocument.getCurrentLock(ExistDocument.java:298) ~[exist-webdav.jar:?]
	at org.exist.webdav.MiltonDocument.getCurrentLock(MiltonDocument.java:503) ~[exist-webdav.jar:?]
	at com.bradmcevoy.http.HandlerHelper.isLockedOut(HandlerHelper.java:152) ~[milton-api-1.8.1.3.jar:?]
	at com.bradmcevoy.http.http11.PutHandler.process(PutHandler.java:109) ~[milton-api-1.8.1.3.jar:?]
	at com.bradmcevoy.http.StandardFilter.process(StandardFilter.java:52) [milton-api-1.8.1.3.jar:?]
	at com.bradmcevoy.http.FilterChain.process(FilterChain.java:40) [milton-api-1.8.1.3.jar:?]
	at com.bradmcevoy.http.HttpManager.process(HttpManager.java:228) [milton-api-1.8.1.3.jar:?]
	at com.bradmcevoy.http.MiltonServlet.service(MiltonServlet.java:195) [milton-servlet-1.8.1.3.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575) [jetty-security-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:229) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:103) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.exist.http.urlrewrite.Forward.doRewrite(Forward.java:50) [exist-optional.jar:?]
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:221) [exist-optional.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [servlet-api-3.0.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533) [jetty-security-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.Server.handle(Server.java:370) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865) [jetty-http-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) [jetty-http-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696) [jetty-io-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53) [jetty-io-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [jetty-util-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [jetty-util-8.1.17.v20150415.jar:8.1.17.v20150415]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

**Comment by joewiz** [comment]
(Note: I've updated the description with steps to reproduce and the output from exist.log.)

**Comment by joewiz** [comment]
(Note: I've updated the title to include "NPE".)

**Comment by joewiz** [comment]
I noticed the same problem when renaming a resource with WebDAV:

```
2015-11-27 15:05:00,430 [eXistThread-43] INFO  (MiltonResource.java [authorise]:351) - MOVE /db/apps/twitter/untitled%20folder (write=true) 
2015-11-27 15:05:00,430 [eXistThread-43] ERROR (StandardFilter.java [process]:68) - process 
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_45]
	at java.util.Optional.<init>(Optional.java:96) ~[?:1.8.0_45]
	at java.util.Optional.of(Optional.java:108) ~[?:1.8.0_45]
	at org.exist.webdav.ExistCollection.getCollectionURIs(ExistCollection.java:142) ~[exist-webdav.jar:?]
	at org.exist.webdav.MiltonCollection.getCollectionResources(MiltonCollection.java:156) ~[exist-webdav.jar:?]
	at org.exist.webdav.MiltonCollection.getChildren(MiltonCollection.java:177) ~[exist-webdav.jar:?]
	at org.exist.webdav.MiltonCollection.child(MiltonCollection.java:143) ~[exist-webdav.jar:?]
	at com.bradmcevoy.http.webdav.MoveHandler.processExistingResource(MoveHandler.java:97) ~[milton-api-1.8.1.3.jar:?]
	at com.bradmcevoy.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:149) ~[milton-api-1.8.1.3.jar:?]
	at com.bradmcevoy.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:95) ~[milton-api-1.8.1.3.jar:?]
	at com.bradmcevoy.http.webdav.MoveHandler.processResource(MoveHandler.java:70) ~[milton-api-1.8.1.3.jar:?]
	at com.bradmcevoy.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:91) ~[milton-api-1.8.1.3.jar:?]
	at com.bradmcevoy.http.webdav.MoveHandler.process(MoveHandler.java:75) ~[milton-api-1.8.1.3.jar:?]
	at com.bradmcevoy.http.StandardFilter.process(StandardFilter.java:52) [milton-api-1.8.1.3.jar:?]
	at com.bradmcevoy.http.FilterChain.process(FilterChain.java:40) [milton-api-1.8.1.3.jar:?]
	at com.bradmcevoy.http.HttpManager.process(HttpManager.java:228) [milton-api-1.8.1.3.jar:?]
	at com.bradmcevoy.http.MiltonServlet.service(MiltonServlet.java:195) [milton-servlet-1.8.1.3.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575) [jetty-security-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:229) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:103) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.exist.http.urlrewrite.Forward.doRewrite(Forward.java:50) [exist-optional.jar:?]
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:221) [exist-optional.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [servlet-api-3.0.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533) [jetty-security-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.Server.handle(Server.java:370) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644) [jetty-http-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235) [jetty-http-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696) [jetty-io-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53) [jetty-io-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [jetty-util-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [jetty-util-8.1.17.v20150415.jar:8.1.17.v20150415]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
 ```

**Comment by dizzzz** [comment]
Ok, thnx for reporting! It seems to be related to some recent changes where java8's Optional is used (introduced by @adamretter ?). This must be fixed for 3.0 for sure .

**Comment by adamretter** [comment]
@joewiz Sorry about that.

@dizzzz When I read the WebDAV code, I thought that `subject` was immutable and not-nullable, and when I ran the test suite and everything passed I assumed everything was fine. At a closer look, it seems that I was mistaken, here is a fix - https://github.com/eXist-db/exist/pull/841
Also I can't seem to find any tests at all for WebDAV, I can't believe that is the case... so what am I missing?

**Comment by joewiz** [comment]
@adamretter Thanks so much! I've tested your branch and can confirm that my problem is fixed. I tested upload, move, rename, and delete - and all work as expected.

**Comment by dizzzz** [comment]
No there are WebDAV tests, they have been on my wish list for a long time. That said, the issues that i fixed overtime were often specific client issues.

There is a more or less official test suite for webdav interfaces but is is not very great.

**Comment by adamretter** [comment]
Okay cool. Do you want to merge it?

On Saturday, 28 November 2015, Joe Wicentowski <notifications@github.com>
wrote:

> @adamretter <https://github.com/adamretter> Thanks so much! I've tested
> your branch and can confirm that my problem is fixed. I tested upload,
> move, rename, and delete - and all work as expected.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eXist-db/exist/issues/835#issuecomment-160307024>.
>


-- 
Adam Retter

skype: adam.retter
tweet: adamretter
http://www.adamretter.org.uk

**Comment by joewiz** [comment]
Thanks, Adam, Dannes, and Wolfgang!
