### ISSUE TITLE
eXist 3.0 RC1 doesn't start

### ISSUE THREAD

**Issue by StephanMa** [eXist-db/exist#844]
Dear Community,

yesterday i tried to start a fresh build of eXist 3.0 RC1 (dev 8b8fb2e).
Starting eXist with `sudo java -jar start.jar` doesn't work.
The Splashscreen appears but the server is not started.

The eXist-Log throws just one Error
"ERROR (Configuration.java [lookupModuleClass]:449) - Configuration problem: class not found for module 'http://exist-db.org/xquery/jndi' (ClassNotFoundException); class:'org.exist.xquery.modules.jndi.JNDIModule'; message:'org.exist.xquery.modules.jndi.JNDIModule' "

System:
Ubuntu 14.04
Java 8 (1.8.0_66-b17)

Best wishes from Germany
Stephan

**Comment by dizzzz** [comment]
What modules did you explicitly set in conf.xml ?

**Comment by StephanMa** [comment]
I haven't changed anything. Just cloned and installed it without any changes. 
JNDI is enabled in this version.

I temporary deleted this line in the conf.xml. The error disappears but the Server does not start either.

`
            <module uri="http://exist-db.org/xquery/contentextraction"  class="org.exist.contentextraction.xquery.ContentExtractionModule" />

            

            <module uri="http://exist-db.org/xquery/counter"            class="org.exist.xquery.modules.counter.CounterModule" />

            <module uri="http://exist-db.org/xquery/datetime"           class="org.exist.xquery.modules.datetime.DateTimeModule" />

            <module uri="http://exist-db.org/xquery/httpclient"         class="org.exist.xquery.modules.httpclient.HTTPClientModule" />

            <module uri="http://exist-db.org/xquery/image"              class="org.exist.xquery.modules.image.ImageModule" />

            

            <module uri="http://exist-db.org/xquery/mail"               class="org.exist.xquery.modules.mail.MailModule" />

            <module uri="http://exist-db.org/xquery/scheduler"          class="org.exist.xquery.modules.scheduler.SchedulerModule" />

            <module uri="http://exist-db.org/xquery/sql"                class="org.exist.xquery.modules.sql.SQLModule" />

            

            <module uri="http://exist-db.org/xquery/xmldiff"            class="org.exist.xquery.modules.xmldiff.XmlDiffModule" />`

**Comment by joewiz** [comment]
After you cloned the repo did you run build.sh/.bat?

**Comment by StephanMa** [comment]
Yes, i run build.sh.

The building process afterwards was without any errors. And as i mentioned.... when i run `sudo java -jar start.jar` everything seems to went well. Unfortunately it does not start completely and it stucks at the Splashscreen.

Its not that urgent. But i wanted to report it in case that its not just my fault....

**Comment by ChiSamurai** [comment]
Same error on jndi here (after 'build.sh rebuild' ), too. Though on my machine 'java -jar start.jar' works and starts DB without any significant problem...

**Comment by joewiz** [comment]
How odd...  Another troubleshooting step: before rebuilding could you do `build.sh clean-all` please?

**Comment by ChiSamurai** [comment]
hmmm.. this drops my database, doesnt it? I could try it on a plain one it you like...

**Comment by ChiSamurai** [comment]
Build of clean checkout (develop branch) leads to that JNDI error:

```
2015-12-04 10:48:04,932 [AWT-EventQueue-0] ERROR (Configuration.java [lookupModuleClass]:449) - Configuration problem: class not found for module 'http://exist-db.org/xquery/jndi' (ClassNotFoundException); class:'org.exist.xquery.modules.jndi.JNDIModule'; message:'org.exist.xquery.modules.jndi.JNDIModule' 
2015-12-04 10:48:05,230 [Thread-4] ERROR (Configuration.java [lookupModuleClass]:449) - Configuration problem: class not found for module 'http://exist-db.org/xquery/jndi' (ClassNotFoundException); class:'org.exist.xquery.modules.jndi.JNDIModule'; message:'org.exist.xquery.modules.jndi.JNDIModule'
```

@joewiz: I could send you the build log if you want. There are some errors like

```
[ivy:retrieve] :: problems summary ::
[ivy:retrieve] :::: ERRORS
[ivy:retrieve]  unknown resolver chain
[ivy:retrieve]  unknown resolver chain
[ivy:retrieve]  unknown resolver chain
```
I'm not familiar with the build process nor sure if related to that issue.

But: eXist starts with java -jar start.jar without problems.

**Comment by joewiz** [comment]
Just to confirm, I assume you haven't modified your $EXIST_HOME/extensions/build.properties or added your own local.build.properties in the same folder?  If you have changed these files, please state where.  But when you said "fresh checkout" I assumed you meant no modifications.

**Comment by joewiz** [comment]
(I guess this is progress, though - despite the build errors related to JNDI, you're able to start the db normally...)

**Comment by StephanMa** [comment]
Well for me, i haven't changed anything. 

But, other then ChiSamurai, eXist doesn't seem to startup.
Tested different times in a VM or on my Testnotebook.

**Comment by ChiSamurai** [comment]
no, i did very new checkout and build.properties are untouched. no modifications to any file at all.

**Comment by pherk** [comment]
I'm not shure if my problem is the same:
I did clean build of today's develop branch (RC2)
the JNDI error (class not found) persists,
despite this the server starts
... but I cannot login via dashboard (admin, guest passswords should be blank after clean build)
exist log shows:
2016-01-07 09:16:49,733 [eXistThread-26] WARN  (ServletHandler.java [doHandle]:538) -  
javax.servlet.ServletException: An error occurred while processing request to /exist/apps/dashboard/plugins/userManager/api/user/: exerr:ERROR You must be an authenticated user [at line 44, column 17, source: /db/apps/dashboard/plugins/userManager/userManager.xqm]

... restoring a existdb2-2master backup completes (after build.sh clean-default-data-dir),
but the login problem persists
... oddly, after refreshing the webpage the login top left is showing admin, but all further action on dashboard fail

regards 
Peter

**Comment by dizzzz** [comment]
Please could you clean your browser cache?

**Comment by pherk** [comment]
already done (Cache, Cookies, Browser-Data cleared), but same picture
- Login error
- after refresh "admin" as logged in but no actions possible

Peter

Ubuntu 14.04LTS, Java8, FF43

Quoting Dannes Wessels <notifications@github.com>:

**Comment by dizzzz** [comment]
@pherk I'd prefer not to hijack this thread :-)
please start a new thread,  and verify if you have any plugin in the browser that blocks javascript,  ads,  etc; please switch them all off.

**Comment by StephanMa** [comment]
Well i will take the opportunity to give you a small feedback.

Now i am using the Version 3.0.RC2 (develop-503ad32).

The log says still the same 
"Configuration problem: class not found for module 'http://exist-db.org/xquery/jndi' (ClassNotFoundException); class:'org.exist.xquery.modules.jndi.JNDIModule'; message:'org.exist.xquery.modules.jndi.JNDIModule' "

No changes were made to any of the conf-Files.
Just plain cloning and ./build.sh

System:
Ubuntu 15.10
Java 1.8.0_74

**Comment by StephanMa** [comment]
2016-04-06 15:59:21,405 [WrapperListener_start_runner] WARN  (WebAppContext.java [doStart]:503) - Failed startup of context eXist-db Open Source Native XML Database 
javax.servlet.UnavailableException: org.directwebremoting.servlet.DwrServlet
	at org.eclipse.jetty.servlet.Holder.doStart(Holder.java:114) ~[jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:298) ~[jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) ~[jetty-util-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:791) ~[jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265) ~[jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242) ~[jetty-webapp-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717) ~[jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494) [jetty-webapp-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.Server.doStart(Server.java:282) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.exist.jetty.JettyStart.run(JettyStart.java:199) [exist-optional.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at org.exist.wrapper.Main.start(Main.java:95) [classes/:?]
	at org.tanukisoftware.wrapper.WrapperManager$10.run(WrapperManager.java:4163) [wrapper.jar:3.5.26]

**Comment by tuurma** [comment]
this issue seems no longer relevant, hopefully @StephanMa would be willing to test new 3.0 release?

**Comment by dizzzz** [comment]
ah... so with 'sudo' it works? Please chown all files to the current user. Probably some crucial files are readonly for the user.

**Comment by joewiz** [comment]
Closing due to lack of response from user reporting the problem. I assume the issue no longer affects 3.x releases. Please open a new issue if you experience this problem with 3.4.0+.
