### ISSUE TITLE
NPE in Modification (sometimes)

### ISSUE THREAD

**Issue by alebastrov** [eXist-db/exist#855]
```
java.lang.NullPointerException
        at org.exist.xupdate.Modification.selectAndLock(Modification.java:249)
        at org.exist.xupdate.Append.process(Append.java:77)
        at org.exist.xmldb.LocalXUpdateQueryService.updateResource(LocalXUpdateQueryService.java:91)
        at org.exist.xmldb.LocalXUpdateQueryService.update(LocalXUpdateQueryService.java:139)
        at org.exist.xquery.functions.xmldb.XMLDBXUpdate.evalWithCollection(XMLDBXUpdate.java:97)
        at org.exist.xquery.functions.xmldb.XMLDBAbstractCollectionManipulator.eval(XMLDBAbstractCollectionManipulator.java:173)
        at org.exist.xquery.BasicFunction.eval(BasicFunction.java:70)
        at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:56)
        at org.exist.xquery.LetExpr.eval(LetExpr.java:142)
        at org.exist.xquery.LetExpr.eval(LetExpr.java:187)
        at org.exist.xquery.LetExpr.eval(LetExpr.java:187)
        at org.exist.xquery.LetExpr.eval(LetExpr.java:187)
        at org.exist.xquery.LetExpr.eval(LetExpr.java:187)
        at org.exist.xquery.BindingExpression.eval(BindingExpression.java:164)
        at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:100)
        at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
        at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:65)
```

**Comment by adamretter** [comment]
Which version of eXist emitted this stacktrace? In the HEAD of develop there is nothing on line 249 of org.exist.xupdate.Modification

**Comment by alebastrov** [comment]
~~~
final StoredNode ql[] = new StoredNode[nl.getLength()];		    
			for (int i = 0; i < ql.length; i++) {
				ql[i] = (StoredNode)nl.item(i);
				if (ql[i] == null) continue;
				final DocumentImpl doc = (DocumentImpl)ql[i].getOwnerDocument();
				
				// call the eventual triggers
				// TODO -jmv separate loop on docs and not on nodes
			
				//prepare Trigger
				prepareTrigger(transaction, doc);
			}
~~~

**Comment by alebastrov** [comment]
I added if (ql[i] == null) continue;
to prevent NPE

**Comment by dizzzz** [comment]
please could you confirm the eXist-db version?

**Comment by alebastrov** [comment]
2.2

**Comment by duncdrum** [comment]
@alebastrov can you confirm this still to be an issue for 4.x ?

**Comment by dizzzz** [comment]
eXist-db v2.x is very old, the core has been changed a lot since then.
