### ISSUE TITLE
client.sh URISyntaxException

### ISSUE THREAD

**Issue by pherk** [eXist-db/exist#896]
I use client.sh with -x -ouri=xmldb:exist:// parameters without problems,
therefore the following error surprises me:

./bin/client.sh -u admin -P xxxxxx -s -ouri=xmldb:exist://
-u admin -P xxxx -s -ouri=xmldb:exist://
Using locale: en_US.UTF-8
eXist version 3.0.RC2 (develop-1f14fa6), Copyright (C) 2001-2016 The eXist-db Project
eXist-db comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; for details read the license file.

Connecting to database...
Connected :-)

type help or ? for help.
exist:/db>help
Expected authority at index 8: exist://
java.net.URISyntaxException: Expected authority at index 8: exist://
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.failExpecting(URI.java:2854)
        at java.net.URI$Parser.parseHierarchical(URI.java:3102)
        at java.net.URI$Parser.parse(URI.java:3053)
        at java.net.URI.<init>(URI.java:588)
        at org.exist.xmldb.XmldbURI.<init>(XmldbURI.java:152)
        at org.exist.xmldb.FullXmldbURI.<init>(FullXmldbURI.java:44)
        at org.exist.xmldb.FullXmldbURI.<init>(FullXmldbURI.java:40)
        at org.exist.xmldb.XmldbURI.getXmldbURI(XmldbURI.java:237)
        at org.exist.xmldb.XmldbURI.xmldbUriFor(XmldbURI.java:180)
        at org.exist.xmldb.XmldbURI.xmldbUriFor(XmldbURI.java:172)
        at org.exist.client.InteractiveClient.process(InteractiveClient.java:521)
        at org.exist.client.InteractiveClient.readlineInputLoop(InteractiveClient.java:2596)
        at org.exist.client.InteractiveClient.run(InteractiveClient.java:2498)
        at org.exist.client.InteractiveClient.main(InteractiveClient.java:269)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.exist.start.Main.invokeMain(Main.java:126)
        at org.exist.start.Main.run(Main.java:454)
        at org.exist.start.Main.main(Main.java:50)

Ubuntu 14.04LTS, RC2 develop, Java1.8_72

regards
Peter

**Comment by dizzzz** [comment]
Hi,

I think another / is needed on the end, reflecting a 'no host name' ....

regards
Dannes

--
www.exist-db.org

**Comment by dizzzz** [comment]
please respond?

**Comment by pherk** [comment]
yes, with another / client.sh connects properly
With two / it says also: Connected :-) but is not  
NB
-ouri=xmldb:exist://localhost:8080/exist/xmlrpc       gives "Connection refused" to me
-l     connects properly

regards 
Peter

**Comment by duncdrum** [comment]
if the client says 
```
Connecting to database...
Connected :-)
```

you should be connected imv.

**Comment by line-o** [comment]
I think this issue can safely be closed
