### ISSUE TITLE
Importing backup fails with java-stacktrace

### ISSUE THREAD

**Issue by thomasmeeus** [eXist-db/exist#911]
Hi,

I took a backup of an empty exist-database. The only value changed is the admin password. I now want to import the backup on a new server. Both servers are using eXist-2.2 and were installed using default settings.

It appears that the import is successful, but that some kind of automatic maintenance task after the import is still using the old admin-password and fails.

```
[root@localhost bin]# ./backup.sh -u admin -r /home/vagrant/
WARNING: JAVA_HOME not found in your environment.

Please, set the JAVA_HOME variable in your enviroment to match the
location of the Java Virtual Machine you want to use in case of run
fail.
Using locale: en_US.UTF-8
Starting restore of backup...
Processing backup: /home/vagrant/db/__contents__.xml
Creating collection /db/system/security/exist
Feb 10, 2016 1:45:43 PM org.expath.pkg.repo.util.Logger info
INFO: Create a new repository with storage: File system storage in /opt/existdb/webapp/WEB-INF/data/expathrepo
Loading mime table from file /opt/existdb/mime-types.xml
Processing backup: /home/vagrant/db/groups/__contents__.xml
Creating collection /db/system/security/exist/groups
2016-02-10 13:45:47,974 ERROR [org.exist.security.SecurityManager] : Group 'eXide' pressent at 'exist' realm, but get event that new one created.
 Restored eXide.xml
Processing backup: /home/vagrant/db/groups/removed/__contents__.xml
Creating collection /db/system/security/exist/groups/removed
Processing backup: /home/vagrant/db/accounts/__contents__.xml
Creating collection /db/system/security/exist/accounts
Restored guest.xml
Restored eXide.xml
Processing backup: /home/vagrant/db/accounts/removed/__contents__.xml
Creating collection /db/system/security/exist/accounts/removed
Restored admin.xml
Finished restore of backup.

If you restored collections inside /db/apps, you may want
to rebuild the application repository. To do so, run the following query
as admin:

import module namespace repair="http://exist-db.org/xquery/repo/repair"
at "resource:org/exist/xquery/modules/expathrepo/repair.xql";
repair:clean-all(),
repair:repair()

org.xmldb.api.base.XMLDBException: Wrong password for user [admin] 
    at org.exist.xmldb.DatabaseImpl.getUser(DatabaseImpl.java:304)
    at org.exist.xmldb.DatabaseImpl.getLocalCollection(DatabaseImpl.java:195)
    at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:162)
    at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:153)
    at org.xmldb.api.DatabaseManager.getCollection(Unknown Source)
    at org.exist.backup.Main.process(Main.java:321)
    at org.exist.backup.Main.main(Main.java:488)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.exist.start.Main.invokeMain(Main.java:126)
    at org.exist.start.Main.run(Main.java:448)
    at org.exist.start.Main.main(Main.java:50)
Caused by: org.exist.security.AuthenticationException: Wrong password for user [admin] 
    at org.exist.security.internal.RealmImpl.authenticate(RealmImpl.java:295)
    at org.exist.security.internal.SecurityManagerImpl.authenticate(SecurityManagerImpl.java:446)
    at org.exist.xmldb.DatabaseImpl.getUser(DatabaseImpl.java:302)
    ... 13 more
[B@7b55d5d0org.exist.security.AuthenticationException: Wrong password for user [admin] 
    at org.exist.security.internal.RealmImpl.authenticate(RealmImpl.java:295)
    at org.exist.security.internal.SecurityManagerImpl.authenticate(SecurityManagerImpl.java:446)
    at org.exist.xmldb.DatabaseImpl.getUser(DatabaseImpl.java:302)
    at org.exist.xmldb.DatabaseImpl.getLocalCollection(DatabaseImpl.java:195)
    at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:162)
    at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:153)
    at org.xmldb.api.DatabaseManager.getCollection(Unknown Source)
    at org.exist.backup.Main.process(Main.java:321)
    at org.exist.backup.Main.main(Main.java:488)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.exist.start.Main.invokeMain(Main.java:126)
    at org.exist.start.Main.run(Main.java:448)
    at org.exist.start.Main.main(Main.java:50)
Caused by: org.exist.security.AuthenticationException: Wrong password for user [admin] 
    at org.exist.security.internal.RealmImpl.authenticate(RealmImpl.java:295)
    at org.exist.security.internal.SecurityManagerImpl.authenticate(SecurityManagerImpl.java:446)
    at org.exist.xmldb.DatabaseImpl.getUser(DatabaseImpl.java:302)
    at org.exist.xmldb.DatabaseImpl.getLocalCollection(DatabaseImpl.java:195)
    at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:162)
    at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:153)
    at org.xmldb.api.DatabaseManager.getCollection(Unknown Source)
    at org.exist.backup.Main.process(Main.java:321)
    at org.exist.backup.Main.main(Main.java:488)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.exist.start.Main.invokeMain(Main.java:126)
    at org.exist.start.Main.run(Main.java:448)
    at org.exist.start.Main.main(Main.java:50)
caused by 
org.exist.security.AuthenticationException: Wrong password for user [admin] 
    at org.exist.security.internal.RealmImpl.authenticate(RealmImpl.java:295)
    at org.exist.security.internal.SecurityManagerImpl.authenticate(SecurityManagerImpl.java:446)
    at org.exist.xmldb.DatabaseImpl.getUser(DatabaseImpl.java:302)
    at org.exist.xmldb.DatabaseImpl.getLocalCollection(DatabaseImpl.java:195)
    at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:162)
    at org.exist.xmldb.DatabaseImpl.getCollection(DatabaseImpl.java:153)
    at org.xmldb.api.DatabaseManager.getCollection(Unknown Source)
    at org.exist.backup.Main.process(Main.java:321)
    at org.exist.backup.Main.main(Main.java:488)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.exist.start.Main.invokeMain(Main.java:126)
    at org.exist.start.Main.run(Main.java:448)
    at org.exist.start.Main.main(Main.java:50)
```

**Comment by dizzzz** [comment]
I'd expect you need to pass a -P options to set a password..... but you are restoring to an empty database? hmmm I did not see this before....

**Comment by thomasmeeus** [comment]
True, but the initial clean database has no password set for the admin user
so this parameter doesn't work. Let me clarify my situation:

I'm packaging ExistDB as an RPM and I want to set a database password when
ExistDB gets installed. Configuring a password seems only possible using
the GUI or via an interactive shell which we can't use in our case.

As a workaround for this I was trying to install ExistDB manually using the
GUI, set a database password and export the database. During the packaging
of ExistDB as an RPM I then can restore the database dump (containing an
admin user with password) on the new database that the fresh install of
ExistDB has created (having an admin user without password). This restore
is done using the command above.

The import seems to go ok since the output lists 'Finished restore of
backup.', but the restore command appears to execute one final command that
fails. Since the command returns exit code 1, the RPM-build fails. I
suspect that at the end the import-process is opening a new DB-connection
using the old connection string without an admin-password specified, while
the new credentials are already in place.

**Comment by dizzzz** [comment]
there is another option: the eXist-db installer asks for the admin password, starts the databqse in embedded mode, configures the password, and shuts it down;

could could use the same approach?

**Comment by thomasmeeus** [comment]
That might be a solution. Can you clarify which parameters for the `build.sh` command are required to let the installer ask for the admin password? I can't find such a feature in the documentation: http://www.exist-db.org/exist/apps/doc/building.xml

**Comment by duncdrum** [comment]
there have been numerous changes since `2.2` backup will work differently again in `5.0.0` so unless this is still an issue going to close soon.
