### ISSUE TITLE
NPE in security manager @restore

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#972]
in current 'develop'

```
2016-04-11 13:55:55,991 [main] INFO  (Configurator.java [save]:1278) - Storing configuration /db/system/security/exist/accounts/eXide.xml 
2016-04-11 13:55:55,993 [main] INFO  (NativeBroker.java [removeXMLResource]:2645) - Removing document eXide.xml (542) ... 
2016-04-11 13:55:57,520 [main] WARN  (TransactionManager.java [close]:257) - Transaction was not committed or aborted, auto aborting! 
2016-04-11 13:56:14,326 [pool-3-thread-1] INFO  (Configurator.java [save]:1278) - Storing configuration /db/system/security/exist/accounts/admin.xml 
2016-04-11 13:56:14,336 [pool-3-thread-1] INFO  (NativeBroker.java [removeXMLResource]:2645) - Removing document admin.xml (5) ... 
2016-04-11 13:56:14,375 [pool-3-thread-1] INFO  (NativeBroker.java [removeXMLResource]:2645) - Removing document config.xml (4) ... 
2016-04-11 13:56:14,388 [pool-3-thread-1] INFO  (NativeBroker.java [removeXMLResource]:2645) - Removing document admin.xml (5) ... 
2016-04-11 13:56:14,399 [pool-3-thread-1] INFO  (NativeBroker.java [removeXMLResource]:2645) - Removing document guest.xml (6) ... 
2016-04-11 13:56:14,419 [pool-3-thread-1] INFO  (NativeBroker.java [removeXMLResource]:2645) - Removing document eXide.xml (542) ... 
2016-04-11 13:56:14,432 [pool-3-thread-1] ERROR (DocumentTriggers.java [afterCreateDocument]:238) - null 
java.lang.NullPointerException
    at org.exist.security.internal.SecurityManagerImpl.lambda$processPramatter$225(SecurityManagerImpl.java:934) ~[exist.jar:?]
    at org.exist.security.internal.SecurityManagerImpl$PrincipalDbById.modify(SecurityManagerImpl.java:1047) ~[exist.jar:?]
    at org.exist.security.internal.SecurityManagerImpl.processPramatter(SecurityManagerImpl.java:933) ~[exist.jar:?]
    at org.exist.config.ConfigurationDocumentTrigger.afterCreateDocument(ConfigurationDocumentTrigger.java:148) ~[exist.jar:?]
    at org.exist.collections.triggers.DocumentTriggers.afterCreateDocument(DocumentTriggers.java:236) ~[exist.jar:?]
    at org.exist.collections.Collection.storeXMLInternal(Collection.java:1399) ~[exist.jar:?]
    at org.exist.collections.Collection.store(Collection.java:1211) ~[exist.jar:?]
    at org.exist.xmldb.LocalCollection.lambda$storeXMLResource$300(LocalCollection.java:597) ~[exist.jar:?]
    at org.exist.xmldb.function.LocalXmldbCollectionFunction.apply(LocalXmldbCollectionFunction.java:48) ~[exist.jar:?]
    at org.exist.xmldb.LocalCollection.lambda$null$309(LocalCollection.java:739) ~[exist.jar:?]
    at org.exist.xmldb.function.LocalXmldbCollectionFunction.apply(LocalXmldbCollectionFunction.java:48) ~[exist.jar:?]
    at org.exist.xmldb.AbstractLocal.lambda$with$274(AbstractLocal.java:172) ~[exist.jar:?]
    at org.exist.xmldb.AbstractLocal.lambda$null$272(AbstractLocal.java:118) ~[exist.jar:?]
    at org.exist.xmldb.function.LocalXmldbFunction.apply(LocalXmldbFunction.java:46) ~[exist.jar:?]
    at org.exist.xmldb.AbstractLocal.withDb(AbstractLocal.java:195) ~[exist.jar:?]
    at org.exist.xmldb.AbstractLocal.lambda$modify$273(AbstractLocal.java:118) ~[exist.jar:?]
    at org.exist.xmldb.LocalCollection.lambda$modify$310(LocalCollection.java:737) ~[exist.jar:?]
    at org.exist.xmldb.LocalCollection.storeXMLResource(LocalCollection.java:566) ~[exist.jar:?]
    at org.exist.xmldb.LocalCollection.storeResource(LocalCollection.java:516) ~[exist.jar:?]
    at org.exist.backup.restore.RestoreHandler.restoreResourceEntry(RestoreHandler.java:392) ~[exist.jar:?]
    at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:122) ~[exist.jar:?]
    at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.exist.backup.restore.RestoreHandler.restoreSubCollectionEntry(RestoreHandler.java:255) ~[exist.jar:?]
    at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:128) ~[exist.jar:?]
    at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.exist.backup.restore.RestoreHandler.restoreSubCollectionEntry(RestoreHandler.java:255) ~[exist.jar:?]
    at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:128) ~[exist.jar:?]
    at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.exist.backup.restore.RestoreHandler.restoreSubCollectionEntry(RestoreHandler.java:255) ~[exist.jar:?]
    at org.exist.backup.restore.RestoreHandler.startElement(RestoreHandler.java:128) ~[exist.jar:?]
    at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.exist.backup.Restore.restore(Restore.java:87) ~[exist.jar:?]
    at org.exist.client.ClientFrame.lambda$doRestore$65(ClientFrame.java:1161) ~[exist.jar:?]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_65]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_65]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
2016-04-11 13:56:14,451 [pool-3-thread-1] INFO  (NativeBroker.java [removeXMLResource]:2645) - Removing document eXide.xml (541) ... 
2016-04-11 13:56:14,454 [pool-3-thread-1] ERROR (SecurityManagerImpl.java [processPramatter]:962) - Group 'eXide' pressent at 'exist' realm, but get event that new one created. 
2016-04-11 13:56:14,490 [pool-3-thread-1] INFO  (NativeBroker.java [removeXMLResource]:2645) - Removing document collection.xconf (1) ... 
2016-04-11 13:56:14,498 [pool-3-thread-1] WARN  (TransactionManager.java [close]:257) - Transaction was not committed or aborted, auto aborting! 
2016-04-11 13:56:14,504 [pool-3-thread-1] WARN  (TransactionManager.java [close]:257) - Transaction was not committed or aborted, auto aborting! 
2016-04-11 13:56:14,510 [pool-3-thread-1] WARN  (TransactionManager.java [close]:257) - Transaction was not committed or aborted, auto aborting! 
2016-04-11 13:56:14,532 [pool-3-thread-1] WARN  (TransactionManager.java [close]:257) - Transaction was not committed or aborted, auto aborting! 
2016-04-11 13:56:14,550 [pool-3-thread-1] WARN  (TransactionManager.java [close]:257) - Transaction was not committed or aborted, auto aborting! 
2016-04-11 13:56:14,567 [pool-3-thread-1] INFO  (NativeBroker.java [removeXMLResource]:2645) - Removing document collection.xconf (404) ... 
```

**Comment by adamretter** [comment]
@dizzzz any idea how I can reproduce this?

**Comment by dizzzz** [comment]
- rebuild exist-db, remove data
- start exist-db `java -jar start.jar`, have databse initialized
- stop exist-db
- start eXist-db with `build.sh -l`
- restore a backup (I used one that required a password)
- `exist.log` shows the exception

**Comment by duncdrum** [comment]
please reopen this ticket if the issue persists on the current major version.
