### ISSUE TITLE
shutdown deadlock

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#992]
```
Found one Java-level deadlock:
=============================
"jetty shutdown schedule":
  waiting to lock monitor 0x00007fb32b8255f8 (object 0x00000007be26fb50, a org.exist.storage.BrokerPool),
  which is held by "main"
"main":
  waiting for ownable synchronizer 0x00000007bedd7f50, (a java.util.concurrent.locks.ReentrantLock$NonfairSync),
  which is held by "jetty shutdown schedule"

Java stack information for the threads listed above:
===================================================
"jetty shutdown schedule":
    at org.exist.storage.BrokerPool.shutdown(BrokerPool.java:1962)
    - waiting to lock <0x00000007be26fb50> (a org.exist.storage.BrokerPool)
    at org.exist.storage.BrokerPool.stopAll(BrokerPool.java:410)
    at org.exist.http.servlets.AbstractExistHttpServlet.destroy(AbstractExistHttpServlet.java:91)
    at org.eclipse.jetty.servlet.ServletHolder.destroyInstance(ServletHolder.java:395)
    at org.eclipse.jetty.servlet.ServletHolder.doStop(ServletHolder.java:368)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
    - locked <0x00000007bec5b5f0> (a java.lang.Object)
    at org.eclipse.jetty.servlet.ServletHandler.doStop(ServletHandler.java:242)
    - locked <0x00000007bec58bc8> (a org.eclipse.jetty.servlet.ServletHandler)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
    - locked <0x00000007bec58c58> (a java.lang.Object)
    at org.eclipse.jetty.server.handler.HandlerWrapper.doStop(HandlerWrapper.java:107)
    at org.eclipse.jetty.security.SecurityHandler.doStop(SecurityHandler.java:392)
    at org.eclipse.jetty.security.ConstraintSecurityHandler.doStop(ConstraintSecurityHandler.java:464)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
    - locked <0x00000007bec58b08> (a java.lang.Object)
    at org.eclipse.jetty.server.handler.HandlerWrapper.doStop(HandlerWrapper.java:107)
    at org.eclipse.jetty.server.session.SessionHandler.doStop(SessionHandler.java:136)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
    - locked <0x00000007bec589d8> (a java.lang.Object)
    at org.eclipse.jetty.server.handler.HandlerWrapper.doStop(HandlerWrapper.java:107)
    at org.eclipse.jetty.server.handler.ContextHandler.doStop(ContextHandler.java:815)
    at org.eclipse.jetty.servlet.ServletContextHandler.doStop(ServletContextHandler.java:160)
    at org.eclipse.jetty.webapp.WebAppContext.doStop(WebAppContext.java:518)
    at org.exist.jetty.WebAppContext.doStop(WebAppContext.java:39)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
    - locked <0x00000007bec588d0> (a java.lang.Object)
    at org.eclipse.jetty.server.handler.HandlerCollection.doStop(HandlerCollection.java:250)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
    - locked <0x00000007bf3224d0> (a java.lang.Object)
    at org.eclipse.jetty.server.handler.HandlerWrapper.doStop(HandlerWrapper.java:107)
    at org.eclipse.jetty.server.Server.doStop(Server.java:343)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
    - locked <0x00000007be2ecd58> (a java.lang.Object)
    at org.exist.jetty.JettyStart$ShutdownListenerImpl$1.run(JettyStart.java:387)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
"main":
    at sun.misc.Unsafe.park(Native Method)
    - parking to wait for  <0x00000007bedd7f50> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
    at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
    at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
    at org.exist.storage.txn.TransactionManager.withLock(TransactionManager.java:344)
    at org.exist.storage.txn.TransactionManager.withLock(TransactionManager.java:324)
    at org.exist.storage.txn.TransactionManager.commit(TransactionManager.java:139)
    at org.exist.repo.Deployment.storeFiles(Deployment.java:780)
    at org.exist.repo.Deployment.scanDirectory(Deployment.java:694)
    at org.exist.repo.Deployment.lambda$scanDirectory$4(Deployment.java:699)
    at org.exist.repo.Deployment$$Lambda$165/1819271005.accept(Unknown Source)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at org.exist.repo.Deployment.scanDirectory(Deployment.java:699)
    at org.exist.repo.Deployment.deploy(Deployment.java:411)
    at org.exist.repo.Deployment.installAndDeploy(Deployment.java:272)
    at org.exist.repo.AutoDeploymentTrigger.execute(AutoDeploymentTrigger.java:72)
    at org.exist.storage.BrokerPool.callStartupTriggers(BrokerPool.java:1101)
    at org.exist.storage.BrokerPool.initialize(BrokerPool.java:1013)
    - locked <0x00000007be26fb50> (a org.exist.storage.BrokerPool)
    at org.exist.storage.BrokerPool.<init>(BrokerPool.java:715)
    at org.exist.storage.BrokerPool.configure(BrokerPool.java:268)
    at org.exist.storage.BrokerPool.configure(BrokerPool.java:242)
    at org.exist.storage.ModificationTimeTest.startDB(ModificationTimeTest.java:137)
    at org.exist.storage.ModificationTimeTest.storeXML(ModificationTimeTest.java:185)
    at org.exist.storage.ModificationTimeTest.check_if_modification_time_is_not_updated_on_parse_error(ModificationTimeTest.java:109)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:27)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
    at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:532)
    at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1179)
    at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1030)

Found 1 deadlock.
```

**Comment by shabanovd** [comment]
@adamretter I don't see who own 0x00000007bedd7f50, ideas?

**Comment by adamretter** [comment]
@duncdrum yes this is resolved.
